from datetime import datetime

# pylint: disable-msg=import-error
from utils.constants import BASE_CREDS, PROD_AGENT_ID, PROD_AGENT_UUID, PROD_HOST

# Setup
NOW = datetime.now().strftime("%Y%m%d%H%M%S")
DS_BEH_SUPPRESS = "AUTO_SUPPRESS_BEH_" + NOW
dataset_name = DS_BEH_SUPPRESS
CONN_BEHAVIOR_SUPPRESS = "APPROVED_POSTGRES_UP"
RUN_DATE_BEHAVIOR_SUPPRESS = "2018-01-16"
QUERY_BEH_SUPPRESS = "select * from public.nyse where trade_date = '${rd}' "
RUN_ID_BEHAVIOR_SUPPRESS = "2018-01-14T00:00:00.000+0000"

PL_SUPPRESS_BEHAVIOR_SUPPRESS = {
    "dataset": DS_BEH_SUPPRESS,
    "runId": RUN_ID_BEHAVIOR_SUPPRESS,
    "item": "Row Count",
    "metricType": "ROW_COUNT",
    "suppress": 1,
}
PL_GENEREAL_BEHAVIOR_SUPPRESS = {
    "dataset": DS_BEH_SUPPRESS,
    "runId": RUN_ID_BEHAVIOR_SUPPRESS,
    "sense": 3,
}
DATASET_DEFS_BEHAVIOR_SUPPRESS = {
    "dataset": DS_BEH_SUPPRESS,
    "runId": RUN_ID_BEHAVIOR_SUPPRESS,
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "host": PROD_HOST,
    "port": "5432/rc202307?currentSchema=validation",
    "user": BASE_CREDS["username"],
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {
        "id": PROD_AGENT_ID,
        "uuid": PROD_AGENT_UUID},
    "load": {
        "dataset": RUN_ID_BEHAVIOR_SUPPRESS,
        "query": QUERY_BEH_SUPPRESS,
        "operator": "=",
        "dateColumn": "trade_date",
        "sample": 1.0,
        "backRun": 10,
        "backRunBin": "DAY",
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "checkHeader": True,
        "inferSchema": True,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "lib": "/opt/owl/drivers/postgres/",
        "driverName": "org.postgresql.Driver",
        "connectionName": CONN_BEHAVIOR_SUPPRESS,
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "useSql": True,
        "numPartitions": 0,
        "partitionNumber": 0,
        "hasHeader": True,
    },
    "profile": {
        "dataset": RUN_ID_BEHAVIOR_SUPPRESS,
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "filter": "",
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNoneCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
        "profileStringLength": False,
        "dataConceptId": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": RUN_ID_BEHAVIOR_SUPPRESS,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": RUN_ID_BEHAVIOR_SUPPRESS,
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 2,
        "conf": "spark.executor.memoryOverhead=1g",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
}
