# pylint: disable-msg=import-error
from datetime import datetime

from utils.constants import BASE_CREDS, PROD_RUN_ID

# Same dataset used for import & export alerts and job schedule
DS_DB_EXPORT_IMPORT_NAME = "AUTO_EXPORT_IMPORT_ALERT_JOB_SCHEDULE"
DS_DB_EXPORT_IMPORT_RUN_ID = PROD_RUN_ID
DS_DB_EXPORT_IMPORT_QUERY = "select * from public.aclaims_master limit 100"
DS_DB_EXPORT_CONN = "APPROVED_POSTGRES_UP"
DS_DEFS_EXPORT_IMPORT_ALERT = {
    "dataset": DS_DB_EXPORT_IMPORT_NAME,
    "runId": DS_DB_EXPORT_IMPORT_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": True,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": "",
    "user": BASE_CREDS["username"],
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": DS_DB_EXPORT_IMPORT_QUERY,
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNone": False,
        "replaceNones": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/postgres/",
        "additionalLib": "",
        "driverName": "org.postgresql.Driver",
        "connectionName": DS_DB_EXPORT_CONN,
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "pushdown": {
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sqlLoggingToggle": True,
    },
    "outliers": [],
    "patterns": [],
    "dupe": {
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1,
        "limit": 300,
    },
    "profile": {
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNoneCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
    },
    "source": {
        "on": False,
        "only": False,
        "validateValues": False,
        "key": None,
        "include": None,
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNone": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateSourceShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": "",
        "driverName": "",
        "user": "",
        "password": "",
        "passwordManager": "",
        "connectionName": "",
        "connectionUrl": "",
        "query": "",
        "lib": "",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "spark.kubernetes.memoryOverheadFactor=0.4,spark.kubernetes.executor."
        "podTemplateFile=local:///opt/owl/config/k8s-executor-template.yml,spark."
        "kubernetes.driver.podTemplateFile=local:///opt/owl/config/k8s-driver-template.yml",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "record": {
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1,
        "dataset": None,
        "dateColumn": None,
        "keyColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "streamDefDTO": None,
    "pipeline": [],
}

# -------- Import/Export Alert
DS_DB_EXPORT_IMPORT_ALERT_NAME = "AUTO Regression - Alert Export/import"
DS_DB_EXPORT_IMPORT_ALERT_EMAIL = "automation_fake_email@collibra.com"
DS_DB_EXPORT_IMPORT_ALERT_COND = "score > 0"

PL_DB_EXPORT = {"schema": "validation", "datasets": DS_DB_EXPORT_IMPORT_NAME}
PL_REMOVE_ALERT = {"dataset": DS_DB_EXPORT_IMPORT_NAME, "alertNm": ""}  # Add later
PL_UPSERT_ALERT = {
    "datasetName": DS_DB_EXPORT_IMPORT_NAME,
    "alertNm": DS_DB_EXPORT_IMPORT_ALERT_NAME,
    "alertCond": DS_DB_EXPORT_IMPORT_ALERT_COND,
    "alertFormatValue": DS_DB_EXPORT_IMPORT_ALERT_EMAIL,
    "alertMsg": DS_DB_EXPORT_IMPORT_NAME,
    "oldRecipients": DS_DB_EXPORT_IMPORT_ALERT_EMAIL,
    "batchName": "",
    "alertFormat": "EMAIL",
    "updateBatchMails": False,
}
PL_DB_IMPORT = (
    "INSERT INTO validation.alert_cond(dataset,alert_nm,alert_cond,alert_format,"
    f"alert_format_value,alert_msg,batch_name) VALUES ('{DS_DB_EXPORT_IMPORT_NAME}',"
    f"'{DS_DB_EXPORT_IMPORT_ALERT_NAME}','{DS_DB_EXPORT_IMPORT_ALERT_COND}','EMAIL',"
    f"'{DS_DB_EXPORT_IMPORT_ALERT_EMAIL}','{DS_DB_EXPORT_IMPORT_NAME}','');"
)

EXP_GET_ALERT = {
    "dataset": DS_DB_EXPORT_IMPORT_NAME,
    "alertNm": DS_DB_EXPORT_IMPORT_ALERT_NAME,
    "alertCond": DS_DB_EXPORT_IMPORT_ALERT_COND,
    "alertFormat": "EMAIL",
    "alertFormatValue": DS_DB_EXPORT_IMPORT_ALERT_EMAIL,
    "alertMsg": DS_DB_EXPORT_IMPORT_NAME,
    "batchName": "",
}

# -------- Job Schedule
SCHEDULED_RUN_TIME = "00:00:00"
SCHEDULED_RUN_TIME_TIME_ZONED = datetime.now().strftime("%a, %d %b %Y")
PL_ACTIVATE_JOB = {"dataset": DS_DB_EXPORT_IMPORT_NAME}
PL_POST_JOB_SCH = {
    "agentId": "10",
    "agentUUID": "da7632d1-94ec-4a3e-88f2-dfad73d9a9de",
    "dataset": DS_DB_EXPORT_IMPORT_NAME,
    "scheduledRunTime": "00:00:00",
    "scheduledRunDateTimeZoned": f"{SCHEDULED_RUN_TIME_TIME_ZONED} 09:00:00 GMT",
    "runDateFmt": "yyyy-MM-dd",
    "freq": "DAILY",
    "dom": "",
    "mon": "0",
    "tue": "2",
    "wed": "0",
    "thu": "4",
    "fri": "0",
    "sat": "0",
    "sun": "0",
}

# Update agent id and regex time in the test
PL_DB_IMPORT_JOB_SCH = (
    "INSERT INTO validation.job_schedule(dataset,updt_ts,agent_id,"
    "scheduled_run_time,run_date_fmt,mon,tue,wed,thu,fri,sat,sun,time_zone,"
    "active,freq,dom,q_start,q_month,q_day,run_offset,agent_uuid) VALUES "
    f"('{DS_DB_EXPORT_IMPORT_NAME}','$TIME$','10','{SCHEDULED_RUN_TIME}',"
    "'yyyy-MM-dd','0','2','0','4','0','0','0','UTC','1','DAILY',NULL,NULL,NULL,"
    "NULL,NULL,'$AGENTUUID$');"
)

EXP_NO_JOB_SCH = {  # This is what returns after delete has been called.
    "alertWindowInMinutes": 30,
    "dataset": None,
    "agentId": None,
    "updtTs": None,
    "scheduledRunTime": "00:00:00",
    "runDateFmt": "yyyy-MM-dd",
    "mon": 1,
    "tue": 2,
    "wed": 3,
    "thu": 4,
    "fri": 5,
    "sat": 6,
    "sun": 7,
    "timeZone": "UTC",
    "active": 0,
    "runStatus": None,
    "freq": "DAILY",
    "dom": None,
    "qStart": None,
    "qMonth": None,
    "qDay": None,
    "runOffset": None,
    "late": True,
    "scheduledDays": [1, 2, 3, 4, 5, 6, 7],
}
EXP_JOB_SCH = {
    "alertWindowInMinutes": 30,
    "dataset": DS_DB_EXPORT_IMPORT_NAME,
    "scheduledRunTime": "00:00:00",
    "runDateFmt": "yyyy-MM-dd",
    "mon": 0,
    "tue": 2,
    "wed": 0,
    "thu": 4,
    "fri": 0,
    "sat": 0,
    "sun": 0,
    "timeZone": "UTC",
    "active": 1,
    "runStatus": None,
    "freq": "DAILY",
    "dom": None,
    "qStart": None,
    "qMonth": None,
    "qDay": None,
    "runOffset": None,
    "late": True,
    "scheduledDays": [2, 4],
}
