# pylint: disable-msg=import-error
from utils.constants import PROD_HOST, PROD_AGENT_UUID, PROD_AGENT_ID

DS_HOUR_MIN = "AUTO_OUTLIERS_HOURMIN"
CONN_HOUR_MIN = "APPROVED_DB2_UP"
RUN_DATE_HOUR_MIN = "2018-01-11"
RUN_ID_HOUR_MIN_FULL = f"{RUN_DATE_HOUR_MIN}T00:00:00.000+0000"
QUERY_HOUR_MIN = "select * from OWLDB2.NYSE_STOCKS where TRADE_DATE = '${rd}' "
COL_DATE_HOUR_MIN = "TRADE_DATE"
BACK_RUN_HOUR_MIN = 10

DS_DEFS_HOUR_MIN = {
    "dataset": DS_HOUR_MIN,
    "runId": RUN_DATE_HOUR_MIN,
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "hootOnly": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "host": PROD_HOST,
    "user": "anonymous : use -owluser",
    "schemaScore": 1.0,
    "keyDelimiter": "~~",
    "agentId": {"id": PROD_AGENT_ID, "uuid": PROD_AGENT_UUID},
    "load": {
        "dataset": DS_HOUR_MIN,
        "query": QUERY_HOUR_MIN,
        "operator": "=",
        "dateColumn": COL_DATE_HOUR_MIN,
        "sample": 1.0,
        "backRun": BACK_RUN_HOUR_MIN,
        "backRunBin": "DAY",
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "checkHeader": True,
        "inferSchema": True,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/db2/",
        "driverName": "com.ibm.db2.jcc.DB2Driver",
        "connectionName": CONN_HOUR_MIN,
        "connectionUrl": "jdbc:db2://10.150.0.3:50000/owldb2",
        "userName": "db2test",
        "useSql": True,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "hasHeader": True,
    },
    "outliers": [
        {
            "id": 342,
            "on": True,
            "only": False,
            "lookback": 5,
            "key": None,
            "include": ["CLOSE", "EXCH", "HIGH", "LOW", "OPEN", "SYMBOL", "TRADE_DATE", "VOLUME"],
            "exclude": ["PART_DATE_STR"],
            "dateColumn": COL_DATE_HOUR_MIN,
            "timeBin": "HOUR",
            "categorical": False,
            "by": "MIN",
            "limit": 300,
            "minHistory": 3,
            "historyLimit": 5,
            "score": 1.0,
            "q1": 0.15,
            "q3": 0.85,
            "categoricalColumnConcatenation": False,
            "multiplierUpper": 1.35,
            "multiplierLower": 1.35,
            "record": True,
            "combine": True,
            "categoricalTopN": 3,
            "categoricalBottomN": 2,
            "categoricalMaxConfidence": 0.02,
            "categoricalMaxFrequencyPercentile": 0.25,
            "categoricalMinFrequency": 1,
            "categoricalMinVariance": 0.0,
            "categoricalMaxCategoryN": 1,
            "categoricalParallel": True,
        }
    ],
    "outlier": {
        "id": None,
        "on": False,
        "only": False,
        "lookback": 5,
        "timeBin": "DAY",
        "categorical": True,
        "limit": 300,
        "minHistory": 3,
        "historyLimit": 5,
        "score": 1.0,
        "q1": 0.15,
        "q3": 0.85,
        "categoricalColumnConcatenation": False,
        "multiplierUpper": 1.35,
        "multiplierLower": 1.35,
        "record": True,
        "combine": True,
        "categoricalTopN": 3,
        "categoricalBottomN": 2,
        "categoricalMaxConfidence": 0.02,
        "categoricalMaxFrequencyPercentile": 0.25,
        "categoricalMinFrequency": 1,
        "categoricalMinVariance": 0.0,
        "categoricalMaxCategoryN": 1,
        "categoricalParallel": True,
    },
    "profile": {
        "dataset": DS_HOUR_MIN,
        "on": False,
        "only": False,
        "shape": True,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "profileStringLength": False,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DS_HOUR_MIN,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
    },
    "spark": {
        "dataset": DS_HOUR_MIN,
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "2g",
        "executorCores": 1,
        "master": "k8s://",
        "deployMode": "cluster",
    },
}
