# pylint: disable-msg=import-error
from utils.constants import PROD_HOST, PROD_PORT, BASE_CREDS

CONN_NAME = "APPROVED_ORACLE_UP"
TABLE_NAME = "OWLUSER.NYSE"
WHERE_COL = "TRADE_DATE"
WHERE_DATE = "2018-01-16"
QUERY = f"select * from {TABLE_NAME} where {WHERE_COL} = '{WHERE_DATE}' limit 500"

DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME = "AUTO_OUTLIER_MONTH_BY_MONTH"
DS_DEFS_OUTLIER_MONTH_BY_MONTH_RUN_ID_FULL = f"{WHERE_DATE}T00:00:00.000+0000"
DS_DEFS_OUTLIER_MONTH_BY_MONTH = {
    "dataset": DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME,
    "runId": WHERE_DATE,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": PROD_HOST,
    "port": PROD_PORT,
    "user": BASE_CREDS["username"],
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 10, "uuid": "da7632d1-94ec-4a3e-88f2-dfad73d9a9de"},
    "load": {
        "dataset": DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": QUERY,
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "TRADE_DATE",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "checkHeader": True,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/oracle",
        "additionalLib": "",
        "driverName": "oracle.jdbc.OracleDriver",
        "connectionName": "APPROVED_ORACLE_UP",
        "connectionUrl": "jdbc:oracle:thin:@10.150.0.31:1521:OWL",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "escapeCharacter": "",
        "hasHeader": True,
    },
    "outliers": [
        {
            "id": 3476,
            "on": True,
            "only": False,
            "lookback": 5,
            "key": ["SYMBOL"],
            "include": [
                "CLOSE",
                "EXCH",
                "HIGH",
                "LOW",
                "OPEN",
                "PART_DATE_STR",
                "SYMBOL",
                "TRADE_DATE",
                "VOLUME",
            ],
            "exclude": None,
            "dateColumn": "TRADE_DATE",
            "timeColumn": None,
            "timeBin": "MONTH",
            "timeBinQuery": "",
            "categorical": False,
            "by": "MONTH",
            "limit": 300,
            "minHistory": 3,
            "historyLimit": 5,
            "score": 1.0,
            "aggFunc": "",
            "aggQuery": "",
            "query": "",
            "q1": 0.15,
            "q3": 0.85,
            "categoricalColumnConcatenation": False,
            "limitCategorical": None,
            "measurementUnit": "",
            "multiplierUpper": 1.35,
            "multiplierLower": 1.35,
            "record": True,
            "filter": None,
            "combine": True,
            "categoricalConfidenceType": "",
            "categoricalTopN": 3,
            "categoricalBottomN": 2,
            "categoricalMaxConfidence": 0.02,
            "categoricalMaxFrequencyPercentile": 0.25,
            "categoricalMinFrequency": 1,
            "categoricalMinVariance": 0.0,
            "categoricalMaxCategoryN": 1,
            "categoricalParallel": True,
            "categoricalAlgorithm": "",
            "categoricalAlgorithmParameters": {},
        }
    ],
    "outlier": {
        "id": None,
        "on": False,
        "only": False,
        "lookback": 5,
        "key": None,
        "include": None,
        "exclude": None,
        "dateColumn": None,
        "timeColumn": None,
        "timeBin": "DAY",
        "timeBinQuery": "",
        "categorical": True,
        "by": None,
        "limit": 300,
        "minHistory": 3,
        "historyLimit": 5,
        "score": 1.0,
        "aggFunc": "",
        "aggQuery": "",
        "query": "",
        "q1": 0.15,
        "q3": 0.85,
        "categoricalColumnConcatenation": False,
        "limitCategorical": None,
        "measurementUnit": "",
        "multiplierUpper": 1.35,
        "multiplierLower": 1.35,
        "record": True,
        "filter": None,
        "combine": True,
        "categoricalConfidenceType": "",
        "categoricalTopN": 3,
        "categoricalBottomN": 2,
        "categoricalMaxConfidence": 0.02,
        "categoricalMaxFrequencyPercentile": 0.25,
        "categoricalMinFrequency": 1,
        "categoricalMinVariance": 0.0,
        "categoricalMaxCategoryN": 1,
        "categoricalParallel": True,
        "categoricalAlgorithm": "",
        "categoricalAlgorithmParameters": {},
    },
    "pattern": {
        "id": None,
        "only": False,
        "lookback": 5,
        "key": None,
        "dateColumn": None,
        "include": None,
        "exclude": None,
        "score": 1.0,
        "minSupport": 3.3e-5,
        "confidence": 0.6,
        "limit": 30,
        "query": "",
        "filter": None,
        "timeBin": "DAY",
        "on": False,
        "match": True,
        "lowFreq": False,
        "bucketLimit": 450000,
        "deDupe": True,
    },
    "patterns": [],
    "dupe": {
        "dataset": None,
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1.0,
        "limit": 300,
    },
    "pushdown": {
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sqlLoggingToggle": True,
    },
    "profile": {
        "dataset": DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME,
        "on": True,
        "only": False,
        "include": [
            "CLOSE",
            "EXCH",
            "HIGH",
            "LOW",
            "OPEN",
            "PART_DATE_STR",
            "SYMBOL",
            "TRADE_DATE",
            "VOLUME",
        ],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": False,
        "histogram": False,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 20,
        "shapeMaxColSize": 12,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": False,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": False,
        "behaviorEmptyCheck": False,
        "behaviorUniqueCheck": False,
        "adaptiveTier": None,
        "profileStringLength": False,
        "dataConceptId": None,
    },
    "source": {
        "on": False,
        "only": False,
        "validateValues": False,
        "key": None,
        "include": None,
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1.0,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNull": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateValuesShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": "",
        "driverName": "",
        "user": "",
        "password": "",
        "passwordManager": "",
        "connectionName": "",
        "connectionUrl": "",
        "query": "",
        "lib": "",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
        "hasHeader": True,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DS_DEFS_OUTLIER_MONTH_BY_MONTH_NAME,
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 2,
        "conf": "spark.executor.memoryOverhead=1g",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}
