# pylint: disable-msg=import-error
from utils.constants import (
    PROD_RUN_ID,
    PROD_HOST,
    PROD_AGENT_ID,
    PROD_AGENT_UUID,
)

# Setup
CONNECTION = "APPROVED_POSTGRES_UP"
OUTLIERS_DATA_VALIDATION_DATASET = "AUTO_POSTGRES_OUTLIERS"

# Job Dataset
OUTLIERS_DATA_VALIDATION_PAYLOAD = {
    "dataset": OUTLIERS_DATA_VALIDATION_DATASET,
    "runId": PROD_RUN_ID,
    "host": PROD_HOST,
    "agentId": {"id": PROD_AGENT_ID, "uuid": PROD_AGENT_UUID},
    "load": {
        "query": "select * from public.nyse limit 100",
        "lib": "/opt/owl/drivers/postgres/",
        "driverName": "org.postgresql.Driver",
        "connectionName": CONNECTION,
    },
    "spark": {
        "dataset": OUTLIERS_DATA_VALIDATION_DATASET,
        "numExecutors": 1,
        "driverMemory": "4g",
        "executorMemory": "1g",
        "executorCores": 2,
        "conf": "spark.executor.memoryOverhead=1g",
        "master": "k8s://",
        "deployMode": "cluster",
    },
    "outliers": [
        {
            "id": 288,
            "on": True,
            "only": False,
            "lookback": 5,
            "key": None,
            "include": ["high", "low"],
            "exclude": [
                "exch",
                "symbol",
                "trade_date",
                "open",
                "close",
                "volume",
                "part_date_str",
            ],
            "dateColumn": None,
            "timeColumn": None,
            "timeBin": "DAY",
            "timeBinQuery": "",
            "categorical": False,
            "by": None,
            "limit": 300,
            "minHistory": 3,
            "historyLimit": 5,
            "score": 1,
            "aggFunc": "",
            "aggQuery": "",
            "query": "",
            "q1": 0.15,
            "q3": 0.85,
            "categoricalColumnConcatenation": False,
            "limitCategorical": None,
            "measurementUnit": "",
            "multiplierUpper": 1.35,
            "multiplierLower": 1.35,
            "record": True,
            "filter": None,
            "combine": True,
            "categoricalConfidenceType": "",
            "categoricalTopN": 3,
            "categoricalBottomN": 2,
            "categoricalMaxConfidence": 0.02,
            "categoricalMaxFrequencyPercentile": 0.25,
            "categoricalMinFrequency": 1,
            "categoricalMinVariance": 0,
            "categoricalMaxCategoryN": 1,
            "categoricalParallel": True,
            "categoricalAlgorithm": "",
            "categoricalAlgorithmParameters": {},
        }
    ],
    "outlier": {
        "id": None,
        "on": False,
        "only": False,
        "lookback": 5,
        "key": None,
        "include": None,
        "exclude": None,
        "dateColumn": None,
        "timeColumn": None,
        "timeBin": "DAY",
        "timeBinQuery": "",
        "categorical": True,
        "by": None,
        "limit": 300,
        "minHistory": 3,
        "historyLimit": 5,
        "score": 1,
        "aggFunc": "",
        "aggQuery": "",
        "query": "",
        "q1": 0.15,
        "q3": 0.85,
        "categoricalColumnConcatenation": False,
        "limitCategorical": None,
        "measurementUnit": "",
        "multiplierUpper": 1.35,
        "multiplierLower": 1.35,
        "record": True,
        "filter": None,
        "combine": True,
        "categoricalConfidenceType": "",
        "categoricalTopN": 3,
        "categoricalBottomN": 2,
        "categoricalMaxConfidence": 0.02,
        "categoricalMaxFrequencyPercentile": 0.25,
        "categoricalMinFrequency": 1,
        "categoricalMinVariance": 0,
        "categoricalMaxCategoryN": 1,
        "categoricalParallel": True,
        "categoricalAlgorithm": "",
        "categoricalAlgorithmParameters": {},
    },
}
