from utils.constants import PROD_RUN_ID

PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_DATASET = "AUTO_PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2"

PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_PAYLOAD = {
	"dataset": PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_DATASET,
	"runId": PROD_RUN_ID,
	"runIdEnd": "",
	"runDateAdjustment": "",
	"runState": "DRAFT",
	"passFail": 1,
	"passFailLimit": 75,
	"jobDescription": "",
	"jobId": {
		"id": -1,
		"uuid": None
	},
	"coreMaxActiveConnections": None,
	"linkId": None,
	"licenseKey": "",
	"logFile": "",
	"logLevel": "INFO",
	"hootOnly": False,
	"prettyPrint": True,
	"useTemplate": False,
	"parallel": False,
	"plan": False,
	"dataPreviewOff": False,
	"datasetSafeOff": False,
	"obslimit": 300,
	"pgUser": "",
	"pgPassword": "",
	"host": "10.64.2.3:5432/dqqa?currentSchema=validation",
	"port": None,
	"user": "anonymous : use -owluser",
	"alertEmail": "",
	"scheduleTime": None,
	"schemaScore": 1,
	"optionAppend": "",
	"keyDelimiter": "~~",
	"agentId": {
		"id": 6,
		"uuid": "8eb1f6a8-70ab-4285-a903-b587523ae61e"
	},
	"load": {
		"readonly": False,
		"passwordManager": None,
		"alias": "",
		"query": "select * from PUBLIC.AUSTIN_CRIME_UNIQUE_KEY",
		"queryHistory": "",
		"key": "",
		"expression": "",
		"addDateColumn": False,
		"zeroFillNone": False,
		"replaceNones": "",
		"stringMode": False,
		"operator": "=",
		"dateColumn": "",
		"transform": "",
		"filter": "",
		"filterNot": "",
		"sample": 1,
		"backRun": 0,
		"backRunBin": "DAY",
		"unionLookBack": False,
		"unionLookBackMinRow": 0,
		"cache": True,
		"dateFormat": "yyyy-MM-dd",
		"timeFormat": "HH:mm:ss.SSS",
		"timestamp": False,
		"filePath": "",
		"fileQuery": "",
		"fullFile": False,
		"fileHeader": None,
		"inferSchema": True,
		"fileType": None,
		"delimiter": ",",
		"fileCharSet": "UTF-8",
		"skipLines": 0,
		"avroSchema": "",
		"xmlRowTag": "",
		"flatten": False,
		"handleMaps": False,
		"handleMixedJson": False,
		"multiLine": False,
		"lib": "/opt/owl/drivers/snowflake/",
		"additionalLib": "",
		"driverName": "net.snowflake.client.jdbc.SnowflakeDriver",
		"connectionName": "APPROVED_SNOWFLAKE_UP",
		"connectionUrl": "",
		"userName": "",
		"password": "",
		"connectionProperties": {},
		"hiveNative": None,
		"hiveNativeHWC": False,
		"useSql": True,
		"columnName": None,
		"lowerBound": None,
		"upperBound": None,
		"numPartitions": 0,
		"partitionNumber": 0,
		"escapeWithBackTick": False,
		"escapeWithSingleQuote": False,
		"escapeWithDoubleQuote": False,
		"escapeCharacter": "",
		"checkHeader": True,
		"archiveConnection": "",
		"coreFetchMode": False,
		"archiveBreaks": False,
		"ruleSerial": False
	},
	"pushdown": {
		"dataset": PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_DATASET,
		"connectionName": "",
		"maxConnections": 10,
		"sourceQuery": "",
		"backRuns": 0,
		"backRunBin": "DAY",
		"dateFormatType": "DATE",
		"threads": 5,
		"manualSourceQuery": False,
		"key": "",
		"sourceOutputSchema": "",
		"sourceBreakRules": False,
		"sourceBreakOutliers": False,
		"sourceBreakDupes": False,
		"sourceBreakShapes": False,
		"sourceBreakResults": False,
		"sqlLoggingToggle": True,
		"unionLookback": False,
		"unionLookbackMin": 5
	},
	"outliers": [],
	"patterns": [],
	"dupe": {
		"on": False,
		"only": False,
		"include": None,
		"exclude": None,
		"depth": 0,
		"lowerBound": 99,
		"upperBound": 100,
		"approximate": 1,
		"limitPerDupe": 15,
		"checkHeader": True,
		"filter": None,
		"ignoreCase": True,
		"score": 1,
		"limit": 300
	},
	"profile": {
		"on": True,
		"only": False,
		"include": [
			"unique_key",
			"address",
			"census_tract",
			"clearance_date",
			"clearance_status",
			"council_district_code",
			"description",
			"district",
			"latitude",
			"longitude",
			"location",
			"location_description",
			"primary_type",
			"timestamp",
			"x_coordinate",
			"y_coordinate",
			"year",
			"zipcode"
		],
		"exclude": [],
		"correlation": None,
		"histogram": None,
		"semantic": None,
		"dataConceptId": 300,
		"limit": 300,
		"histogramLimit": 0,
		"score": 1,
		"shape": True,
		"shapeTotalScore": 0,
		"shapeSensitivity": 0.007,
		"shapeMaxPerCol": 46,
		"shapeMaxColSize": 43,
		"shapeGranular": True,
		"behavioralDimension": "",
		"behavioralDimensionGroup": "",
		"behavioralValueColumn": "",
		"behaviorScoreOff": False,
		"behaviorLookback": 10,
		"behaviorMinSupport": 4,
		"profilePushDown": None,
		"behaviorRowCheck": True,
		"behaviorTimeCheck": False,
		"behaviorMinValueCheck": False,
		"behaviorMaxValueCheck": False,
		"behaviorMeanValueCheck": False,
		"behaviorNoneCheck": True,
		"behaviorEmptyCheck": True,
		"behaviorUniqueCheck": True,
		"profileStringLength": False,
		"detectStringNumerics": True,
		"detectTopnBotn": True,
		"detectScalePrecision": True,
		"adaptiveTier": None,
		"advancedTier": None,
		"filter": ""
	},
	"source": {
		"on": False,
		"only": False,
		"validateValues": False,
		"key": None,
		"include": None,
		"exclude": None,
		"includeSrc": None,
		"excludeSrc": None,
		"map": None,
		"score": 1,
		"limit": 30,
		"sourcePushDownCount": False,
		"checkType": True,
		"checkCase": False,
		"validateSchemaOrder": False,
		"matches": False,
		"validateValuesThreshold": 0.9,
		"validateValuesThresholdStrictDownScore": False,
		"validateValuesShowAll": False,
		"validateValuesIgnoreNone": False,
		"validateValuesIgnoreEmpty": False,
		"validateValuesIgnorePrecision": False,
		"validateValuesTrim": False,
		"validateValuesShowMissingKeys": False,
		"validateSrcJoinOnly": False,
		"validateValuesFilter": "",
		"dataset": "",
		"driverName": "",
		"user": "",
		"password": "",
		"passwordManager": "",
		"connectionName": "",
		"connectionUrl": "",
		"query": "",
		"lib": "",
		"connectionProperties": {},
		"filePath": "",
		"fileQuery": "",
		"fullFile": False,
		"header": None,
		"skipLines": 0,
		"inferSchema": True,
		"fileType": None,
		"delimiter": ",",
		"fileCharSet": "UTF-8",
		"avroSchema": "",
		"xmlRowTag": "",
		"flatten": False,
		"handleMaps": False,
		"handleMixedJson": False,
		"multiLine": False,
		"filterCols": None
	},
	"rule": {
		"on": True,
		"only": False,
		"lib": None,
		"name": "",
		"absoluteScoring": False,
		"ruleBreakPreviewLimit": 6
	},
	"colMatch": {
		"colMatchParallelProcesses": 3,
		"colMatchDurationMins": 20,
		"colMatchBatchSize": 2,
		"level": "exact",
		"fuzzyDistance": 1,
		"connectionList": []
	},
	"spark": {
		"numExecutors": 1,
		"driverMemory": "1g",
		"executorMemory": "2g",
		"executorCores": 1,
		"conf": "",
		"queue": "",
		"master": "k8s://",
		"principal": "",
		"keyTab": "",
		"deployMode": "cluster",
		"jars": None,
		"packages": None,
		"files": None
	},
	"env": {
		"dataset": PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_DATASET,
		"jdbcPrincipal": "",
		"jdbcKeyTab": ""
	},
	"record": {
		"on": False,
		"in": "",
		"notIn": "",
		"include": None,
		"percDeltaLimit": 0.1,
		"score": 1,
		"dataset": None,
		"dateColumn": None,
		"keyColumn": None,
		"timeBin": "DAY",
		"by": None
	},
	"stream": None,
	"pipeline": [],
	"metaTags": None,
	"outlierConfiguration": None,
	"shape": {
		"enabled": True,
		"totalScore": 0,
		"sensitivity": 0.007,
		"maxPerCol": 46,
		"maxColSize": 43,
		"granular": True,
		"columnSettings": []
	},
	"jobSchedule": None,
	"connectionType": "PULLUP"
}

PULLUP_SF_SHAPES_GRANULAR_AUSTIN_CRIME_2_SHAPES_SETTINGS = {
    "dataShapeColInclusion[address]": 1,
    "dataShapeColInclusion[census_tract]": 1,
    "dataShapeColInclusion[clearance_date]": 1,
    "dataShapeColInclusion[clearance_status]": 1,
    "dataShapeColInclusion[council_district_code]": 1,
    "dataShapeColInclusion[description]": 1,
    "dataShapeColInclusion[district]": 1,
    "dataShapeColInclusion[latitude]": 1,
    "dataShapeColInclusion[location]": 1,
    "dataShapeColInclusion[location_description]": 1,
    "dataShapeColInclusion[longitude]": 1,
    "dataShapeColInclusion[primary_type]": 1,
    "dataShapeColInclusion[timestamp]": 1,
    "dataShapeColInclusion[unique_key]": 1,
    "dataShapeColInclusion[x_coordinate]": 1,
    "dataShapeColInclusion[y_coordinate]": 1,
    "dataShapeColInclusion[year]": 1,
    "dataShapeColInclusion[zipcode]": 1,
    "dataShapeColType[address]": "VARCHAR",
    "dataShapeColType[census_tract]": "DOUBLE",
    "dataShapeColType[clearance_date]": "TIMESTAMP",
    "dataShapeColType[clearance_status]": "VARCHAR",
    "dataShapeColType[council_district_code]": "NUMBER",
    "dataShapeColType[description]": "VARCHAR",
    "dataShapeColType[district]": "VARCHAR",
    "dataShapeColType[latitude]": "DOUBLE",
    "dataShapeColType[location]": "VARCHAR",
    "dataShapeColType[location_description]": "VARCHAR",
    "dataShapeColType[longitude]": "DOUBLE",
    "dataShapeColType[primary_type]": "VARCHAR",
    "dataShapeColType[timestamp]": "TIMESTAMP",
    "dataShapeColType[unique_key]": "NUMBER",
    "dataShapeColType[x_coordinate]": "NUMBER",
    "dataShapeColType[y_coordinate]": "NUMBER",
    "dataShapeColType[year]": "NUMBER",
    "dataShapeColType[zipcode]": "VARCHAR",
    "dataShapeMaxColSize": 43,
    "dataShapeMaxPerCol": 46,
    "dataShapeSensitivity": 0.007
}
