# pylint: disable-msg=import-error
from utils.constants import PROD_HOST, PROD_PORT, BASE_CREDS

DS_DEFS_COPY_TARGET_NAME = "AUTO_RULES_COPY_TARGET_DATASET"
DS_DEFS_COPY_TARGET_RUN_ID = "2023-06-20"
DS_DEFS_COPY_SOURCE_NAME = "AUTO_RULES_COPY_SOURCE"
DS_DEFS_COPY_SOURCE_RUN_ID = "2023-07-20"
DS_DEFS_COPY_QUERY = "select * from dbo.nyse_regular"

PL_RULES_COPY = [
    {
        "sourceDataset": DS_DEFS_COPY_SOURCE_NAME,
        "sourceRuleName": "sqlg_stat_volume_passrule",
        "targetDataset": DS_DEFS_COPY_TARGET_NAME,
        "generatedRuleName": "sqlg_stat_volume_passrule",
    }
]
PL_RULES_SOURCE_COPY = {
    "source": DS_DEFS_COPY_SOURCE_NAME,
    "target": DS_DEFS_COPY_TARGET_NAME,
}
PL_RULES = [
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "if_close_is_DATATYPE",
        "ruleType": "DATATYPECHECK",
        "ruleValue": "close",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": "kusuma",
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": 4,
        "dimName": "VALIDITY",
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "if_open_is_DATATYPE",
        "ruleType": "DATATYPECHECK",
        "ruleValue": "open",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": "kusuma",
        "exception": None,
        "columnName": "open",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlf_pass_rule",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{DS_DEFS_COPY_SOURCE_NAME} A where A.volume.$min > 1",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "if_part_date_str_is_DATE_YYYY_MM_DD",
        "ruleType": "CUSTOM",
        "ruleValue": "part_date_str",
        "points": 1,
        "perc": 1,
        "ruleRepo": "DATE YYYY-MM-DD",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "part_date_str",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlf_close_206_br",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{DS_DEFS_COPY_SOURCE_NAME} A where A.close = 25.3",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlg_stat_volume_passrule",
        "ruleType": "SQLG",
        "ruleValue": "volume.$min > 1",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "volume",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlg_stat_volume_br",
        "ruleType": "SQLG",
        "ruleValue": "volume.$min < 1",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlg_partdate_str_passrule",
        "ruleType": "SQLG",
        "ruleValue": "part_date_str = '2023-12-19 00:00:00.0'",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "sqlf_stat_br",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{DS_DEFS_COPY_SOURCE_NAME} A where A.volume.$min < 1",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "if_trade_date_is_DATE",
        "ruleType": "DATECHECK",
        "ruleValue": "trade_date",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": "kusuma",
        "exception": None,
        "columnName": "trade_date",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "native_close_notNonechk_allrecords_break",
        "ruleType": "NATIVE",
        "ruleValue": 'select * from nyse_regular where nyse_regular."close" is not None',
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": "kusuma",
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": '{"condition":"AND","rules":[{"id":None,"field":None,"type":None,'
        '"input":None,"operator":None}],"not":false,"valid":false}',
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
    {
        "dataset": DS_DEFS_COPY_SOURCE_NAME,
        "ruleNm": "native_partdatestr_Nonecheck_allpass",
        "ruleType": "NATIVE",
        "ruleValue": 'select * from nyse_regular where nyse_regular."part_date_str" is None',
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": "kusuma",
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": '{"condition":"AND","rules":[{"id":None,"field":None,"type":None,'
        '"input":None,"operator":None}],"not":false,"valid":false}',
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
    },
]

DS_DEFS_COPY_SOURCE = {
    "dataset": DS_DEFS_COPY_SOURCE_NAME,
    "runId": DS_DEFS_COPY_SOURCE_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": True,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": PROD_HOST,
    "port": PROD_PORT,
    "user": BASE_CREDS["username"],
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": DS_DEFS_COPY_QUERY,
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/mssql",
        "additionalLib": "",
        "driverName": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        "connectionName": "APPROVED_SQLSERVER_UP",
        "connectionUrl": "jdbc:sqlserver://104.196.190.91:1433;databaseName=samples",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "profile": {
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "spark.kubernetes.memoryOverheadFactor=0.4,spark.kubernetes.executor."
        "podTemplateFile=local:///opt/owl/config/k8s-executor-template.yml,spark."
        "kubernetes.driver.podTemplateFile=local:///opt/owl/config/k8s-driver-template.yml",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
}
DS_DEFS_COPY_TARGET = {
    "dataset": DS_DEFS_COPY_TARGET_NAME,
    "runId": DS_DEFS_COPY_TARGET_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": True,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": PROD_HOST,
    "port": PROD_PORT,
    "user": BASE_CREDS["username"],
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": DS_DEFS_COPY_QUERY,
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/mssql",
        "additionalLib": "",
        "driverName": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        "connectionName": "APPROVED_SQLSERVER_UP",
        "connectionUrl": "jdbc:sqlserver://104.196.190.91:1433;databaseName=samples",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "profile": {
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
    },
    "source": {
        "on": False,
        "only": False,
        "validateValues": False,
        "key": None,
        "include": None,
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNull": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateSourceShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": "",
        "driverName": "",
        "user": "",
        "password": "",
        "passwordManager": "",
        "connectionName": "",
        "connectionUrl": "",
        "query": "",
        "lib": "",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "2g",
        "executorCores": 1,
        "conf": "spark.kubernetes.memoryOverheadFactor=0.4,spark.kubernetes.executor."
        "podTemplateFile=local:///opt/owl/config/k8s-executor-template.yml,spark."
        "kubernetes.driver.podTemplateFile=local:///opt/owl/config/k8s-driver-template.yml",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
}
