# pylint: disable-msg=import-error
from utils.constants import (
    PROD_HOST,
    PROD_PORT,
    BASE_CREDS,
    PROD_AGENT_ID,
    PROD_AGENT_UUID,
)

DS_DEF_SOUCE_OFF_VALIDATE_VALUES_SRC = "src_AUTO_SOURCE_VALIDATEOFF"

DS_DEF_SOUCE_OFF_VALIDATE_VALUES = {
    "dataset": "AUTO_SOURCE_VALIDATEOFF",
    "runId": "2023-05-23",
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": True,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": PROD_HOST,
    "port": PROD_PORT,
    "user": BASE_CREDS["username"],
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": PROD_AGENT_ID, "uuid": PROD_AGENT_UUID},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "select * from public.nyse",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNone": False,
        "replaceNones": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/postgres/",
        "additionalLib": "",
        "driverName": "org.postgresql.Driver",
        "connectionName": "APPROVED_POSTGRES_UP",
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "dupe": {
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1,
        "limit": 300,
    },
    "profile": {
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNoneCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
    },
    "source": {
        "on": True,
        "only": False,
        "validateValues": False,
        "key": ["symbol"],
        "include": [
            "exch",
            "symbol",
            "trade_date",
            "open",
            "high",
            "low",
            "close",
            "volume",
            "part_date_str",
        ],
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1,
        "limit": 30,
        "sourcePushDownCount": True,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNone": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateSourceShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": DS_DEF_SOUCE_OFF_VALIDATE_VALUES_SRC,
        "driverName": "com.ibm.db2.jcc.DB2Driver",
        "user": "db2test",
        "password": "",
        "passwordManager": None,
        "connectionName": "APPROVED_DB2_UP",
        "connectionUrl": "jdbc:db2://10.150.0.3:50000/owldb2",
        "query": "select * from OWLDB2.NYSE_STOCKS",
        "lib": "/opt/owl/drivers/db2/",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "spark.kubernetes.memoryOverheadFactor=0.4,spark.kubernetes."
        "executor.podTemplateFile=local:///opt/owl/config/k8s-executor"
        "-template.yml,spark.kubernetes.driver.podTemplateFile="
        "local:///opt/owl/config/k8s-driver-template.yml",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "record": {
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1,
        "dataset": None,
        "dateColumn": None,
        "keyColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "streamDefDTO": None,
    "pipeline": [],
}
