# --- COMMON ---
from utils.constants import PROD_RUN_ID

CONN_NAME_GCS = "APPROVED_GCS"
FILE_CHAR_SET = "UTF-8"
HOST_NAME = "gs://owl-bucket/"

# --- CSV format ---
WHERE_DATE = "2017-12-20"
TABLE_NAME = "TEST_DATA_FILES/nyse.csv"
COL_NAME = "TRADE_DATE"
DATASET = "APPROVED_GCS_CSV"
ROW_COUNT = 50
QUERY = f"select * from {TABLE_NAME} where {COL_NAME} = '{WHERE_DATE}' limit {ROW_COUNT}"
CONN_NAME = "APPROVED_GCS"
PATH = f"{HOST_NAME}{TABLE_NAME}"

PL_DS_GEN = {"dataset": DATASET, "runId": WHERE_DATE}
PL_DS_STATS = {"dataset": DATASET, "runId": WHERE_DATE, "sense": 3}
PL_FILTERGRAM = {
    "dataset": DATASET,
    "column": COL_NAME,
    "runid": f"{WHERE_DATE}T00:00:00.000 0000",
    "datevalue": f"{WHERE_DATE} 00:00:00 00",
    "limit": 500,
}
PL_DAYS_WITH_DATA = {
    "connectionalias": CONN_NAME,
    "path": TABLE_NAME,
    "colNm": COL_NAME,
    "type": "csv",
}
PL_JOB_EST = {
    "aliasname": CONN_NAME,
    "cols": "CLOSE,EXCH,HIGH,LOW,OPEN,PART_DATE_STR,SYMBOL,TRADE_DATE,VOLUME",
    "path": TABLE_NAME,
    "query": QUERY,
    "type": "csv",
}
PL_READ_REMOTE_FILE = {
    "connectionalias": "APPROVED_GCS",
    "path": "/TEST_DATA_FILES/nyse.csv",
    "type": "csv",
    "rowtag": "",
    "delimiter": ",",
    "hasheaders": True,
    "header": "",
    "charset": "UTF-8",
    "dtfmt": "yyyy-MM-dd",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}

EXP_READ_REMOTE_FILE = [
    {
        "HIGH": {"DoubleType": "4.16"},
        "SYMBOL": {"StringType": "ANFI"},
        "LOW": {"DoubleType": "4.05"},
        "VOLUME": {"IntegerType": "112800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "4.07"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "4.09"},
    },
    {
        "HIGH": {"DoubleType": "5.35"},
        "SYMBOL": {"StringType": "ANH"},
        "LOW": {"DoubleType": "5.28"},
        "VOLUME": {"IntegerType": "507600"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "5.34"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "5.3"},
    },
    {
        "HIGH": {"DoubleType": "26.17"},
        "SYMBOL": {"StringType": "ANH-A"},
        "LOW": {"DoubleType": "26.02"},
        "VOLUME": {"IntegerType": "2000"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "26.11"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "26.02"},
    },
    {
        "HIGH": {"DoubleType": "27.0"},
        "SYMBOL": {"StringType": "ANH-B"},
        "LOW": {"DoubleType": "26.81"},
        "VOLUME": {"IntegerType": "700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "27.0"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "26.81"},
    },
    {
        "HIGH": {"DoubleType": "25.23"},
        "SYMBOL": {"StringType": "ANH-C"},
        "LOW": {"DoubleType": "25.2"},
        "VOLUME": {"IntegerType": "1300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "25.22"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "25.23"},
    },
    {
        "HIGH": {"DoubleType": "237.0"},
        "SYMBOL": {"StringType": "ANTM"},
        "LOW": {"DoubleType": "233.9"},
        "VOLUME": {"IntegerType": "1520300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "235.0"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "234.0"},
    },
    {
        "HIGH": {"DoubleType": "57.65"},
        "SYMBOL": {"StringType": "ANTX"},
        "LOW": {"DoubleType": "56.91"},
        "VOLUME": {"IntegerType": "66900"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "57.3"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "57.28"},
    },
    {
        "HIGH": {"DoubleType": "4.725"},
        "SYMBOL": {"StringType": "ANW"},
        "LOW": {"DoubleType": "4.525"},
        "VOLUME": {"IntegerType": "317500"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "4.65"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "4.55"},
    },
    {
        "HIGH": {"DoubleType": "9.7"},
        "SYMBOL": {"StringType": "AOD"},
        "LOW": {"DoubleType": "9.65"},
        "VOLUME": {"IntegerType": "195800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "9.7"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "9.66"},
    },
    {
        "HIGH": {"DoubleType": "13.75"},
        "SYMBOL": {"StringType": "AOI"},
        "LOW": {"DoubleType": "13.4"},
        "VOLUME": {"IntegerType": "26700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11"},
        "CLOSE": {"DoubleType": "13.65"},
        "PART_DATE_STR": {"Date": "2018-01-11"},
        "OPEN": {"DoubleType": "13.4"},
    },
]
EXP_FILTERGRAM = {f"{WHERE_DATE}": ROW_COUNT}
EXP_JOB_EST = {"rowCount": ROW_COUNT, "colCount": 9}
EXP_DAYS_WITH = [
    {"rowcount": "3088", "days": "2018-01-16 00:00:00.0"},
    {"rowcount": "3087", "days": "2018-01-15 00:00:00.0"},
    {"rowcount": "3100", "days": "2018-01-12 00:00:00.0"},
    {"rowcount": "3104", "days": "2018-01-11 00:00:00.0"},
    {"rowcount": "3107", "days": "2018-01-10 00:00:00.0"},
    {"rowcount": "3105", "days": "2018-01-09 00:00:00.0"},
    {"rowcount": "3106", "days": "2018-01-08 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-05 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-04 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-03 00:00:00.0"},
    {"rowcount": "3113", "days": "2018-01-02 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-01 00:00:00.0"},
    {"rowcount": "3116", "days": "2017-12-29 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-28 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-27 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-26 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-25 00:00:00.0"},
    {"rowcount": "3121", "days": "2017-12-22 00:00:00.0"},
    {"rowcount": "3125", "days": "2017-12-21 00:00:00.0"},
    {"rowcount": "3127", "days": "2017-12-20 00:00:00.0"},
]
EXP_DS_SCAN = {
    "score": 100,
    "rc": 50,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0.0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_DS_SCORE = {
    "failScore": 75,
    "datashapeScore": 1.0,
    "dupeScore": 1.0,
    "schemaScore": 1.0,
    "recordScore": 1.0,
    "outlierScore": 1.0,
    "fpgScore": 1.0,
    "validateSrcScore": 1.0,
    "behaviorScore": 1.0,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0.0,
    "behaviorScoreOff": False,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}
DS_DEFS = {
    "dataset": DATASET,
    "runId": WHERE_DATE,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": "",
    "user": "anonymous : use -owluser",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": "", "uuid": ""},
    "load": {
        "dataset": DATASET,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": COL_NAME,
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": PATH,
        "fileQuery": QUERY,
        "fullFile": True,
        "fileHeader": "",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "csv",
        "delimiter": ",",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",  # Blank for file
        "additionalLib": "",
        "driverName": "",  # Blank for file
        "connectionName": CONN_NAME,
        "connectionUrl": "",  # Blank for file
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "profile": {
        "dataset": DATASET,
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "filter": "",
        "shape": True,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": None,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
        "profileStringLength": False,
        "dataConceptId": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET,
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
}

# --- JSON format ---
TABLE_NAME_GCS_JSON = "TEST_DATA_FILES/freddie_json.json"
DATASET_GCS_JSON = "APPROVED_GCS_JSON"
ROW_COUNT_GCS_JSON = 10
QUERY_GCS_JSON = f"select * from dataset limit {ROW_COUNT_GCS_JSON}"
PATH_GCS_JSON = f"{HOST_NAME}{TABLE_NAME_GCS_JSON}"
PL_DS_RUN_ID_GCS_JSON = {"dataset": DATASET_GCS_JSON, "runId": PROD_RUN_ID}
PL_DS_STATS_GCS_JSON = {"dataset": DATASET_GCS_JSON, "runId": PROD_RUN_ID, "sense": 3}

EXP_DS_SCORE_GCS_JSON = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": True,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}
EXP_DS_SCAN_GCS_JSON = {
    "score": 100,
    "rc": ROW_COUNT_GCS_JSON,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_JOB_EST_GCS_JSON = {
    "rowCount": ROW_COUNT_GCS_JSON,
    "colCount": 27,
}
DS_DEFS_GCS_JSON = {
    "dataset": DATASET_GCS_JSON,
    "runId": PROD_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": "",
    "user": "",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 1, "uuid": ""},
    "load": {
        "dataset": DATASET_GCS_JSON,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyyMM",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": PATH_GCS_JSON,
        "fileQuery": QUERY_GCS_JSON,
        "fullFile": True,
        "fileHeader": "",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "json",
        "delimiter": ",",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME_GCS,
        "connectionUrl": "",
        "userName": "serviceaccount",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "ruleSerial": False,
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "outliers": [],
    "outlier": {
        "id": None,
        "dataset": None,
        "on": False,
        "only": False,
        "lookback": 5,
        "key": None,
        "include": None,
        "exclude": None,
        "dateColumn": None,
        "timeColumn": None,
        "timeBin": "DAY",
        "timeBinQuery": "",
        "categorical": True,
        "by": None,
        "limit": 300,
        "minHistory": 3,
        "historyLimit": 5,
        "score": 1.0,
        "aggFunc": "",
        "aggQuery": "",
        "query": "",
        "q1": 0.15,
        "q3": 0.85,
        "categoricalColumnConcatenation": False,
        "limitCategorical": None,
        "measurementUnit": "",
        "multiplierUpper": 1.35,
        "multiplierLower": 1.35,
        "record": True,
        "filter": None,
        "combine": True,
        "categoricalConfidenceType": "",
        "categoricalTopN": 3,
        "categoricalBottomN": 2,
        "categoricalMaxConfidence": 0.02,
        "categoricalMaxFrequencyPercentile": 0.25,
        "categoricalMinFrequency": 1,
        "categoricalMinVariance": 0.0,
        "categoricalMaxCategoryN": 1,
        "categoricalParallel": True,
        "categoricalAlgorithm": "",
        "categoricalAlgorithmParameters": {},
    },
    "pattern": {
        "id": None,
        "dataset": None,
        "only": False,
        "lookback": 5,
        "key": None,
        "dateColumn": None,
        "include": None,
        "exclude": None,
        "score": 1.0,
        "minSupport": 3.3e-5,
        "confidence": 0.6,
        "limit": 30,
        "query": "",
        "filter": None,
        "timeBin": "DAY",
        "on": False,
        "match": True,
        "lowFreq": False,
        "bucketLimit": 450000,
        "deDupe": True,
    },
    "patterns": [],
    "dupe": {
        "dataset": None,
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1.0,
        "limit": 300,
    },
    "pushdown": {
        "dataset": DATASET_GCS_JSON,
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sqlLoggingToggle": True,
    },
    "profile": {
        "dataset": DATASET_GCS_JSON,
        "on": True,
        "only": False,
        "include": [
            "channel",
            "credit_score",
            "debt_to_income_ratio",
            "first_payment_date",
            "first_time_buyer",
            "loan_purpose",
            "loan_seq_number",
            "loan_to_value",
            "maturity_date",
            "mortgage_insurance_percentage",
            "msa",
            "no_of_borrowers",
            "no_of_units",
            "ocuupancy_status",
            "orig_interest_rate",
            "orig_loan_term",
            "orig_upb",
            "original_ltv",
            "postal_code",
            "ppm_flag",
            "preharp_loan_sequence_number",
            "product_type",
            "property_state",
            "property_type",
            "seller_name",
            "servicer_name",
            "super_confirming_flag",
        ],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": False,
        "histogram": False,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": False,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": False,
        "behaviorEmptyCheck": False,
        "behaviorUniqueCheck": False,
        "adaptiveTier": None,
        "profileStringLength": False,
        "detectStringNumerics": True,
        "detectTopnBotn": True,
        "detectScalePrecision": True,
        "dataConceptId": None,
        "advancedTier": None,
    },
    "source": {
        "on": False,
        "only": False,
        "validateValues": False,
        "key": None,
        "include": None,
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1.0,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNull": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateValuesShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": "",
        "datasetSrc": "",
        "driverName": "",
        "user": "",
        "password": "",
        "passwordManager": "",
        "connectionName": "",
        "connectionUrl": "",
        "query": "",
        "lib": "",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
        "hasHeader": True,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET_GCS_JSON,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET_GCS_JSON,
        "numExecutors": 3,
        "driverMemory": "4g",
        "executorMemory": "2g",
        "executorCores": 4,
        "conf": "spark.executor.memoryOverhead=1g",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"dataset": DATASET_GCS_JSON, "jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}

# --- Parquet format
TABLE_NAME_GCS_PQ = "user_data.parquet"
DATASET_GCS_PQ = "APPROVED_GCS_PQ"
ROW_COUNT_GCS_PQ = 10
QUERY_GCS_PQ = f"select * from dataset limit {ROW_COUNT_GCS_PQ}"
PATH_GCS_PQ = f"{HOST_NAME}{TABLE_NAME_GCS_PQ}"
PL_DS_RUN_ID_GCS_PQ = {"dataset": DATASET_GCS_PQ, "runId": PROD_RUN_ID}
PL_DS_STATS_GCS_PQ = {"dataset": DATASET_GCS_PQ, "runId": PROD_RUN_ID, "sense": 3}

EXP_DS_SCORE_GCS_PQ = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": False,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}
EXP_DS_SCAN_GCS_PQ = {
    "score": 100,
    "rc": ROW_COUNT_GCS_PQ,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_JOB_EST_GCS_PQ = {
    "rowCount": ROW_COUNT_GCS_PQ,
    "colCount": 13,
}
DS_DEFS_GCS_PQ = {
    "dataset": DATASET_GCS_PQ,
    "runId": PROD_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": None,
    "user": "anonymous : use -owluser",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "dataset": DATASET_GCS_PQ,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": PATH_GCS_PQ,
        "fileQuery": QUERY_GCS_PQ,
        "fullFile": True,
        "fileHeader": "",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "parquet",
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME_GCS,
        "connectionUrl": "",
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "profile": {
        "dataset": DATASET_GCS_PQ,
        "on": False,
        "only": False,
        "include": [
            "birthdate",
            "cc",
            "comments",
            "country",
            "email",
            "first_name",
            "gender",
            "id",
            "ip_address",
            "last_name",
            "registration_dttm",
            "salary",
            "title",
        ],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": False,
        "histogram": False,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": False,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": False,
        "behaviorEmptyCheck": False,
        "behaviorUniqueCheck": False,
        "adaptiveTier": None,
        "profileStringLength": False,
        "dataConceptId": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET_GCS_PQ,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET_GCS_PQ,
        "numExecutors": 1,
        "driverMemory": "4g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}
