CONN_NAME = "APPROVED_HDFS_KT"
FILE_CHAR_SET = "UTF-8"
ROW_COUNT = 50
WHERE_DATE = "2017-12-20"
TABLE_NAME = "nyse.csv"
COL_NAME = "TRADE_DATE"
DATASET = "AUTO_CXN_HDFS_KT"
QUERY = f"select * from {TABLE_NAME} where {COL_NAME} = '{WHERE_DATE}' limit {ROW_COUNT}"
PATH = f"/{TABLE_NAME}"
FILE_PATH = (
    f"hdfs://cdp-master-01.us-central1-a.c.owl-hadoop-cdh.internal:8020//TEST_DATA_FILES{PATH}"
)


PL_DS_GEN = {"dataset": DATASET, "runId": WHERE_DATE}
PL_DS_STATS = {"dataset": DATASET, "runId": WHERE_DATE, "sense": 3}
PL_FILTERGRAM = {
    "dataset": DATASET,
    "column": COL_NAME,
    "runid": f"{WHERE_DATE}T00:00:00.000 0000",
    "datevalue": f"{WHERE_DATE} 00:00:00 00",
    "limit": 500,
}
PL_DAYS_WITH_DATA = {
    "connectionalias": CONN_NAME,
    "path": TABLE_NAME,
    "colNm": COL_NAME,
    "type": "csv",
}
PL_JOB_EST = {
    "aliasname": CONN_NAME,
    "cols": "CLOSE,EXCH,HIGH,LOW,OPEN,PART_DATE_STR,SYMBOL,TRADE_DATE,VOLUME",
    "path": TABLE_NAME,
    "query": QUERY,
    "type": "csv",
}
PL_READ_REMOTE_FILE = {
    "connectionalias": CONN_NAME,
    "path": PATH,
    "type": "csv",
    "rowtag": "",
    "delimiter": ",",
    "hasheaders": True,
    "header": "",
    "charset": "UTF-8",
    "dtfmt": "yyyy-MM-dd",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}

EXP_READ_REMOTE_FILE = [
    {
        "HIGH": {"DoubleType": "4.16"},
        "SYMBOL": {"StringType": "ANFI"},
        "LOW": {"DoubleType": "4.05"},
        "VOLUME": {"IntegerType": "112800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "4.07"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "4.09"},
    },
    {
        "HIGH": {"DoubleType": "5.35"},
        "SYMBOL": {"StringType": "ANH"},
        "LOW": {"DoubleType": "5.28"},
        "VOLUME": {"IntegerType": "507600"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "5.34"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "5.3"},
    },
    {
        "HIGH": {"DoubleType": "26.17"},
        "SYMBOL": {"StringType": "ANH-A"},
        "LOW": {"DoubleType": "26.02"},
        "VOLUME": {"IntegerType": "2000"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "26.11"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "26.02"},
    },
    {
        "HIGH": {"DoubleType": "27.0"},
        "SYMBOL": {"StringType": "ANH-B"},
        "LOW": {"DoubleType": "26.81"},
        "VOLUME": {"IntegerType": "700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "27.0"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "26.81"},
    },
    {
        "HIGH": {"DoubleType": "25.23"},
        "SYMBOL": {"StringType": "ANH-C"},
        "LOW": {"DoubleType": "25.2"},
        "VOLUME": {"IntegerType": "1300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "25.22"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "25.23"},
    },
    {
        "HIGH": {"DoubleType": "237.0"},
        "SYMBOL": {"StringType": "ANTM"},
        "LOW": {"DoubleType": "233.9"},
        "VOLUME": {"IntegerType": "1520300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "235.0"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "234.0"},
    },
    {
        "HIGH": {"DoubleType": "57.65"},
        "SYMBOL": {"StringType": "ANTX"},
        "LOW": {"DoubleType": "56.91"},
        "VOLUME": {"IntegerType": "66900"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "57.3"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "57.28"},
    },
    {
        "HIGH": {"DoubleType": "4.725"},
        "SYMBOL": {"StringType": "ANW"},
        "LOW": {"DoubleType": "4.525"},
        "VOLUME": {"IntegerType": "317500"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "4.65"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "4.55"},
    },
    {
        "HIGH": {"DoubleType": "9.7"},
        "SYMBOL": {"StringType": "AOD"},
        "LOW": {"DoubleType": "9.65"},
        "VOLUME": {"IntegerType": "195800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "9.7"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "9.66"},
    },
    {
        "HIGH": {"DoubleType": "13.75"},
        "SYMBOL": {"StringType": "AOI"},
        "LOW": {"DoubleType": "13.4"},
        "VOLUME": {"IntegerType": "26700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "13.65"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "13.4"},
    },
]
EXP_FILTERGRAM = {f"{WHERE_DATE}": ROW_COUNT}
EXP_JOB_EST = {"rowCount": ROW_COUNT, "colCount": 9}
EXP_DAYS_WITH = [
    {"rowcount": "3088", "days": "2018-01-16 00:00:00.0"},
    {"rowcount": "3087", "days": "2018-01-15 00:00:00.0"},
    {"rowcount": "3100", "days": "2018-01-12 00:00:00.0"},
    {"rowcount": "3104", "days": "2018-01-11 00:00:00.0"},
    {"rowcount": "3107", "days": "2018-01-10 00:00:00.0"},
    {"rowcount": "3105", "days": "2018-01-09 00:00:00.0"},
    {"rowcount": "3106", "days": "2018-01-08 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-05 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-04 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-03 00:00:00.0"},
    {"rowcount": "3113", "days": "2018-01-02 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-01 00:00:00.0"},
    {"rowcount": "3116", "days": "2017-12-29 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-28 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-27 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-26 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-25 00:00:00.0"},
    {"rowcount": "3121", "days": "2017-12-22 00:00:00.0"},
    {"rowcount": "3125", "days": "2017-12-21 00:00:00.0"},
    {"rowcount": "3127", "days": "2017-12-20 00:00:00.0"},
]
EXP_DS_SCAN = {
    "score": 100,
    "rc": 50,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_DS_SCORE = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": True,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}

DS_DEFS = {
    "dataset": DATASET,
    "runId": WHERE_DATE,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": "",
    "user": "",
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNone": False,
        "replaceNones": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy/MM/dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": FILE_PATH,
        "fileQuery": QUERY,
        "fullFile": True,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "remoteFileConndriverlocation",
        "additionalLib": "",
        "driverName": "remoteFileConnDriver",
        "connectionName": CONN_NAME,
        "connectionUrl": "hdfs://cdp-master-01.us-central1-a.c.owl-hadoop-cdh.internal:8020/",
        "userName": "dq-user@DQ.CP.COLLIBRA.DEV",
        "password": "",
        "connectionProperties": {"hadoop.rpc.protection": "privacy"},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "partitionNumber": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "pushdown": {
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sqlLoggingToggle": True,
    },
    "outliers": [],
    "patterns": [],
    "dupe": {
        "on": False,
        "only": False,
        "include": None,
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1,
        "limit": 300,
    },
    "profile": {
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": False,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNoneCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
        "profileStringLength": False,
    },
    "source": {
        "on": False,
        "only": False,
        "validateValues": False,
        "key": None,
        "include": None,
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": None,
        "score": 1,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNone": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateValuesShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": "",
        "driverName": "",
        "user": "",
        "password": "",
        "passwordManager": "",
        "connectionName": "",
        "connectionUrl": "",
        "query": "",
        "lib": "",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "4g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "dq-user@DQ.CP.COLLIBRA.DEV",
        "keyTab": "/tmp/keytab/dq-user.keytab",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "record": {
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1,
        "dataset": None,
        "dateColumn": None,
        "keyColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "streamDefDTO": None,
    "pipeline": [],
}
