# ---- COMMON
from utils.constants import PROD_RUN_ID

CONN_NAME = "APPROVED_S3_KEY"
FILE_CHAR_SET = "UTF-8"
ROW_COUNT = 50

WHERE_DATE = "2017-12-20"
WHERE_DATE_PQT = "2022-06-06"
TABLE_NAME = "nyse.csv"
COL_NAME = "TRADE_DATE"
DATASET = "AUTO_CXN_S3"
DATASET_PIPE = "AUTO_CXN_S3_PIPE"
DATASET_JSON = "AUTO_CXN_S3_JSON"
DATASET_PQT = "AUTO_CXN_S3_PQT"
QUERY = f"select * from {TABLE_NAME} where {COL_NAME} = '{WHERE_DATE}' limit {ROW_COUNT}"
QUERY_PQT = f"select * from dataset where Date > '{WHERE_DATE_PQT}' limit {ROW_COUNT}"

PATH = f"/{TABLE_NAME}"
PATH_PIPE = "/PankajCSV/NOHEADERS_PIPE_DELIMITED_PANKAJ_Student_Performance_DATA.csv"
PATH_JSON = "/TEST_DATA_FILES/freddie_json.json"
PATH_PQT = "/TEST_DATA_FILES/covid19_timeseries_us_all_june_26.snappy.parquet"
FILE_PATH = f"s3a://cdq-datasets-hr7wprr{PATH}"

PL_DS_GEN = {"dataset": DATASET, "runId": WHERE_DATE}
PL_DS_STATS = {"dataset": DATASET, "runId": WHERE_DATE, "sense": 3}
PL_DS_RID_PIPE = {"dataset": DATASET_PIPE, "runId": PROD_RUN_ID}
PL_DS_STATS_PIPE = {"dataset": DATASET_PIPE, "runId": PROD_RUN_ID, "sense": 3}
PL_DS_RID_JSON = {"dataset": DATASET_JSON, "runId": PROD_RUN_ID}
PL_DS_STATS_JSON = {"dataset": DATASET_JSON, "runId": PROD_RUN_ID, "sense": 3}
PL_DS_RID_PQT = {"dataset": DATASET_PQT, "runId": WHERE_DATE_PQT}
PL_DS_STATS_PQT = {"dataset": DATASET_PQT, "runId": WHERE_DATE_PQT, "sense": 3}

PL_FILTERGRAM = {
    "dataset": DATASET,
    "column": COL_NAME,
    "runid": f"{WHERE_DATE}T00:00:00.000 0000",
    "datevalue": f"{WHERE_DATE} 00:00:00 00",
    "limit": 500,
}
PL_DAYS_WITH_DATA = {
    "connectionalias": CONN_NAME,
    "path": TABLE_NAME,
    "colNm": COL_NAME,
    "type": "csv",
}
PL_DAYS_WITH_DATA_PQT = {
    "connectionalias": CONN_NAME,
    "path": PATH_PQT,
    "colNm": "DATE",
    "type": "parquet",
}
PL_JOB_EST = {
    "aliasname": CONN_NAME,
    "cols": "CLOSE,EXCH,HIGH,LOW,OPEN,PART_DATE_STR,SYMBOL,TRADE_DATE,VOLUME",
    "path": TABLE_NAME,
    "query": QUERY,
    "type": "csv",
}

PL_READ_REMOTE_FILE = {
    "connectionalias": CONN_NAME,
    "path": PATH,
    "type": "csv",
    "rowtag": "",
    "delimiter": ",",
    "hasheaders": True,
    "header": "",
    "charset": FILE_CHAR_SET,
    "dtfmt": "yyyy-MM-dd",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}
PL_READ_REMOTE_FILE_PIPE = {
    "connectionalias": CONN_NAME,
    "path": PATH_PIPE,
    "type": "csv",
    "rowtag": "",
    "delimiter": "|",
    "hasheaders": True,
    "header": "col1,col2,col3,col4,col5,col6,col7,col8",
    "charset": FILE_CHAR_SET,
    "dtfmt": "",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}
PL_READ_REMOTE_FILE_JSON = {
    "connectionalias": CONN_NAME,
    "path": PATH_JSON,
    "type": "json",
    "rowtag": "",
    "delimiter": ",",
    "hasheaders": True,
    "header": None,
    "charset": FILE_CHAR_SET,
    "dtfmt": "",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}
PL_READ_REMOTE_FILE_PQT = {
    "connectionalias": CONN_NAME,
    "path": PATH_PQT,
    "type": "parquet",
    "rowtag": "",
    "delimiter": ",",
    "hasheaders": True,
    "header": None,
    "charset": FILE_CHAR_SET,
    "dtfmt": "",
    "resetcache": True,
    "skiplines": 0,
    "multiline": False,
    "flatten": False,
}

EXP_READ_REMOTE_FILE = [
    {
        "HIGH": {"DoubleType": "4.16"},
        "SYMBOL": {"StringType": "ANFI"},
        "LOW": {"DoubleType": "4.05"},
        "VOLUME": {"IntegerType": "112800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "4.07"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "4.09"},
    },
    {
        "HIGH": {"DoubleType": "5.35"},
        "SYMBOL": {"StringType": "ANH"},
        "LOW": {"DoubleType": "5.28"},
        "VOLUME": {"IntegerType": "507600"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "5.34"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "5.3"},
    },
    {
        "HIGH": {"DoubleType": "26.17"},
        "SYMBOL": {"StringType": "ANH-A"},
        "LOW": {"DoubleType": "26.02"},
        "VOLUME": {"IntegerType": "2000"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "26.11"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "26.02"},
    },
    {
        "HIGH": {"DoubleType": "27.0"},
        "SYMBOL": {"StringType": "ANH-B"},
        "LOW": {"DoubleType": "26.81"},
        "VOLUME": {"IntegerType": "700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "27.0"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "26.81"},
    },
    {
        "HIGH": {"DoubleType": "25.23"},
        "SYMBOL": {"StringType": "ANH-C"},
        "LOW": {"DoubleType": "25.2"},
        "VOLUME": {"IntegerType": "1300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "25.22"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "25.23"},
    },
    {
        "HIGH": {"DoubleType": "237.0"},
        "SYMBOL": {"StringType": "ANTM"},
        "LOW": {"DoubleType": "233.9"},
        "VOLUME": {"IntegerType": "1520300"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "235.0"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "234.0"},
    },
    {
        "HIGH": {"DoubleType": "57.65"},
        "SYMBOL": {"StringType": "ANTX"},
        "LOW": {"DoubleType": "56.91"},
        "VOLUME": {"IntegerType": "66900"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "57.3"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "57.28"},
    },
    {
        "HIGH": {"DoubleType": "4.725"},
        "SYMBOL": {"StringType": "ANW"},
        "LOW": {"DoubleType": "4.525"},
        "VOLUME": {"IntegerType": "317500"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "4.65"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "4.55"},
    },
    {
        "HIGH": {"DoubleType": "9.7"},
        "SYMBOL": {"StringType": "AOD"},
        "LOW": {"DoubleType": "9.65"},
        "VOLUME": {"IntegerType": "195800"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "9.7"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "9.66"},
    },
    {
        "HIGH": {"DoubleType": "13.75"},
        "SYMBOL": {"StringType": "AOI"},
        "LOW": {"DoubleType": "13.4"},
        "VOLUME": {"IntegerType": "26700"},
        "EXCH": {"StringType": "NYSE"},
        "TRADE_DATE": {"Date": "2018-01-11 00:00:00.0"},
        "CLOSE": {"DoubleType": "13.65"},
        "PART_DATE_STR": {"Date": "2018-01-11 00:00:00.0"},
        "OPEN": {"DoubleType": "13.4"},
    },
]
EXP_READ_REMOTE_FILE_PIPE = [
    {
        "col8": {"IntegerType": "88"},
        "col6": {"IntegerType": "69"},
        "col7": {"IntegerType": "90"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "completed"},
        "col2": {"StringType": "group C"},
        "col3": {"StringType": "some college"},
        "col1": {"StringType": "female"},
    },
    {
        "col8": {"IntegerType": "93"},
        "col6": {"IntegerType": "90"},
        "col7": {"IntegerType": "95"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group B"},
        "col3": {"StringType": "master's degree"},
        "col1": {"StringType": "female"},
    },
    {
        "col8": {"IntegerType": "44"},
        "col6": {"IntegerType": "47"},
        "col7": {"IntegerType": "57"},
        "col4": {"StringType": "free/reduced"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group A"},
        "col3": {"StringType": "associate's degree"},
        "col1": {"StringType": "male"},
    },
    {
        "col8": {"IntegerType": "75"},
        "col6": {"IntegerType": "76"},
        "col7": {"IntegerType": "78"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group C"},
        "col3": {"StringType": "some college"},
        "col1": {"StringType": "male"},
    },
    {
        "col8": {"IntegerType": "78"},
        "col6": {"IntegerType": "71"},
        "col7": {"IntegerType": "83"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group B"},
        "col3": {"StringType": "associate's degree"},
        "col1": {"StringType": "female"},
    },
    {
        "col8": {"IntegerType": "92"},
        "col6": {"IntegerType": "88"},
        "col7": {"IntegerType": "95"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "completed"},
        "col2": {"StringType": "group B"},
        "col3": {"StringType": "some college"},
        "col1": {"StringType": "female"},
    },
    {
        "col8": {"IntegerType": "39"},
        "col6": {"IntegerType": "40"},
        "col7": {"IntegerType": "43"},
        "col4": {"StringType": "free/reduced"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group B"},
        "col3": {"StringType": "some college"},
        "col1": {"StringType": "male"},
    },
    {
        "col8": {"IntegerType": "67"},
        "col6": {"IntegerType": "64"},
        "col7": {"IntegerType": "64"},
        "col4": {"StringType": "free/reduced"},
        "col5": {"StringType": "completed"},
        "col2": {"StringType": "group D"},
        "col3": {"StringType": "high school"},
        "col1": {"StringType": "male"},
    },
    {
        "col8": {"IntegerType": "50"},
        "col6": {"IntegerType": "38"},
        "col7": {"IntegerType": "60"},
        "col4": {"StringType": "free/reduced"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group B"},
        "col3": {"StringType": "high school"},
        "col1": {"StringType": "female"},
    },
    {
        "col8": {"IntegerType": "52"},
        "col6": {"IntegerType": "58"},
        "col7": {"IntegerType": "54"},
        "col4": {"StringType": "standard"},
        "col5": {"StringType": "none"},
        "col2": {"StringType": "group C"},
        "col3": {"StringType": "associate's degree"},
        "col1": {"StringType": "male"},
    },
]
EXP_READ_REMOTE_FILE_JSON = [
    {
        "credit_score": {"LongType": "779"},
        "orig_upb": {"LongType": "399000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204904"},
        "orig_interest_rate": {"DoubleType": "4.25"},
        "loan_purpose": {"StringType": "P"},
        "property_state": {"StringType": "ND"},
        "first_time_buyer": {"StringType": "N"},
        "loan_to_value": {"LongType": "80"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "1"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "44"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000001"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "80"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": "22020"},
        "first_payment_date": {"LongType": "201905"},
        "postal_code": {"LongType": "58100"},
    },
    {
        "credit_score": {"LongType": "636"},
        "orig_upb": {"LongType": "364000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204907"},
        "orig_interest_rate": {"DoubleType": "5.375"},
        "loan_purpose": {"StringType": "N"},
        "property_state": {"StringType": "KY"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "80"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "2"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "27"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000002"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "80"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": "14540"},
        "first_payment_date": {"LongType": "201908"},
        "postal_code": {"LongType": "42100"},
    },
    {
        "credit_score": {"LongType": "669"},
        "orig_upb": {"LongType": "240000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204906"},
        "orig_interest_rate": {"DoubleType": "4.375"},
        "loan_purpose": {"StringType": "N"},
        "property_state": {"StringType": "GA"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "66"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "1"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "42"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000003"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "66"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": "12060"},
        "first_payment_date": {"LongType": "201907"},
        "postal_code": {"LongType": "30200"},
    },
    {
        "credit_score": {"LongType": "814"},
        "orig_upb": {"LongType": "78000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "203405"},
        "orig_interest_rate": {"DoubleType": "4.0"},
        "loan_purpose": {"StringType": "C"},
        "property_state": {"StringType": "IL"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "65"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "180"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "1"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "22"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000004"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "65"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": ""},
        "first_payment_date": {"LongType": "201906"},
        "postal_code": {"LongType": "61400"},
    },
    {
        "credit_score": {"LongType": "794"},
        "orig_upb": {"LongType": "262000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "203405"},
        "orig_interest_rate": {"DoubleType": "3.75"},
        "loan_purpose": {"StringType": "N"},
        "property_state": {"StringType": "IA"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "76"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "180"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "1"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "39"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000005"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "76"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": ""},
        "first_payment_date": {"LongType": "201906"},
        "postal_code": {"LongType": "51300"},
    },
    {
        "credit_score": {"LongType": "724"},
        "orig_upb": {"LongType": "413000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204907"},
        "orig_interest_rate": {"DoubleType": "4.125"},
        "loan_purpose": {"StringType": "N"},
        "property_state": {"StringType": "OH"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "64"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "2"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "34"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000006"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "64"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "CMC FUNDING, INC."},
        "msa": {"LongType": "49660"},
        "first_payment_date": {"LongType": "201908"},
        "postal_code": {"LongType": "44400"},
    },
    {
        "credit_score": {"LongType": "625"},
        "orig_upb": {"LongType": "45000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "203405"},
        "orig_interest_rate": {"DoubleType": "5.75"},
        "loan_purpose": {"StringType": "C"},
        "property_state": {"StringType": "IL"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "75"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "180"},
        "ppm_flag": {"StringType": ""},
        "no_of_borrowers": {"LongType": "2"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "29"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000007"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "75"},
        "ocuupancy_status": {"StringType": "I"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": ""},
        "first_payment_date": {"LongType": "201906"},
        "postal_code": {"LongType": "61300"},
    },
    {
        "credit_score": {"LongType": "736"},
        "orig_upb": {"LongType": "207000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204906"},
        "orig_interest_rate": {"DoubleType": "4.375"},
        "loan_purpose": {"StringType": "P"},
        "property_state": {"StringType": "PA"},
        "first_time_buyer": {"StringType": "Y"},
        "loan_to_value": {"LongType": "90"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "2"},
        "property_type": {"StringType": "PU"},
        "debt_to_income_ratio": {"LongType": "20"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000008"},
        "mortgage_insurance_percentage": {"LongType": "25"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "90"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": "49620"},
        "first_payment_date": {"LongType": "201907"},
        "postal_code": {"LongType": "17300"},
    },
    {
        "credit_score": {"LongType": "804"},
        "orig_upb": {"LongType": "90000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204906"},
        "orig_interest_rate": {"DoubleType": "4.375"},
        "loan_purpose": {"StringType": "N"},
        "property_state": {"StringType": "KY"},
        "first_time_buyer": {"StringType": "9"},
        "loan_to_value": {"LongType": "48"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "1"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "42"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000009"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "48"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": "36980"},
        "first_payment_date": {"LongType": "201907"},
        "postal_code": {"LongType": "42300"},
    },
    {
        "credit_score": {"LongType": "786"},
        "orig_upb": {"LongType": "200000"},
        "channel": {"StringType": "R"},
        "maturity_date": {"LongType": "204906"},
        "orig_interest_rate": {"DoubleType": "4.0"},
        "loan_purpose": {"StringType": "P"},
        "property_state": {"StringType": "KS"},
        "first_time_buyer": {"StringType": "N"},
        "loan_to_value": {"LongType": "80"},
        "seller_name": {"StringType": "Other sellers"},
        "orig_loan_term": {"LongType": "360"},
        "ppm_flag": {"StringType": "N"},
        "no_of_borrowers": {"LongType": "2"},
        "property_type": {"StringType": "SF"},
        "debt_to_income_ratio": {"LongType": "24"},
        "preharp_loan_sequence_number": {"StringType": "9"},
        "super_confirming_flag": {"StringType": ""},
        "no_of_units": {"LongType": "1"},
        "loan_seq_number": {"StringType": "F119Q2000010"},
        "mortgage_insurance_percentage": {"LongType": "0"},
        "product_type": {"StringType": "FRM"},
        "original_ltv": {"LongType": "80"},
        "ocuupancy_status": {"StringType": "P"},
        "servicer_name": {"StringType": "Other servicers"},
        "msa": {"LongType": ""},
        "first_payment_date": {"LongType": "201907"},
        "postal_code": {"LongType": "67600"},
    },
]
EXP_READ_REMOTE_FILE_PQT = [
    {
        "major_city": {"StringType": "Prattville"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Autauga"},
        "uuid": {"StringType": "eb3d9c37-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-86.64408227"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "55869.0"},
        "state_county": {"StringType": "Alabama_Autauga"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "32.53952745"},
    },
    {
        "major_city": {"StringType": "Daphne"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Baldwin"},
        "uuid": {"StringType": "eb3e1168-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-87.72207058"},
        "univ_largest": {"StringType": "Columbia Southern University"},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "223234.0"},
        "state_county": {"StringType": "Alabama_Baldwin"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "30.72774991"},
    },
    {
        "major_city": {"StringType": "Eufaula"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Barbour"},
        "uuid": {"StringType": "eb3e3879-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-85.3871286"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "24686.0"},
        "state_county": {"StringType": "Alabama_Barbour"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "31.868263"},
    },
    {
        "major_city": {"StringType": "Brent"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Bibb"},
        "uuid": {"StringType": "eb3e5f8a-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-87.1251146"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "22394.0"},
        "state_county": {"StringType": "Alabama_Bibb"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "32.99642064"},
    },
    {
        "major_city": {"StringType": "Oneonta"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Blount"},
        "uuid": {"StringType": "eb3e869b-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-86.56790593"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "57826.0"},
        "state_county": {"StringType": "Alabama_Blount"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "33.98210918"},
    },
    {
        "major_city": {"StringType": "Union Springs"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Bullock"},
        "uuid": {"StringType": "eb3ed4bc-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-85.71265535"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "10101.0"},
        "state_county": {"StringType": "Alabama_Bullock"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "32.10030533"},
    },
    {
        "major_city": {"StringType": "Greenville"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Butler"},
        "uuid": {"StringType": "eb3efbcd-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-86.68057478"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "19448.0"},
        "state_county": {"StringType": "Alabama_Butler"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "31.75300095"},
    },
    {
        "major_city": {"StringType": "Anniston"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Calhoun"},
        "uuid": {"StringType": "eb3f22de-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-85.82630386"},
        "univ_largest": {"StringType": "Jacksonville State University"},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "113605.0"},
        "state_county": {"StringType": "Alabama_Calhoun"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "33.77483727"},
    },
    {
        "major_city": {"StringType": "Valley"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Chambers"},
        "uuid": {"StringType": "eb3f70ff-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-85.39072749"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "33254.0"},
        "state_county": {"StringType": "Alabama_Chambers"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "32.91360079"},
    },
    {
        "major_city": {"StringType": "Centre"},
        "ncd_14": {"DoubleType": ""},
        "county": {"StringType": "Cherokee"},
        "uuid": {"StringType": "eb3fbf20-f58d-11ec-b56e-2f46688f4199"},
        "Date": {"StringType": "2020-01-22 00:00:00"},
        "long": {"DoubleType": "-85.60638968"},
        "univ_largest": {"StringType": ""},
        "cuml_sma14": {"DoubleType": ""},
        "population": {"DoubleType": "26196.0"},
        "state_county": {"StringType": "Alabama_Cherokee"},
        "State": {"StringType": "Alabama"},
        "ncdd_7": {"DoubleType": ""},
        "ncd_7": {"DoubleType": ""},
        "active_cases": {"DoubleType": "0.0"},
        "cuml_sma7": {"DoubleType": ""},
        "lat": {"DoubleType": "34.17805983"},
    },
]

EXP_FILTERGRAM = {f"{WHERE_DATE}": ROW_COUNT}
EXP_JOB_EST = {"rowCount": ROW_COUNT, "colCount": 9}
EXP_DAYS_WITH = [
    {"rowcount": "3088", "days": "2018-01-16 00:00:00.0"},
    {"rowcount": "3087", "days": "2018-01-15 00:00:00.0"},
    {"rowcount": "3100", "days": "2018-01-12 00:00:00.0"},
    {"rowcount": "3104", "days": "2018-01-11 00:00:00.0"},
    {"rowcount": "3107", "days": "2018-01-10 00:00:00.0"},
    {"rowcount": "3105", "days": "2018-01-09 00:00:00.0"},
    {"rowcount": "3106", "days": "2018-01-08 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-05 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-04 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-03 00:00:00.0"},
    {"rowcount": "3113", "days": "2018-01-02 00:00:00.0"},
    {"rowcount": "3111", "days": "2018-01-01 00:00:00.0"},
    {"rowcount": "3116", "days": "2017-12-29 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-28 00:00:00.0"},
    {"rowcount": "3117", "days": "2017-12-27 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-26 00:00:00.0"},
    {"rowcount": "3119", "days": "2017-12-25 00:00:00.0"},
    {"rowcount": "3121", "days": "2017-12-22 00:00:00.0"},
    {"rowcount": "3125", "days": "2017-12-21 00:00:00.0"},
    {"rowcount": "3127", "days": "2017-12-20 00:00:00.0"},
]
EXP_DAYS_WITH_PQT = [
    {"rowcount": "3256", "days": "2022-06-25 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-24 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-23 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-22 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-21 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-20 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-19 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-18 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-17 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-16 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-15 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-14 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-13 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-12 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-11 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-10 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-09 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-08 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-07 00:00:00.0"},
    {"rowcount": "3256", "days": "2022-06-06 00:00:00.0"},
]
EXP_DS_SCAN = {
    "score": 100,
    "rc": ROW_COUNT,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_DS_SCORE = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": True,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}
EXP_DS_SCORE_JSON = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": False,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}
EXP_DS_SCORE_PQT = {
  "failScore": 75,
  "datashapeScore": 1,
  "dupeScore": 1,
  "schemaScore": 1,
  "recordScore": 1,
  "outlierScore": 1,
  "fpgScore": 1,
  "validateSrcScore": 1,
  "behaviorScore": 1,
  "rulesTotalScore": 0,
  "validateSrcTotalScore": 0,
  "dupeTotalScore": 0,
  "fpgTotalScore": 0,
  "behaviorTotalScore": 0,
  "outlierTotalScore": 0,
  "schemaTotalScore": 0,
  "recordTotalScore": 0,
  "datashapeTotalScore": 0,
  "datashapeMaxPerCol": 20,
  "datashapeMaxColSize": 12,
  "datashapeSensitivity": 0,
  "behaviorScoreOff": True,
  "lbAbsRowCnt": None,
  "ubAbsRowCnt": None,
  "lbZscoreRowCnt": None,
  "ubZscoreRowCnt": None
}

DS_DEFS = {
    "dataset": DATASET,
    "runId": WHERE_DATE,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "",
    "port": "5",
    "user": "",
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 0, "uuid": ""},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNone": False,
        "replaceNones": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": FILE_PATH,
        "fileQuery": QUERY,
        "fullFile": True,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "remoteFileConndriverlocation",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME,
        "connectionUrl": "",
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "partitionNumber": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveBreakRecords": False,
        "archiveConnection": "",
    },
    "pushdown": {
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sqlLoggingToggle": True,
    },
    "profile": {
        "on": True,
        "only": False,
        "include": None,
        "exclude": None,
        "shape": False,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNoneCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
        "profileStringLength": False,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "4g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
}
DS_DEFS_PIPE = {
    "dataset": DATASET_PIPE,
    "runId": PROD_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "10.64.2.3:5432/rc202309?currentSchema=automation",
    "port": None,
    "user": "anonymous : use -owluser",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 11, "uuid": "a4f4a2c8-3acc-48d4-b715-88da2c0c1956"},
    "load": {
        "dataset": DATASET_PIPE,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": f"s3a://s3-datasets{PATH_PIPE}",
        "fileQuery": f"select col1,col2,col3,col4,col5,col6,col7,col8 from dataset "
        f"limit {ROW_COUNT}",
        "fullFile": True,
        "fileHeader": "col1,col2,col3,col4,col5,col6,col7,col8",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "csv",
        "delimiter": "|",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME,
        "connectionUrl": "",
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "ruleSerial": False,
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "profile": {
        "dataset": DATASET_PIPE,
        "on": True,
        "only": False,
        "include": ["col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": False,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": False,
        "behaviorEmptyCheck": False,
        "behaviorUniqueCheck": False,
        "adaptiveTier": None,
        "profileStringLength": False,
        "dataConceptId": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET_PIPE,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET_PIPE,
        "numExecutors": 1,
        "driverMemory": "4g",
        "executorMemory": "1g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}
DS_DEFS_JSON = {
    "dataset": DATASET_JSON,
    "runId": PROD_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "10.64.2.3:5432/rc202310?currentSchema=automation",
    "port": None,
    "user": "anonymous : use -owluser",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 518, "uuid": "e77bc3eb-bc90-4f02-b005-9939fd24e3b2"},
    "load": {
        "dataset": DATASET_JSON,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": f"s3a://s3-datasets{PATH_JSON}",
        "fileQuery": f"select * from dataset limit {ROW_COUNT}",
        "fullFile": True,
        "fileHeader": "",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "json",
        "delimiter": ",",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME,
        "connectionUrl": "",
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "ruleSerial": False,
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "profile": {
        "dataset": DATASET_JSON,
        "on": True,
        "only": False,
        "include": [
            "channel",
            "credit_score",
            "debt_to_income_ratio",
            "first_payment_date",
            "first_time_buyer",
            "loan_purpose",
            "loan_seq_number",
            "loan_to_value",
            "maturity_date",
            "mortgage_insurance_percentage",
            "msa",
            "no_of_borrowers",
            "no_of_units",
            "ocuupancy_status",
            "orig_interest_rate",
            "orig_loan_term",
            "orig_upb",
            "original_ltv",
            "postal_code",
            "ppm_flag",
            "preharp_loan_sequence_number",
            "product_type",
            "property_state",
            "property_type",
            "seller_name",
            "servicer_name",
            "super_confirming_flag",
        ],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "adaptiveTier": None,
        "profileStringLength": False,
        "detectStringNumerics": True,
        "detectTopnBotn": True,
        "detectScalePrecision": True,
        "dataConceptId": None,
        "advancedTier": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET_JSON,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET_JSON,
        "numExecutors": 3,
        "driverMemory": "4g",
        "executorMemory": "2g",
        "executorCores": 4,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}
DS_DEFS_PQT = {
    "dataset": DATASET_PQT,
    "runId": PROD_RUN_ID,
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "10.64.2.3:5432/rc202310?currentSchema=automation",
    "port": None,
    "user": "anonymous : use -owluser",
    "alertEmail": "",
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 518, "uuid": "e77bc3eb-bc90-4f02-b005-9939fd24e3b2"},
    "load": {
        "dataset": DATASET_PQT,
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "",
        "queryHistory": "",
        "key": "",
        "expression": "",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": "=",
        "dateColumn": "Date",
        "transform": "",
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": f"s3a://s3-datasets{PATH_PQT}",
        "fileQuery": QUERY_PQT,
        "fullFile": True,
        "fileHeader": "",
        "checkHeader": True,
        "inferSchema": True,
        "fileType": "parquet",
        "delimiter": ",",
        "fileCharSet": FILE_CHAR_SET,
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "",
        "additionalLib": "",
        "driverName": "",
        "connectionName": CONN_NAME,
        "connectionUrl": "",
        "userName": "",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "partitionNumber": 0,
        "archiveBreaks": False,
        "archiveConnection": "",
        "ruleSerial": False,
        "escapeCharacter": "",
        "hasHeader": False,
    },
    "profile": {
        "dataset": DATASET_PQT,
        "on": True,
        "only": False,
        "include": [
            "active_cases",
            "county",
            "cuml_sma14",
            "cuml_sma7",
            "Date",
            "lat",
            "long",
            "major_city",
            "ncd_14",
            "ncd_7",
            "ncdd_7",
            "population",
            "State",
            "state_county",
            "univ_largest",
            "uuid",
        ],
        "exclude": None,
        "filter": "",
        "shape": False,
        "correlation": None,
        "histogram": None,
        "semantic": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": False,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": True,
        "behaviorLookback": 10,
        "behaviorMinSupport": 4,
        "profilePushDown": None,
        "behaviorRowCheck": False,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": False,
        "behaviorEmptyCheck": False,
        "behaviorUniqueCheck": False,
        "adaptiveTier": None,
        "profileStringLength": False,
        "detectStringNumerics": True,
        "detectTopnBotn": True,
        "detectScalePrecision": True,
        "dataConceptId": None,
        "advancedTier": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "dataset": DATASET_PQT,
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "dataset": DATASET_PQT,
        "numExecutors": 2,
        "driverMemory": "4g",
        "executorMemory": "6g",
        "executorCores": 1,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"jdbcPrincipal": "", "jdbcKeyTab": ""},
    "stream": None,
    "record": {
        "dataset": None,
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "keyColumn": None,
        "dateColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "transforms": [],
    "pipeline": [],
    "jobDescription": "",
}
