WHERE_DATE = "2021-07-06"
TABLE_NAME = "default.aclaims_master"
COL_NAME = "cm_bdos"
DATASET = "AUTO_CXN_ATHENA_PUSHDOWN"
ROW_COUNT = 3
QUERY = (
    f"select * from {TABLE_NAME} where {COL_NAME} > try_cast('{WHERE_DATE}' as DATE) "
    f"limit {ROW_COUNT}"
)
CONN_NAME = "APPROVED_ATHENA_PUSHDOWN"

PL_DS_GEN = {"dataset": DATASET, "runId": WHERE_DATE}
PL_DS_STATS = {"dataset": DATASET, "runId": WHERE_DATE, "sense": 3}
PL_DAYS_WITH_DATA = {
    "cxn": CONN_NAME,
    "schemaAndTableNm": TABLE_NAME,
    "colNm": COL_NAME,
    "groupBy": "day",
}

EXP_DAYS_WITH = [
    {"rowcount": 6, "day_owl_str": "2021-07-06", "day": "2021-07-06"},
    {"rowcount": 1, "day_owl_str": "2021-07-07", "day": "2021-07-07"},
    {"rowcount": 1, "day_owl_str": "2021-07-08", "day": "2021-07-08"},
    {"rowcount": 1, "day_owl_str": "2021-07-09", "day": "2021-07-09"},
    {"rowcount": 1, "day_owl_str": "2021-07-10", "day": "2021-07-10"},
    {"rowcount": 2, "day_owl_str": "2021-07-12", "day": "2021-07-12"},
    {"rowcount": 2, "day_owl_str": "2021-07-13", "day": "2021-07-13"},
    {"rowcount": 2, "day_owl_str": "2021-07-14", "day": "2021-07-14"},
    {"rowcount": 1, "day_owl_str": "2021-07-15", "day": "2021-07-15"},
    {"rowcount": 1, "day_owl_str": "2021-07-16", "day": "2021-07-16"},
    {"rowcount": 2, "day_owl_str": "2021-07-18", "day": "2021-07-18"},
    {"rowcount": 2, "day_owl_str": "2021-07-20", "day": "2021-07-20"},
    {"rowcount": 1, "day_owl_str": "2021-07-25", "day": "2021-07-25"},
    {"rowcount": 1, "day_owl_str": "2021-07-26", "day": "2021-07-26"},
    {"rowcount": 3, "day_owl_str": "2021-07-27", "day": "2021-07-27"},
    {"rowcount": 2, "day_owl_str": "2021-07-28", "day": "2021-07-28"},
    {"rowcount": 1, "day_owl_str": "2021-08-11", "day": "2021-08-11"},
    {"rowcount": 1, "day_owl_str": "2021-11-02", "day": "2021-11-02"},
    {"rowcount": 1, "day_owl_str": "2021-11-29", "day": "2021-11-29"},
    {"rowcount": 1, "day_owl_str": "2025-05-19", "day": "2025-05-19"},
]
EXP_DS_SCAN = {
    "score": 100,
    "rc": ROW_COUNT,
    "passFail": 1,
    "peak": 1,
    "scoreDupe": 0,
    "scoreSource": 0,
    "scoreDatashape": 0,
    "scoreSchema": 0,
    "scoreRecord": 0,
    "scoreOutlier": 0,
    "scorePattern": 0,
    "scoreRule": 0,
    "scoreBehavior": 0,
    "passFailAvg": 0,
    "physicalName": None,
    "userLabel": None,
    "rcSrc": None,
    "passFailRc": 1,
    "pushDownOptions": None,
    "daysWithoutData": 0,
    "runsWithoutData": 0,
    "daysSinceLastRun": 0,
}
EXP_DS_SCORE = {
    "failScore": 75,
    "datashapeScore": 1,
    "dupeScore": 1,
    "schemaScore": 1,
    "recordScore": 1,
    "outlierScore": 1,
    "fpgScore": 1,
    "validateSrcScore": 1,
    "behaviorScore": 1,
    "rulesTotalScore": 0,
    "validateSrcTotalScore": 0,
    "dupeTotalScore": 0,
    "fpgTotalScore": 0,
    "behaviorTotalScore": 0,
    "outlierTotalScore": 0,
    "schemaTotalScore": 0,
    "recordTotalScore": 0,
    "datashapeTotalScore": 0,
    "datashapeMaxPerCol": 20,
    "datashapeMaxColSize": 12,
    "datashapeSensitivity": 0,
    "behaviorScoreOff": False,
    "lbAbsRowCnt": None,
    "ubAbsRowCnt": None,
    "lbZscoreRowCnt": None,
    "ubZscoreRowCnt": None,
}

AEF_ATHENA_PD_PAYLOAD = {
	"dataset": DATASET,
	"runId": WHERE_DATE,
	"runIdEnd": "",
	"runState": "DRAFT",
	"passFail": 1,
	"passFailLimit": 75,
	"jobDescription": "",
	"jobId": {
		"id": -1,
		"uuid": None
	},
	"coreMaxActiveConnections": None,
	"linkId": None,
	"licenseKey": "",
	"logFile": "",
	"logLevel": "INFO",
	"hootOnly": False,
	"prettyPrint": True,
	"useTemplate": False,
	"parallel": False,
	"plan": False,
	"dataPreviewOff": False,
	"datasetSafeOff": False,
	"obslimit": 300,
	"pgUser": "",
	"pgPassword": "",
	"host": "10.64.2.3:5432/dqqa?currentSchema=automation",
	"port": None,
	"user": "anonymous : use -owluser",
	"alertEmail": "",
	"scheduleTime": None,
	"schemaScore": 1,
	"optionAppend": "",
	"keyDelimiter": "~~",
	"agentId": {
		"id": 0,
		"uuid": None
	},
	"load": {
		"readonly": False,
		"passwordManager": None,
		"alias": "",
		"query": "",
		"queryHistory": "",
		"key": "",
		"expression": "",
		"addDateColumn": False,
		"zeroFillNull": False,
		"replaceNulls": "",
		"stringMode": False,
		"operator": None,
		"dateColumn": None,
		"transform": None,
		"filter": "",
		"filterNot": "",
		"sample": 1,
		"backRun": 0,
		"backRunBin": "DAY",
		"unionLookBack": False,
		"unionLookBackMinRow": 0,
		"cache": True,
		"dateFormat": "yyyy-MM-dd",
		"timeFormat": "HH:mm:ss.SSS",
		"timestamp": False,
		"filePath": "",
		"fileQuery": "",
		"fullFile": False,
		"fileHeader": None,
		"inferSchema": True,
		"fileType": None,
		"delimiter": ",",
		"fileCharSet": "UTF-8",
		"skipLines": 0,
		"avroSchema": "",
		"xmlRowTag": "",
		"flatten": False,
		"handleMaps": False,
		"handleMixedJson": False,
		"multiLine": False,
		"lib": "",
		"additionalLib": "",
		"driverName": None,
		"connectionName": "",
		"connectionUrl": "",
		"userName": "",
		"password": "",
		"connectionProperties": {},
		"hiveNative": None,
		"hiveNativeHWC": False,
		"useSql": True,
		"columnName": None,
		"lowerBound": None,
		"upperBound": None,
		"numPartitions": 0,
		"partitionNumber": 0,
		"escapeWithBackTick": False,
		"escapeWithSingleQuote": False,
		"escapeWithDoubleQuote": False,
		"escapeCharacter": "",
		"checkHeader": True,
		"archiveConnection": "",
		"coreFetchMode": False,
		"archiveBreaks": False,
		"ruleSerial": False
	},
	"pushdown": {
		"dataset": DATASET,
		"connectionName": CONN_NAME,
		"maxConnections": 10,
		"sourceQuery": QUERY,
		"backRuns": 0,
		"backRunBin": "DAY",
		"dateFormatType": "DATE",
		"threads": 2,
		"manualSourceQuery": False,
		"key": "",
		"sourceOutputSchema": "",
		"sourceBreakRules": False,
		"sourceBreakOutliers": False,
		"sourceBreakDupes": False,
		"sourceBreakShapes": False,
		"sourceBreakResults": False,
		"sqlLoggingToggle": False,
		"unionLookback": False,
		"unionLookbackMin": 0
	},
	"outliers": [],
	"patterns": [],
	"dupe": {
		"on": False,
		"only": False,
		"include": None,
		"exclude": None,
		"depth": 0,
		"lowerBound": 99,
		"upperBound": 100,
		"approximate": 1,
		"limitPerDupe": 15,
		"checkHeader": True,
		"filter": None,
		"ignoreCase": True,
		"score": 1,
		"limit": 300
	},
	"profile": {
		"on": True,
		"only": False,
		"include": [
			"cm_bdos",
			"cm_claim_status",
			"cm_claimant_age",
			"cm_claimant_bdate",
			"cm_claimant_sex",
			"cm_conversion_date",
			"cm_date_claim_paid",
			"cm_date_received",
			"cm_denied_reason1",
			"cm_denied_reason2",
			"cm_diagnosis_code",
			"cm_disab_days",
			"cm_doc_origin_dsc",
			"cm_edos",
			"cm_eff_date_family",
			"cm_end_treatmn_dte",
			"cm_fica_date",
			"cm_group_number",
			"cm_hospital_days",
			"cm_lob",
			"cm_medicare_number",
			"cm_pending_flag1",
			"cm_pending_flag2",
			"cm_pending_flag3",
			"cm_pending_flag4",
			"cm_proof_loss_dt",
			"cm_relationship",
			"cm_state_of_issue",
			"cm_state_of_res",
			"cm_tax_status"
		],
		"exclude": [],
		"correlation": None,
		"histogram": None,
		"semantic": None,
		"dataConceptId": 300,
		"limit": 300,
		"histogramLimit": 0,
		"score": 1,
		"shape": False,
		"shapeTotalScore": 0,
		"shapeSensitivity": 0,
		"shapeMaxPerCol": 20,
		"shapeMaxColSize": 12,
		"shapeGranular": None,
		"behavioralDimension": "",
		"behavioralDimensionGroup": "",
		"behavioralValueColumn": "",
		"behaviorScoreOff": False,
		"behaviorLookback": 10,
		"behaviorMinSupport": 4,
		"profilePushDown": [
			"count",
			"distinct",
			"mean",
			"minmax",
			"quality"
		],
		"behaviorRowCheck": True,
		"behaviorTimeCheck": False,
		"behaviorMinValueCheck": False,
		"behaviorMaxValueCheck": False,
		"behaviorMeanValueCheck": False,
		"behaviorNullCheck": True,
		"behaviorEmptyCheck": True,
		"behaviorUniqueCheck": True,
		"profileStringLength": False,
		"detectStringNumerics": False,
		"detectTopnBotn": False,
		"detectScalePrecision": False,
		"adaptiveTier": None,
		"advancedTier": False,
		"filter": ""
	},
	"source": {
		"on": False,
		"only": False,
		"validateValues": False,
		"key": None,
		"include": None,
		"exclude": None,
		"includeSrc": None,
		"excludeSrc": None,
		"map": None,
		"score": 1,
		"limit": 30,
		"sourcePushDownCount": False,
		"checkType": True,
		"checkCase": False,
		"validateSchemaOrder": False,
		"matches": False,
		"validateValuesThreshold": 0.9,
		"validateValuesThresholdStrictDownScore": False,
		"validateValuesShowAll": False,
		"validateValuesIgnoreNull": False,
		"validateValuesIgnoreEmpty": False,
		"validateValuesIgnorePrecision": False,
		"validateValuesTrim": False,
		"validateValuesShowMissingKeys": False,
		"validateSrcJoinOnly": False,
		"validateValuesFilter": "",
		"dataset": "",
		"driverName": "",
		"user": "",
		"password": "",
		"passwordManager": "",
		"connectionName": "",
		"connectionUrl": "",
		"query": "",
		"lib": "",
		"connectionProperties": {},
		"filePath": "",
		"fileQuery": "",
		"fullFile": False,
		"header": None,
		"skipLines": 0,
		"inferSchema": True,
		"fileType": None,
		"delimiter": ",",
		"fileCharSet": "UTF-8",
		"avroSchema": "",
		"xmlRowTag": "",
		"flatten": False,
		"handleMaps": False,
		"handleMixedJson": False,
		"multiLine": False,
		"filterCols": None
	},
	"rule": {
		"on": True,
		"only": False,
		"lib": None,
		"name": "",
		"absoluteScoring": False,
		"ruleBreakPreviewLimit": 6
	},
	"colMatch": {
		"colMatchParallelProcesses": 3,
		"colMatchDurationMins": 20,
		"colMatchBatchSize": 2,
		"level": "exact",
		"fuzzyDistance": 1,
		"connectionList": []
	},
	"spark": {
		"numExecutors": 3,
		"driverMemory": "",
		"executorMemory": "",
		"executorCores": 1,
		"conf": "",
		"queue": "",
		"master": "local[*]",
		"principal": "",
		"keyTab": "",
		"deployMode": "",
		"jars": None,
		"packages": None,
		"files": None
	},
	"env": {
		"dataset": DATASET,
		"jdbcPrincipal": "",
		"jdbcKeyTab": ""
	},
	"record": {
		"on": False,
		"in": "",
		"notIn": "",
		"include": None,
		"percDeltaLimit": 0.1,
		"score": 1,
		"dataset": None,
		"dateColumn": None,
		"keyColumn": None,
		"timeBin": "DAY",
		"by": None
	},
	"stream": None,
	"pipeline": [],
	"metaTags": None,
	"outlierConfiguration": None,
	"shape": {
		"enabled": False,
		"totalScore": 0,
		"sensitivity": 0,
		"maxPerCol": 20,
		"maxColSize": 12,
		"granular": None,
		"columnSettings": []
	},
	"jobSchedule": None,
	"connectionType": "PUSHDOWN"
}
