from payloads.pushdown.dupes.pl_pd_trino_dupes_score_case_employees_dt_archive_breaks import (
    PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
)

PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "home_phone": "865-418-3128",
                "street_address": "66675 High Crossing Way",
                "gender": "Male",
                "city": "Knoxville",
                "item_key": "9325151e141a0d45bc166774cbf181ab",
                "latitude": "40.7955",
                "last_name": "Clarage",
                "type": "DUPE",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "score": "85",
                "time_in_service_yrs": "2.96",
                "assignment_uuid": "a6f20694-fff4-4b03-b677-ba4b6963f4c4",
                "employee_id": "583",
                "date_of_hire": "11/6/2018",
                "state": "TN",
                "postal_code": "37924",
                "department": "Sales",
                "first_name": "Katherine",
                "email": "kclarageg6@creativecommons.org",
                "longitude": "-84.1383"
            },
            {
                "street_address": "8658 Ridgeway Point",
                "home_phone": "909-606-7780",
                "gender": "Male",
                "city": "San Bernardino",
                "item_key": "9325151e141a0d45bc166774cbf181ab",
                "latitude": "34.84",
                "last_name": "Clardge",
                "type": "DUPE",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "score": "85",
                "time_in_service_yrs": "3.12",
                "assignment_uuid": "a6f20694-fff4-4b03-b677-ba4b6963f4c4",
                "employee_id": "990",
                "date_of_hire": "9/9/2018",
                "state": "CA",
                "department": "Human Resources",
                "postal_code": "92424",
                "first_name": "Brook",
                "email": "bcheerrh@marketwatch.com",
                "longitude": "-115.9671"
            },
            {
                "street_address": "83 Kropf Way",
                "home_phone": "304-559-1266",
                "gender": "Male",
                "city": "Huntington",
                "item_key": "9a1c4af9baff0abbb13bec1a1d965600",
                "latitude": "38.4134",
                "last_name": "Clardge",
                "type": "DUPE",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "score": "85",
                "time_in_service_yrs": "3.31",
                "assignment_uuid": "f8c852ad-4b0e-460a-8bea-0503a1c569a2",
                "employee_id": "354",
                "date_of_hire": "7/2/2018",
                "state": "WV",
                "department": "Research and Development",
                "postal_code": "25716",
                "first_name": "Jdavie",
                "email": "jclardge9t@illinois.edu",
                "longitude": "-82.2774"
            },
            {
                "home_phone": "865-418-3128",
                "street_address": "66675 High Crossing Way",
                "gender": "Male",
                "city": "Knoxville",
                "item_key": "9a1c4af9baff0abbb13bec1a1d965600",
                "latitude": "40.7955",
                "last_name": "Clarage",
                "type": "DUPE",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "score": "85",
                "time_in_service_yrs": "2.96",
                "assignment_uuid": "f8c852ad-4b0e-460a-8bea-0503a1c569a2",
                "employee_id": "583",
                "date_of_hire": "11/6/2018",
                "state": "TN",
                "department": "Sales",
                "postal_code": "37924",
                "first_name": "Katherine",
                "email": "kclarageg6@creativecommons.org",
                "longitude": "-84.1383"
            },
            {
                "street_address": "150 Magdeline Crossing",
                "home_phone": "786-873-7423",
                "gender": "Female",
                "city": "Miami",
                "item_key": "9ef7b3b1d84d3bacfa0e0a108bffb750",
                "latitude": "25.6615",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:3][Pollins, 3]||[Rollins, 3]",
                "score": "85",
                "time_in_service_yrs": "6.05",
                "assignment_uuid": "674603ca-c7f9-472a-a25c-5af047ce12c7",
                "employee_id": "368",
                "date_of_hire": "10/7/2015",
                "state": "FL",
                "postal_code": "33196",
                "department": "Support",
                "first_name": "Ari",
                "email": "apollinsa7@pen.io",
                "longitude": "-80.441"
            },
            {
                "home_phone": "915-822-0254",
                "street_address": "732 Burning Wood Crossing",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "9ef7b3b1d84d3bacfa0e0a108bffb750",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:3][Pollins, 3]||[Rollins, 3]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "674603ca-c7f9-472a-a25c-5af047ce12c7",
                "employee_id": "499",
                "date_of_hire": "10/16/2018",
                "state": "TX",
                "department": "Business Development",
                "postal_code": "88535",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "street_address": "732 Burning Wood Crossing",
                "home_phone": "915-822-0254",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "59238f93f877bd5da4defea5f35be11d",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:4][Pollins, 4]||[Rollins, 4]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "d0f3d00c-d115-49ee-b4db-6a7c867bb8a8",
                "employee_id": "499",
                "date_of_hire": "10/16/2018",
                "state": "TX",
                "postal_code": "88535",
                "department": "Business Development",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "home_phone": "954-559-4887",
                "street_address": "2 Shelley Crossing",
                "gender": "NULL",
                "city": "Orlando",
                "item_key": "59238f93f877bd5da4defea5f35be11d",
                "latitude": "28.5469",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:4][Pollins, 4]||[Rollins, 4]",
                "score": "85",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "d0f3d00c-d115-49ee-b4db-6a7c867bb8a8",
                "employee_id": "988",
                "date_of_hire": "11/28/2018",
                "state": "FL",
                "department": "Legal",
                "postal_code": "32825",
                "first_name": "Kassi",
                "email": "kderellrf@ft.com",
                "longitude": "-81.2571"
            },
            {
                "street_address": "79438 Parkside Drive",
                "home_phone": "952-832-3196",
                "gender": "Female",
                "city": "Young America",
                "item_key": "28915ea401e38dd8d63ad0ec4aee101b",
                "latitude": "44.8055",
                "last_name": "Tainton",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Tainton, 5]||[Taunton, 5]",
                "score": "85",
                "time_in_service_yrs": "3.06",
                "assignment_uuid": "bbb5c763-ebac-4955-be62-efd99e82642f",
                "employee_id": "22",
                "state": "MN",
                "date_of_hire": "9/30/2018",
                "department": "Research and Development",
                "postal_code": "55557",
                "first_name": "Dyanne",
                "email": "dtaintonl@answers.com",
                "longitude": "-93.7665"
            },
            {
                "street_address": "43942 Forest Run Pass",
                "home_phone": "513-885-7912",
                "gender": "Female",
                "city": "Columbus",
                "item_key": "28915ea401e38dd8d63ad0ec4aee101b",
                "latitude": "39.9671",
                "last_name": "Taunton",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Tainton, 5]||[Taunton, 5]",
                "score": "85",
                "time_in_service_yrs": "5.98",
                "assignment_uuid": "bbb5c763-ebac-4955-be62-efd99e82642f",
                "employee_id": "437",
                "state": "OH",
                "date_of_hire": "11/1/2015",
                "postal_code": "43215",
                "department": "Engineering",
                "first_name": "Diena",
                "email": "dtauntonc4@about.com",
                "longitude": "-83.0044"
            },
            {
                "street_address": "150 Magdeline Crossing",
                "home_phone": "786-873-7423",
                "gender": "Female",
                "city": "Miami",
                "item_key": "d5d2183463ecdaf46b6bbd45fad256fd",
                "latitude": "25.6615",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[pollins, 6]",
                "score": "85",
                "time_in_service_yrs": "6.05",
                "assignment_uuid": "295451f5-72df-4e55-a10d-bfc6e3b188cf",
                "employee_id": "368",
                "date_of_hire": "10/7/2015",
                "state": "FL",
                "department": "Support",
                "postal_code": "33196",
                "first_name": "Ari",
                "email": "apollinsa7@pen.io",
                "longitude": "-80.441"
            },
            {
                "street_address": "5 Sunnyside Junction",
                "home_phone": "719-537-1533",
                "gender": "Female",
                "city": "Colorado Springs",
                "item_key": "d5d2183463ecdaf46b6bbd45fad256fd",
                "latitude": "38.7378",
                "last_name": "pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[pollins, 6]",
                "score": "85",
                "time_in_service_yrs": "3.5",
                "assignment_uuid": "295451f5-72df-4e55-a10d-bfc6e3b188cf",
                "employee_id": "987",
                "date_of_hire": "4/24/2018",
                "state": "CO",
                "department": "Marketing",
                "postal_code": "80925",
                "first_name": "Katinka",
                "email": "kendeanre@seesaa.net",
                "longitude": "-104.6459"
            },
            {
                "home_phone": "719-537-1533",
                "street_address": "5 Sunnyside Junction",
                "gender": "Female",
                "city": "Colorado Springs",
                "item_key": "d2bfe941bf0c9a27f90fa08b94c5b282",
                "latitude": "38.7378",
                "last_name": "pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:7][Pollins, 7]||[pollins, 7]",
                "score": "85",
                "time_in_service_yrs": "3.5",
                "assignment_uuid": "77ef6644-9ed1-43f0-bd68-e52b5566f940",
                "employee_id": "987",
                "date_of_hire": "4/24/2018",
                "state": "CO",
                "department": "Marketing",
                "postal_code": "80925",
                "first_name": "Katinka",
                "email": "kendeanre@seesaa.net",
                "longitude": "-104.6459"
            },
            {
                "home_phone": "954-559-4887",
                "street_address": "2 Shelley Crossing",
                "gender": "NULL",
                "city": "Orlando",
                "item_key": "d2bfe941bf0c9a27f90fa08b94c5b282",
                "latitude": "28.5469",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:7][Pollins, 7]||[pollins, 7]",
                "score": "85",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "77ef6644-9ed1-43f0-bd68-e52b5566f940",
                "employee_id": "988",
                "date_of_hire": "11/28/2018",
                "state": "FL",
                "department": "Legal",
                "postal_code": "32825",
                "first_name": "Kassi",
                "email": "kderellrf@ft.com",
                "longitude": "-81.2571"
            },
            {
                "home_phone": "915-822-0254",
                "street_address": "732 Burning Wood Crossing",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "44dedd3a7b251de1a034520f63afff0c",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:8][Rollins, 8]||[pollins, 8]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "e589d94e-bf53-4423-b880-8b1f84ef4e56",
                "employee_id": "499",
                "date_of_hire": "10/16/2018",
                "state": "TX",
                "postal_code": "88535",
                "department": "Business Development",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "street_address": "5 Sunnyside Junction",
                "home_phone": "719-537-1533",
                "gender": "Female",
                "city": "Colorado Springs",
                "item_key": "44dedd3a7b251de1a034520f63afff0c",
                "latitude": "38.7378",
                "last_name": "pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:8][Rollins, 8]||[pollins, 8]",
                "score": "85",
                "time_in_service_yrs": "3.5",
                "assignment_uuid": "e589d94e-bf53-4423-b880-8b1f84ef4e56",
                "employee_id": "987",
                "state": "CO",
                "date_of_hire": "4/24/2018",
                "department": "Marketing",
                "postal_code": "80925",
                "first_name": "Katinka",
                "email": "kendeanre@seesaa.net",
                "longitude": "-104.6459"
            },
            {
                "street_address": "3 Buena Vista Drive",
                "home_phone": "609-938-9163",
                "gender": "Male",
                "city": "Trenton",
                "item_key": "69d63de415ad67180ad3ca02089ff48d",
                "latitude": "40.2805",
                "last_name": "Diggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:9][Diggins, 9]||[Siggins, 9]",
                "score": "85",
                "time_in_service_yrs": "2.88",
                "assignment_uuid": "6a07e566-22a7-4650-8e6d-72e186af2bc8",
                "employee_id": "100",
                "state": "NJ",
                "date_of_hire": "12/4/2018",
                "postal_code": "8650",
                "department": "Services",
                "first_name": "Nicky",
                "email": "ndiggins2r@gov.uk",
                "longitude": "-74.712"
            },
            {
                "street_address": "6886 Granby Park",
                "home_phone": "901-601-7599",
                "gender": "Male",
                "city": "Memphis",
                "item_key": "69d63de415ad67180ad3ca02089ff48d",
                "latitude": "35.0425",
                "last_name": "Siggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:9][Diggins, 9]||[Siggins, 9]",
                "score": "85",
                "time_in_service_yrs": "3.88",
                "assignment_uuid": "6a07e566-22a7-4650-8e6d-72e186af2bc8",
                "employee_id": "839",
                "date_of_hire": "12/6/2017",
                "state": "TN",
                "postal_code": "38109",
                "department": "Business Development",
                "first_name": "Filia",
                "email": "fsigginsna@symantec.com",
                "longitude": "-90.0732"
            },
            {
                "home_phone": "202-453-5054",
                "street_address": "8724 Kenwood Junction",
                "gender": "Male",
                "city": "Alexandria",
                "item_key": "620dc90ab1a10e1307039e6b44bb6678",
                "latitude": "38.7192",
                "last_name": "Flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][Flatley, 10]||[flatley, 10]",
                "score": "85",
                "time_in_service_yrs": "3.11",
                "assignment_uuid": "d98bf724-e3ba-455c-9b3a-a760098e0ac4",
                "employee_id": "956",
                "date_of_hire": "9/12/2018",
                "state": "VA",
                "department": "Legal",
                "postal_code": "22309",
                "first_name": "Perry",
                "email": "pflatleyqj@cnet.com",
                "longitude": "-77.1073"
            },
            {
                "home_phone": "410-512-9139",
                "street_address": "0433 Homewood Crossing",
                "gender": "Male",
                "city": "Baltimore",
                "item_key": "620dc90ab1a10e1307039e6b44bb6678",
                "latitude": "39.3093",
                "last_name": "flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][Flatley, 10]||[flatley, 10]",
                "score": "85",
                "time_in_service_yrs": "4.51",
                "assignment_uuid": "d98bf724-e3ba-455c-9b3a-a760098e0ac4",
                "employee_id": "995",
                "date_of_hire": "4/18/2017",
                "state": "MD",
                "department": "Accounting & Finance",
                "postal_code": "21216",
                "first_name": "Paula",
                "email": "pnabbsrm@domainmarket.com",
                "longitude": "-76.6699"
            },
            {
                "home_phone": "410-512-9139",
                "street_address": "0433 Homewood Crossing",
                "gender": "Male",
                "city": "Baltimore",
                "item_key": "7ecdf05376a721b4cf7907b3def0f181",
                "latitude": "39.3093",
                "last_name": "flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Flatley, 11]||[flatley, 11]",
                "score": "85",
                "time_in_service_yrs": "4.51",
                "assignment_uuid": "6e766639-84e6-437a-92d5-b303c1ba85af",
                "employee_id": "995",
                "state": "MD",
                "date_of_hire": "4/18/2017",
                "postal_code": "21216",
                "department": "Accounting & Finance",
                "first_name": "Paula",
                "email": "pnabbsrm@domainmarket.com",
                "longitude": "-76.6699"
            },
            {
                "street_address": "107 Division Avenue",
                "home_phone": "773-506-5309",
                "gender": "Female",
                "city": "Chicago",
                "item_key": "7ecdf05376a721b4cf7907b3def0f181",
                "latitude": "41.8804",
                "last_name": "Flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Flatley, 11]||[flatley, 11]",
                "score": "85",
                "time_in_service_yrs": "2.98",
                "assignment_uuid": "6e766639-84e6-437a-92d5-b303c1ba85af",
                "employee_id": "1000",
                "state": "IL",
                "date_of_hire": "10/28/2018",
                "postal_code": "60624",
                "department": "Business Development",
                "first_name": "Maribel",
                "email": "mbruntjerr@blog.com",
                "longitude": "-87.7223"
            },
            {
                "street_address": "34245 Susan Court",
                "home_phone": "317-779-4918",
                "gender": "Female",
                "city": "Indianapolis",
                "item_key": "b0190a486912a775a6e5a7870a6e7c2a",
                "latitude": "39.7851",
                "last_name": "Flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:12][Flatley, 12]||[flatley, 12]",
                "score": "85",
                "time_in_service_yrs": "5.13",
                "assignment_uuid": "3a1055ed-54e4-49e3-8ea7-1de5681e5ef4",
                "employee_id": "809",
                "date_of_hire": "9/5/2016",
                "state": "IN",
                "department": "Engineering",
                "postal_code": "46202",
                "first_name": "Arabele",
                "email": "aflatleymg@feedburner.com",
                "longitude": "-86.1595"
            },
            {
                "street_address": "0433 Homewood Crossing",
                "home_phone": "410-512-9139",
                "gender": "Male",
                "city": "Baltimore",
                "item_key": "b0190a486912a775a6e5a7870a6e7c2a",
                "latitude": "39.3093",
                "last_name": "flatley",
                "type": "DUPE",
                "item_value": "[score:85, key_id:12][Flatley, 12]||[flatley, 12]",
                "score": "85",
                "time_in_service_yrs": "4.51",
                "assignment_uuid": "3a1055ed-54e4-49e3-8ea7-1de5681e5ef4",
                "employee_id": "995",
                "state": "MD",
                "date_of_hire": "4/18/2017",
                "postal_code": "21216",
                "department": "Accounting & Finance",
                "first_name": "Paula",
                "email": "pnabbsrm@domainmarket.com",
                "longitude": "-76.6699"
            },
            {
                "home_phone": "571-285-8377",
                "street_address": "35 Carioca Court",
                "gender": "Male",
                "city": "Dulles",
                "item_key": "27d3285155ea8f40bc3c46b57802989e",
                "latitude": "39.009",
                "last_name": "Eldridge",
                "type": "DUPE",
                "item_value": "[score:86, key_id:13][Edridge, 13]||[Eldridge, 13]",
                "score": "86",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "d9292faa-f5c1-4256-901e-04d6433a933f",
                "employee_id": "355",
                "date_of_hire": "11/28/2018",
                "state": "VA",
                "department": "Marketing",
                "postal_code": "20189",
                "first_name": "Justus",
                "email": "jeldridge9u@hp.com",
                "longitude": "-77.4422"
            },
            {
                "home_phone": "818-851-0399",
                "street_address": "95 Northwestern Pass",
                "gender": "Male",
                "city": "Northridge",
                "item_key": "27d3285155ea8f40bc3c46b57802989e",
                "latitude": "33.7866",
                "last_name": "Edridge",
                "type": "DUPE",
                "item_value": "[score:86, key_id:13][Edridge, 13]||[Eldridge, 13]",
                "score": "86",
                "time_in_service_yrs": "3.01",
                "assignment_uuid": "d9292faa-f5c1-4256-901e-04d6433a933f",
                "employee_id": "802",
                "date_of_hire": "10/19/2018",
                "state": "CA",
                "postal_code": "91328",
                "department": "Legal",
                "first_name": "Rubin",
                "email": "redridgem9@wikipedia.org",
                "longitude": "-118.2987"
            },
            {
                "street_address": "6173 Glacier Hill Trail",
                "home_phone": "336-142-9688",
                "gender": "Male",
                "city": "Greensboro",
                "item_key": "e8ecb8b29c4a144ab8e446975b18ea18",
                "latitude": "36.0807",
                "last_name": "Robinet",
                "type": "DUPE",
                "item_value": "[score:86, key_id:14][Robinet, 14]||[Robinett, 14]",
                "score": "86",
                "time_in_service_yrs": "2.99",
                "assignment_uuid": "571e0c4e-4baa-49f3-a38c-f4eaa6221657",
                "employee_id": "706",
                "state": "NC",
                "date_of_hire": "10/25/2018",
                "postal_code": "27404",
                "department": "Accounting",
                "first_name": "Buckie",
                "email": "brobinetjl@ftc.gov",
                "longitude": "-80.0244"
            },
            {
                "home_phone": "312-341-6435",
                "street_address": "5883 Donald Alley",
                "gender": "Female",
                "city": "Chicago",
                "item_key": "e8ecb8b29c4a144ab8e446975b18ea18",
                "latitude": "41.8756",
                "last_name": "Robinett",
                "type": "DUPE",
                "item_value": "[score:86, key_id:14][Robinet, 14]||[Robinett, 14]",
                "score": "86",
                "time_in_service_yrs": "4.63",
                "assignment_uuid": "571e0c4e-4baa-49f3-a38c-f4eaa6221657",
                "employee_id": "815",
                "date_of_hire": "3/6/2017",
                "state": "IL",
                "department": "Legal",
                "postal_code": "60686",
                "first_name": "Johnna",
                "email": "jrobinettmm@photobucket.com",
                "longitude": "-87.6378"
            },
            {
                "street_address": "02931 Monument Drive",
                "home_phone": "972-374-8599",
                "gender": "Female",
                "city": "Dallas",
                "item_key": "6239e4c9bb9c419da16ddd14f5f02c45",
                "latitude": "32.7887",
                "last_name": "Aldridge",
                "type": "DUPE",
                "item_value": "[score:87, key_id:15][Aldridge, 15]||[Eldridge, 15]",
                "score": "87",
                "time_in_service_yrs": "4.03",
                "assignment_uuid": "46e23c0d-d254-42e3-b86d-656e99b44f3f",
                "employee_id": "179",
                "date_of_hire": "10/13/2017",
                "state": "TX",
                "postal_code": "75226",
                "department": "Product Management",
                "first_name": "Jayme",
                "email": "jaldridge4y@instagram.com",
                "longitude": "-96.7676"
            },
            {
                "street_address": "35 Carioca Court",
                "home_phone": "571-285-8377",
                "gender": "Male",
                "city": "Dulles",
                "item_key": "6239e4c9bb9c419da16ddd14f5f02c45",
                "latitude": "39.009",
                "last_name": "Eldridge",
                "type": "DUPE",
                "item_value": "[score:87, key_id:15][Aldridge, 15]||[Eldridge, 15]",
                "score": "87",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "46e23c0d-d254-42e3-b86d-656e99b44f3f",
                "employee_id": "355",
                "date_of_hire": "11/28/2018",
                "state": "VA",
                "department": "Marketing",
                "postal_code": "20189",
                "first_name": "Justus",
                "email": "jeldridge9u@hp.com",
                "longitude": "-77.4422"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Male",
                "city": "Cincinnati",
                "item_key": "a9707466f293acbb832941697ecde839",
                "latitude": "39.0706",
                "last_name": "Gillings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:16][Billings, 16]||[Gillings, 16]",
                "score": "87",
                "time_in_service_yrs": "3.48",
                "assignment_uuid": "699c088e-1cc6-4906-9003-60d23a8ce917",
                "employee_id": "441",
                "date_of_hire": "5/1/2018",
                "state": "OH",
                "postal_code": "45228",
                "department": "Training",
                "first_name": "Curcio",
                "email": "cgillingsc8@stumbleupon.com",
                "longitude": "-84.4179"
            },
            {
                "home_phone": "410-189-4551",
                "street_address": "0903 Bellgrove Avenue",
                "gender": "Female",
                "city": "Baltimore",
                "item_key": "a9707466f293acbb832941697ecde839",
                "latitude": "39.361",
                "last_name": "Billings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:16][Billings, 16]||[Gillings, 16]",
                "score": "87",
                "time_in_service_yrs": "3.35",
                "assignment_uuid": "699c088e-1cc6-4906-9003-60d23a8ce917",
                "employee_id": "624",
                "date_of_hire": "6/18/2018",
                "state": "MD",
                "department": "Product Management",
                "postal_code": "21239",
                "first_name": "Cecilia",
                "email": "cbillingshb@nbcnews.com",
                "longitude": "-76.5891"
            },
            {
                "home_phone": "410-189-4551",
                "street_address": "0903 Bellgrove Avenue",
                "gender": "Female",
                "city": "Baltimore",
                "item_key": "17262a3004d94294496b97a1f6d866d5",
                "latitude": "39.361",
                "last_name": "Billings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:17][Billings, 17]||[Millings, 17]",
                "score": "87",
                "time_in_service_yrs": "3.35",
                "assignment_uuid": "0707887d-c2c8-455f-81b0-a266704e26ab",
                "employee_id": "624",
                "state": "MD",
                "date_of_hire": "6/18/2018",
                "postal_code": "21239",
                "department": "Product Management",
                "first_name": "Cecilia",
                "email": "cbillingshb@nbcnews.com",
                "longitude": "-76.5891"
            },
            {
                "street_address": "8 Dorton Circle",
                "home_phone": "763-174-2429",
                "gender": "Female",
                "city": "Monticello",
                "item_key": "17262a3004d94294496b97a1f6d866d5",
                "latitude": "45.2009",
                "last_name": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:17][Billings, 17]||[Millings, 17]",
                "score": "87",
                "time_in_service_yrs": "3.59",
                "assignment_uuid": "0707887d-c2c8-455f-81b0-a266704e26ab",
                "employee_id": "999",
                "state": "MN",
                "date_of_hire": "3/21/2018",
                "postal_code": "55565",
                "department": "Training",
                "first_name": "Cloris",
                "email": "cgreenroadrq@mapy.cz",
                "longitude": "-93.8881"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Male",
                "city": "Cincinnati",
                "item_key": "403867ce49aaf9e0ef3912300a663e7e",
                "latitude": "39.0706",
                "last_name": "Gillings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:18][Gillings, 18]||[Millings, 18]",
                "score": "87",
                "time_in_service_yrs": "3.48",
                "assignment_uuid": "c6a9399a-703c-44b1-85d3-c232d0847db2",
                "employee_id": "441",
                "state": "OH",
                "date_of_hire": "5/1/2018",
                "postal_code": "45228",
                "department": "Training",
                "first_name": "Curcio",
                "email": "cgillingsc8@stumbleupon.com",
                "longitude": "-84.4179"
            },
            {
                "home_phone": "763-174-2429",
                "street_address": "8 Dorton Circle",
                "gender": "Female",
                "city": "Monticello",
                "item_key": "403867ce49aaf9e0ef3912300a663e7e",
                "latitude": "45.2009",
                "last_name": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:18][Gillings, 18]||[Millings, 18]",
                "score": "87",
                "time_in_service_yrs": "3.59",
                "assignment_uuid": "c6a9399a-703c-44b1-85d3-c232d0847db2",
                "employee_id": "999",
                "date_of_hire": "3/21/2018",
                "state": "MN",
                "department": "Training",
                "postal_code": "55565",
                "first_name": "Cloris",
                "email": "cgreenroadrq@mapy.cz",
                "longitude": "-93.8881"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "home_phone",
                "name": "home_phone",
                "title": "home_phone"
            },
            {
                "data": "street_address",
                "name": "street_address",
                "title": "street_address"
            },
            {
                "data": "gender",
                "name": "gender",
                "title": "gender"
            },
            {
                "data": "city",
                "name": "city",
                "title": "city"
            },
            {
                "data": "latitude",
                "name": "latitude",
                "title": "latitude"
            },
            {
                "data": "last_name",
                "name": "last_name",
                "title": "last_name"
            },
            {
                "data": "time_in_service_yrs",
                "name": "time_in_service_yrs",
                "title": "time_in_service_yrs"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "employee_id",
                "name": "employee_id",
                "title": "employee_id"
            },
            {
                "data": "date_of_hire",
                "name": "date_of_hire",
                "title": "date_of_hire"
            },
            {
                "data": "state",
                "name": "state",
                "title": "state"
            },
            {
                "data": "postal_code",
                "name": "postal_code",
                "title": "postal_code"
            },
            {
                "data": "department",
                "name": "department",
                "title": "department"
            },
            {
                "data": "first_name",
                "name": "first_name",
                "title": "first_name"
            },
            {
                "data": "email",
                "name": "email",
                "title": "email"
            },
            {
                "data": "longitude",
                "name": "longitude",
                "title": "longitude"
            }
        ]
    }
]

PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": 301,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "990",
        "score": 85
    },
    {
        "seqno": 302,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 18,
        "dupe1": "Gillings",
        "dupe1_link_id": "441",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": 303,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 17,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": 304,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 16,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Gillings",
        "dupe2_link_id": "441",
        "score": 87
    },
    {
        "seqno": 305,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 15,
        "dupe1": "Aldridge",
        "dupe1_link_id": "179",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 87
    },
    {
        "seqno": 306,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 14,
        "dupe1": "Robinet",
        "dupe1_link_id": "706",
        "dupe2": "Robinett",
        "dupe2_link_id": "815",
        "score": 86
    },
    {
        "seqno": 307,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 13,
        "dupe1": "Edridge",
        "dupe1_link_id": "802",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 86
    },
    {
        "seqno": 308,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 12,
        "dupe1": "Flatley",
        "dupe1_link_id": "809",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": 309,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 11,
        "dupe1": "Flatley",
        "dupe1_link_id": "1000",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": 310,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 10,
        "dupe1": "Flatley",
        "dupe1_link_id": "956",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": 311,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 9,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": 312,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Rollins",
        "dupe1_link_id": "499",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": 313,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": 314,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": 315,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Tainton",
        "dupe1_link_id": "22",
        "dupe2": "Taunton",
        "dupe2_link_id": "437",
        "score": 85
    },
    {
        "seqno": 316,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": 317,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": 318,
        "updts": "2024-07-22T14:38:26.217+0000",
        "job_uuid": "ba9b7646-f75a-4cd8-aa6b-10891c2b5e6c",
        "dataset": PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "354",
        "score": 85
    }
]

PD_TRINO_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "583",
        "first_name": "Katherine",
        "last_name": "Clarage",
        "email": "kclarageg6@creativecommons.org",
        "gender": "Male",
        "city": "Knoxville",
        "department": "Sales",
        "latitude": "40.7955",
        "longitude": "-84.1383",
        "home_phone": "865-418-3128",
        "postal_code": "37924",
        "state": "TN",
        "street_address": "66675 High Crossing Way",
        "date_of_hire": "11/6/2018",
        "time_in_service_yrs": 2.96
    },
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "990",
        "first_name": "Brook",
        "last_name": "Clardge",
        "email": "bcheerrh@marketwatch.com",
        "gender": "Male",
        "city": "San Bernardino",
        "department": "Human Resources",
        "latitude": "34.84",
        "longitude": "-115.9671",
        "home_phone": "909-606-7780",
        "postal_code": "92424",
        "state": "CA",
        "street_address": "8658 Ridgeway Point",
        "date_of_hire": "9/9/2018",
        "time_in_service_yrs": 3.12
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "354",
        "first_name": "Jdavie",
        "last_name": "Clardge",
        "email": "jclardge9t@illinois.edu",
        "gender": "Male",
        "city": "Huntington",
        "department": "Research and Development",
        "latitude": "38.4134",
        "longitude": "-82.2774",
        "home_phone": "304-559-1266",
        "postal_code": "25716",
        "state": "WV",
        "street_address": "83 Kropf Way",
        "date_of_hire": "7/2/2018",
        "time_in_service_yrs": 3.31
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "583",
        "first_name": "Katherine",
        "last_name": "Clarage",
        "email": "kclarageg6@creativecommons.org",
        "gender": "Male",
        "city": "Knoxville",
        "department": "Sales",
        "latitude": "40.7955",
        "longitude": "-84.1383",
        "home_phone": "865-418-3128",
        "postal_code": "37924",
        "state": "TN",
        "street_address": "66675 High Crossing Way",
        "date_of_hire": "11/6/2018",
        "time_in_service_yrs": 2.96
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "368",
        "first_name": "Ari",
        "last_name": "Pollins",
        "email": "apollinsa7@pen.io",
        "gender": "Female",
        "city": "Miami",
        "department": "Support",
        "latitude": "25.6615",
        "longitude": "-80.441",
        "home_phone": "786-873-7423",
        "postal_code": "33196",
        "state": "FL",
        "street_address": "150 Magdeline Crossing",
        "date_of_hire": "10/7/2015",
        "time_in_service_yrs": 6.05
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "988",
        "first_name": "Kassi",
        "last_name": "Pollins",
        "email": "kderellrf@ft.com",
        "gender": None,
        "city": "Orlando",
        "department": "Legal",
        "latitude": "28.5469",
        "longitude": "-81.2571",
        "home_phone": "954-559-4887",
        "postal_code": "32825",
        "state": "FL",
        "street_address": "2 Shelley Crossing",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "employee_id": "22",
        "first_name": "Dyanne",
        "last_name": "Tainton",
        "email": "dtaintonl@answers.com",
        "gender": "Female",
        "city": "Young America",
        "department": "Research and Development",
        "latitude": "44.8055",
        "longitude": "-93.7665",
        "home_phone": "952-832-3196",
        "postal_code": "55557",
        "state": "MN",
        "street_address": "79438 Parkside Drive",
        "date_of_hire": "9/30/2018",
        "time_in_service_yrs": 3.06
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "employee_id": "437",
        "first_name": "Diena",
        "last_name": "Taunton",
        "email": "dtauntonc4@about.com",
        "gender": "Female",
        "city": "Columbus",
        "department": "Engineering",
        "latitude": "39.9671",
        "longitude": "-83.0044",
        "home_phone": "513-885-7912",
        "postal_code": "43215",
        "state": "OH",
        "street_address": "43942 Forest Run Pass",
        "date_of_hire": "11/1/2015",
        "time_in_service_yrs": 5.98
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "employee_id": "368",
        "first_name": "Ari",
        "last_name": "Pollins",
        "email": "apollinsa7@pen.io",
        "gender": "Female",
        "city": "Miami",
        "department": "Support",
        "latitude": "25.6615",
        "longitude": "-80.441",
        "home_phone": "786-873-7423",
        "postal_code": "33196",
        "state": "FL",
        "street_address": "150 Magdeline Crossing",
        "date_of_hire": "10/7/2015",
        "time_in_service_yrs": 6.05
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "employee_id": "987",
        "first_name": "Katinka",
        "last_name": "pollins",
        "email": "kendeanre@seesaa.net",
        "gender": "Female",
        "city": "Colorado Springs",
        "department": "Marketing",
        "latitude": "38.7378",
        "longitude": "-104.6459",
        "home_phone": "719-537-1533",
        "postal_code": "80925",
        "state": "CO",
        "street_address": "5 Sunnyside Junction",
        "date_of_hire": "4/24/2018",
        "time_in_service_yrs": 3.5
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "employee_id": "987",
        "first_name": "Katinka",
        "last_name": "pollins",
        "email": "kendeanre@seesaa.net",
        "gender": "Female",
        "city": "Colorado Springs",
        "department": "Marketing",
        "latitude": "38.7378",
        "longitude": "-104.6459",
        "home_phone": "719-537-1533",
        "postal_code": "80925",
        "state": "CO",
        "street_address": "5 Sunnyside Junction",
        "date_of_hire": "4/24/2018",
        "time_in_service_yrs": 3.5
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "employee_id": "988",
        "first_name": "Kassi",
        "last_name": "Pollins",
        "email": "kderellrf@ft.com",
        "gender": None,
        "city": "Orlando",
        "department": "Legal",
        "latitude": "28.5469",
        "longitude": "-81.2571",
        "home_phone": "954-559-4887",
        "postal_code": "32825",
        "state": "FL",
        "street_address": "2 Shelley Crossing",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Rollins",
        "dupe2": "pollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Rollins",
        "dupe2": "pollins",
        "employee_id": "987",
        "first_name": "Katinka",
        "last_name": "pollins",
        "email": "kendeanre@seesaa.net",
        "gender": "Female",
        "city": "Colorado Springs",
        "department": "Marketing",
        "latitude": "38.7378",
        "longitude": "-104.6459",
        "home_phone": "719-537-1533",
        "postal_code": "80925",
        "state": "CO",
        "street_address": "5 Sunnyside Junction",
        "date_of_hire": "4/24/2018",
        "time_in_service_yrs": 3.5
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "employee_id": "100",
        "first_name": "Nicky",
        "last_name": "Diggins",
        "email": "ndiggins2r@gov.uk",
        "gender": "Male",
        "city": "Trenton",
        "department": "Services",
        "latitude": "40.2805",
        "longitude": "-74.712",
        "home_phone": "609-938-9163",
        "postal_code": "8650",
        "state": "NJ",
        "street_address": "3 Buena Vista Drive",
        "date_of_hire": "12/4/2018",
        "time_in_service_yrs": 2.88
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "employee_id": "839",
        "first_name": "Filia",
        "last_name": "Siggins",
        "email": "fsigginsna@symantec.com",
        "gender": "Male",
        "city": "Memphis",
        "department": "Business Development",
        "latitude": "35.0425",
        "longitude": "-90.0732",
        "home_phone": "901-601-7599",
        "postal_code": "38109",
        "state": "TN",
        "street_address": "6886 Granby Park",
        "date_of_hire": "12/6/2017",
        "time_in_service_yrs": 3.88
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "956",
        "first_name": "Perry",
        "last_name": "Flatley",
        "email": "pflatleyqj@cnet.com",
        "gender": "Male",
        "city": "Alexandria",
        "department": "Legal",
        "latitude": "38.7192",
        "longitude": "-77.1073",
        "home_phone": "202-453-5054",
        "postal_code": "22309",
        "state": "VA",
        "street_address": "8724 Kenwood Junction",
        "date_of_hire": "9/12/2018",
        "time_in_service_yrs": 3.11
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "995",
        "first_name": "Paula",
        "last_name": "flatley",
        "email": "pnabbsrm@domainmarket.com",
        "gender": "Male",
        "city": "Baltimore",
        "department": "Accounting & Finance",
        "latitude": "39.3093",
        "longitude": "-76.6699",
        "home_phone": "410-512-9139",
        "postal_code": "21216",
        "state": "MD",
        "street_address": "0433 Homewood Crossing",
        "date_of_hire": "4/18/2017",
        "time_in_service_yrs": 4.51
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "995",
        "first_name": "Paula",
        "last_name": "flatley",
        "email": "pnabbsrm@domainmarket.com",
        "gender": "Male",
        "city": "Baltimore",
        "department": "Accounting & Finance",
        "latitude": "39.3093",
        "longitude": "-76.6699",
        "home_phone": "410-512-9139",
        "postal_code": "21216",
        "state": "MD",
        "street_address": "0433 Homewood Crossing",
        "date_of_hire": "4/18/2017",
        "time_in_service_yrs": 4.51
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "1000",
        "first_name": "Maribel",
        "last_name": "Flatley",
        "email": "mbruntjerr@blog.com",
        "gender": "Female",
        "city": "Chicago",
        "department": "Business Development",
        "latitude": "41.8804",
        "longitude": "-87.7223",
        "home_phone": "773-506-5309",
        "postal_code": "60624",
        "state": "IL",
        "street_address": "107 Division Avenue",
        "date_of_hire": "10/28/2018",
        "time_in_service_yrs": 2.98
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "809",
        "first_name": "Arabele",
        "last_name": "Flatley",
        "email": "aflatleymg@feedburner.com",
        "gender": "Female",
        "city": "Indianapolis",
        "department": "Engineering",
        "latitude": "39.7851",
        "longitude": "-86.1595",
        "home_phone": "317-779-4918",
        "postal_code": "46202",
        "state": "IN",
        "street_address": "34245 Susan Court",
        "date_of_hire": "9/5/2016",
        "time_in_service_yrs": 5.13
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "employee_id": "995",
        "first_name": "Paula",
        "last_name": "flatley",
        "email": "pnabbsrm@domainmarket.com",
        "gender": "Male",
        "city": "Baltimore",
        "department": "Accounting & Finance",
        "latitude": "39.3093",
        "longitude": "-76.6699",
        "home_phone": "410-512-9139",
        "postal_code": "21216",
        "state": "MD",
        "street_address": "0433 Homewood Crossing",
        "date_of_hire": "4/18/2017",
        "time_in_service_yrs": 4.51
    },
    {
        "key_id": 13,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "employee_id": "355",
        "first_name": "Justus",
        "last_name": "Eldridge",
        "email": "jeldridge9u@hp.com",
        "gender": "Male",
        "city": "Dulles",
        "department": "Marketing",
        "latitude": "39.009",
        "longitude": "-77.4422",
        "home_phone": "571-285-8377",
        "postal_code": "20189",
        "state": "VA",
        "street_address": "35 Carioca Court",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 13,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "employee_id": "802",
        "first_name": "Rubin",
        "last_name": "Edridge",
        "email": "redridgem9@wikipedia.org",
        "gender": "Male",
        "city": "Northridge",
        "department": "Legal",
        "latitude": "33.7866",
        "longitude": "-118.2987",
        "home_phone": "818-851-0399",
        "postal_code": "91328",
        "state": "CA",
        "street_address": "95 Northwestern Pass",
        "date_of_hire": "10/19/2018",
        "time_in_service_yrs": 3.01
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "employee_id": "706",
        "first_name": "Buckie",
        "last_name": "Robinet",
        "email": "brobinetjl@ftc.gov",
        "gender": "Male",
        "city": "Greensboro",
        "department": "Accounting",
        "latitude": "36.0807",
        "longitude": "-80.0244",
        "home_phone": "336-142-9688",
        "postal_code": "27404",
        "state": "NC",
        "street_address": "6173 Glacier Hill Trail",
        "date_of_hire": "10/25/2018",
        "time_in_service_yrs": 2.99
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "employee_id": "815",
        "first_name": "Johnna",
        "last_name": "Robinett",
        "email": "jrobinettmm@photobucket.com",
        "gender": "Female",
        "city": "Chicago",
        "department": "Legal",
        "latitude": "41.8756",
        "longitude": "-87.6378",
        "home_phone": "312-341-6435",
        "postal_code": "60686",
        "state": "IL",
        "street_address": "5883 Donald Alley",
        "date_of_hire": "3/6/2017",
        "time_in_service_yrs": 4.63
    },
    {
        "key_id": 15,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "employee_id": "179",
        "first_name": "Jayme",
        "last_name": "Aldridge",
        "email": "jaldridge4y@instagram.com",
        "gender": "Female",
        "city": "Dallas",
        "department": "Product Management",
        "latitude": "32.7887",
        "longitude": "-96.7676",
        "home_phone": "972-374-8599",
        "postal_code": "75226",
        "state": "TX",
        "street_address": "02931 Monument Drive",
        "date_of_hire": "10/13/2017",
        "time_in_service_yrs": 4.03
    },
    {
        "key_id": 15,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "employee_id": "355",
        "first_name": "Justus",
        "last_name": "Eldridge",
        "email": "jeldridge9u@hp.com",
        "gender": "Male",
        "city": "Dulles",
        "department": "Marketing",
        "latitude": "39.009",
        "longitude": "-77.4422",
        "home_phone": "571-285-8377",
        "postal_code": "20189",
        "state": "VA",
        "street_address": "35 Carioca Court",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 16,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "employee_id": "441",
        "first_name": "Curcio",
        "last_name": "Gillings",
        "email": "cgillingsc8@stumbleupon.com",
        "gender": "Male",
        "city": "Cincinnati",
        "department": "Training",
        "latitude": "39.0706",
        "longitude": "-84.4179",
        "home_phone": None,
        "postal_code": "45228",
        "state": "OH",
        "street_address": None,
        "date_of_hire": "5/1/2018",
        "time_in_service_yrs": 3.48
    },
    {
        "key_id": 16,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "employee_id": "624",
        "first_name": "Cecilia",
        "last_name": "Billings",
        "email": "cbillingshb@nbcnews.com",
        "gender": "Female",
        "city": "Baltimore",
        "department": "Product Management",
        "latitude": "39.361",
        "longitude": "-76.5891",
        "home_phone": "410-189-4551",
        "postal_code": "21239",
        "state": "MD",
        "street_address": "0903 Bellgrove Avenue",
        "date_of_hire": "6/18/2018",
        "time_in_service_yrs": 3.35
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "employee_id": "624",
        "first_name": "Cecilia",
        "last_name": "Billings",
        "email": "cbillingshb@nbcnews.com",
        "gender": "Female",
        "city": "Baltimore",
        "department": "Product Management",
        "latitude": "39.361",
        "longitude": "-76.5891",
        "home_phone": "410-189-4551",
        "postal_code": "21239",
        "state": "MD",
        "street_address": "0903 Bellgrove Avenue",
        "date_of_hire": "6/18/2018",
        "time_in_service_yrs": 3.35
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "employee_id": "999",
        "first_name": "Cloris",
        "last_name": "Millings",
        "email": "cgreenroadrq@mapy.cz",
        "gender": "Female",
        "city": "Monticello",
        "department": "Training",
        "latitude": "45.2009",
        "longitude": "-93.8881",
        "home_phone": "763-174-2429",
        "postal_code": "55565",
        "state": "MN",
        "street_address": "8 Dorton Circle",
        "date_of_hire": "3/21/2018",
        "time_in_service_yrs": 3.59
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "employee_id": "441",
        "first_name": "Curcio",
        "last_name": "Gillings",
        "email": "cgillingsc8@stumbleupon.com",
        "gender": "Male",
        "city": "Cincinnati",
        "department": "Training",
        "latitude": "39.0706",
        "longitude": "-84.4179",
        "home_phone": None,
        "postal_code": "45228",
        "state": "OH",
        "street_address": None,
        "date_of_hire": "5/1/2018",
        "time_in_service_yrs": 3.48
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "employee_id": "999",
        "first_name": "Cloris",
        "last_name": "Millings",
        "email": "cgreenroadrq@mapy.cz",
        "gender": "Female",
        "city": "Monticello",
        "department": "Training",
        "latitude": "45.2009",
        "longitude": "-93.8881",
        "home_phone": "763-174-2429",
        "postal_code": "55565",
        "state": "MN",
        "street_address": "8 Dorton Circle",
        "date_of_hire": "3/21/2018",
        "time_in_service_yrs": 3.59
    }
]
