from payloads.pushdown.dupes.pl_pd_trino_dupes_score_nocase_employees_dt_archive_breaks import (
    PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
)

PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "home_phone": "865-418-3128",
                "street_address": "66675 High Crossing Way",
                "gender": "Male",
                "city": "Knoxville",
                "item_key": "4090fde0e55a82d822e8102f7ee16f2e",
                "latitude": "40.7955",
                "last_name": "Clarage",
                "type": "DUPE",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "score": "85",
                "time_in_service_yrs": "2.96",
                "assignment_uuid": "b38975e9-1959-4485-9cef-6ef51bc86d78",
                "employee_id": "583",
                "date_of_hire": "11/6/2018",
                "state": "TN",
                "department": "Sales",
                "postal_code": "37924",
                "first_name": "Katherine",
                "email": "kclarageg6@creativecommons.org",
                "longitude": "-84.1383"
            },
            {
                "home_phone": "304-559-1266",
                "street_address": "83 Kropf Way",
                "gender": "Male",
                "city": "Huntington",
                "item_key": "4090fde0e55a82d822e8102f7ee16f2e",
                "latitude": "38.4134",
                "last_name": "Clardge",
                "type": "DUPE",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "score": "85",
                "time_in_service_yrs": "3.31",
                "assignment_uuid": "b38975e9-1959-4485-9cef-6ef51bc86d78",
                "employee_id": "354",
                "state": "WV",
                "date_of_hire": "7/2/2018",
                "department": "Research and Development",
                "postal_code": "25716",
                "first_name": "Jdavie",
                "email": "jclardge9t@illinois.edu",
                "longitude": "-82.2774"
            },
            {
                "home_phone": "212-511-8481",
                "street_address": "505 Golf Course Road",
                "gender": "NULL",
                "city": "New York City",
                "item_key": "eb71b2dc555831f3dbae94c03a66921c",
                "latitude": "40.7808",
                "last_name": "CLARDGE",
                "type": "DUPE",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[CLARDGE, 2]",
                "score": "85",
                "time_in_service_yrs": "4.56",
                "assignment_uuid": "9a5edb6f-bdda-4d4f-aac1-7c8986480995",
                "employee_id": "989",
                "date_of_hire": "4/1/2017",
                "state": "NY",
                "department": "Research and Development",
                "postal_code": "10125",
                "first_name": "Terrye",
                "email": "thayerrg@home.pl",
                "longitude": "-73.9772"
            },
            {
                "home_phone": "865-418-3128",
                "street_address": "66675 High Crossing Way",
                "gender": "Male",
                "city": "Knoxville",
                "item_key": "eb71b2dc555831f3dbae94c03a66921c",
                "latitude": "40.7955",
                "last_name": "Clarage",
                "type": "DUPE",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[CLARDGE, 2]",
                "score": "85",
                "time_in_service_yrs": "2.96",
                "assignment_uuid": "9a5edb6f-bdda-4d4f-aac1-7c8986480995",
                "employee_id": "583",
                "date_of_hire": "11/6/2018",
                "state": "TN",
                "postal_code": "37924",
                "department": "Sales",
                "first_name": "Katherine",
                "email": "kclarageg6@creativecommons.org",
                "longitude": "-84.1383"
            },
            {
                "street_address": "8658 Ridgeway Point",
                "home_phone": "909-606-7780",
                "gender": "Male",
                "city": "San Bernardino",
                "item_key": "449790c9244f920e44a479521ad052eb",
                "latitude": "34.84",
                "last_name": "Clardge",
                "type": "DUPE",
                "item_value": "[score:85, key_id:3][Clarage, 3]||[Clardge, 3]",
                "score": "85",
                "time_in_service_yrs": "3.12",
                "assignment_uuid": "c6e3df18-611a-41de-933a-4d405f6d012b",
                "employee_id": "990",
                "state": "CA",
                "date_of_hire": "9/9/2018",
                "department": "Human Resources",
                "postal_code": "92424",
                "first_name": "Brook",
                "email": "bcheerrh@marketwatch.com",
                "longitude": "-115.9671"
            },
            {
                "home_phone": "865-418-3128",
                "street_address": "66675 High Crossing Way",
                "gender": "Male",
                "city": "Knoxville",
                "item_key": "449790c9244f920e44a479521ad052eb",
                "latitude": "40.7955",
                "last_name": "Clarage",
                "type": "DUPE",
                "item_value": "[score:85, key_id:3][Clarage, 3]||[Clardge, 3]",
                "score": "85",
                "time_in_service_yrs": "2.96",
                "assignment_uuid": "c6e3df18-611a-41de-933a-4d405f6d012b",
                "employee_id": "583",
                "date_of_hire": "11/6/2018",
                "state": "TN",
                "department": "Sales",
                "postal_code": "37924",
                "first_name": "Katherine",
                "email": "kclarageg6@creativecommons.org",
                "longitude": "-84.1383"
            },
            {
                "home_phone": "303-255-9434",
                "street_address": "17 Dixon Circle",
                "gender": "Male",
                "city": "Denver",
                "item_key": "069440338592af65ef39c31a24a651e2",
                "latitude": "39.734",
                "last_name": "hAlLoCk",
                "type": "DUPE",
                "item_value": "[score:85, key_id:4][hAlLoCk, 4]||[Harlock, 4]",
                "score": "85",
                "time_in_service_yrs": "2.89",
                "assignment_uuid": "6a46da87-85dc-4d65-a838-4d62f0320d9d",
                "employee_id": "511",
                "date_of_hire": "12/2/2018",
                "state": "CO",
                "department": "Product Management",
                "postal_code": "80204",
                "first_name": "Beaufort",
                "email": "bhallocke6@dailymail.co.uk",
                "longitude": "-105.0259"
            },
            {
                "home_phone": "915-842-8761",
                "street_address": "6 Loeprich Pass",
                "gender": "NULL",
                "city": "El Paso",
                "item_key": "069440338592af65ef39c31a24a651e2",
                "latitude": "31.9386",
                "last_name": "Harlock",
                "type": "DUPE",
                "item_value": "[score:85, key_id:4][hAlLoCk, 4]||[Harlock, 4]",
                "score": "85",
                "time_in_service_yrs": "3.94",
                "assignment_uuid": "6a46da87-85dc-4d65-a838-4d62f0320d9d",
                "employee_id": "146",
                "date_of_hire": "11/13/2017",
                "state": "TX",
                "department": "Marketing",
                "postal_code": "79934",
                "first_name": "Dale",
                "email": "dharlock41@guardian.co.uk",
                "longitude": "-106.4073"
            },
            {
                "street_address": "41171 Becker Lane",
                "home_phone": "512-954-0424",
                "gender": "Female",
                "city": "Austin",
                "item_key": "4bc7476e4e39cb48c66856773d4f867c",
                "latitude": "30.3264",
                "last_name": "Giblett",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Giblett, 5]||[NibletT, 5]",
                "score": "85",
                "time_in_service_yrs": "3.11",
                "assignment_uuid": "f1d5bc2e-933b-496b-9086-73e96dfc9fef",
                "employee_id": "944",
                "state": "TX",
                "date_of_hire": "9/12/2018",
                "department": "Support",
                "postal_code": "78769",
                "first_name": "Kata",
                "email": "kgiblettq7@census.gov",
                "longitude": "-97.7713"
            },
            {
                "street_address": "2177 Kenwood Drive",
                "home_phone": "415-989-1878",
                "gender": "NULL",
                "city": "San Francisco",
                "item_key": "4bc7476e4e39cb48c66856773d4f867c",
                "latitude": "37.7848",
                "last_name": "NibletT",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Giblett, 5]||[NibletT, 5]",
                "score": "85",
                "time_in_service_yrs": "3.06",
                "assignment_uuid": "f1d5bc2e-933b-496b-9086-73e96dfc9fef",
                "employee_id": "163",
                "date_of_hire": "9/30/2018",
                "state": "CA",
                "department": "Training",
                "postal_code": "94154",
                "first_name": "Rosetta",
                "email": "rniblett4i@unblog.fr",
                "longitude": "-122.7278"
            },
            {
                "home_phone": "915-822-0254",
                "street_address": "732 Burning Wood Crossing",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "548b18a3141e408793f09f19b5f6f385",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[Rollins, 6]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "7e502ede-2a51-4c0f-842e-1fc3cdf3b3db",
                "employee_id": "499",
                "date_of_hire": "10/16/2018",
                "state": "TX",
                "department": "Business Development",
                "postal_code": "88535",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "home_phone": "786-873-7423",
                "street_address": "150 Magdeline Crossing",
                "gender": "Female",
                "city": "Miami",
                "item_key": "548b18a3141e408793f09f19b5f6f385",
                "latitude": "25.6615",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[Rollins, 6]",
                "score": "85",
                "time_in_service_yrs": "6.05",
                "assignment_uuid": "7e502ede-2a51-4c0f-842e-1fc3cdf3b3db",
                "employee_id": "368",
                "date_of_hire": "10/7/2015",
                "state": "FL",
                "department": "Support",
                "postal_code": "33196",
                "first_name": "Ari",
                "email": "apollinsa7@pen.io",
                "longitude": "-80.441"
            },
            {
                "street_address": "5 Sunnyside Junction",
                "home_phone": "719-537-1533",
                "gender": "Female",
                "city": "Colorado Springs",
                "item_key": "3149f3c34ca517a441086b18f84df6a3",
                "latitude": "38.7378",
                "last_name": "pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:7][pollins, 7]||[Rollins, 7]",
                "score": "85",
                "time_in_service_yrs": "3.5",
                "assignment_uuid": "ceaf62c4-5ba0-489f-befd-9d0bf1b615b6",
                "employee_id": "987",
                "date_of_hire": "4/24/2018",
                "state": "CO",
                "postal_code": "80925",
                "department": "Marketing",
                "first_name": "Katinka",
                "email": "kendeanre@seesaa.net",
                "longitude": "-104.6459"
            },
            {
                "home_phone": "915-822-0254",
                "street_address": "732 Burning Wood Crossing",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "3149f3c34ca517a441086b18f84df6a3",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:7][pollins, 7]||[Rollins, 7]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "ceaf62c4-5ba0-489f-befd-9d0bf1b615b6",
                "employee_id": "499",
                "date_of_hire": "10/16/2018",
                "state": "TX",
                "department": "Business Development",
                "postal_code": "88535",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "home_phone": "954-559-4887",
                "street_address": "2 Shelley Crossing",
                "gender": "NULL",
                "city": "Orlando",
                "item_key": "2fbd62034cacbb8df22022bc03bfbf19",
                "latitude": "28.5469",
                "last_name": "Pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[Rollins, 8]",
                "score": "85",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "3ba01110-bd31-4beb-8a72-ef60eafea253",
                "employee_id": "988",
                "date_of_hire": "11/28/2018",
                "state": "FL",
                "department": "Legal",
                "postal_code": "32825",
                "first_name": "Kassi",
                "email": "kderellrf@ft.com",
                "longitude": "-81.2571"
            },
            {
                "street_address": "732 Burning Wood Crossing",
                "home_phone": "915-822-0254",
                "gender": "Male",
                "city": "El Paso",
                "item_key": "2fbd62034cacbb8df22022bc03bfbf19",
                "latitude": "31.6948",
                "last_name": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[Rollins, 8]",
                "score": "85",
                "time_in_service_yrs": "3.02",
                "assignment_uuid": "3ba01110-bd31-4beb-8a72-ef60eafea253",
                "employee_id": "499",
                "state": "TX",
                "date_of_hire": "10/16/2018",
                "postal_code": "88535",
                "department": "Business Development",
                "first_name": "Colver",
                "email": "crollinsdu@sciencedaily.com",
                "longitude": "-106.3"
            },
            {
                "home_phone": "904-482-9750",
                "street_address": "00622 Golf Avenue",
                "gender": "Male",
                "city": "Jacksonville",
                "item_key": "e3070c5108ad6a625eea8ca852d33d0a",
                "latitude": "30.0956",
                "last_name": "SaYwOoD",
                "type": "DUPE",
                "item_value": "[score:85, key_id:9][Maywood, 9]||[SaYwOoD, 9]",
                "score": "85",
                "time_in_service_yrs": "2.97",
                "assignment_uuid": "c20be1bb-8574-49d4-bb5f-2831e630eddf",
                "employee_id": "688",
                "date_of_hire": "11/4/2018",
                "state": "FL",
                "department": "Human Resources",
                "postal_code": "32259",
                "first_name": "Denys",
                "email": "dsaywoodj3@weibo.com",
                "longitude": "-81.6217"
            },
            {
                "street_address": "96 Oneill Parkway",
                "home_phone": "814-174-0191",
                "gender": "NULL",
                "city": "Erie",
                "item_key": "e3070c5108ad6a625eea8ca852d33d0a",
                "latitude": "42.1827",
                "last_name": "Maywood",
                "type": "DUPE",
                "item_value": "[score:85, key_id:9][Maywood, 9]||[SaYwOoD, 9]",
                "score": "85",
                "time_in_service_yrs": "3.24",
                "assignment_uuid": "c20be1bb-8574-49d4-bb5f-2831e630eddf",
                "employee_id": "129",
                "date_of_hire": "7/29/2018",
                "state": "PA",
                "department": "Research and Development",
                "postal_code": "16522",
                "first_name": "Thaddeus",
                "email": "tmaywood3k@microsoft.com",
                "longitude": "-80.0649"
            },
            {
                "street_address": "2 Gerald Park",
                "home_phone": "718-149-3139",
                "gender": "Female",
                "city": "New York City",
                "item_key": "56215618687fcfa5328870732d9b050b",
                "latitude": "40.754",
                "last_name": "RIGGINS",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][RIGGINS, 10]||[Siggins, 10]",
                "score": "85",
                "time_in_service_yrs": "2.93",
                "assignment_uuid": "a86e1547-17ff-4906-a1a6-3ef159a6babe",
                "employee_id": "994",
                "state": "NY",
                "date_of_hire": "11/17/2018",
                "department": "Marketing",
                "postal_code": "10110",
                "first_name": "Reamonn",
                "email": "rfalconerrl@spotify.com",
                "longitude": "-73.9808"
            },
            {
                "street_address": "6886 Granby Park",
                "home_phone": "901-601-7599",
                "gender": "Male",
                "city": "Memphis",
                "item_key": "56215618687fcfa5328870732d9b050b",
                "latitude": "35.0425",
                "last_name": "Siggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][RIGGINS, 10]||[Siggins, 10]",
                "score": "85",
                "time_in_service_yrs": "3.88",
                "assignment_uuid": "a86e1547-17ff-4906-a1a6-3ef159a6babe",
                "employee_id": "839",
                "state": "TN",
                "date_of_hire": "12/6/2017",
                "postal_code": "38109",
                "department": "Business Development",
                "first_name": "Filia",
                "email": "fsigginsna@symantec.com",
                "longitude": "-90.0732"
            },
            {
                "home_phone": "513-885-7912",
                "street_address": "43942 Forest Run Pass",
                "gender": "Female",
                "city": "Columbus",
                "item_key": "59e7869faabc69e33ccd34f6842f9719",
                "latitude": "39.9671",
                "last_name": "Taunton",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Tainton, 11]||[Taunton, 11]",
                "score": "85",
                "time_in_service_yrs": "5.98",
                "assignment_uuid": "e1894b5b-93fb-4b2a-8f9b-c0ce222f0cc9",
                "employee_id": "437",
                "date_of_hire": "11/1/2015",
                "state": "OH",
                "department": "Engineering",
                "postal_code": "43215",
                "first_name": "Diena",
                "email": "dtauntonc4@about.com",
                "longitude": "-83.0044"
            },
            {
                "home_phone": "952-832-3196",
                "street_address": "79438 Parkside Drive",
                "gender": "Female",
                "city": "Young America",
                "item_key": "59e7869faabc69e33ccd34f6842f9719",
                "latitude": "44.8055",
                "last_name": "Tainton",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Tainton, 11]||[Taunton, 11]",
                "score": "85",
                "time_in_service_yrs": "3.06",
                "assignment_uuid": "e1894b5b-93fb-4b2a-8f9b-c0ce222f0cc9",
                "employee_id": "22",
                "date_of_hire": "9/30/2018",
                "state": "MN",
                "postal_code": "55557",
                "department": "Research and Development",
                "first_name": "Dyanne",
                "email": "dtaintonl@answers.com",
                "longitude": "-93.7665"
            },
            {
                "home_phone": "609-938-9163",
                "street_address": "3 Buena Vista Drive",
                "gender": "Male",
                "city": "Trenton",
                "item_key": "6ad4ebb814a9827b357a1e241078ef0e",
                "latitude": "40.2805",
                "last_name": "Diggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:12][Diggins, 12]||[RIGGINS, 12]",
                "score": "85",
                "time_in_service_yrs": "2.88",
                "assignment_uuid": "e4757c34-08ba-4671-ad24-d8606225287a",
                "employee_id": "100",
                "date_of_hire": "12/4/2018",
                "state": "NJ",
                "department": "Services",
                "postal_code": "8650",
                "first_name": "Nicky",
                "email": "ndiggins2r@gov.uk",
                "longitude": "-74.712"
            },
            {
                "street_address": "2 Gerald Park",
                "home_phone": "718-149-3139",
                "gender": "Female",
                "city": "New York City",
                "item_key": "6ad4ebb814a9827b357a1e241078ef0e",
                "latitude": "40.754",
                "last_name": "RIGGINS",
                "type": "DUPE",
                "item_value": "[score:85, key_id:12][Diggins, 12]||[RIGGINS, 12]",
                "score": "85",
                "time_in_service_yrs": "2.93",
                "assignment_uuid": "e4757c34-08ba-4671-ad24-d8606225287a",
                "employee_id": "994",
                "date_of_hire": "11/17/2018",
                "state": "NY",
                "department": "Marketing",
                "postal_code": "10110",
                "first_name": "Reamonn",
                "email": "rfalconerrl@spotify.com",
                "longitude": "-73.9808"
            },
            {
                "home_phone": "901-601-7599",
                "street_address": "6886 Granby Park",
                "gender": "Male",
                "city": "Memphis",
                "item_key": "5f14e29248ed755369e8687588a79809",
                "latitude": "35.0425",
                "last_name": "Siggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:13][Diggins, 13]||[Siggins, 13]",
                "score": "85",
                "time_in_service_yrs": "3.88",
                "assignment_uuid": "c70df8e2-8a3b-4e55-a97f-3fe54a005768",
                "employee_id": "839",
                "date_of_hire": "12/6/2017",
                "state": "TN",
                "department": "Business Development",
                "postal_code": "38109",
                "first_name": "Filia",
                "email": "fsigginsna@symantec.com",
                "longitude": "-90.0732"
            },
            {
                "street_address": "3 Buena Vista Drive",
                "home_phone": "609-938-9163",
                "gender": "Male",
                "city": "Trenton",
                "item_key": "5f14e29248ed755369e8687588a79809",
                "latitude": "40.2805",
                "last_name": "Diggins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:13][Diggins, 13]||[Siggins, 13]",
                "score": "85",
                "time_in_service_yrs": "2.88",
                "assignment_uuid": "c70df8e2-8a3b-4e55-a97f-3fe54a005768",
                "employee_id": "100",
                "state": "NJ",
                "date_of_hire": "12/4/2018",
                "postal_code": "8650",
                "department": "Services",
                "first_name": "Nicky",
                "email": "ndiggins2r@gov.uk",
                "longitude": "-74.712"
            },
            {
                "street_address": "4204 Vera Park",
                "home_phone": "316-864-5692",
                "gender": "Female",
                "city": "Wichita",
                "item_key": "0c2d60d9f44c4b412465afadb9901d89",
                "latitude": "37.6808",
                "last_name": "mosdall",
                "type": "DUPE",
                "item_value": "[score:86, key_id:14][mosdall, 14]||[Mousdall, 14]",
                "score": "86",
                "time_in_service_yrs": "5.27",
                "assignment_uuid": "3bd79044-a44e-47aa-ab8c-4015fc0b7575",
                "employee_id": "680",
                "state": "KS",
                "date_of_hire": "7/18/2016",
                "postal_code": "67230",
                "department": "Business Development",
                "first_name": "Dorotea",
                "email": "dmosdalliv@acquirethisname.com",
                "longitude": "-97.1558"
            },
            {
                "home_phone": "727-495-9149",
                "street_address": "98 Myrtle Terrace",
                "gender": "NULL",
                "city": "Largo",
                "item_key": "0c2d60d9f44c4b412465afadb9901d89",
                "latitude": "27.881",
                "last_name": "Mousdall",
                "type": "DUPE",
                "item_value": "[score:86, key_id:14][mosdall, 14]||[Mousdall, 14]",
                "score": "86",
                "time_in_service_yrs": "3.35",
                "assignment_uuid": "3bd79044-a44e-47aa-ab8c-4015fc0b7575",
                "employee_id": "498",
                "date_of_hire": "6/17/2018",
                "state": "FL",
                "department": "Support",
                "postal_code": "34643",
                "first_name": "May",
                "email": "mmousdalldt@phpbb.com",
                "longitude": "-82.7619"
            },
            {
                "home_phone": "818-851-0399",
                "street_address": "95 Northwestern Pass",
                "gender": "Male",
                "city": "Northridge",
                "item_key": "0534b4e9c361cff221c74f6d0166d824",
                "latitude": "33.7866",
                "last_name": "Edridge",
                "type": "DUPE",
                "item_value": "[score:86, key_id:15][Edridge, 15]||[Eldridge, 15]",
                "score": "86",
                "time_in_service_yrs": "3.01",
                "assignment_uuid": "f663ef98-4b53-4b4b-aad9-9801c924be75",
                "employee_id": "802",
                "date_of_hire": "10/19/2018",
                "state": "CA",
                "department": "Legal",
                "postal_code": "91328",
                "first_name": "Rubin",
                "email": "redridgem9@wikipedia.org",
                "longitude": "-118.2987"
            },
            {
                "street_address": "35 Carioca Court",
                "home_phone": "571-285-8377",
                "gender": "Male",
                "city": "Dulles",
                "item_key": "0534b4e9c361cff221c74f6d0166d824",
                "latitude": "39.009",
                "last_name": "Eldridge",
                "type": "DUPE",
                "item_value": "[score:86, key_id:15][Edridge, 15]||[Eldridge, 15]",
                "score": "86",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "f663ef98-4b53-4b4b-aad9-9801c924be75",
                "employee_id": "355",
                "date_of_hire": "11/28/2018",
                "state": "VA",
                "department": "Marketing",
                "postal_code": "20189",
                "first_name": "Justus",
                "email": "jeldridge9u@hp.com",
                "longitude": "-77.4422"
            },
            {
                "street_address": "5883 Donald Alley",
                "home_phone": "312-341-6435",
                "gender": "Female",
                "city": "Chicago",
                "item_key": "12d69c774bf9ba81e181c869c6b7e686",
                "latitude": "41.8756",
                "last_name": "Robinett",
                "type": "DUPE",
                "item_value": "[score:86, key_id:16][Robinet, 16]||[Robinett, 16]",
                "score": "86",
                "time_in_service_yrs": "4.63",
                "assignment_uuid": "3e031cd9-1f64-452b-a9cd-b712a77119ea",
                "employee_id": "815",
                "state": "IL",
                "date_of_hire": "3/6/2017",
                "postal_code": "60686",
                "department": "Legal",
                "first_name": "Johnna",
                "email": "jrobinettmm@photobucket.com",
                "longitude": "-87.6378"
            },
            {
                "street_address": "6173 Glacier Hill Trail",
                "home_phone": "336-142-9688",
                "gender": "Male",
                "city": "Greensboro",
                "item_key": "12d69c774bf9ba81e181c869c6b7e686",
                "latitude": "36.0807",
                "last_name": "Robinet",
                "type": "DUPE",
                "item_value": "[score:86, key_id:16][Robinet, 16]||[Robinett, 16]",
                "score": "86",
                "time_in_service_yrs": "2.99",
                "assignment_uuid": "3e031cd9-1f64-452b-a9cd-b712a77119ea",
                "employee_id": "706",
                "state": "NC",
                "date_of_hire": "10/25/2018",
                "postal_code": "27404",
                "department": "Accounting",
                "first_name": "Buckie",
                "email": "brobinetjl@ftc.gov",
                "longitude": "-80.0244"
            },
            {
                "street_address": "8 Dorton Circle",
                "home_phone": "763-174-2429",
                "gender": "Female",
                "city": "Monticello",
                "item_key": "3fe104799bbbdbfec538c0cdb950ef65",
                "latitude": "45.2009",
                "last_name": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:17][Gillings, 17]||[Millings, 17]",
                "score": "87",
                "time_in_service_yrs": "3.59",
                "assignment_uuid": "4f6da2a4-2e30-4309-9f3f-4327e564b63b",
                "employee_id": "999",
                "state": "MN",
                "date_of_hire": "3/21/2018",
                "postal_code": "55565",
                "department": "Training",
                "first_name": "Cloris",
                "email": "cgreenroadrq@mapy.cz",
                "longitude": "-93.8881"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Male",
                "city": "Cincinnati",
                "item_key": "3fe104799bbbdbfec538c0cdb950ef65",
                "latitude": "39.0706",
                "last_name": "Gillings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:17][Gillings, 17]||[Millings, 17]",
                "score": "87",
                "time_in_service_yrs": "3.48",
                "assignment_uuid": "4f6da2a4-2e30-4309-9f3f-4327e564b63b",
                "employee_id": "441",
                "date_of_hire": "5/1/2018",
                "state": "OH",
                "department": "Training",
                "postal_code": "45228",
                "first_name": "Curcio",
                "email": "cgillingsc8@stumbleupon.com",
                "longitude": "-84.4179"
            },
            {
                "home_phone": "571-285-8377",
                "street_address": "35 Carioca Court",
                "gender": "Male",
                "city": "Dulles",
                "item_key": "405b43696f7ba5ff742e8ea0facde15e",
                "latitude": "39.009",
                "last_name": "Eldridge",
                "type": "DUPE",
                "item_value": "[score:87, key_id:18][Aldridge, 18]||[Eldridge, 18]",
                "score": "87",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "4c4179ef-1cbb-4441-b96a-19c87fda7826",
                "employee_id": "355",
                "date_of_hire": "11/28/2018",
                "state": "VA",
                "department": "Marketing",
                "postal_code": "20189",
                "first_name": "Justus",
                "email": "jeldridge9u@hp.com",
                "longitude": "-77.4422"
            },
            {
                "home_phone": "972-374-8599",
                "street_address": "02931 Monument Drive",
                "gender": "Female",
                "city": "Dallas",
                "item_key": "405b43696f7ba5ff742e8ea0facde15e",
                "latitude": "32.7887",
                "last_name": "Aldridge",
                "type": "DUPE",
                "item_value": "[score:87, key_id:18][Aldridge, 18]||[Eldridge, 18]",
                "score": "87",
                "time_in_service_yrs": "4.03",
                "assignment_uuid": "4c4179ef-1cbb-4441-b96a-19c87fda7826",
                "employee_id": "179",
                "date_of_hire": "10/13/2017",
                "state": "TX",
                "department": "Product Management",
                "postal_code": "75226",
                "first_name": "Jayme",
                "email": "jaldridge4y@instagram.com",
                "longitude": "-96.7676"
            },
            {
                "street_address": "0903 Bellgrove Avenue",
                "home_phone": "410-189-4551",
                "gender": "Female",
                "city": "Baltimore",
                "item_key": "28ad4d428a7611d2925701f9312e961e",
                "latitude": "39.361",
                "last_name": "Billings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:19][Billings, 19]||[Gillings, 19]",
                "score": "87",
                "time_in_service_yrs": "3.35",
                "assignment_uuid": "9b2532f4-e2cc-4768-b871-cd8b4ed4ec8b",
                "employee_id": "624",
                "date_of_hire": "6/18/2018",
                "state": "MD",
                "department": "Product Management",
                "postal_code": "21239",
                "first_name": "Cecilia",
                "email": "cbillingshb@nbcnews.com",
                "longitude": "-76.5891"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Male",
                "city": "Cincinnati",
                "item_key": "28ad4d428a7611d2925701f9312e961e",
                "latitude": "39.0706",
                "last_name": "Gillings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:19][Billings, 19]||[Gillings, 19]",
                "score": "87",
                "time_in_service_yrs": "3.48",
                "assignment_uuid": "9b2532f4-e2cc-4768-b871-cd8b4ed4ec8b",
                "employee_id": "441",
                "date_of_hire": "5/1/2018",
                "state": "OH",
                "department": "Training",
                "postal_code": "45228",
                "first_name": "Curcio",
                "email": "cgillingsc8@stumbleupon.com",
                "longitude": "-84.4179"
            },
            {
                "street_address": "8 Dorton Circle",
                "home_phone": "763-174-2429",
                "gender": "Female",
                "city": "Monticello",
                "item_key": "2f6d7aea318c5f48a02cf6fb0971080f",
                "latitude": "45.2009",
                "last_name": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:20][Billings, 20]||[Millings, 20]",
                "score": "87",
                "time_in_service_yrs": "3.59",
                "assignment_uuid": "0354a335-248a-4def-a7ab-d8bf180fc660",
                "employee_id": "999",
                "state": "MN",
                "date_of_hire": "3/21/2018",
                "postal_code": "55565",
                "department": "Training",
                "first_name": "Cloris",
                "email": "cgreenroadrq@mapy.cz",
                "longitude": "-93.8881"
            },
            {
                "home_phone": "410-189-4551",
                "street_address": "0903 Bellgrove Avenue",
                "gender": "Female",
                "city": "Baltimore",
                "item_key": "2f6d7aea318c5f48a02cf6fb0971080f",
                "latitude": "39.361",
                "last_name": "Billings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:20][Billings, 20]||[Millings, 20]",
                "score": "87",
                "time_in_service_yrs": "3.35",
                "assignment_uuid": "0354a335-248a-4def-a7ab-d8bf180fc660",
                "employee_id": "624",
                "state": "MD",
                "date_of_hire": "6/18/2018",
                "department": "Product Management",
                "postal_code": "21239",
                "first_name": "Cecilia",
                "email": "cbillingshb@nbcnews.com",
                "longitude": "-76.5891"
            },
            {
                "street_address": "96 Sunbrook Plaza",
                "home_phone": "202-493-9320",
                "gender": "Female",
                "city": "Washington",
                "item_key": "60f4f9a9e4398e33245d460247b026cb",
                "latitude": "38.8933",
                "last_name": "PHILPOTTS",
                "type": "DUPE",
                "item_value": "[score:88, key_id:21][Philpots, 21]||[PHILPOTTS, 21]",
                "score": "88",
                "time_in_service_yrs": "3.16",
                "assignment_uuid": "7f7554a3-5b2b-4909-9e20-9a1114fe7d5b",
                "employee_id": "603",
                "state": "DC",
                "date_of_hire": "8/27/2018",
                "postal_code": "20580",
                "department": "Support",
                "first_name": "Bettye",
                "email": "bphilpottsgq@mail.ru",
                "longitude": "-77.0146"
            },
            {
                "home_phone": "972-569-5687",
                "street_address": "59170 Manufacturers Pass",
                "gender": "Female",
                "city": "Dallas",
                "item_key": "60f4f9a9e4398e33245d460247b026cb",
                "latitude": "32.7948",
                "last_name": "Philpots",
                "type": "DUPE",
                "item_value": "[score:88, key_id:21][Philpots, 21]||[PHILPOTTS, 21]",
                "score": "88",
                "time_in_service_yrs": "2.99",
                "assignment_uuid": "7f7554a3-5b2b-4909-9e20-9a1114fe7d5b",
                "employee_id": "295",
                "date_of_hire": "10/26/2018",
                "state": "TX",
                "department": "Training",
                "postal_code": "75246",
                "first_name": "Hynda",
                "email": "hphilpots86@example.com",
                "longitude": "-96.7697"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "home_phone",
                "name": "home_phone",
                "title": "home_phone"
            },
            {
                "data": "street_address",
                "name": "street_address",
                "title": "street_address"
            },
            {
                "data": "gender",
                "name": "gender",
                "title": "gender"
            },
            {
                "data": "city",
                "name": "city",
                "title": "city"
            },
            {
                "data": "latitude",
                "name": "latitude",
                "title": "latitude"
            },
            {
                "data": "last_name",
                "name": "last_name",
                "title": "last_name"
            },
            {
                "data": "time_in_service_yrs",
                "name": "time_in_service_yrs",
                "title": "time_in_service_yrs"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "employee_id",
                "name": "employee_id",
                "title": "employee_id"
            },
            {
                "data": "date_of_hire",
                "name": "date_of_hire",
                "title": "date_of_hire"
            },
            {
                "data": "state",
                "name": "state",
                "title": "state"
            },
            {
                "data": "department",
                "name": "department",
                "title": "department"
            },
            {
                "data": "postal_code",
                "name": "postal_code",
                "title": "postal_code"
            },
            {
                "data": "first_name",
                "name": "first_name",
                "title": "first_name"
            },
            {
                "data": "email",
                "name": "email",
                "title": "email"
            },
            {
                "data": "longitude",
                "name": "longitude",
                "title": "longitude"
            }
        ]
    }
]

PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": 219,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "354",
        "score": 85
    },
    {
        "seqno": 220,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 21,
        "dupe1": "Philpots",
        "dupe1_link_id": "295",
        "dupe2": "PHILPOTTS",
        "dupe2_link_id": "603",
        "score": 88
    },
    {
        "seqno": 221,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 20,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": 222,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 19,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Gillings",
        "dupe2_link_id": "441",
        "score": 87
    },
    {
        "seqno": 223,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 18,
        "dupe1": "Aldridge",
        "dupe1_link_id": "179",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 87
    },
    {
        "seqno": 224,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 17,
        "dupe1": "Gillings",
        "dupe1_link_id": "441",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": 225,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 16,
        "dupe1": "Robinet",
        "dupe1_link_id": "706",
        "dupe2": "Robinett",
        "dupe2_link_id": "815",
        "score": 86
    },
    {
        "seqno": 226,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 15,
        "dupe1": "Edridge",
        "dupe1_link_id": "802",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 86
    },
    {
        "seqno": 227,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 14,
        "dupe1": "mosdall",
        "dupe1_link_id": "680",
        "dupe2": "Mousdall",
        "dupe2_link_id": "498",
        "score": 86
    },
    {
        "seqno": 228,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 13,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": 229,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 12,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "RIGGINS",
        "dupe2_link_id": "994",
        "score": 85
    },
    {
        "seqno": 230,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 11,
        "dupe1": "Tainton",
        "dupe1_link_id": "22",
        "dupe2": "Taunton",
        "dupe2_link_id": "437",
        "score": 85
    },
    {
        "seqno": 231,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 10,
        "dupe1": "RIGGINS",
        "dupe1_link_id": "994",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": 232,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 9,
        "dupe1": "Maywood",
        "dupe1_link_id": "129",
        "dupe2": "SaYwOoD",
        "dupe2_link_id": "688",
        "score": 85
    },
    {
        "seqno": 233,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": 234,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "pollins",
        "dupe1_link_id": "987",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": 235,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": 236,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Giblett",
        "dupe1_link_id": "944",
        "dupe2": "NibletT",
        "dupe2_link_id": "163",
        "score": 85
    },
    {
        "seqno": 237,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "hAlLoCk",
        "dupe1_link_id": "511",
        "dupe2": "Harlock",
        "dupe2_link_id": "146",
        "score": 85
    },
    {
        "seqno": 238,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "990",
        "score": 85
    },
    {
        "seqno": 239,
        "updts": "2024-07-22T14:56:46.150+0000",
        "job_uuid": "c9a1d620-4f86-4324-9947-8a721136c9b2",
        "dataset": PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-22T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "CLARDGE",
        "dupe2_link_id": "989",
        "score": 85
    }
]

PD_TRINO_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "583",
        "first_name": "Katherine",
        "last_name": "Clarage",
        "email": "kclarageg6@creativecommons.org",
        "gender": "Male",
        "city": "Knoxville",
        "department": "Sales",
        "latitude": "40.7955",
        "longitude": "-84.1383",
        "home_phone": "865-418-3128",
        "postal_code": "37924",
        "state": "TN",
        "street_address": "66675 High Crossing Way",
        "date_of_hire": "11/6/2018",
        "time_in_service_yrs": 2.96
    },
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "354",
        "first_name": "Jdavie",
        "last_name": "Clardge",
        "email": "jclardge9t@illinois.edu",
        "gender": "Male",
        "city": "Huntington",
        "department": "Research and Development",
        "latitude": "38.4134",
        "longitude": "-82.2774",
        "home_phone": "304-559-1266",
        "postal_code": "25716",
        "state": "WV",
        "street_address": "83 Kropf Way",
        "date_of_hire": "7/2/2018",
        "time_in_service_yrs": 3.31
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "CLARDGE",
        "employee_id": "989",
        "first_name": "Terrye",
        "last_name": "CLARDGE",
        "email": "thayerrg@home.pl",
        "gender": None,
        "city": "New York City",
        "department": "Research and Development",
        "latitude": "40.7808",
        "longitude": "-73.9772",
        "home_phone": "212-511-8481",
        "postal_code": "10125",
        "state": "NY",
        "street_address": "505 Golf Course Road",
        "date_of_hire": "4/1/2017",
        "time_in_service_yrs": 4.56
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "CLARDGE",
        "employee_id": "583",
        "first_name": "Katherine",
        "last_name": "Clarage",
        "email": "kclarageg6@creativecommons.org",
        "gender": "Male",
        "city": "Knoxville",
        "department": "Sales",
        "latitude": "40.7955",
        "longitude": "-84.1383",
        "home_phone": "865-418-3128",
        "postal_code": "37924",
        "state": "TN",
        "street_address": "66675 High Crossing Way",
        "date_of_hire": "11/6/2018",
        "time_in_service_yrs": 2.96
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "990",
        "first_name": "Brook",
        "last_name": "Clardge",
        "email": "bcheerrh@marketwatch.com",
        "gender": "Male",
        "city": "San Bernardino",
        "department": "Human Resources",
        "latitude": "34.84",
        "longitude": "-115.9671",
        "home_phone": "909-606-7780",
        "postal_code": "92424",
        "state": "CA",
        "street_address": "8658 Ridgeway Point",
        "date_of_hire": "9/9/2018",
        "time_in_service_yrs": 3.12
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "employee_id": "583",
        "first_name": "Katherine",
        "last_name": "Clarage",
        "email": "kclarageg6@creativecommons.org",
        "gender": "Male",
        "city": "Knoxville",
        "department": "Sales",
        "latitude": "40.7955",
        "longitude": "-84.1383",
        "home_phone": "865-418-3128",
        "postal_code": "37924",
        "state": "TN",
        "street_address": "66675 High Crossing Way",
        "date_of_hire": "11/6/2018",
        "time_in_service_yrs": 2.96
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "hAlLoCk",
        "dupe2": "Harlock",
        "employee_id": "511",
        "first_name": "Beaufort",
        "last_name": "hAlLoCk",
        "email": "bhallocke6@dailymail.co.uk",
        "gender": "Male",
        "city": "Denver",
        "department": "Product Management",
        "latitude": "39.734",
        "longitude": "-105.0259",
        "home_phone": "303-255-9434",
        "postal_code": "80204",
        "state": "CO",
        "street_address": "17 Dixon Circle",
        "date_of_hire": "12/2/2018",
        "time_in_service_yrs": 2.89
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "hAlLoCk",
        "dupe2": "Harlock",
        "employee_id": "146",
        "first_name": "Dale",
        "last_name": "Harlock",
        "email": "dharlock41@guardian.co.uk",
        "gender": None,
        "city": "El Paso",
        "department": "Marketing",
        "latitude": "31.9386",
        "longitude": "-106.4073",
        "home_phone": "915-842-8761",
        "postal_code": "79934",
        "state": "TX",
        "street_address": "6 Loeprich Pass",
        "date_of_hire": "11/13/2017",
        "time_in_service_yrs": 3.94
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Giblett",
        "dupe2": "NibletT",
        "employee_id": "944",
        "first_name": "Kata",
        "last_name": "Giblett",
        "email": "kgiblettq7@census.gov",
        "gender": "Female",
        "city": "Austin",
        "department": "Support",
        "latitude": "30.3264",
        "longitude": "-97.7713",
        "home_phone": "512-954-0424",
        "postal_code": "78769",
        "state": "TX",
        "street_address": "41171 Becker Lane",
        "date_of_hire": "9/12/2018",
        "time_in_service_yrs": 3.11
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Giblett",
        "dupe2": "NibletT",
        "employee_id": "163",
        "first_name": "Rosetta",
        "last_name": "NibletT",
        "email": "rniblett4i@unblog.fr",
        "gender": None,
        "city": "San Francisco",
        "department": "Training",
        "latitude": "37.7848",
        "longitude": "-122.7278",
        "home_phone": "415-989-1878",
        "postal_code": "94154",
        "state": "CA",
        "street_address": "2177 Kenwood Drive",
        "date_of_hire": "9/30/2018",
        "time_in_service_yrs": 3.06
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "368",
        "first_name": "Ari",
        "last_name": "Pollins",
        "email": "apollinsa7@pen.io",
        "gender": "Female",
        "city": "Miami",
        "department": "Support",
        "latitude": "25.6615",
        "longitude": "-80.441",
        "home_phone": "786-873-7423",
        "postal_code": "33196",
        "state": "FL",
        "street_address": "150 Magdeline Crossing",
        "date_of_hire": "10/7/2015",
        "time_in_service_yrs": 6.05
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "pollins",
        "dupe2": "Rollins",
        "employee_id": "987",
        "first_name": "Katinka",
        "last_name": "pollins",
        "email": "kendeanre@seesaa.net",
        "gender": "Female",
        "city": "Colorado Springs",
        "department": "Marketing",
        "latitude": "38.7378",
        "longitude": "-104.6459",
        "home_phone": "719-537-1533",
        "postal_code": "80925",
        "state": "CO",
        "street_address": "5 Sunnyside Junction",
        "date_of_hire": "4/24/2018",
        "time_in_service_yrs": 3.5
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "pollins",
        "dupe2": "Rollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "988",
        "first_name": "Kassi",
        "last_name": "Pollins",
        "email": "kderellrf@ft.com",
        "gender": None,
        "city": "Orlando",
        "department": "Legal",
        "latitude": "28.5469",
        "longitude": "-81.2571",
        "home_phone": "954-559-4887",
        "postal_code": "32825",
        "state": "FL",
        "street_address": "2 Shelley Crossing",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "employee_id": "499",
        "first_name": "Colver",
        "last_name": "Rollins",
        "email": "crollinsdu@sciencedaily.com",
        "gender": "Male",
        "city": "El Paso",
        "department": "Business Development",
        "latitude": "31.6948",
        "longitude": "-106.3",
        "home_phone": "915-822-0254",
        "postal_code": "88535",
        "state": "TX",
        "street_address": "732 Burning Wood Crossing",
        "date_of_hire": "10/16/2018",
        "time_in_service_yrs": 3.02
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Maywood",
        "dupe2": "SaYwOoD",
        "employee_id": "688",
        "first_name": "Denys",
        "last_name": "SaYwOoD",
        "email": "dsaywoodj3@weibo.com",
        "gender": "Male",
        "city": "Jacksonville",
        "department": "Human Resources",
        "latitude": "30.0956",
        "longitude": "-81.6217",
        "home_phone": "904-482-9750",
        "postal_code": "32259",
        "state": "FL",
        "street_address": "00622 Golf Avenue",
        "date_of_hire": "11/4/2018",
        "time_in_service_yrs": 2.97
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Maywood",
        "dupe2": "SaYwOoD",
        "employee_id": "129",
        "first_name": "Thaddeus",
        "last_name": "Maywood",
        "email": "tmaywood3k@microsoft.com",
        "gender": None,
        "city": "Erie",
        "department": "Research and Development",
        "latitude": "42.1827",
        "longitude": "-80.0649",
        "home_phone": "814-174-0191",
        "postal_code": "16522",
        "state": "PA",
        "street_address": "96 Oneill Parkway",
        "date_of_hire": "7/29/2018",
        "time_in_service_yrs": 3.24
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "RIGGINS",
        "dupe2": "Siggins",
        "employee_id": "994",
        "first_name": "Reamonn",
        "last_name": "RIGGINS",
        "email": "rfalconerrl@spotify.com",
        "gender": "Female",
        "city": "New York City",
        "department": "Marketing",
        "latitude": "40.754",
        "longitude": "-73.9808",
        "home_phone": "718-149-3139",
        "postal_code": "10110",
        "state": "NY",
        "street_address": "2 Gerald Park",
        "date_of_hire": "11/17/2018",
        "time_in_service_yrs": 2.93
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "RIGGINS",
        "dupe2": "Siggins",
        "employee_id": "839",
        "first_name": "Filia",
        "last_name": "Siggins",
        "email": "fsigginsna@symantec.com",
        "gender": "Male",
        "city": "Memphis",
        "department": "Business Development",
        "latitude": "35.0425",
        "longitude": "-90.0732",
        "home_phone": "901-601-7599",
        "postal_code": "38109",
        "state": "TN",
        "street_address": "6886 Granby Park",
        "date_of_hire": "12/6/2017",
        "time_in_service_yrs": 3.88
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "employee_id": "437",
        "first_name": "Diena",
        "last_name": "Taunton",
        "email": "dtauntonc4@about.com",
        "gender": "Female",
        "city": "Columbus",
        "department": "Engineering",
        "latitude": "39.9671",
        "longitude": "-83.0044",
        "home_phone": "513-885-7912",
        "postal_code": "43215",
        "state": "OH",
        "street_address": "43942 Forest Run Pass",
        "date_of_hire": "11/1/2015",
        "time_in_service_yrs": 5.98
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "employee_id": "22",
        "first_name": "Dyanne",
        "last_name": "Tainton",
        "email": "dtaintonl@answers.com",
        "gender": "Female",
        "city": "Young America",
        "department": "Research and Development",
        "latitude": "44.8055",
        "longitude": "-93.7665",
        "home_phone": "952-832-3196",
        "postal_code": "55557",
        "state": "MN",
        "street_address": "79438 Parkside Drive",
        "date_of_hire": "9/30/2018",
        "time_in_service_yrs": 3.06
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "RIGGINS",
        "employee_id": "100",
        "first_name": "Nicky",
        "last_name": "Diggins",
        "email": "ndiggins2r@gov.uk",
        "gender": "Male",
        "city": "Trenton",
        "department": "Services",
        "latitude": "40.2805",
        "longitude": "-74.712",
        "home_phone": "609-938-9163",
        "postal_code": "8650",
        "state": "NJ",
        "street_address": "3 Buena Vista Drive",
        "date_of_hire": "12/4/2018",
        "time_in_service_yrs": 2.88
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "RIGGINS",
        "employee_id": "994",
        "first_name": "Reamonn",
        "last_name": "RIGGINS",
        "email": "rfalconerrl@spotify.com",
        "gender": "Female",
        "city": "New York City",
        "department": "Marketing",
        "latitude": "40.754",
        "longitude": "-73.9808",
        "home_phone": "718-149-3139",
        "postal_code": "10110",
        "state": "NY",
        "street_address": "2 Gerald Park",
        "date_of_hire": "11/17/2018",
        "time_in_service_yrs": 2.93
    },
    {
        "key_id": 13,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "employee_id": "839",
        "first_name": "Filia",
        "last_name": "Siggins",
        "email": "fsigginsna@symantec.com",
        "gender": "Male",
        "city": "Memphis",
        "department": "Business Development",
        "latitude": "35.0425",
        "longitude": "-90.0732",
        "home_phone": "901-601-7599",
        "postal_code": "38109",
        "state": "TN",
        "street_address": "6886 Granby Park",
        "date_of_hire": "12/6/2017",
        "time_in_service_yrs": 3.88
    },
    {
        "key_id": 13,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "employee_id": "100",
        "first_name": "Nicky",
        "last_name": "Diggins",
        "email": "ndiggins2r@gov.uk",
        "gender": "Male",
        "city": "Trenton",
        "department": "Services",
        "latitude": "40.2805",
        "longitude": "-74.712",
        "home_phone": "609-938-9163",
        "postal_code": "8650",
        "state": "NJ",
        "street_address": "3 Buena Vista Drive",
        "date_of_hire": "12/4/2018",
        "time_in_service_yrs": 2.88
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "mosdall",
        "dupe2": "Mousdall",
        "employee_id": "680",
        "first_name": "Dorotea",
        "last_name": "mosdall",
        "email": "dmosdalliv@acquirethisname.com",
        "gender": "Female",
        "city": "Wichita",
        "department": "Business Development",
        "latitude": "37.6808",
        "longitude": "-97.1558",
        "home_phone": "316-864-5692",
        "postal_code": "67230",
        "state": "KS",
        "street_address": "4204 Vera Park",
        "date_of_hire": "7/18/2016",
        "time_in_service_yrs": 5.27
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "mosdall",
        "dupe2": "Mousdall",
        "employee_id": "498",
        "first_name": "May",
        "last_name": "Mousdall",
        "email": "mmousdalldt@phpbb.com",
        "gender": None,
        "city": "Largo",
        "department": "Support",
        "latitude": "27.881",
        "longitude": "-82.7619",
        "home_phone": "727-495-9149",
        "postal_code": "34643",
        "state": "FL",
        "street_address": "98 Myrtle Terrace",
        "date_of_hire": "6/17/2018",
        "time_in_service_yrs": 3.35
    },
    {
        "key_id": 15,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "employee_id": "802",
        "first_name": "Rubin",
        "last_name": "Edridge",
        "email": "redridgem9@wikipedia.org",
        "gender": "Male",
        "city": "Northridge",
        "department": "Legal",
        "latitude": "33.7866",
        "longitude": "-118.2987",
        "home_phone": "818-851-0399",
        "postal_code": "91328",
        "state": "CA",
        "street_address": "95 Northwestern Pass",
        "date_of_hire": "10/19/2018",
        "time_in_service_yrs": 3.01
    },
    {
        "key_id": 15,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "employee_id": "355",
        "first_name": "Justus",
        "last_name": "Eldridge",
        "email": "jeldridge9u@hp.com",
        "gender": "Male",
        "city": "Dulles",
        "department": "Marketing",
        "latitude": "39.009",
        "longitude": "-77.4422",
        "home_phone": "571-285-8377",
        "postal_code": "20189",
        "state": "VA",
        "street_address": "35 Carioca Court",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 16,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "employee_id": "815",
        "first_name": "Johnna",
        "last_name": "Robinett",
        "email": "jrobinettmm@photobucket.com",
        "gender": "Female",
        "city": "Chicago",
        "department": "Legal",
        "latitude": "41.8756",
        "longitude": "-87.6378",
        "home_phone": "312-341-6435",
        "postal_code": "60686",
        "state": "IL",
        "street_address": "5883 Donald Alley",
        "date_of_hire": "3/6/2017",
        "time_in_service_yrs": 4.63
    },
    {
        "key_id": 16,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "employee_id": "706",
        "first_name": "Buckie",
        "last_name": "Robinet",
        "email": "brobinetjl@ftc.gov",
        "gender": "Male",
        "city": "Greensboro",
        "department": "Accounting",
        "latitude": "36.0807",
        "longitude": "-80.0244",
        "home_phone": "336-142-9688",
        "postal_code": "27404",
        "state": "NC",
        "street_address": "6173 Glacier Hill Trail",
        "date_of_hire": "10/25/2018",
        "time_in_service_yrs": 2.99
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "employee_id": "999",
        "first_name": "Cloris",
        "last_name": "Millings",
        "email": "cgreenroadrq@mapy.cz",
        "gender": "Female",
        "city": "Monticello",
        "department": "Training",
        "latitude": "45.2009",
        "longitude": "-93.8881",
        "home_phone": "763-174-2429",
        "postal_code": "55565",
        "state": "MN",
        "street_address": "8 Dorton Circle",
        "date_of_hire": "3/21/2018",
        "time_in_service_yrs": 3.59
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "employee_id": "441",
        "first_name": "Curcio",
        "last_name": "Gillings",
        "email": "cgillingsc8@stumbleupon.com",
        "gender": "Male",
        "city": "Cincinnati",
        "department": "Training",
        "latitude": "39.0706",
        "longitude": "-84.4179",
        "home_phone": None,
        "postal_code": "45228",
        "state": "OH",
        "street_address": None,
        "date_of_hire": "5/1/2018",
        "time_in_service_yrs": 3.48
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "employee_id": "355",
        "first_name": "Justus",
        "last_name": "Eldridge",
        "email": "jeldridge9u@hp.com",
        "gender": "Male",
        "city": "Dulles",
        "department": "Marketing",
        "latitude": "39.009",
        "longitude": "-77.4422",
        "home_phone": "571-285-8377",
        "postal_code": "20189",
        "state": "VA",
        "street_address": "35 Carioca Court",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "employee_id": "179",
        "first_name": "Jayme",
        "last_name": "Aldridge",
        "email": "jaldridge4y@instagram.com",
        "gender": "Female",
        "city": "Dallas",
        "department": "Product Management",
        "latitude": "32.7887",
        "longitude": "-96.7676",
        "home_phone": "972-374-8599",
        "postal_code": "75226",
        "state": "TX",
        "street_address": "02931 Monument Drive",
        "date_of_hire": "10/13/2017",
        "time_in_service_yrs": 4.03
    },
    {
        "key_id": 19,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "employee_id": "624",
        "first_name": "Cecilia",
        "last_name": "Billings",
        "email": "cbillingshb@nbcnews.com",
        "gender": "Female",
        "city": "Baltimore",
        "department": "Product Management",
        "latitude": "39.361",
        "longitude": "-76.5891",
        "home_phone": "410-189-4551",
        "postal_code": "21239",
        "state": "MD",
        "street_address": "0903 Bellgrove Avenue",
        "date_of_hire": "6/18/2018",
        "time_in_service_yrs": 3.35
    },
    {
        "key_id": 19,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "employee_id": "441",
        "first_name": "Curcio",
        "last_name": "Gillings",
        "email": "cgillingsc8@stumbleupon.com",
        "gender": "Male",
        "city": "Cincinnati",
        "department": "Training",
        "latitude": "39.0706",
        "longitude": "-84.4179",
        "home_phone": None,
        "postal_code": "45228",
        "state": "OH",
        "street_address": None,
        "date_of_hire": "5/1/2018",
        "time_in_service_yrs": 3.48
    },
    {
        "key_id": 20,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "employee_id": "999",
        "first_name": "Cloris",
        "last_name": "Millings",
        "email": "cgreenroadrq@mapy.cz",
        "gender": "Female",
        "city": "Monticello",
        "department": "Training",
        "latitude": "45.2009",
        "longitude": "-93.8881",
        "home_phone": "763-174-2429",
        "postal_code": "55565",
        "state": "MN",
        "street_address": "8 Dorton Circle",
        "date_of_hire": "3/21/2018",
        "time_in_service_yrs": 3.59
    },
    {
        "key_id": 20,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "employee_id": "624",
        "first_name": "Cecilia",
        "last_name": "Billings",
        "email": "cbillingshb@nbcnews.com",
        "gender": "Female",
        "city": "Baltimore",
        "department": "Product Management",
        "latitude": "39.361",
        "longitude": "-76.5891",
        "home_phone": "410-189-4551",
        "postal_code": "21239",
        "state": "MD",
        "street_address": "0903 Bellgrove Avenue",
        "date_of_hire": "6/18/2018",
        "time_in_service_yrs": 3.35
    },
    {
        "key_id": 21,
        "score": 88,
        "dupe1": "Philpots",
        "dupe2": "PHILPOTTS",
        "employee_id": "603",
        "first_name": "Bettye",
        "last_name": "PHILPOTTS",
        "email": "bphilpottsgq@mail.ru",
        "gender": "Female",
        "city": "Washington",
        "department": "Support",
        "latitude": "38.8933",
        "longitude": "-77.0146",
        "home_phone": "202-493-9320",
        "postal_code": "20580",
        "state": "DC",
        "street_address": "96 Sunbrook Plaza",
        "date_of_hire": "8/27/2018",
        "time_in_service_yrs": 3.16
    },
    {
        "key_id": 21,
        "score": 88,
        "dupe1": "Philpots",
        "dupe2": "PHILPOTTS",
        "employee_id": "295",
        "first_name": "Hynda",
        "last_name": "Philpots",
        "email": "hphilpots86@example.com",
        "gender": "Female",
        "city": "Dallas",
        "department": "Training",
        "latitude": "32.7948",
        "longitude": "-96.7697",
        "home_phone": "972-569-5687",
        "postal_code": "75246",
        "state": "TX",
        "street_address": "59170 Manufacturers Pass",
        "date_of_hire": "10/26/2018",
        "time_in_service_yrs": 2.99
    }
]
