from payloads.pushdown.dupes.pl_pd_bq_dupes_exact_case_employees_dt_archive_breaks import (
    PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET
)

PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "EMPLOYEE_ID": "817",
                "item_key": "07da7567f1f4fe615f9e517caeb50260",
                "LONGITUDE": "-121.3978",
                "STATE": "CA",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.05",
                "LAST_NAME": "Brigginshaw",
                "EMAIL": "bbrigginshawmo@dailymail.co.uk",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:1][2, Brigginshaw]||[2, Brigginshaw]",
                "FIRST_NAME": "Bobinette",
                "score": "100",
                "DATE_OF_HIRE": "10/5/2018",
                "CITY": "Sacramento",
                "POSTAL_CODE": "95865",
                "assignment_uuid": "94200c8b-f78f-4dd5-8fda-55835fd629dd",
                "GENDER": "Female",
                "HOME_PHONE": "916-728-0816",
                "STREET_ADDRESS": "477 Eastlawn Junction",
                "LATITUDE": "38.596"
            },
            {
                "EMPLOYEE_ID": "80",
                "item_key": "07da7567f1f4fe615f9e517caeb50260",
                "LONGITUDE": "-95.6982",
                "STATE": "KS",
                "DEPARTMENT": "Accounting",
                "TIME_IN_SERVICE_YRS": "4.39",
                "LAST_NAME": "Brigginshaw",
                "occurs": "2",
                "type": "DUPE",
                "EMAIL": "jbrigginshaw27@livejournal.com",
                "item_value": "[score:100, key_id:1][2, Brigginshaw]||[2, Brigginshaw]",
                "FIRST_NAME": "Joshuah",
                "score": "100",
                "DATE_OF_HIRE": "6/3/2017",
                "CITY": "Topeka",
                "POSTAL_CODE": "66611",
                "assignment_uuid": "94200c8b-f78f-4dd5-8fda-55835fd629dd",
                "GENDER": "NULL",
                "HOME_PHONE": "785-777-6486",
                "STREET_ADDRESS": "06719 Blackbird Hill",
                "LATITUDE": "39.0142"
            },
            {
                "EMPLOYEE_ID": "354",
                "item_key": "e113dfd5d28daf9f8e4affb7caff3429",
                "LONGITUDE": "-82.2774",
                "STATE": "WV",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.31",
                "occurs": "2",
                "LAST_NAME": "Clardge",
                "EMAIL": "jclardge9t@illinois.edu",
                "type": "DUPE",
                "item_value": "[score:100, key_id:2][2, Clardge]||[2, Clardge]",
                "FIRST_NAME": "Jdavie",
                "score": "100",
                "DATE_OF_HIRE": "7/2/2018",
                "CITY": "Huntington",
                "POSTAL_CODE": "25716",
                "assignment_uuid": "d0962f1d-8541-4b4c-817f-c0e808019f05",
                "GENDER": "Male",
                "HOME_PHONE": "304-559-1266",
                "STREET_ADDRESS": "83 Kropf Way",
                "LATITUDE": "38.4134"
            },
            {
                "EMPLOYEE_ID": "990",
                "item_key": "e113dfd5d28daf9f8e4affb7caff3429",
                "LONGITUDE": "-115.9671",
                "STATE": "CA",
                "DEPARTMENT": "Human Resources",
                "TIME_IN_SERVICE_YRS": "3.12",
                "type": "DUPE",
                "occurs": "2",
                "LAST_NAME": "Clardge",
                "EMAIL": "bcheerrh@marketwatch.com",
                "item_value": "[score:100, key_id:2][2, Clardge]||[2, Clardge]",
                "FIRST_NAME": "Brook",
                "score": "100",
                "DATE_OF_HIRE": "9/9/2018",
                "CITY": "San Bernardino",
                "POSTAL_CODE": "92424",
                "assignment_uuid": "d0962f1d-8541-4b4c-817f-c0e808019f05",
                "GENDER": "Male",
                "HOME_PHONE": "909-606-7780",
                "STREET_ADDRESS": "8658 Ridgeway Point",
                "LATITUDE": "34.84"
            },
            {
                "EMPLOYEE_ID": "1000",
                "item_key": "1f333b7574636c56758d13b032d8b6cd",
                "LONGITUDE": "-87.7223",
                "STATE": "IL",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "2.98",
                "type": "DUPE",
                "LAST_NAME": "Flatley",
                "EMAIL": "mbruntjerr@blog.com",
                "occurs": "3",
                "item_value": "[score:100, key_id:3][3, Flatley]||[3, Flatley]",
                "FIRST_NAME": "Maribel",
                "score": "100",
                "DATE_OF_HIRE": "10/28/2018",
                "CITY": "Chicago",
                "POSTAL_CODE": "60624",
                "assignment_uuid": "f6cf0c72-bc31-420f-b0e7-5f18c1fb4359",
                "GENDER": "Female",
                "HOME_PHONE": "773-506-5309",
                "STREET_ADDRESS": "107 Division Avenue",
                "LATITUDE": "41.8804"
            },
            {
                "EMPLOYEE_ID": "956",
                "item_key": "1f333b7574636c56758d13b032d8b6cd",
                "LONGITUDE": "-77.1073",
                "STATE": "VA",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "3.11",
                "type": "DUPE",
                "occurs": "3",
                "LAST_NAME": "Flatley",
                "EMAIL": "pflatleyqj@cnet.com",
                "item_value": "[score:100, key_id:3][3, Flatley]||[3, Flatley]",
                "FIRST_NAME": "Perry",
                "score": "100",
                "DATE_OF_HIRE": "9/12/2018",
                "CITY": "Alexandria",
                "POSTAL_CODE": "22309",
                "assignment_uuid": "f6cf0c72-bc31-420f-b0e7-5f18c1fb4359",
                "GENDER": "Male",
                "HOME_PHONE": "202-453-5054",
                "STREET_ADDRESS": "8724 Kenwood Junction",
                "LATITUDE": "38.7192"
            },
            {
                "EMPLOYEE_ID": "763",
                "item_key": "4ae00a92fe8df40c0236e3ac81ddf1db",
                "LONGITUDE": "-116.846",
                "STATE": "CA",
                "DEPARTMENT": "Services",
                "TIME_IN_SERVICE_YRS": "2.98",
                "LAST_NAME": "Gemmill",
                "EMAIL": "lgemmilll6@storify.com",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:4][2, Gemmill]||[2, Gemmill]",
                "FIRST_NAME": "Lizette",
                "score": "100",
                "DATE_OF_HIRE": "10/30/2018",
                "CITY": "Escondido",
                "POSTAL_CODE": "92030",
                "assignment_uuid": "66bf41f0-f74c-4a2e-aa3d-94250d6b9212",
                "GENDER": "Female",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "33.0169"
            },
            {
                "EMPLOYEE_ID": "749",
                "item_key": "4ae00a92fe8df40c0236e3ac81ddf1db",
                "LONGITUDE": "-118.9052",
                "STATE": "CA",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "4.8",
                "type": "DUPE",
                "EMAIL": "mgemmillks@sogou.com",
                "LAST_NAME": "Gemmill",
                "occurs": "2",
                "item_value": "[score:100, key_id:4][2, Gemmill]||[2, Gemmill]",
                "FIRST_NAME": "Madelle",
                "score": "100",
                "DATE_OF_HIRE": "1/3/2017",
                "CITY": "Bakersfield",
                "POSTAL_CODE": "93386",
                "assignment_uuid": "66bf41f0-f74c-4a2e-aa3d-94250d6b9212",
                "GENDER": "Female",
                "HOME_PHONE": "661-796-7132",
                "STREET_ADDRESS": "2966 Shoshone Junction",
                "LATITUDE": "35.2944"
            },
            {
                "EMPLOYEE_ID": "468",
                "item_key": "3a8e91235bf231bd0bde94e69af38dd5",
                "LONGITUDE": "-96.7776",
                "STATE": "TX",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.98",
                "EMAIL": "fmitchesoncz@godaddy.com",
                "LAST_NAME": "Mitcheson",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:5][2, Mitcheson]||[2, Mitcheson]",
                "FIRST_NAME": "Fraze",
                "score": "100",
                "DATE_OF_HIRE": "10/31/2018",
                "CITY": "Dallas",
                "POSTAL_CODE": "75379",
                "assignment_uuid": "e024240e-6667-4a3e-adc1-3fc823f73195",
                "GENDER": "Female",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "32.7673"
            },
            {
                "EMPLOYEE_ID": "878",
                "item_key": "3a8e91235bf231bd0bde94e69af38dd5",
                "LONGITUDE": "-97.4075",
                "STATE": "OK",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "3.12",
                "LAST_NAME": "Mitcheson",
                "EMAIL": "mmitchesonod@bluehost.com",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:5][2, Mitcheson]||[2, Mitcheson]",
                "FIRST_NAME": "Morgen",
                "score": "100",
                "DATE_OF_HIRE": "9/10/2018",
                "CITY": "Oklahoma City",
                "POSTAL_CODE": "73167",
                "assignment_uuid": "e024240e-6667-4a3e-adc1-3fc823f73195",
                "GENDER": "Male",
                "HOME_PHONE": "405-779-6403",
                "STREET_ADDRESS": "297 Iowa Circle",
                "LATITUDE": "35.5514"
            },
            {
                "EMPLOYEE_ID": "6",
                "item_key": "012a98088f9868cc094e411bbae30ed2",
                "LONGITUDE": "-79.9579",
                "STATE": "VA",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "3.34",
                "LAST_NAME": "Oldford",
                "occurs": "2",
                "EMAIL": "roldford5@mtv.com",
                "type": "DUPE",
                "item_value": "[score:100, key_id:6][2, Oldford]||[2, Oldford]",
                "FIRST_NAME": "Rudolf",
                "score": "100",
                "DATE_OF_HIRE": "6/19/2018",
                "CITY": "Roanoke",
                "POSTAL_CODE": "24024",
                "assignment_uuid": "76824bee-58a0-443f-bb4f-9db60a30511b",
                "GENDER": "Male",
                "HOME_PHONE": "540-762-6329",
                "STREET_ADDRESS": "3871 Quincy Alley",
                "LATITUDE": "37.2742"
            },
            {
                "EMPLOYEE_ID": "573",
                "item_key": "012a98088f9868cc094e411bbae30ed2",
                "LONGITUDE": "-75.1179",
                "STATE": "PA",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "3.5",
                "LAST_NAME": "Oldford",
                "type": "DUPE",
                "EMAIL": "soldfordfw@linkedin.com",
                "occurs": "2",
                "item_value": "[score:100, key_id:6][2, Oldford]||[2, Oldford]",
                "FIRST_NAME": "Sigfrid",
                "score": "100",
                "DATE_OF_HIRE": "4/24/2018",
                "CITY": "Philadelphia",
                "POSTAL_CODE": "19178",
                "assignment_uuid": "76824bee-58a0-443f-bb4f-9db60a30511b",
                "GENDER": "Male",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "40.0018"
            },
            {
                "EMPLOYEE_ID": "370",
                "item_key": "89feb276ce0c5802de6a38080d466d55",
                "LONGITUDE": "-119.7764",
                "STATE": "NV",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "2.85",
                "LAST_NAME": "Owttrim",
                "EMAIL": "cowttrima9@toplist.cz",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:7][2, Owttrim]||[2, Owttrim]",
                "FIRST_NAME": "Clary",
                "score": "100",
                "DATE_OF_HIRE": "12/16/2018",
                "CITY": "Carson City",
                "POSTAL_CODE": "89714",
                "assignment_uuid": "6c7f6638-7cb7-4b36-b66e-6ee7e7dc5825",
                "GENDER": "Male",
                "HOME_PHONE": "775-479-3671",
                "STREET_ADDRESS": "4780 Hayes Junction",
                "LATITUDE": "39.1678"
            },
            {
                "EMPLOYEE_ID": "772",
                "item_key": "89feb276ce0c5802de6a38080d466d55",
                "LONGITUDE": "-77.0146",
                "STATE": "DC",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "3.04",
                "LAST_NAME": "Owttrim",
                "occurs": "2",
                "type": "DUPE",
                "EMAIL": "cowttrimlf@stumbleupon.com",
                "item_value": "[score:100, key_id:7][2, Owttrim]||[2, Owttrim]",
                "FIRST_NAME": "Conway",
                "score": "100",
                "DATE_OF_HIRE": "10/9/2018",
                "CITY": "Washington",
                "POSTAL_CODE": "20215",
                "assignment_uuid": "6c7f6638-7cb7-4b36-b66e-6ee7e7dc5825",
                "GENDER": "Male",
                "HOME_PHONE": "202-450-1228",
                "STREET_ADDRESS": "4821 Warrior Court",
                "LATITUDE": "38.8933"
            },
            {
                "EMPLOYEE_ID": "368",
                "item_key": "0a681bb4c4b6530a7aafde58c0451d24",
                "LONGITUDE": "-80.441",
                "STATE": "FL",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "6.05",
                "EMAIL": "apollinsa7@pen.io",
                "LAST_NAME": "Pollins",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:8][2, Pollins]||[2, Pollins]",
                "FIRST_NAME": "Ari",
                "score": "100",
                "DATE_OF_HIRE": "10/7/2015",
                "CITY": "Miami",
                "POSTAL_CODE": "33196",
                "assignment_uuid": "1cdd9678-0377-47ad-938d-3658000ebc5f",
                "GENDER": "Female",
                "HOME_PHONE": "786-873-7423",
                "STREET_ADDRESS": "150 Magdeline Crossing",
                "LATITUDE": "25.6615"
            },
            {
                "EMPLOYEE_ID": "988",
                "item_key": "0a681bb4c4b6530a7aafde58c0451d24",
                "LONGITUDE": "-81.2571",
                "STATE": "FL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "2.9",
                "type": "DUPE",
                "EMAIL": "kderellrf@ft.com",
                "LAST_NAME": "Pollins",
                "occurs": "2",
                "item_value": "[score:100, key_id:8][2, Pollins]||[2, Pollins]",
                "FIRST_NAME": "Kassi",
                "score": "100",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Orlando",
                "POSTAL_CODE": "32825",
                "assignment_uuid": "1cdd9678-0377-47ad-938d-3658000ebc5f",
                "GENDER": "NULL",
                "HOME_PHONE": "954-559-4887",
                "STREET_ADDRESS": "2 Shelley Crossing",
                "LATITUDE": "28.5469"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "EMPLOYEE_ID",
                "name": "EMPLOYEE_ID",
                "title": "EMPLOYEE_ID"
            },
            {
                "data": "LONGITUDE",
                "name": "LONGITUDE",
                "title": "LONGITUDE"
            },
            {
                "data": "STATE",
                "name": "STATE",
                "title": "STATE"
            },
            {
                "data": "DEPARTMENT",
                "name": "DEPARTMENT",
                "title": "DEPARTMENT"
            },
            {
                "data": "TIME_IN_SERVICE_YRS",
                "name": "TIME_IN_SERVICE_YRS",
                "title": "TIME_IN_SERVICE_YRS"
            },
            {
                "data": "LAST_NAME",
                "name": "LAST_NAME",
                "title": "LAST_NAME"
            },
            {
                "data": "EMAIL",
                "name": "EMAIL",
                "title": "EMAIL"
            },
            {
                "data": "occurs",
                "name": "occurs",
                "title": "occurs"
            },
            {
                "data": "FIRST_NAME",
                "name": "FIRST_NAME",
                "title": "FIRST_NAME"
            },
            {
                "data": "DATE_OF_HIRE",
                "name": "DATE_OF_HIRE",
                "title": "DATE_OF_HIRE"
            },
            {
                "data": "CITY",
                "name": "CITY",
                "title": "CITY"
            },
            {
                "data": "POSTAL_CODE",
                "name": "POSTAL_CODE",
                "title": "POSTAL_CODE"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "GENDER",
                "name": "GENDER",
                "title": "GENDER"
            },
            {
                "data": "HOME_PHONE",
                "name": "HOME_PHONE",
                "title": "HOME_PHONE"
            },
            {
                "data": "STREET_ADDRESS",
                "name": "STREET_ADDRESS",
                "title": "STREET_ADDRESS"
            },
            {
                "data": "LATITUDE",
                "name": "LATITUDE",
                "title": "LATITUDE"
            }
        ]
    }
]

PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "809",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Owttrim",
        "dupe1_link_id": "370",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Oldford",
        "dupe1_link_id": "573",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Brigginshaw",
        "dupe1_link_id": "80",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clardge",
        "dupe1_link_id": "354",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "1000",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Gemmill",
        "dupe1_link_id": "763",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Gemmill",
        "dupe1_link_id": "749",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clardge",
        "dupe1_link_id": "990",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "956",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Owttrim",
        "dupe1_link_id": "772",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Brigginshaw",
        "dupe1_link_id": "817",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Mitcheson",
        "dupe1_link_id": "468",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Mitcheson",
        "dupe1_link_id": "878",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Oldford",
        "dupe1_link_id": "6",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": None,
        "updts": "2024-07-15T02:35:19.433+0000",
        "job_uuid": "c7604acd-0981-447a-83d5-2573604eae4e",
        "dataset": PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    }
]

PD_BQ_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 100,
        "dupe1": "Brigginshaw",
        "dupe2": "",
        "EMPLOYEE_ID": "817",
        "FIRST_NAME": "Bobinette",
        "LAST_NAME": "Brigginshaw",
        "EMAIL": "bbrigginshawmo@dailymail.co.uk",
        "GENDER": "Female",
        "CITY": "Sacramento",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "38.596",
        "LONGITUDE": "-121.3978",
        "HOME_PHONE": "916-728-0816",
        "POSTAL_CODE": "95865",
        "STATE": "CA",
        "STREET_ADDRESS": "477 Eastlawn Junction",
        "DATE_OF_HIRE": "10/5/2018",
        "TIME_IN_SERVICE_YRS": 3.05
    },
    {
        "key_id": 1,
        "score": 100,
        "dupe1": "Brigginshaw",
        "dupe2": "",
        "EMPLOYEE_ID": "80",
        "FIRST_NAME": "Joshuah",
        "LAST_NAME": "Brigginshaw",
        "EMAIL": "jbrigginshaw27@livejournal.com",
        "GENDER": None,
        "CITY": "Topeka",
        "DEPARTMENT": "Accounting",
        "LATITUDE": "39.0142",
        "LONGITUDE": "-95.6982",
        "HOME_PHONE": "785-777-6486",
        "POSTAL_CODE": "66611",
        "STATE": "KS",
        "STREET_ADDRESS": "06719 Blackbird Hill",
        "DATE_OF_HIRE": "6/3/2017",
        "TIME_IN_SERVICE_YRS": 4.39
    },
    {
        "key_id": 2,
        "score": 100,
        "dupe1": "Clardge",
        "dupe2": "",
        "EMPLOYEE_ID": "990",
        "FIRST_NAME": "Brook",
        "LAST_NAME": "Clardge",
        "EMAIL": "bcheerrh@marketwatch.com",
        "GENDER": "Male",
        "CITY": "San Bernardino",
        "DEPARTMENT": "Human Resources",
        "LATITUDE": "34.84",
        "LONGITUDE": "-115.9671",
        "HOME_PHONE": "909-606-7780",
        "POSTAL_CODE": "92424",
        "STATE": "CA",
        "STREET_ADDRESS": "8658 Ridgeway Point",
        "DATE_OF_HIRE": "9/9/2018",
        "TIME_IN_SERVICE_YRS": 3.12
    },
    {
        "key_id": 2,
        "score": 100,
        "dupe1": "Clardge",
        "dupe2": "",
        "EMPLOYEE_ID": "354",
        "FIRST_NAME": "Jdavie",
        "LAST_NAME": "Clardge",
        "EMAIL": "jclardge9t@illinois.edu",
        "GENDER": "Male",
        "CITY": "Huntington",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "38.4134",
        "LONGITUDE": "-82.2774",
        "HOME_PHONE": "304-559-1266",
        "POSTAL_CODE": "25716",
        "STATE": "WV",
        "STREET_ADDRESS": "83 Kropf Way",
        "DATE_OF_HIRE": "7/2/2018",
        "TIME_IN_SERVICE_YRS": 3.31
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "EMPLOYEE_ID": "1000",
        "FIRST_NAME": "Maribel",
        "LAST_NAME": "Flatley",
        "EMAIL": "mbruntjerr@blog.com",
        "GENDER": "Female",
        "CITY": "Chicago",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "41.8804",
        "LONGITUDE": "-87.7223",
        "HOME_PHONE": "773-506-5309",
        "POSTAL_CODE": "60624",
        "STATE": "IL",
        "STREET_ADDRESS": "107 Division Avenue",
        "DATE_OF_HIRE": "10/28/2018",
        "TIME_IN_SERVICE_YRS": 2.98
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "EMPLOYEE_ID": "809",
        "FIRST_NAME": "Arabele",
        "LAST_NAME": "Flatley",
        "EMAIL": "aflatleymg@feedburner.com",
        "GENDER": "Female",
        "CITY": "Indianapolis",
        "DEPARTMENT": "Engineering",
        "LATITUDE": "39.7851",
        "LONGITUDE": "-86.1595",
        "HOME_PHONE": "317-779-4918",
        "POSTAL_CODE": "46202",
        "STATE": "IN",
        "STREET_ADDRESS": "34245 Susan Court",
        "DATE_OF_HIRE": "9/5/2016",
        "TIME_IN_SERVICE_YRS": 5.13
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "EMPLOYEE_ID": "956",
        "FIRST_NAME": "Perry",
        "LAST_NAME": "Flatley",
        "EMAIL": "pflatleyqj@cnet.com",
        "GENDER": "Male",
        "CITY": "Alexandria",
        "DEPARTMENT": "Legal",
        "LATITUDE": "38.7192",
        "LONGITUDE": "-77.1073",
        "HOME_PHONE": "202-453-5054",
        "POSTAL_CODE": "22309",
        "STATE": "VA",
        "STREET_ADDRESS": "8724 Kenwood Junction",
        "DATE_OF_HIRE": "9/12/2018",
        "TIME_IN_SERVICE_YRS": 3.11
    },
    {
        "key_id": 4,
        "score": 100,
        "dupe1": "Gemmill",
        "dupe2": "",
        "EMPLOYEE_ID": "763",
        "FIRST_NAME": "Lizette",
        "LAST_NAME": "Gemmill",
        "EMAIL": "lgemmilll6@storify.com",
        "GENDER": "Female",
        "CITY": "Escondido",
        "DEPARTMENT": "Services",
        "LATITUDE": "33.0169",
        "LONGITUDE": "-116.846",
        "HOME_PHONE": None,
        "POSTAL_CODE": "92030",
        "STATE": "CA",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "10/30/2018",
        "TIME_IN_SERVICE_YRS": 2.98
    },
    {
        "key_id": 4,
        "score": 100,
        "dupe1": "Gemmill",
        "dupe2": "",
        "EMPLOYEE_ID": "749",
        "FIRST_NAME": "Madelle",
        "LAST_NAME": "Gemmill",
        "EMAIL": "mgemmillks@sogou.com",
        "GENDER": "Female",
        "CITY": "Bakersfield",
        "DEPARTMENT": "Sales",
        "LATITUDE": "35.2944",
        "LONGITUDE": "-118.9052",
        "HOME_PHONE": "661-796-7132",
        "POSTAL_CODE": "93386",
        "STATE": "CA",
        "STREET_ADDRESS": "2966 Shoshone Junction",
        "DATE_OF_HIRE": "1/3/2017",
        "TIME_IN_SERVICE_YRS": 4.8
    },
    {
        "key_id": 5,
        "score": 100,
        "dupe1": "Mitcheson",
        "dupe2": "",
        "EMPLOYEE_ID": "468",
        "FIRST_NAME": "Fraze",
        "LAST_NAME": "Mitcheson",
        "EMAIL": "fmitchesoncz@godaddy.com",
        "GENDER": "Female",
        "CITY": "Dallas",
        "DEPARTMENT": "Sales",
        "LATITUDE": "32.7673",
        "LONGITUDE": "-96.7776",
        "HOME_PHONE": None,
        "POSTAL_CODE": "75379",
        "STATE": "TX",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "10/31/2018",
        "TIME_IN_SERVICE_YRS": 2.98
    },
    {
        "key_id": 5,
        "score": 100,
        "dupe1": "Mitcheson",
        "dupe2": "",
        "EMPLOYEE_ID": "878",
        "FIRST_NAME": "Morgen",
        "LAST_NAME": "Mitcheson",
        "EMAIL": "mmitchesonod@bluehost.com",
        "GENDER": "Male",
        "CITY": "Oklahoma City",
        "DEPARTMENT": "Support",
        "LATITUDE": "35.5514",
        "LONGITUDE": "-97.4075",
        "HOME_PHONE": "405-779-6403",
        "POSTAL_CODE": "73167",
        "STATE": "OK",
        "STREET_ADDRESS": "297 Iowa Circle",
        "DATE_OF_HIRE": "9/10/2018",
        "TIME_IN_SERVICE_YRS": 3.12
    },
    {
        "key_id": 6,
        "score": 100,
        "dupe1": "Oldford",
        "dupe2": "",
        "EMPLOYEE_ID": "573",
        "FIRST_NAME": "Sigfrid",
        "LAST_NAME": "Oldford",
        "EMAIL": "soldfordfw@linkedin.com",
        "GENDER": "Male",
        "CITY": "Philadelphia",
        "DEPARTMENT": "Legal",
        "LATITUDE": "40.0018",
        "LONGITUDE": "-75.1179",
        "HOME_PHONE": None,
        "POSTAL_CODE": "19178",
        "STATE": "PA",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "4/24/2018",
        "TIME_IN_SERVICE_YRS": 3.5
    },
    {
        "key_id": 6,
        "score": 100,
        "dupe1": "Oldford",
        "dupe2": "",
        "EMPLOYEE_ID": "6",
        "FIRST_NAME": "Rudolf",
        "LAST_NAME": "Oldford",
        "EMAIL": "roldford5@mtv.com",
        "GENDER": "Male",
        "CITY": "Roanoke",
        "DEPARTMENT": "Sales",
        "LATITUDE": "37.2742",
        "LONGITUDE": "-79.9579",
        "HOME_PHONE": "540-762-6329",
        "POSTAL_CODE": "24024",
        "STATE": "VA",
        "STREET_ADDRESS": "3871 Quincy Alley",
        "DATE_OF_HIRE": "6/19/2018",
        "TIME_IN_SERVICE_YRS": 3.34
    },
    {
        "key_id": 7,
        "score": 100,
        "dupe1": "Owttrim",
        "dupe2": "",
        "EMPLOYEE_ID": "370",
        "FIRST_NAME": "Clary",
        "LAST_NAME": "Owttrim",
        "EMAIL": "cowttrima9@toplist.cz",
        "GENDER": "Male",
        "CITY": "Carson City",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.1678",
        "LONGITUDE": "-119.7764",
        "HOME_PHONE": "775-479-3671",
        "POSTAL_CODE": "89714",
        "STATE": "NV",
        "STREET_ADDRESS": "4780 Hayes Junction",
        "DATE_OF_HIRE": "12/16/2018",
        "TIME_IN_SERVICE_YRS": 2.85
    },
    {
        "key_id": 7,
        "score": 100,
        "dupe1": "Owttrim",
        "dupe2": "",
        "EMPLOYEE_ID": "772",
        "FIRST_NAME": "Conway",
        "LAST_NAME": "Owttrim",
        "EMAIL": "cowttrimlf@stumbleupon.com",
        "GENDER": "Male",
        "CITY": "Washington",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "38.8933",
        "LONGITUDE": "-77.0146",
        "HOME_PHONE": "202-450-1228",
        "POSTAL_CODE": "20215",
        "STATE": "DC",
        "STREET_ADDRESS": "4821 Warrior Court",
        "DATE_OF_HIRE": "10/9/2018",
        "TIME_IN_SERVICE_YRS": 3.04
    },
    {
        "key_id": 8,
        "score": 100,
        "dupe1": "Pollins",
        "dupe2": "",
        "EMPLOYEE_ID": "988",
        "FIRST_NAME": "Kassi",
        "LAST_NAME": "Pollins",
        "EMAIL": "kderellrf@ft.com",
        "GENDER": None,
        "CITY": "Orlando",
        "DEPARTMENT": "Legal",
        "LATITUDE": "28.5469",
        "LONGITUDE": "-81.2571",
        "HOME_PHONE": "954-559-4887",
        "POSTAL_CODE": "32825",
        "STATE": "FL",
        "STREET_ADDRESS": "2 Shelley Crossing",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 8,
        "score": 100,
        "dupe1": "Pollins",
        "dupe2": "",
        "EMPLOYEE_ID": "368",
        "FIRST_NAME": "Ari",
        "LAST_NAME": "Pollins",
        "EMAIL": "apollinsa7@pen.io",
        "GENDER": "Female",
        "CITY": "Miami",
        "DEPARTMENT": "Support",
        "LATITUDE": "25.6615",
        "LONGITUDE": "-80.441",
        "HOME_PHONE": "786-873-7423",
        "POSTAL_CODE": "33196",
        "STATE": "FL",
        "STREET_ADDRESS": "150 Magdeline Crossing",
        "DATE_OF_HIRE": "10/7/2015",
        "TIME_IN_SERVICE_YRS": 6.05
    }
]
