from payloads.pushdown.dupes.pl_pd_trino_dupes_exact_case_employees_dt_archive_breaks import (
    PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
)

PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "street_address": "477 Eastlawn Junction",
                "home_phone": "916-728-0816",
                "gender": "Female",
                "city": "Sacramento",
                "item_key": "9d218006466d57f8fb2a17e841dbb265",
                "latitude": "38.596",
                "last_name": "Brigginshaw",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:1][2, Brigginshaw]||[2, Brigginshaw]",
                "score": "100",
                "time_in_service_yrs": "3.05",
                "assignment_uuid": "ef9f7c3e-72ca-4b66-b5d7-e045a8ca36c3",
                "employee_id": "817",
                "state": "CA",
                "date_of_hire": "10/5/2018",
                "department": "Marketing",
                "postal_code": "95865",
                "first_name": "Bobinette",
                "email": "bbrigginshawmo@dailymail.co.uk",
                "longitude": "-121.3978"
            },
            {
                "street_address": "06719 Blackbird Hill",
                "home_phone": "785-777-6486",
                "gender": "NULL",
                "city": "Topeka",
                "item_key": "9d218006466d57f8fb2a17e841dbb265",
                "latitude": "39.0142",
                "last_name": "Brigginshaw",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:1][2, Brigginshaw]||[2, Brigginshaw]",
                "score": "100",
                "time_in_service_yrs": "4.39",
                "assignment_uuid": "ef9f7c3e-72ca-4b66-b5d7-e045a8ca36c3",
                "employee_id": "80",
                "date_of_hire": "6/3/2017",
                "state": "KS",
                "postal_code": "66611",
                "department": "Accounting",
                "first_name": "Joshuah",
                "email": "jbrigginshaw27@livejournal.com",
                "longitude": "-95.6982"
            },
            {
                "street_address": "8658 Ridgeway Point",
                "home_phone": "909-606-7780",
                "gender": "Male",
                "city": "San Bernardino",
                "item_key": "4b33ccf6fcda57d5665bb9f8f6f8f85b",
                "latitude": "34.84",
                "last_name": "Clardge",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:2][2, Clardge]||[2, Clardge]",
                "score": "100",
                "time_in_service_yrs": "3.12",
                "assignment_uuid": "f2b43d0b-38bd-4004-ad92-16ea7b92bd18",
                "employee_id": "990",
                "date_of_hire": "9/9/2018",
                "state": "CA",
                "department": "Human Resources",
                "postal_code": "92424",
                "first_name": "Brook",
                "email": "bcheerrh@marketwatch.com",
                "longitude": "-115.9671"
            },
            {
                "home_phone": "304-559-1266",
                "street_address": "83 Kropf Way",
                "gender": "Male",
                "city": "Huntington",
                "item_key": "4b33ccf6fcda57d5665bb9f8f6f8f85b",
                "latitude": "38.4134",
                "last_name": "Clardge",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:2][2, Clardge]||[2, Clardge]",
                "score": "100",
                "time_in_service_yrs": "3.31",
                "assignment_uuid": "f2b43d0b-38bd-4004-ad92-16ea7b92bd18",
                "employee_id": "354",
                "date_of_hire": "7/2/2018",
                "state": "WV",
                "department": "Research and Development",
                "postal_code": "25716",
                "first_name": "Jdavie",
                "email": "jclardge9t@illinois.edu",
                "longitude": "-82.2774"
            },
            {
                "home_phone": "773-506-5309",
                "street_address": "107 Division Avenue",
                "gender": "Female",
                "city": "Chicago",
                "item_key": "db74d28ee6e87c1190eb8ee1e846d63d",
                "latitude": "41.8804",
                "last_name": "Flatley",
                "occurs": "3",
                "type": "DUPE",
                "item_value": "[score:100, key_id:3][3, Flatley]||[3, Flatley]",
                "score": "100",
                "time_in_service_yrs": "2.98",
                "assignment_uuid": "f04047ab-a347-4cd1-9f73-6052f580d019",
                "employee_id": "1000",
                "state": "IL",
                "date_of_hire": "10/28/2018",
                "postal_code": "60624",
                "department": "Business Development",
                "first_name": "Maribel",
                "email": "mbruntjerr@blog.com",
                "longitude": "-87.7223"
            },
            {
                "home_phone": "317-779-4918",
                "street_address": "34245 Susan Court",
                "gender": "Female",
                "city": "Indianapolis",
                "item_key": "db74d28ee6e87c1190eb8ee1e846d63d",
                "latitude": "39.7851",
                "last_name": "Flatley",
                "occurs": "3",
                "type": "DUPE",
                "item_value": "[score:100, key_id:3][3, Flatley]||[3, Flatley]",
                "score": "100",
                "time_in_service_yrs": "5.13",
                "assignment_uuid": "f04047ab-a347-4cd1-9f73-6052f580d019",
                "employee_id": "809",
                "date_of_hire": "9/5/2016",
                "state": "IN",
                "department": "Engineering",
                "postal_code": "46202",
                "first_name": "Arabele",
                "email": "aflatleymg@feedburner.com",
                "longitude": "-86.1595"
            },
            {
                "home_phone": "661-796-7132",
                "street_address": "2966 Shoshone Junction",
                "gender": "Female",
                "city": "Bakersfield",
                "item_key": "ab5394c8454e2940dd016a8a6c485479",
                "latitude": "35.2944",
                "last_name": "Gemmill",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:4][2, Gemmill]||[2, Gemmill]",
                "score": "100",
                "time_in_service_yrs": "4.8",
                "assignment_uuid": "cc987555-7df6-4447-8833-4c6a6193ea79",
                "employee_id": "749",
                "date_of_hire": "1/3/2017",
                "state": "CA",
                "department": "Sales",
                "postal_code": "93386",
                "first_name": "Madelle",
                "email": "mgemmillks@sogou.com",
                "longitude": "-118.9052"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Female",
                "city": "Escondido",
                "item_key": "ab5394c8454e2940dd016a8a6c485479",
                "latitude": "33.0169",
                "last_name": "Gemmill",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:4][2, Gemmill]||[2, Gemmill]",
                "score": "100",
                "time_in_service_yrs": "2.98",
                "assignment_uuid": "cc987555-7df6-4447-8833-4c6a6193ea79",
                "employee_id": "763",
                "date_of_hire": "10/30/2018",
                "state": "CA",
                "department": "Services",
                "postal_code": "92030",
                "first_name": "Lizette",
                "email": "lgemmilll6@storify.com",
                "longitude": "-116.846"
            },
            {
                "home_phone": "405-779-6403",
                "street_address": "297 Iowa Circle",
                "gender": "Male",
                "city": "Oklahoma City",
                "item_key": "7efdacf02983bba4be5a342c401fc552",
                "latitude": "35.5514",
                "last_name": "Mitcheson",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:5][2, Mitcheson]||[2, Mitcheson]",
                "score": "100",
                "time_in_service_yrs": "3.12",
                "assignment_uuid": "27e9afe0-a78e-441c-8411-46e340052f69",
                "employee_id": "878",
                "date_of_hire": "9/10/2018",
                "state": "OK",
                "department": "Support",
                "postal_code": "73167",
                "first_name": "Morgen",
                "email": "mmitchesonod@bluehost.com",
                "longitude": "-97.4075"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Female",
                "city": "Dallas",
                "item_key": "7efdacf02983bba4be5a342c401fc552",
                "latitude": "32.7673",
                "last_name": "Mitcheson",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:5][2, Mitcheson]||[2, Mitcheson]",
                "score": "100",
                "time_in_service_yrs": "2.98",
                "assignment_uuid": "27e9afe0-a78e-441c-8411-46e340052f69",
                "employee_id": "468",
                "state": "TX",
                "date_of_hire": "10/31/2018",
                "postal_code": "75379",
                "department": "Sales",
                "first_name": "Fraze",
                "email": "fmitchesoncz@godaddy.com",
                "longitude": "-96.7776"
            },
            {
                "home_phone": "540-762-6329",
                "street_address": "3871 Quincy Alley",
                "gender": "Male",
                "city": "Roanoke",
                "item_key": "d90a0a4bd4cec2b28d146d22c604d798",
                "latitude": "37.2742",
                "last_name": "Oldford",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:6][2, Oldford]||[2, Oldford]",
                "score": "100",
                "time_in_service_yrs": "3.34",
                "assignment_uuid": "60013a44-0399-4e74-8bdd-1afb226b8bd9",
                "employee_id": "6",
                "date_of_hire": "6/19/2018",
                "state": "VA",
                "department": "Sales",
                "postal_code": "24024",
                "first_name": "Rudolf",
                "email": "roldford5@mtv.com",
                "longitude": "-79.9579"
            },
            {
                "home_phone": "NULL",
                "street_address": "NULL",
                "gender": "Male",
                "city": "Philadelphia",
                "item_key": "d90a0a4bd4cec2b28d146d22c604d798",
                "latitude": "40.0018",
                "last_name": "Oldford",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:6][2, Oldford]||[2, Oldford]",
                "score": "100",
                "time_in_service_yrs": "3.5",
                "assignment_uuid": "60013a44-0399-4e74-8bdd-1afb226b8bd9",
                "employee_id": "573",
                "date_of_hire": "4/24/2018",
                "state": "PA",
                "department": "Legal",
                "postal_code": "19178",
                "first_name": "Sigfrid",
                "email": "soldfordfw@linkedin.com",
                "longitude": "-75.1179"
            },
            {
                "home_phone": "775-479-3671",
                "street_address": "4780 Hayes Junction",
                "gender": "Male",
                "city": "Carson City",
                "item_key": "4ed0748158aedb8122a43bc214e1be89",
                "latitude": "39.1678",
                "last_name": "Owttrim",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:7][2, Owttrim]||[2, Owttrim]",
                "score": "100",
                "time_in_service_yrs": "2.85",
                "assignment_uuid": "bd1d418a-afab-4b1e-98c7-38795374c9aa",
                "employee_id": "370",
                "date_of_hire": "12/16/2018",
                "state": "NV",
                "department": "Product Management",
                "postal_code": "89714",
                "first_name": "Clary",
                "email": "cowttrima9@toplist.cz",
                "longitude": "-119.7764"
            },
            {
                "home_phone": "202-450-1228",
                "street_address": "4821 Warrior Court",
                "gender": "Male",
                "city": "Washington",
                "item_key": "4ed0748158aedb8122a43bc214e1be89",
                "latitude": "38.8933",
                "last_name": "Owttrim",
                "type": "DUPE",
                "occurs": "2",
                "item_value": "[score:100, key_id:7][2, Owttrim]||[2, Owttrim]",
                "score": "100",
                "time_in_service_yrs": "3.04",
                "assignment_uuid": "bd1d418a-afab-4b1e-98c7-38795374c9aa",
                "employee_id": "772",
                "date_of_hire": "10/9/2018",
                "state": "DC",
                "department": "Product Management",
                "postal_code": "20215",
                "first_name": "Conway",
                "email": "cowttrimlf@stumbleupon.com",
                "longitude": "-77.0146"
            },
            {
                "street_address": "150 Magdeline Crossing",
                "home_phone": "786-873-7423",
                "gender": "Female",
                "city": "Miami",
                "item_key": "7cb62d334594ffd2e180025b1f136f57",
                "latitude": "25.6615",
                "last_name": "Pollins",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:8][2, Pollins]||[2, Pollins]",
                "score": "100",
                "time_in_service_yrs": "6.05",
                "assignment_uuid": "e9f93ff1-08af-4559-ab02-3b7c723d86dd",
                "employee_id": "368",
                "date_of_hire": "10/7/2015",
                "state": "FL",
                "department": "Support",
                "postal_code": "33196",
                "first_name": "Ari",
                "email": "apollinsa7@pen.io",
                "longitude": "-80.441"
            },
            {
                "home_phone": "954-559-4887",
                "street_address": "2 Shelley Crossing",
                "gender": "NULL",
                "city": "Orlando",
                "item_key": "7cb62d334594ffd2e180025b1f136f57",
                "latitude": "28.5469",
                "last_name": "Pollins",
                "occurs": "2",
                "type": "DUPE",
                "item_value": "[score:100, key_id:8][2, Pollins]||[2, Pollins]",
                "score": "100",
                "time_in_service_yrs": "2.9",
                "assignment_uuid": "e9f93ff1-08af-4559-ab02-3b7c723d86dd",
                "employee_id": "988",
                "date_of_hire": "11/28/2018",
                "state": "FL",
                "postal_code": "32825",
                "department": "Legal",
                "first_name": "Kassi",
                "email": "kderellrf@ft.com",
                "longitude": "-81.2571"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "street_address",
                "name": "street_address",
                "title": "street_address"
            },
            {
                "data": "home_phone",
                "name": "home_phone",
                "title": "home_phone"
            },
            {
                "data": "gender",
                "name": "gender",
                "title": "gender"
            },
            {
                "data": "city",
                "name": "city",
                "title": "city"
            },
            {
                "data": "latitude",
                "name": "latitude",
                "title": "latitude"
            },
            {
                "data": "last_name",
                "name": "last_name",
                "title": "last_name"
            },
            {
                "data": "occurs",
                "name": "occurs",
                "title": "occurs"
            },
            {
                "data": "time_in_service_yrs",
                "name": "time_in_service_yrs",
                "title": "time_in_service_yrs"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "employee_id",
                "name": "employee_id",
                "title": "employee_id"
            },
            {
                "data": "state",
                "name": "state",
                "title": "state"
            },
            {
                "data": "date_of_hire",
                "name": "date_of_hire",
                "title": "date_of_hire"
            },
            {
                "data": "department",
                "name": "department",
                "title": "department"
            },
            {
                "data": "postal_code",
                "name": "postal_code",
                "title": "postal_code"
            },
            {
                "data": "first_name",
                "name": "first_name",
                "title": "first_name"
            },
            {
                "data": "email",
                "name": "email",
                "title": "email"
            },
            {
                "data": "longitude",
                "name": "longitude",
                "title": "longitude"
            }
        ]
    }
]

PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": 35,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Brigginshaw",
        "dupe1_link_id": "817",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 36,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 37,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 38,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Owttrim",
        "dupe1_link_id": "772",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 39,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Owttrim",
        "dupe1_link_id": "370",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 40,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Oldford",
        "dupe1_link_id": "6",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 41,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Oldford",
        "dupe1_link_id": "573",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 42,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Mitcheson",
        "dupe1_link_id": "878",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 43,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Mitcheson",
        "dupe1_link_id": "468",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 44,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Gemmill",
        "dupe1_link_id": "749",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 45,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Gemmill",
        "dupe1_link_id": "763",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 46,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "809",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 47,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "956",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 48,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Flatley",
        "dupe1_link_id": "1000",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 49,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clardge",
        "dupe1_link_id": "354",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 50,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clardge",
        "dupe1_link_id": "990",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    },
    {
        "seqno": 51,
        "updts": "2024-07-19T13:09:53.751+0000",
        "job_uuid": "cde67c31-2764-4aef-89c8-30440821cc9a",
        "dataset": PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-19T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Brigginshaw",
        "dupe1_link_id": "80",
        "dupe2": "",
        "dupe2_link_id": "",
        "score": 100
    }
]

PD_TRINO_DUPES_EXACT_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 100,
        "dupe1": "Brigginshaw",
        "dupe2": "",
        "employee_id": "817",
        "first_name": "Bobinette",
        "last_name": "Brigginshaw",
        "email": "bbrigginshawmo@dailymail.co.uk",
        "gender": "Female",
        "city": "Sacramento",
        "department": "Marketing",
        "latitude": "38.596",
        "longitude": "-121.3978",
        "home_phone": "916-728-0816",
        "postal_code": "95865",
        "state": "CA",
        "street_address": "477 Eastlawn Junction",
        "date_of_hire": "10/5/2018",
        "time_in_service_yrs": 3.05
    },
    {
        "key_id": 1,
        "score": 100,
        "dupe1": "Brigginshaw",
        "dupe2": "",
        "employee_id": "80",
        "first_name": "Joshuah",
        "last_name": "Brigginshaw",
        "email": "jbrigginshaw27@livejournal.com",
        "gender": None,
        "city": "Topeka",
        "department": "Accounting",
        "latitude": "39.0142",
        "longitude": "-95.6982",
        "home_phone": "785-777-6486",
        "postal_code": "66611",
        "state": "KS",
        "street_address": "06719 Blackbird Hill",
        "date_of_hire": "6/3/2017",
        "time_in_service_yrs": 4.39
    },
    {
        "key_id": 2,
        "score": 100,
        "dupe1": "Clardge",
        "dupe2": "",
        "employee_id": "990",
        "first_name": "Brook",
        "last_name": "Clardge",
        "email": "bcheerrh@marketwatch.com",
        "gender": "Male",
        "city": "San Bernardino",
        "department": "Human Resources",
        "latitude": "34.84",
        "longitude": "-115.9671",
        "home_phone": "909-606-7780",
        "postal_code": "92424",
        "state": "CA",
        "street_address": "8658 Ridgeway Point",
        "date_of_hire": "9/9/2018",
        "time_in_service_yrs": 3.12
    },
    {
        "key_id": 2,
        "score": 100,
        "dupe1": "Clardge",
        "dupe2": "",
        "employee_id": "354",
        "first_name": "Jdavie",
        "last_name": "Clardge",
        "email": "jclardge9t@illinois.edu",
        "gender": "Male",
        "city": "Huntington",
        "department": "Research and Development",
        "latitude": "38.4134",
        "longitude": "-82.2774",
        "home_phone": "304-559-1266",
        "postal_code": "25716",
        "state": "WV",
        "street_address": "83 Kropf Way",
        "date_of_hire": "7/2/2018",
        "time_in_service_yrs": 3.31
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "employee_id": "1000",
        "first_name": "Maribel",
        "last_name": "Flatley",
        "email": "mbruntjerr@blog.com",
        "gender": "Female",
        "city": "Chicago",
        "department": "Business Development",
        "latitude": "41.8804",
        "longitude": "-87.7223",
        "home_phone": "773-506-5309",
        "postal_code": "60624",
        "state": "IL",
        "street_address": "107 Division Avenue",
        "date_of_hire": "10/28/2018",
        "time_in_service_yrs": 2.98
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "employee_id": "809",
        "first_name": "Arabele",
        "last_name": "Flatley",
        "email": "aflatleymg@feedburner.com",
        "gender": "Female",
        "city": "Indianapolis",
        "department": "Engineering",
        "latitude": "39.7851",
        "longitude": "-86.1595",
        "home_phone": "317-779-4918",
        "postal_code": "46202",
        "state": "IN",
        "street_address": "34245 Susan Court",
        "date_of_hire": "9/5/2016",
        "time_in_service_yrs": 5.13
    },
    {
        "key_id": 3,
        "score": 100,
        "dupe1": "Flatley",
        "dupe2": "",
        "employee_id": "956",
        "first_name": "Perry",
        "last_name": "Flatley",
        "email": "pflatleyqj@cnet.com",
        "gender": "Male",
        "city": "Alexandria",
        "department": "Legal",
        "latitude": "38.7192",
        "longitude": "-77.1073",
        "home_phone": "202-453-5054",
        "postal_code": "22309",
        "state": "VA",
        "street_address": "8724 Kenwood Junction",
        "date_of_hire": "9/12/2018",
        "time_in_service_yrs": 3.11
    },
    {
        "key_id": 4,
        "score": 100,
        "dupe1": "Gemmill",
        "dupe2": "",
        "employee_id": "749",
        "first_name": "Madelle",
        "last_name": "Gemmill",
        "email": "mgemmillks@sogou.com",
        "gender": "Female",
        "city": "Bakersfield",
        "department": "Sales",
        "latitude": "35.2944",
        "longitude": "-118.9052",
        "home_phone": "661-796-7132",
        "postal_code": "93386",
        "state": "CA",
        "street_address": "2966 Shoshone Junction",
        "date_of_hire": "1/3/2017",
        "time_in_service_yrs": 4.8
    },
    {
        "key_id": 4,
        "score": 100,
        "dupe1": "Gemmill",
        "dupe2": "",
        "employee_id": "763",
        "first_name": "Lizette",
        "last_name": "Gemmill",
        "email": "lgemmilll6@storify.com",
        "gender": "Female",
        "city": "Escondido",
        "department": "Services",
        "latitude": "33.0169",
        "longitude": "-116.846",
        "home_phone": None,
        "postal_code": "92030",
        "state": "CA",
        "street_address": None,
        "date_of_hire": "10/30/2018",
        "time_in_service_yrs": 2.98
    },
    {
        "key_id": 5,
        "score": 100,
        "dupe1": "Mitcheson",
        "dupe2": "",
        "employee_id": "878",
        "first_name": "Morgen",
        "last_name": "Mitcheson",
        "email": "mmitchesonod@bluehost.com",
        "gender": "Male",
        "city": "Oklahoma City",
        "department": "Support",
        "latitude": "35.5514",
        "longitude": "-97.4075",
        "home_phone": "405-779-6403",
        "postal_code": "73167",
        "state": "OK",
        "street_address": "297 Iowa Circle",
        "date_of_hire": "9/10/2018",
        "time_in_service_yrs": 3.12
    },
    {
        "key_id": 5,
        "score": 100,
        "dupe1": "Mitcheson",
        "dupe2": "",
        "employee_id": "468",
        "first_name": "Fraze",
        "last_name": "Mitcheson",
        "email": "fmitchesoncz@godaddy.com",
        "gender": "Female",
        "city": "Dallas",
        "department": "Sales",
        "latitude": "32.7673",
        "longitude": "-96.7776",
        "home_phone": None,
        "postal_code": "75379",
        "state": "TX",
        "street_address": None,
        "date_of_hire": "10/31/2018",
        "time_in_service_yrs": 2.98
    },
    {
        "key_id": 6,
        "score": 100,
        "dupe1": "Oldford",
        "dupe2": "",
        "employee_id": "6",
        "first_name": "Rudolf",
        "last_name": "Oldford",
        "email": "roldford5@mtv.com",
        "gender": "Male",
        "city": "Roanoke",
        "department": "Sales",
        "latitude": "37.2742",
        "longitude": "-79.9579",
        "home_phone": "540-762-6329",
        "postal_code": "24024",
        "state": "VA",
        "street_address": "3871 Quincy Alley",
        "date_of_hire": "6/19/2018",
        "time_in_service_yrs": 3.34
    },
    {
        "key_id": 6,
        "score": 100,
        "dupe1": "Oldford",
        "dupe2": "",
        "employee_id": "573",
        "first_name": "Sigfrid",
        "last_name": "Oldford",
        "email": "soldfordfw@linkedin.com",
        "gender": "Male",
        "city": "Philadelphia",
        "department": "Legal",
        "latitude": "40.0018",
        "longitude": "-75.1179",
        "home_phone": None,
        "postal_code": "19178",
        "state": "PA",
        "street_address": None,
        "date_of_hire": "4/24/2018",
        "time_in_service_yrs": 3.5
    },
    {
        "key_id": 7,
        "score": 100,
        "dupe1": "Owttrim",
        "dupe2": "",
        "employee_id": "370",
        "first_name": "Clary",
        "last_name": "Owttrim",
        "email": "cowttrima9@toplist.cz",
        "gender": "Male",
        "city": "Carson City",
        "department": "Product Management",
        "latitude": "39.1678",
        "longitude": "-119.7764",
        "home_phone": "775-479-3671",
        "postal_code": "89714",
        "state": "NV",
        "street_address": "4780 Hayes Junction",
        "date_of_hire": "12/16/2018",
        "time_in_service_yrs": 2.85
    },
    {
        "key_id": 7,
        "score": 100,
        "dupe1": "Owttrim",
        "dupe2": "",
        "employee_id": "772",
        "first_name": "Conway",
        "last_name": "Owttrim",
        "email": "cowttrimlf@stumbleupon.com",
        "gender": "Male",
        "city": "Washington",
        "department": "Product Management",
        "latitude": "38.8933",
        "longitude": "-77.0146",
        "home_phone": "202-450-1228",
        "postal_code": "20215",
        "state": "DC",
        "street_address": "4821 Warrior Court",
        "date_of_hire": "10/9/2018",
        "time_in_service_yrs": 3.04
    },
    {
        "key_id": 8,
        "score": 100,
        "dupe1": "Pollins",
        "dupe2": "",
        "employee_id": "368",
        "first_name": "Ari",
        "last_name": "Pollins",
        "email": "apollinsa7@pen.io",
        "gender": "Female",
        "city": "Miami",
        "department": "Support",
        "latitude": "25.6615",
        "longitude": "-80.441",
        "home_phone": "786-873-7423",
        "postal_code": "33196",
        "state": "FL",
        "street_address": "150 Magdeline Crossing",
        "date_of_hire": "10/7/2015",
        "time_in_service_yrs": 6.05
    },
    {
        "key_id": 8,
        "score": 100,
        "dupe1": "Pollins",
        "dupe2": "",
        "employee_id": "988",
        "first_name": "Kassi",
        "last_name": "Pollins",
        "email": "kderellrf@ft.com",
        "gender": None,
        "city": "Orlando",
        "department": "Legal",
        "latitude": "28.5469",
        "longitude": "-81.2571",
        "home_phone": "954-559-4887",
        "postal_code": "32825",
        "state": "FL",
        "street_address": "2 Shelley Crossing",
        "date_of_hire": "11/28/2018",
        "time_in_service_yrs": 2.9
    }
]
