from payloads.pushdown.dupes.pl_pd_dbrks_dupes_score_case_employees_dt_archive_breaks import (
    PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
)

PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "EMPLOYEE_ID": "583",
                "item_key": "6e1be205c21f2d5c7c1082d8235f4517",
                "LONGITUDE": "-84.1383",
                "STATE": "TN",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.96",
                "type": "DUPE",
                "LAST_NAME": "Clarage",
                "EMAIL": "kclarageg6@creativecommons.org",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "FIRST_NAME": "Katherine",
                "score": "85",
                "DATE_OF_HIRE": "11/6/2018",
                "CITY": "Knoxville",
                "POSTAL_CODE": "37924",
                "assignment_uuid": "4e5b93c0-bcd4-43f4-87b6-2f0dec1798d1",
                "GENDER": "Male",
                "HOME_PHONE": "865-418-3128",
                "STREET_ADDRESS": "66675 High Crossing Way",
                "LATITUDE": "40.7955"
            },
            {
                "EMPLOYEE_ID": "990",
                "item_key": "6e1be205c21f2d5c7c1082d8235f4517",
                "LONGITUDE": "-115.9671",
                "STATE": "CA",
                "DEPARTMENT": "Human Resources",
                "TIME_IN_SERVICE_YRS": "3.12",
                "type": "DUPE",
                "EMAIL": "bcheerrh@marketwatch.com",
                "LAST_NAME": "Clardge",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "FIRST_NAME": "Brook",
                "score": "85",
                "DATE_OF_HIRE": "9/9/2018",
                "CITY": "San Bernardino",
                "POSTAL_CODE": "92424",
                "assignment_uuid": "4e5b93c0-bcd4-43f4-87b6-2f0dec1798d1",
                "GENDER": "Male",
                "HOME_PHONE": "909-606-7780",
                "STREET_ADDRESS": "8658 Ridgeway Point",
                "LATITUDE": "34.84"
            },
            {
                "EMPLOYEE_ID": "354",
                "item_key": "b43141e50d89318a8f553a8e9f256f04",
                "LONGITUDE": "-82.2774",
                "STATE": "WV",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.31",
                "type": "DUPE",
                "LAST_NAME": "Clardge",
                "EMAIL": "jclardge9t@illinois.edu",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "FIRST_NAME": "Jdavie",
                "score": "85",
                "DATE_OF_HIRE": "7/2/2018",
                "CITY": "Huntington",
                "POSTAL_CODE": "25716",
                "assignment_uuid": "ee9de5a4-5f79-46ab-a39a-f25cdfab0f20",
                "GENDER": "Male",
                "HOME_PHONE": "304-559-1266",
                "STREET_ADDRESS": "83 Kropf Way",
                "LATITUDE": "38.4134"
            },
            {
                "EMPLOYEE_ID": "583",
                "item_key": "b43141e50d89318a8f553a8e9f256f04",
                "LONGITUDE": "-84.1383",
                "STATE": "TN",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.96",
                "type": "DUPE",
                "EMAIL": "kclarageg6@creativecommons.org",
                "LAST_NAME": "Clarage",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "FIRST_NAME": "Katherine",
                "score": "85",
                "DATE_OF_HIRE": "11/6/2018",
                "CITY": "Knoxville",
                "POSTAL_CODE": "37924",
                "assignment_uuid": "ee9de5a4-5f79-46ab-a39a-f25cdfab0f20",
                "GENDER": "Male",
                "HOME_PHONE": "865-418-3128",
                "STREET_ADDRESS": "66675 High Crossing Way",
                "LATITUDE": "40.7955"
            },
            {
                "EMPLOYEE_ID": "22",
                "item_key": "ec3639827646eab108716856b0bcccf3",
                "LONGITUDE": "-93.7665",
                "STATE": "MN",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.06",
                "type": "DUPE",
                "EMAIL": "dtaintonl@answers.com",
                "LAST_NAME": "Tainton",
                "item_value": "[score:85, key_id:3][Tainton, 3]||[Taunton, 3]",
                "FIRST_NAME": "Dyanne",
                "score": "85",
                "DATE_OF_HIRE": "9/30/2018",
                "CITY": "Young America",
                "POSTAL_CODE": "55557",
                "assignment_uuid": "d23a6c1f-c269-406a-b107-9dcbe83dd71c",
                "GENDER": "Female",
                "HOME_PHONE": "952-832-3196",
                "STREET_ADDRESS": "79438 Parkside Drive",
                "LATITUDE": "44.8055"
            },
            {
                "EMPLOYEE_ID": "437",
                "item_key": "ec3639827646eab108716856b0bcccf3",
                "LONGITUDE": "-83.0044",
                "STATE": "OH",
                "DEPARTMENT": "Engineering",
                "TIME_IN_SERVICE_YRS": "5.98",
                "type": "DUPE",
                "LAST_NAME": "Taunton",
                "EMAIL": "dtauntonc4@about.com",
                "item_value": "[score:85, key_id:3][Tainton, 3]||[Taunton, 3]",
                "FIRST_NAME": "Diena",
                "score": "85",
                "DATE_OF_HIRE": "11/1/2015",
                "CITY": "Columbus",
                "POSTAL_CODE": "43215",
                "assignment_uuid": "d23a6c1f-c269-406a-b107-9dcbe83dd71c",
                "GENDER": "Female",
                "HOME_PHONE": "513-885-7912",
                "STREET_ADDRESS": "43942 Forest Run Pass",
                "LATITUDE": "39.9671"
            },
            {
                "EMPLOYEE_ID": "368",
                "item_key": "0f112508417027a003ce9ef0358294a0",
                "LONGITUDE": "-80.441",
                "STATE": "FL",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "6.05",
                "LAST_NAME": "Pollins",
                "EMAIL": "apollinsa7@pen.io",
                "type": "DUPE",
                "item_value": "[score:85, key_id:4][Pollins, 4]||[Rollins, 4]",
                "FIRST_NAME": "Ari",
                "score": "85",
                "DATE_OF_HIRE": "10/7/2015",
                "CITY": "Miami",
                "POSTAL_CODE": "33196",
                "assignment_uuid": "c591e01d-a73d-4e76-891b-3562b4128eae",
                "GENDER": "Female",
                "HOME_PHONE": "786-873-7423",
                "STREET_ADDRESS": "150 Magdeline Crossing",
                "LATITUDE": "25.6615"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "0f112508417027a003ce9ef0358294a0",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "type": "DUPE",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "LAST_NAME": "Rollins",
                "item_value": "[score:85, key_id:4][Pollins, 4]||[Rollins, 4]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "c591e01d-a73d-4e76-891b-3562b4128eae",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "1f49659b2ad863d7f9fcaac1cfd3597e",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "LAST_NAME": "Rollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Pollins, 5]||[Rollins, 5]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "204bb28e-bd62-4e7c-9127-1c4a16d8ed36",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "988",
                "item_key": "1f49659b2ad863d7f9fcaac1cfd3597e",
                "LONGITUDE": "-81.2571",
                "STATE": "FL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "2.9",
                "LAST_NAME": "Pollins",
                "EMAIL": "kderellrf@ft.com",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][Pollins, 5]||[Rollins, 5]",
                "FIRST_NAME": "Kassi",
                "score": "85",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Orlando",
                "POSTAL_CODE": "32825",
                "assignment_uuid": "204bb28e-bd62-4e7c-9127-1c4a16d8ed36",
                "GENDER": "NULL",
                "HOME_PHONE": "954-559-4887",
                "STREET_ADDRESS": "2 Shelley Crossing",
                "LATITUDE": "28.5469"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "d0bd62f4cc6e9e8d603a1c5ae2708ffb",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "type": "DUPE",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "LAST_NAME": "Rollins",
                "item_value": "[score:85, key_id:6][Rollins, 6]||[pollins, 6]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "b728ed27-570c-482b-b845-509174f78c7a",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "987",
                "item_key": "d0bd62f4cc6e9e8d603a1c5ae2708ffb",
                "LONGITUDE": "-104.6459",
                "STATE": "CO",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.5",
                "EMAIL": "kendeanre@seesaa.net",
                "LAST_NAME": "pollins",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Rollins, 6]||[pollins, 6]",
                "FIRST_NAME": "Katinka",
                "score": "85",
                "DATE_OF_HIRE": "4/24/2018",
                "CITY": "Colorado Springs",
                "POSTAL_CODE": "80925",
                "assignment_uuid": "b728ed27-570c-482b-b845-509174f78c7a",
                "GENDER": "Female",
                "HOME_PHONE": "719-537-1533",
                "STREET_ADDRESS": "5 Sunnyside Junction",
                "LATITUDE": "38.7378"
            },
            {
                "EMPLOYEE_ID": "368",
                "item_key": "0609fb5073a217bdf3655f67c5070707",
                "LONGITUDE": "-80.441",
                "STATE": "FL",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "6.05",
                "EMAIL": "apollinsa7@pen.io",
                "type": "DUPE",
                "LAST_NAME": "Pollins",
                "item_value": "[score:85, key_id:7][Pollins, 7]||[pollins, 7]",
                "FIRST_NAME": "Ari",
                "score": "85",
                "DATE_OF_HIRE": "10/7/2015",
                "CITY": "Miami",
                "POSTAL_CODE": "33196",
                "assignment_uuid": "8a81c9d5-3c50-47df-b3af-a8a53c1a777b",
                "GENDER": "Female",
                "HOME_PHONE": "786-873-7423",
                "STREET_ADDRESS": "150 Magdeline Crossing",
                "LATITUDE": "25.6615"
            },
            {
                "EMPLOYEE_ID": "987",
                "item_key": "0609fb5073a217bdf3655f67c5070707",
                "LONGITUDE": "-104.6459",
                "STATE": "CO",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.5",
                "LAST_NAME": "pollins",
                "type": "DUPE",
                "EMAIL": "kendeanre@seesaa.net",
                "item_value": "[score:85, key_id:7][Pollins, 7]||[pollins, 7]",
                "FIRST_NAME": "Katinka",
                "score": "85",
                "DATE_OF_HIRE": "4/24/2018",
                "CITY": "Colorado Springs",
                "POSTAL_CODE": "80925",
                "assignment_uuid": "8a81c9d5-3c50-47df-b3af-a8a53c1a777b",
                "GENDER": "Female",
                "HOME_PHONE": "719-537-1533",
                "STREET_ADDRESS": "5 Sunnyside Junction",
                "LATITUDE": "38.7378"
            },
            {
                "EMPLOYEE_ID": "987",
                "item_key": "c9512f326e378e8f3ba3a5f99876aee7",
                "LONGITUDE": "-104.6459",
                "STATE": "CO",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.5",
                "LAST_NAME": "pollins",
                "type": "DUPE",
                "EMAIL": "kendeanre@seesaa.net",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[pollins, 8]",
                "FIRST_NAME": "Katinka",
                "score": "85",
                "DATE_OF_HIRE": "4/24/2018",
                "CITY": "Colorado Springs",
                "POSTAL_CODE": "80925",
                "assignment_uuid": "a4be7e51-968b-440e-982c-761e344ef86d",
                "GENDER": "Female",
                "HOME_PHONE": "719-537-1533",
                "STREET_ADDRESS": "5 Sunnyside Junction",
                "LATITUDE": "38.7378"
            },
            {
                "EMPLOYEE_ID": "988",
                "item_key": "c9512f326e378e8f3ba3a5f99876aee7",
                "LONGITUDE": "-81.2571",
                "STATE": "FL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "2.9",
                "EMAIL": "kderellrf@ft.com",
                "type": "DUPE",
                "LAST_NAME": "Pollins",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[pollins, 8]",
                "FIRST_NAME": "Kassi",
                "score": "85",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Orlando",
                "POSTAL_CODE": "32825",
                "assignment_uuid": "a4be7e51-968b-440e-982c-761e344ef86d",
                "GENDER": "NULL",
                "HOME_PHONE": "954-559-4887",
                "STREET_ADDRESS": "2 Shelley Crossing",
                "LATITUDE": "28.5469"
            },
            {
                "EMPLOYEE_ID": "839",
                "item_key": "e4a24dfc9988fa3fb72db3d8c136cd0c",
                "LONGITUDE": "-90.0732",
                "STATE": "TN",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.88",
                "type": "DUPE",
                "LAST_NAME": "Siggins",
                "EMAIL": "fsigginsna@symantec.com",
                "item_value": "[score:85, key_id:9][Diggins, 9]||[Siggins, 9]",
                "FIRST_NAME": "Filia",
                "score": "85",
                "DATE_OF_HIRE": "12/6/2017",
                "CITY": "Memphis",
                "POSTAL_CODE": "38109",
                "assignment_uuid": "bac71436-5b23-47de-bca6-0f1a09fa72d0",
                "GENDER": "Male",
                "HOME_PHONE": "901-601-7599",
                "STREET_ADDRESS": "6886 Granby Park",
                "LATITUDE": "35.0425"
            },
            {
                "EMPLOYEE_ID": "100",
                "item_key": "e4a24dfc9988fa3fb72db3d8c136cd0c",
                "LONGITUDE": "-74.712",
                "STATE": "NJ",
                "DEPARTMENT": "Services",
                "TIME_IN_SERVICE_YRS": "2.88",
                "type": "DUPE",
                "EMAIL": "ndiggins2r@gov.uk",
                "LAST_NAME": "Diggins",
                "item_value": "[score:85, key_id:9][Diggins, 9]||[Siggins, 9]",
                "FIRST_NAME": "Nicky",
                "score": "85",
                "DATE_OF_HIRE": "12/4/2018",
                "CITY": "Trenton",
                "POSTAL_CODE": "8650",
                "assignment_uuid": "bac71436-5b23-47de-bca6-0f1a09fa72d0",
                "GENDER": "Male",
                "HOME_PHONE": "609-938-9163",
                "STREET_ADDRESS": "3 Buena Vista Drive",
                "LATITUDE": "40.2805"
            },
            {
                "EMPLOYEE_ID": "995",
                "item_key": "08f8948222688fde8457346bc3b8425e",
                "LONGITUDE": "-76.6699",
                "STATE": "MD",
                "DEPARTMENT": "Accounting & Finance",
                "TIME_IN_SERVICE_YRS": "4.51",
                "LAST_NAME": "flatley",
                "EMAIL": "pnabbsrm@domainmarket.com",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][Flatley, 10]||[flatley, 10]",
                "FIRST_NAME": "Paula",
                "score": "85",
                "DATE_OF_HIRE": "4/18/2017",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21216",
                "assignment_uuid": "454f47d8-c755-4651-8018-e00829c13f56",
                "GENDER": "Male",
                "HOME_PHONE": "410-512-9139",
                "STREET_ADDRESS": "0433 Homewood Crossing",
                "LATITUDE": "39.3093"
            },
            {
                "EMPLOYEE_ID": "1000",
                "item_key": "08f8948222688fde8457346bc3b8425e",
                "LONGITUDE": "-87.7223",
                "STATE": "IL",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "2.98",
                "type": "DUPE",
                "LAST_NAME": "Flatley",
                "EMAIL": "mbruntjerr@blog.com",
                "item_value": "[score:85, key_id:10][Flatley, 10]||[flatley, 10]",
                "FIRST_NAME": "Maribel",
                "score": "85",
                "DATE_OF_HIRE": "10/28/2018",
                "CITY": "Chicago",
                "POSTAL_CODE": "60624",
                "assignment_uuid": "454f47d8-c755-4651-8018-e00829c13f56",
                "GENDER": "Female",
                "HOME_PHONE": "773-506-5309",
                "STREET_ADDRESS": "107 Division Avenue",
                "LATITUDE": "41.8804"
            },
            {
                "EMPLOYEE_ID": "956",
                "item_key": "2279c32f6087753a7a0d7054a82545c4",
                "LONGITUDE": "-77.1073",
                "STATE": "VA",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "3.11",
                "LAST_NAME": "Flatley",
                "EMAIL": "pflatleyqj@cnet.com",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Flatley, 11]||[flatley, 11]",
                "FIRST_NAME": "Perry",
                "score": "85",
                "DATE_OF_HIRE": "9/12/2018",
                "CITY": "Alexandria",
                "POSTAL_CODE": "22309",
                "assignment_uuid": "9aed2dfd-7d23-4b65-b6db-bb8292fa0f99",
                "GENDER": "Male",
                "HOME_PHONE": "202-453-5054",
                "STREET_ADDRESS": "8724 Kenwood Junction",
                "LATITUDE": "38.7192"
            },
            {
                "EMPLOYEE_ID": "995",
                "item_key": "2279c32f6087753a7a0d7054a82545c4",
                "LONGITUDE": "-76.6699",
                "STATE": "MD",
                "DEPARTMENT": "Accounting & Finance",
                "TIME_IN_SERVICE_YRS": "4.51",
                "type": "DUPE",
                "LAST_NAME": "flatley",
                "EMAIL": "pnabbsrm@domainmarket.com",
                "item_value": "[score:85, key_id:11][Flatley, 11]||[flatley, 11]",
                "FIRST_NAME": "Paula",
                "score": "85",
                "DATE_OF_HIRE": "4/18/2017",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21216",
                "assignment_uuid": "9aed2dfd-7d23-4b65-b6db-bb8292fa0f99",
                "GENDER": "Male",
                "HOME_PHONE": "410-512-9139",
                "STREET_ADDRESS": "0433 Homewood Crossing",
                "LATITUDE": "39.3093"
            },
            {
                "EMPLOYEE_ID": "809",
                "item_key": "60ead045d850983f74846d110146830c",
                "LONGITUDE": "-86.1595",
                "STATE": "IN",
                "DEPARTMENT": "Engineering",
                "TIME_IN_SERVICE_YRS": "5.13",
                "type": "DUPE",
                "LAST_NAME": "Flatley",
                "EMAIL": "aflatleymg@feedburner.com",
                "item_value": "[score:85, key_id:12][Flatley, 12]||[flatley, 12]",
                "FIRST_NAME": "Arabele",
                "score": "85",
                "DATE_OF_HIRE": "9/5/2016",
                "CITY": "Indianapolis",
                "POSTAL_CODE": "46202",
                "assignment_uuid": "750b70b2-58e8-48c4-9307-4ea570dd5e23",
                "GENDER": "Female",
                "HOME_PHONE": "317-779-4918",
                "STREET_ADDRESS": "34245 Susan Court",
                "LATITUDE": "39.7851"
            },
            {
                "EMPLOYEE_ID": "995",
                "item_key": "60ead045d850983f74846d110146830c",
                "LONGITUDE": "-76.6699",
                "STATE": "MD",
                "DEPARTMENT": "Accounting & Finance",
                "TIME_IN_SERVICE_YRS": "4.51",
                "LAST_NAME": "flatley",
                "type": "DUPE",
                "EMAIL": "pnabbsrm@domainmarket.com",
                "item_value": "[score:85, key_id:12][Flatley, 12]||[flatley, 12]",
                "FIRST_NAME": "Paula",
                "score": "85",
                "DATE_OF_HIRE": "4/18/2017",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21216",
                "assignment_uuid": "750b70b2-58e8-48c4-9307-4ea570dd5e23",
                "GENDER": "Male",
                "HOME_PHONE": "410-512-9139",
                "STREET_ADDRESS": "0433 Homewood Crossing",
                "LATITUDE": "39.3093"
            },
            {
                "EMPLOYEE_ID": "706",
                "item_key": "bdfaedd2a1167588e1ca7be1789cd439",
                "LONGITUDE": "-80.0244",
                "STATE": "NC",
                "DEPARTMENT": "Accounting",
                "TIME_IN_SERVICE_YRS": "2.99",
                "EMAIL": "brobinetjl@ftc.gov",
                "LAST_NAME": "Robinet",
                "type": "DUPE",
                "item_value": "[score:86, key_id:13][Robinet, 13]||[Robinett, 13]",
                "FIRST_NAME": "Buckie",
                "score": "86",
                "DATE_OF_HIRE": "10/25/2018",
                "CITY": "Greensboro",
                "POSTAL_CODE": "27404",
                "assignment_uuid": "ddd25d9f-bd82-4656-bcb1-72639e9d503f",
                "GENDER": "Male",
                "HOME_PHONE": "336-142-9688",
                "STREET_ADDRESS": "6173 Glacier Hill Trail",
                "LATITUDE": "36.0807"
            },
            {
                "EMPLOYEE_ID": "815",
                "item_key": "bdfaedd2a1167588e1ca7be1789cd439",
                "LONGITUDE": "-87.6378",
                "STATE": "IL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "4.63",
                "LAST_NAME": "Robinett",
                "type": "DUPE",
                "EMAIL": "jrobinettmm@photobucket.com",
                "item_value": "[score:86, key_id:13][Robinet, 13]||[Robinett, 13]",
                "FIRST_NAME": "Johnna",
                "score": "86",
                "DATE_OF_HIRE": "3/6/2017",
                "CITY": "Chicago",
                "POSTAL_CODE": "60686",
                "assignment_uuid": "ddd25d9f-bd82-4656-bcb1-72639e9d503f",
                "GENDER": "Female",
                "HOME_PHONE": "312-341-6435",
                "STREET_ADDRESS": "5883 Donald Alley",
                "LATITUDE": "41.8756"
            },
            {
                "EMPLOYEE_ID": "802",
                "item_key": "00f0a784e163822a6208845751c2e183",
                "LONGITUDE": "-118.2987",
                "STATE": "CA",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "3.01",
                "LAST_NAME": "Edridge",
                "EMAIL": "redridgem9@wikipedia.org",
                "type": "DUPE",
                "item_value": "[score:86, key_id:14][Edridge, 14]||[Eldridge, 14]",
                "FIRST_NAME": "Rubin",
                "score": "86",
                "DATE_OF_HIRE": "10/19/2018",
                "CITY": "Northridge",
                "POSTAL_CODE": "91328",
                "assignment_uuid": "73227f26-d303-49b4-b27a-6054a650cd2d",
                "GENDER": "Male",
                "HOME_PHONE": "818-851-0399",
                "STREET_ADDRESS": "95 Northwestern Pass",
                "LATITUDE": "33.7866"
            },
            {
                "EMPLOYEE_ID": "355",
                "item_key": "00f0a784e163822a6208845751c2e183",
                "LONGITUDE": "-77.4422",
                "STATE": "VA",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.9",
                "LAST_NAME": "Eldridge",
                "type": "DUPE",
                "EMAIL": "jeldridge9u@hp.com",
                "item_value": "[score:86, key_id:14][Edridge, 14]||[Eldridge, 14]",
                "FIRST_NAME": "Justus",
                "score": "86",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Dulles",
                "POSTAL_CODE": "20189",
                "assignment_uuid": "73227f26-d303-49b4-b27a-6054a650cd2d",
                "GENDER": "Male",
                "HOME_PHONE": "571-285-8377",
                "STREET_ADDRESS": "35 Carioca Court",
                "LATITUDE": "39.009"
            },
            {
                "EMPLOYEE_ID": "441",
                "item_key": "cd84835ea2eb1f587d398c6721b0ed3b",
                "LONGITUDE": "-84.4179",
                "STATE": "OH",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.48",
                "LAST_NAME": "Gillings",
                "type": "DUPE",
                "EMAIL": "cgillingsc8@stumbleupon.com",
                "item_value": "[score:87, key_id:15][Gillings, 15]||[Millings, 15]",
                "FIRST_NAME": "Curcio",
                "score": "87",
                "DATE_OF_HIRE": "5/1/2018",
                "CITY": "Cincinnati",
                "POSTAL_CODE": "45228",
                "assignment_uuid": "475e814e-4c3b-4490-8459-d4d6b93d48ff",
                "GENDER": "Male",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "39.0706"
            },
            {
                "EMPLOYEE_ID": "999",
                "item_key": "cd84835ea2eb1f587d398c6721b0ed3b",
                "LONGITUDE": "-93.8881",
                "STATE": "MN",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.59",
                "EMAIL": "cgreenroadrq@mapy.cz",
                "LAST_NAME": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:15][Gillings, 15]||[Millings, 15]",
                "FIRST_NAME": "Cloris",
                "score": "87",
                "DATE_OF_HIRE": "3/21/2018",
                "CITY": "Monticello",
                "POSTAL_CODE": "55565",
                "assignment_uuid": "475e814e-4c3b-4490-8459-d4d6b93d48ff",
                "GENDER": "Female",
                "HOME_PHONE": "763-174-2429",
                "STREET_ADDRESS": "8 Dorton Circle",
                "LATITUDE": "45.2009"
            },
            {
                "EMPLOYEE_ID": "179",
                "item_key": "72af921364d5ab1cf85512761ea1193a",
                "LONGITUDE": "-96.7676",
                "STATE": "TX",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "4.03",
                "EMAIL": "jaldridge4y@instagram.com",
                "type": "DUPE",
                "LAST_NAME": "Aldridge",
                "item_value": "[score:87, key_id:16][Aldridge, 16]||[Eldridge, 16]",
                "FIRST_NAME": "Jayme",
                "score": "87",
                "DATE_OF_HIRE": "10/13/2017",
                "CITY": "Dallas",
                "POSTAL_CODE": "75226",
                "assignment_uuid": "00c8521f-ae72-4c4a-9886-170e63eba9d7",
                "GENDER": "Female",
                "HOME_PHONE": "972-374-8599",
                "STREET_ADDRESS": "02931 Monument Drive",
                "LATITUDE": "32.7887"
            },
            {
                "EMPLOYEE_ID": "355",
                "item_key": "72af921364d5ab1cf85512761ea1193a",
                "LONGITUDE": "-77.4422",
                "STATE": "VA",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.9",
                "LAST_NAME": "Eldridge",
                "type": "DUPE",
                "EMAIL": "jeldridge9u@hp.com",
                "item_value": "[score:87, key_id:16][Aldridge, 16]||[Eldridge, 16]",
                "FIRST_NAME": "Justus",
                "score": "87",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Dulles",
                "POSTAL_CODE": "20189",
                "assignment_uuid": "00c8521f-ae72-4c4a-9886-170e63eba9d7",
                "GENDER": "Male",
                "HOME_PHONE": "571-285-8377",
                "STREET_ADDRESS": "35 Carioca Court",
                "LATITUDE": "39.009"
            },
            {
                "EMPLOYEE_ID": "624",
                "item_key": "48a0e5446de5a051c9cb10b135a10f34",
                "LONGITUDE": "-76.5891",
                "STATE": "MD",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "3.35",
                "LAST_NAME": "Billings",
                "type": "DUPE",
                "EMAIL": "cbillingshb@nbcnews.com",
                "item_value": "[score:87, key_id:17][Billings, 17]||[Gillings, 17]",
                "FIRST_NAME": "Cecilia",
                "score": "87",
                "DATE_OF_HIRE": "6/18/2018",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21239",
                "assignment_uuid": "33817e6b-75ce-4971-9d9b-e9cbd9a60d2c",
                "GENDER": "Female",
                "HOME_PHONE": "410-189-4551",
                "STREET_ADDRESS": "0903 Bellgrove Avenue",
                "LATITUDE": "39.361"
            },
            {
                "EMPLOYEE_ID": "441",
                "item_key": "48a0e5446de5a051c9cb10b135a10f34",
                "LONGITUDE": "-84.4179",
                "STATE": "OH",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.48",
                "type": "DUPE",
                "LAST_NAME": "Gillings",
                "EMAIL": "cgillingsc8@stumbleupon.com",
                "item_value": "[score:87, key_id:17][Billings, 17]||[Gillings, 17]",
                "FIRST_NAME": "Curcio",
                "score": "87",
                "DATE_OF_HIRE": "5/1/2018",
                "CITY": "Cincinnati",
                "POSTAL_CODE": "45228",
                "assignment_uuid": "33817e6b-75ce-4971-9d9b-e9cbd9a60d2c",
                "GENDER": "Male",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "39.0706"
            },
            {
                "EMPLOYEE_ID": "624",
                "item_key": "424a0c41452a3a22492c6ee440ae6fbe",
                "LONGITUDE": "-76.5891",
                "STATE": "MD",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "3.35",
                "LAST_NAME": "Billings",
                "type": "DUPE",
                "EMAIL": "cbillingshb@nbcnews.com",
                "item_value": "[score:87, key_id:18][Billings, 18]||[Millings, 18]",
                "FIRST_NAME": "Cecilia",
                "score": "87",
                "DATE_OF_HIRE": "6/18/2018",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21239",
                "assignment_uuid": "c38b1396-fd62-4d7f-a1a9-e62e0812266a",
                "GENDER": "Female",
                "HOME_PHONE": "410-189-4551",
                "STREET_ADDRESS": "0903 Bellgrove Avenue",
                "LATITUDE": "39.361"
            },
            {
                "EMPLOYEE_ID": "999",
                "item_key": "424a0c41452a3a22492c6ee440ae6fbe",
                "LONGITUDE": "-93.8881",
                "STATE": "MN",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.59",
                "LAST_NAME": "Millings",
                "EMAIL": "cgreenroadrq@mapy.cz",
                "type": "DUPE",
                "item_value": "[score:87, key_id:18][Billings, 18]||[Millings, 18]",
                "FIRST_NAME": "Cloris",
                "score": "87",
                "DATE_OF_HIRE": "3/21/2018",
                "CITY": "Monticello",
                "POSTAL_CODE": "55565",
                "assignment_uuid": "c38b1396-fd62-4d7f-a1a9-e62e0812266a",
                "GENDER": "Female",
                "HOME_PHONE": "763-174-2429",
                "STREET_ADDRESS": "8 Dorton Circle",
                "LATITUDE": "45.2009"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "EMPLOYEE_ID",
                "name": "EMPLOYEE_ID",
                "title": "EMPLOYEE_ID"
            },
            {
                "data": "LONGITUDE",
                "name": "LONGITUDE",
                "title": "LONGITUDE"
            },
            {
                "data": "STATE",
                "name": "STATE",
                "title": "STATE"
            },
            {
                "data": "DEPARTMENT",
                "name": "DEPARTMENT",
                "title": "DEPARTMENT"
            },
            {
                "data": "TIME_IN_SERVICE_YRS",
                "name": "TIME_IN_SERVICE_YRS",
                "title": "TIME_IN_SERVICE_YRS"
            },
            {
                "data": "LAST_NAME",
                "name": "LAST_NAME",
                "title": "LAST_NAME"
            },
            {
                "data": "EMAIL",
                "name": "EMAIL",
                "title": "EMAIL"
            },
            {
                "data": "FIRST_NAME",
                "name": "FIRST_NAME",
                "title": "FIRST_NAME"
            },
            {
                "data": "DATE_OF_HIRE",
                "name": "DATE_OF_HIRE",
                "title": "DATE_OF_HIRE"
            },
            {
                "data": "CITY",
                "name": "CITY",
                "title": "CITY"
            },
            {
                "data": "POSTAL_CODE",
                "name": "POSTAL_CODE",
                "title": "POSTAL_CODE"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "GENDER",
                "name": "GENDER",
                "title": "GENDER"
            },
            {
                "data": "HOME_PHONE",
                "name": "HOME_PHONE",
                "title": "HOME_PHONE"
            },
            {
                "data": "STREET_ADDRESS",
                "name": "STREET_ADDRESS",
                "title": "STREET_ADDRESS"
            },
            {
                "data": "LATITUDE",
                "name": "LATITUDE",
                "title": "LATITUDE"
            }
        ]
    }
]

PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "990",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "354",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Tainton",
        "dupe1_link_id": "22",
        "dupe2": "Taunton",
        "dupe2_link_id": "437",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Rollins",
        "dupe1_link_id": "499",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "pollins",
        "dupe2_link_id": "987",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 9,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 10,
        "dupe1": "Flatley",
        "dupe1_link_id": "1000",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 11,
        "dupe1": "Flatley",
        "dupe1_link_id": "956",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 12,
        "dupe1": "Flatley",
        "dupe1_link_id": "809",
        "dupe2": "flatley",
        "dupe2_link_id": "995",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 13,
        "dupe1": "Robinet",
        "dupe1_link_id": "706",
        "dupe2": "Robinett",
        "dupe2_link_id": "815",
        "score": 86
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 14,
        "dupe1": "Edridge",
        "dupe1_link_id": "802",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 86
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 15,
        "dupe1": "Gillings",
        "dupe1_link_id": "441",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 16,
        "dupe1": "Aldridge",
        "dupe1_link_id": "179",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 17,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Gillings",
        "dupe2_link_id": "441",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:02:40.175+0000",
        "job_uuid": "eff91249-ce29-42f1-9ce3-cd6575c6fa94",
        "dataset": PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 18,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    }
]

PD_DBRKS_DUPES_SCORE_CASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "583",
        "FIRST_NAME": "Katherine",
        "LAST_NAME": "Clarage",
        "EMAIL": "kclarageg6@creativecommons.org",
        "GENDER": "Male",
        "CITY": "Knoxville",
        "DEPARTMENT": "Sales",
        "LATITUDE": "40.7955",
        "LONGITUDE": "-84.1383",
        "HOME_PHONE": "865-418-3128",
        "POSTAL_CODE": "37924",
        "STATE": "TN",
        "STREET_ADDRESS": "66675 High Crossing Way",
        "DATE_OF_HIRE": "11/6/2018",
        "TIME_IN_SERVICE_YRS": 2.96
    },
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "990",
        "FIRST_NAME": "Brook",
        "LAST_NAME": "Clardge",
        "EMAIL": "bcheerrh@marketwatch.com",
        "GENDER": "Male",
        "CITY": "San Bernardino",
        "DEPARTMENT": "Human Resources",
        "LATITUDE": "34.84",
        "LONGITUDE": "-115.9671",
        "HOME_PHONE": "909-606-7780",
        "POSTAL_CODE": "92424",
        "STATE": "CA",
        "STREET_ADDRESS": "8658 Ridgeway Point",
        "DATE_OF_HIRE": "9/9/2018",
        "TIME_IN_SERVICE_YRS": 3.12
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "354",
        "FIRST_NAME": "Jdavie",
        "LAST_NAME": "Clardge",
        "EMAIL": "jclardge9t@illinois.edu",
        "GENDER": "Male",
        "CITY": "Huntington",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "38.4134",
        "LONGITUDE": "-82.2774",
        "HOME_PHONE": "304-559-1266",
        "POSTAL_CODE": "25716",
        "STATE": "WV",
        "STREET_ADDRESS": "83 Kropf Way",
        "DATE_OF_HIRE": "7/2/2018",
        "TIME_IN_SERVICE_YRS": 3.31
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "583",
        "FIRST_NAME": "Katherine",
        "LAST_NAME": "Clarage",
        "EMAIL": "kclarageg6@creativecommons.org",
        "GENDER": "Male",
        "CITY": "Knoxville",
        "DEPARTMENT": "Sales",
        "LATITUDE": "40.7955",
        "LONGITUDE": "-84.1383",
        "HOME_PHONE": "865-418-3128",
        "POSTAL_CODE": "37924",
        "STATE": "TN",
        "STREET_ADDRESS": "66675 High Crossing Way",
        "DATE_OF_HIRE": "11/6/2018",
        "TIME_IN_SERVICE_YRS": 2.96
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "EMPLOYEE_ID": "22",
        "FIRST_NAME": "Dyanne",
        "LAST_NAME": "Tainton",
        "EMAIL": "dtaintonl@answers.com",
        "GENDER": "Female",
        "CITY": "Young America",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "44.8055",
        "LONGITUDE": "-93.7665",
        "HOME_PHONE": "952-832-3196",
        "POSTAL_CODE": "55557",
        "STATE": "MN",
        "STREET_ADDRESS": "79438 Parkside Drive",
        "DATE_OF_HIRE": "9/30/2018",
        "TIME_IN_SERVICE_YRS": 3.06
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "EMPLOYEE_ID": "437",
        "FIRST_NAME": "Diena",
        "LAST_NAME": "Taunton",
        "EMAIL": "dtauntonc4@about.com",
        "GENDER": "Female",
        "CITY": "Columbus",
        "DEPARTMENT": "Engineering",
        "LATITUDE": "39.9671",
        "LONGITUDE": "-83.0044",
        "HOME_PHONE": "513-885-7912",
        "POSTAL_CODE": "43215",
        "STATE": "OH",
        "STREET_ADDRESS": "43942 Forest Run Pass",
        "DATE_OF_HIRE": "11/1/2015",
        "TIME_IN_SERVICE_YRS": 5.98
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "368",
        "FIRST_NAME": "Ari",
        "LAST_NAME": "Pollins",
        "EMAIL": "apollinsa7@pen.io",
        "GENDER": "Female",
        "CITY": "Miami",
        "DEPARTMENT": "Support",
        "LATITUDE": "25.6615",
        "LONGITUDE": "-80.441",
        "HOME_PHONE": "786-873-7423",
        "POSTAL_CODE": "33196",
        "STATE": "FL",
        "STREET_ADDRESS": "150 Magdeline Crossing",
        "DATE_OF_HIRE": "10/7/2015",
        "TIME_IN_SERVICE_YRS": 6.05
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "988",
        "FIRST_NAME": "Kassi",
        "LAST_NAME": "Pollins",
        "EMAIL": "kderellrf@ft.com",
        "GENDER": None,
        "CITY": "Orlando",
        "DEPARTMENT": "Legal",
        "LATITUDE": "28.5469",
        "LONGITUDE": "-81.2571",
        "HOME_PHONE": "954-559-4887",
        "POSTAL_CODE": "32825",
        "STATE": "FL",
        "STREET_ADDRESS": "2 Shelley Crossing",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Rollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Rollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "987",
        "FIRST_NAME": "Katinka",
        "LAST_NAME": "pollins",
        "EMAIL": "kendeanre@seesaa.net",
        "GENDER": "Female",
        "CITY": "Colorado Springs",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "38.7378",
        "LONGITUDE": "-104.6459",
        "HOME_PHONE": "719-537-1533",
        "POSTAL_CODE": "80925",
        "STATE": "CO",
        "STREET_ADDRESS": "5 Sunnyside Junction",
        "DATE_OF_HIRE": "4/24/2018",
        "TIME_IN_SERVICE_YRS": 3.5
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "368",
        "FIRST_NAME": "Ari",
        "LAST_NAME": "Pollins",
        "EMAIL": "apollinsa7@pen.io",
        "GENDER": "Female",
        "CITY": "Miami",
        "DEPARTMENT": "Support",
        "LATITUDE": "25.6615",
        "LONGITUDE": "-80.441",
        "HOME_PHONE": "786-873-7423",
        "POSTAL_CODE": "33196",
        "STATE": "FL",
        "STREET_ADDRESS": "150 Magdeline Crossing",
        "DATE_OF_HIRE": "10/7/2015",
        "TIME_IN_SERVICE_YRS": 6.05
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "987",
        "FIRST_NAME": "Katinka",
        "LAST_NAME": "pollins",
        "EMAIL": "kendeanre@seesaa.net",
        "GENDER": "Female",
        "CITY": "Colorado Springs",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "38.7378",
        "LONGITUDE": "-104.6459",
        "HOME_PHONE": "719-537-1533",
        "POSTAL_CODE": "80925",
        "STATE": "CO",
        "STREET_ADDRESS": "5 Sunnyside Junction",
        "DATE_OF_HIRE": "4/24/2018",
        "TIME_IN_SERVICE_YRS": 3.5
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "987",
        "FIRST_NAME": "Katinka",
        "LAST_NAME": "pollins",
        "EMAIL": "kendeanre@seesaa.net",
        "GENDER": "Female",
        "CITY": "Colorado Springs",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "38.7378",
        "LONGITUDE": "-104.6459",
        "HOME_PHONE": "719-537-1533",
        "POSTAL_CODE": "80925",
        "STATE": "CO",
        "STREET_ADDRESS": "5 Sunnyside Junction",
        "DATE_OF_HIRE": "4/24/2018",
        "TIME_IN_SERVICE_YRS": 3.5
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "pollins",
        "EMPLOYEE_ID": "988",
        "FIRST_NAME": "Kassi",
        "LAST_NAME": "Pollins",
        "EMAIL": "kderellrf@ft.com",
        "GENDER": None,
        "CITY": "Orlando",
        "DEPARTMENT": "Legal",
        "LATITUDE": "28.5469",
        "LONGITUDE": "-81.2571",
        "HOME_PHONE": "954-559-4887",
        "POSTAL_CODE": "32825",
        "STATE": "FL",
        "STREET_ADDRESS": "2 Shelley Crossing",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "100",
        "FIRST_NAME": "Nicky",
        "LAST_NAME": "Diggins",
        "EMAIL": "ndiggins2r@gov.uk",
        "GENDER": "Male",
        "CITY": "Trenton",
        "DEPARTMENT": "Services",
        "LATITUDE": "40.2805",
        "LONGITUDE": "-74.712",
        "HOME_PHONE": "609-938-9163",
        "POSTAL_CODE": "8650",
        "STATE": "NJ",
        "STREET_ADDRESS": "3 Buena Vista Drive",
        "DATE_OF_HIRE": "12/4/2018",
        "TIME_IN_SERVICE_YRS": 2.88
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "839",
        "FIRST_NAME": "Filia",
        "LAST_NAME": "Siggins",
        "EMAIL": "fsigginsna@symantec.com",
        "GENDER": "Male",
        "CITY": "Memphis",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "35.0425",
        "LONGITUDE": "-90.0732",
        "HOME_PHONE": "901-601-7599",
        "POSTAL_CODE": "38109",
        "STATE": "TN",
        "STREET_ADDRESS": "6886 Granby Park",
        "DATE_OF_HIRE": "12/6/2017",
        "TIME_IN_SERVICE_YRS": 3.88
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "995",
        "FIRST_NAME": "Paula",
        "LAST_NAME": "flatley",
        "EMAIL": "pnabbsrm@domainmarket.com",
        "GENDER": "Male",
        "CITY": "Baltimore",
        "DEPARTMENT": "Accounting & Finance",
        "LATITUDE": "39.3093",
        "LONGITUDE": "-76.6699",
        "HOME_PHONE": "410-512-9139",
        "POSTAL_CODE": "21216",
        "STATE": "MD",
        "STREET_ADDRESS": "0433 Homewood Crossing",
        "DATE_OF_HIRE": "4/18/2017",
        "TIME_IN_SERVICE_YRS": 4.51
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "1000",
        "FIRST_NAME": "Maribel",
        "LAST_NAME": "Flatley",
        "EMAIL": "mbruntjerr@blog.com",
        "GENDER": "Female",
        "CITY": "Chicago",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "41.8804",
        "LONGITUDE": "-87.7223",
        "HOME_PHONE": "773-506-5309",
        "POSTAL_CODE": "60624",
        "STATE": "IL",
        "STREET_ADDRESS": "107 Division Avenue",
        "DATE_OF_HIRE": "10/28/2018",
        "TIME_IN_SERVICE_YRS": 2.98
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "956",
        "FIRST_NAME": "Perry",
        "LAST_NAME": "Flatley",
        "EMAIL": "pflatleyqj@cnet.com",
        "GENDER": "Male",
        "CITY": "Alexandria",
        "DEPARTMENT": "Legal",
        "LATITUDE": "38.7192",
        "LONGITUDE": "-77.1073",
        "HOME_PHONE": "202-453-5054",
        "POSTAL_CODE": "22309",
        "STATE": "VA",
        "STREET_ADDRESS": "8724 Kenwood Junction",
        "DATE_OF_HIRE": "9/12/2018",
        "TIME_IN_SERVICE_YRS": 3.11
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "995",
        "FIRST_NAME": "Paula",
        "LAST_NAME": "flatley",
        "EMAIL": "pnabbsrm@domainmarket.com",
        "GENDER": "Male",
        "CITY": "Baltimore",
        "DEPARTMENT": "Accounting & Finance",
        "LATITUDE": "39.3093",
        "LONGITUDE": "-76.6699",
        "HOME_PHONE": "410-512-9139",
        "POSTAL_CODE": "21216",
        "STATE": "MD",
        "STREET_ADDRESS": "0433 Homewood Crossing",
        "DATE_OF_HIRE": "4/18/2017",
        "TIME_IN_SERVICE_YRS": 4.51
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "809",
        "FIRST_NAME": "Arabele",
        "LAST_NAME": "Flatley",
        "EMAIL": "aflatleymg@feedburner.com",
        "GENDER": "Female",
        "CITY": "Indianapolis",
        "DEPARTMENT": "Engineering",
        "LATITUDE": "39.7851",
        "LONGITUDE": "-86.1595",
        "HOME_PHONE": "317-779-4918",
        "POSTAL_CODE": "46202",
        "STATE": "IN",
        "STREET_ADDRESS": "34245 Susan Court",
        "DATE_OF_HIRE": "9/5/2016",
        "TIME_IN_SERVICE_YRS": 5.13
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Flatley",
        "dupe2": "flatley",
        "EMPLOYEE_ID": "995",
        "FIRST_NAME": "Paula",
        "LAST_NAME": "flatley",
        "EMAIL": "pnabbsrm@domainmarket.com",
        "GENDER": "Male",
        "CITY": "Baltimore",
        "DEPARTMENT": "Accounting & Finance",
        "LATITUDE": "39.3093",
        "LONGITUDE": "-76.6699",
        "HOME_PHONE": "410-512-9139",
        "POSTAL_CODE": "21216",
        "STATE": "MD",
        "STREET_ADDRESS": "0433 Homewood Crossing",
        "DATE_OF_HIRE": "4/18/2017",
        "TIME_IN_SERVICE_YRS": 4.51
    },
    {
        "key_id": 13,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "EMPLOYEE_ID": "706",
        "FIRST_NAME": "Buckie",
        "LAST_NAME": "Robinet",
        "EMAIL": "brobinetjl@ftc.gov",
        "GENDER": "Male",
        "CITY": "Greensboro",
        "DEPARTMENT": "Accounting",
        "LATITUDE": "36.0807",
        "LONGITUDE": "-80.0244",
        "HOME_PHONE": "336-142-9688",
        "POSTAL_CODE": "27404",
        "STATE": "NC",
        "STREET_ADDRESS": "6173 Glacier Hill Trail",
        "DATE_OF_HIRE": "10/25/2018",
        "TIME_IN_SERVICE_YRS": 2.99
    },
    {
        "key_id": 13,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "EMPLOYEE_ID": "815",
        "FIRST_NAME": "Johnna",
        "LAST_NAME": "Robinett",
        "EMAIL": "jrobinettmm@photobucket.com",
        "GENDER": "Female",
        "CITY": "Chicago",
        "DEPARTMENT": "Legal",
        "LATITUDE": "41.8756",
        "LONGITUDE": "-87.6378",
        "HOME_PHONE": "312-341-6435",
        "POSTAL_CODE": "60686",
        "STATE": "IL",
        "STREET_ADDRESS": "5883 Donald Alley",
        "DATE_OF_HIRE": "3/6/2017",
        "TIME_IN_SERVICE_YRS": 4.63
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "355",
        "FIRST_NAME": "Justus",
        "LAST_NAME": "Eldridge",
        "EMAIL": "jeldridge9u@hp.com",
        "GENDER": "Male",
        "CITY": "Dulles",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "39.009",
        "LONGITUDE": "-77.4422",
        "HOME_PHONE": "571-285-8377",
        "POSTAL_CODE": "20189",
        "STATE": "VA",
        "STREET_ADDRESS": "35 Carioca Court",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "802",
        "FIRST_NAME": "Rubin",
        "LAST_NAME": "Edridge",
        "EMAIL": "redridgem9@wikipedia.org",
        "GENDER": "Male",
        "CITY": "Northridge",
        "DEPARTMENT": "Legal",
        "LATITUDE": "33.7866",
        "LONGITUDE": "-118.2987",
        "HOME_PHONE": "818-851-0399",
        "POSTAL_CODE": "91328",
        "STATE": "CA",
        "STREET_ADDRESS": "95 Northwestern Pass",
        "DATE_OF_HIRE": "10/19/2018",
        "TIME_IN_SERVICE_YRS": 3.01
    },
    {
        "key_id": 15,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "441",
        "FIRST_NAME": "Curcio",
        "LAST_NAME": "Gillings",
        "EMAIL": "cgillingsc8@stumbleupon.com",
        "GENDER": "Male",
        "CITY": "Cincinnati",
        "DEPARTMENT": "Training",
        "LATITUDE": "39.0706",
        "LONGITUDE": "-84.4179",
        "HOME_PHONE": None,
        "POSTAL_CODE": "45228",
        "STATE": "OH",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "5/1/2018",
        "TIME_IN_SERVICE_YRS": 3.48
    },
    {
        "key_id": 15,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "999",
        "FIRST_NAME": "Cloris",
        "LAST_NAME": "Millings",
        "EMAIL": "cgreenroadrq@mapy.cz",
        "GENDER": "Female",
        "CITY": "Monticello",
        "DEPARTMENT": "Training",
        "LATITUDE": "45.2009",
        "LONGITUDE": "-93.8881",
        "HOME_PHONE": "763-174-2429",
        "POSTAL_CODE": "55565",
        "STATE": "MN",
        "STREET_ADDRESS": "8 Dorton Circle",
        "DATE_OF_HIRE": "3/21/2018",
        "TIME_IN_SERVICE_YRS": 3.59
    },
    {
        "key_id": 16,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "179",
        "FIRST_NAME": "Jayme",
        "LAST_NAME": "Aldridge",
        "EMAIL": "jaldridge4y@instagram.com",
        "GENDER": "Female",
        "CITY": "Dallas",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "32.7887",
        "LONGITUDE": "-96.7676",
        "HOME_PHONE": "972-374-8599",
        "POSTAL_CODE": "75226",
        "STATE": "TX",
        "STREET_ADDRESS": "02931 Monument Drive",
        "DATE_OF_HIRE": "10/13/2017",
        "TIME_IN_SERVICE_YRS": 4.03
    },
    {
        "key_id": 16,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "355",
        "FIRST_NAME": "Justus",
        "LAST_NAME": "Eldridge",
        "EMAIL": "jeldridge9u@hp.com",
        "GENDER": "Male",
        "CITY": "Dulles",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "39.009",
        "LONGITUDE": "-77.4422",
        "HOME_PHONE": "571-285-8377",
        "POSTAL_CODE": "20189",
        "STATE": "VA",
        "STREET_ADDRESS": "35 Carioca Court",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "EMPLOYEE_ID": "441",
        "FIRST_NAME": "Curcio",
        "LAST_NAME": "Gillings",
        "EMAIL": "cgillingsc8@stumbleupon.com",
        "GENDER": "Male",
        "CITY": "Cincinnati",
        "DEPARTMENT": "Training",
        "LATITUDE": "39.0706",
        "LONGITUDE": "-84.4179",
        "HOME_PHONE": None,
        "POSTAL_CODE": "45228",
        "STATE": "OH",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "5/1/2018",
        "TIME_IN_SERVICE_YRS": 3.48
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "EMPLOYEE_ID": "624",
        "FIRST_NAME": "Cecilia",
        "LAST_NAME": "Billings",
        "EMAIL": "cbillingshb@nbcnews.com",
        "GENDER": "Female",
        "CITY": "Baltimore",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.361",
        "LONGITUDE": "-76.5891",
        "HOME_PHONE": "410-189-4551",
        "POSTAL_CODE": "21239",
        "STATE": "MD",
        "STREET_ADDRESS": "0903 Bellgrove Avenue",
        "DATE_OF_HIRE": "6/18/2018",
        "TIME_IN_SERVICE_YRS": 3.35
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "624",
        "FIRST_NAME": "Cecilia",
        "LAST_NAME": "Billings",
        "EMAIL": "cbillingshb@nbcnews.com",
        "GENDER": "Female",
        "CITY": "Baltimore",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.361",
        "LONGITUDE": "-76.5891",
        "HOME_PHONE": "410-189-4551",
        "POSTAL_CODE": "21239",
        "STATE": "MD",
        "STREET_ADDRESS": "0903 Bellgrove Avenue",
        "DATE_OF_HIRE": "6/18/2018",
        "TIME_IN_SERVICE_YRS": 3.35
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "999",
        "FIRST_NAME": "Cloris",
        "LAST_NAME": "Millings",
        "EMAIL": "cgreenroadrq@mapy.cz",
        "GENDER": "Female",
        "CITY": "Monticello",
        "DEPARTMENT": "Training",
        "LATITUDE": "45.2009",
        "LONGITUDE": "-93.8881",
        "HOME_PHONE": "763-174-2429",
        "POSTAL_CODE": "55565",
        "STATE": "MN",
        "STREET_ADDRESS": "8 Dorton Circle",
        "DATE_OF_HIRE": "3/21/2018",
        "TIME_IN_SERVICE_YRS": 3.59
    }
]
