from payloads.pushdown.dupes.pl_pd_dbrks_dupes_score_nocase_employees_dt_archive_breaks import (
    PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
)

PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DUPES = [
    {
        "data": [
            {
                "EMPLOYEE_ID": "354",
                "item_key": "f5c81cf15f7e720abcb1aa165586a46a",
                "LONGITUDE": "-82.2774",
                "STATE": "WV",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.31",
                "EMAIL": "jclardge9t@illinois.edu",
                "type": "DUPE",
                "LAST_NAME": "Clardge",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "FIRST_NAME": "Jdavie",
                "score": "85",
                "DATE_OF_HIRE": "7/2/2018",
                "CITY": "Huntington",
                "POSTAL_CODE": "25716",
                "assignment_uuid": "0349cd62-57cf-44bf-a9cf-0f79410827c8",
                "GENDER": "Male",
                "HOME_PHONE": "304-559-1266",
                "STREET_ADDRESS": "83 Kropf Way",
                "LATITUDE": "38.4134"
            },
            {
                "EMPLOYEE_ID": "583",
                "item_key": "f5c81cf15f7e720abcb1aa165586a46a",
                "LONGITUDE": "-84.1383",
                "STATE": "TN",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.96",
                "type": "DUPE",
                "LAST_NAME": "Clarage",
                "EMAIL": "kclarageg6@creativecommons.org",
                "item_value": "[score:85, key_id:1][Clarage, 1]||[Clardge, 1]",
                "FIRST_NAME": "Katherine",
                "score": "85",
                "DATE_OF_HIRE": "11/6/2018",
                "CITY": "Knoxville",
                "POSTAL_CODE": "37924",
                "assignment_uuid": "0349cd62-57cf-44bf-a9cf-0f79410827c8",
                "GENDER": "Male",
                "HOME_PHONE": "865-418-3128",
                "STREET_ADDRESS": "66675 High Crossing Way",
                "LATITUDE": "40.7955"
            },
            {
                "EMPLOYEE_ID": "990",
                "item_key": "b17769133bfdb0ea132b789901c872f2",
                "LONGITUDE": "-115.9671",
                "STATE": "CA",
                "DEPARTMENT": "Human Resources",
                "TIME_IN_SERVICE_YRS": "3.12",
                "EMAIL": "bcheerrh@marketwatch.com",
                "LAST_NAME": "Clardge",
                "type": "DUPE",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "FIRST_NAME": "Brook",
                "score": "85",
                "DATE_OF_HIRE": "9/9/2018",
                "CITY": "San Bernardino",
                "POSTAL_CODE": "92424",
                "assignment_uuid": "381ed016-880f-4717-954f-a04968fb4c6e",
                "GENDER": "Male",
                "HOME_PHONE": "909-606-7780",
                "STREET_ADDRESS": "8658 Ridgeway Point",
                "LATITUDE": "34.84"
            },
            {
                "EMPLOYEE_ID": "583",
                "item_key": "b17769133bfdb0ea132b789901c872f2",
                "LONGITUDE": "-84.1383",
                "STATE": "TN",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.96",
                "type": "DUPE",
                "LAST_NAME": "Clarage",
                "EMAIL": "kclarageg6@creativecommons.org",
                "item_value": "[score:85, key_id:2][Clarage, 2]||[Clardge, 2]",
                "FIRST_NAME": "Katherine",
                "score": "85",
                "DATE_OF_HIRE": "11/6/2018",
                "CITY": "Knoxville",
                "POSTAL_CODE": "37924",
                "assignment_uuid": "381ed016-880f-4717-954f-a04968fb4c6e",
                "GENDER": "Male",
                "HOME_PHONE": "865-418-3128",
                "STREET_ADDRESS": "66675 High Crossing Way",
                "LATITUDE": "40.7955"
            },
            {
                "EMPLOYEE_ID": "989",
                "item_key": "2f4a9acd55e1292d594f8ca7c841006f",
                "LONGITUDE": "-73.9772",
                "STATE": "NY",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "4.56",
                "EMAIL": "thayerrg@home.pl",
                "type": "DUPE",
                "LAST_NAME": "CLARDGE",
                "item_value": "[score:85, key_id:3][Clarage, 3]||[CLARDGE, 3]",
                "FIRST_NAME": "Terrye",
                "score": "85",
                "DATE_OF_HIRE": "4/1/2017",
                "CITY": "New York City",
                "POSTAL_CODE": "10125",
                "assignment_uuid": "c18220fc-06c9-4526-90a8-528781fbeaba",
                "GENDER": "NULL",
                "HOME_PHONE": "212-511-8481",
                "STREET_ADDRESS": "505 Golf Course Road",
                "LATITUDE": "40.7808"
            },
            {
                "EMPLOYEE_ID": "583",
                "item_key": "2f4a9acd55e1292d594f8ca7c841006f",
                "LONGITUDE": "-84.1383",
                "STATE": "TN",
                "DEPARTMENT": "Sales",
                "TIME_IN_SERVICE_YRS": "2.96",
                "EMAIL": "kclarageg6@creativecommons.org",
                "type": "DUPE",
                "LAST_NAME": "Clarage",
                "item_value": "[score:85, key_id:3][Clarage, 3]||[CLARDGE, 3]",
                "FIRST_NAME": "Katherine",
                "score": "85",
                "DATE_OF_HIRE": "11/6/2018",
                "CITY": "Knoxville",
                "POSTAL_CODE": "37924",
                "assignment_uuid": "c18220fc-06c9-4526-90a8-528781fbeaba",
                "GENDER": "Male",
                "HOME_PHONE": "865-418-3128",
                "STREET_ADDRESS": "66675 High Crossing Way",
                "LATITUDE": "40.7955"
            },
            {
                "EMPLOYEE_ID": "22",
                "item_key": "9e1f800a96907511e65eae66b14e124e",
                "LONGITUDE": "-93.7665",
                "STATE": "MN",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.06",
                "type": "DUPE",
                "EMAIL": "dtaintonl@answers.com",
                "LAST_NAME": "Tainton",
                "item_value": "[score:85, key_id:4][Tainton, 4]||[Taunton, 4]",
                "FIRST_NAME": "Dyanne",
                "score": "85",
                "DATE_OF_HIRE": "9/30/2018",
                "CITY": "Young America",
                "POSTAL_CODE": "55557",
                "assignment_uuid": "3553a7fa-9151-451f-8ce9-d990f896595c",
                "GENDER": "Female",
                "HOME_PHONE": "952-832-3196",
                "STREET_ADDRESS": "79438 Parkside Drive",
                "LATITUDE": "44.8055"
            },
            {
                "EMPLOYEE_ID": "437",
                "item_key": "9e1f800a96907511e65eae66b14e124e",
                "LONGITUDE": "-83.0044",
                "STATE": "OH",
                "DEPARTMENT": "Engineering",
                "TIME_IN_SERVICE_YRS": "5.98",
                "type": "DUPE",
                "LAST_NAME": "Taunton",
                "EMAIL": "dtauntonc4@about.com",
                "item_value": "[score:85, key_id:4][Tainton, 4]||[Taunton, 4]",
                "FIRST_NAME": "Diena",
                "score": "85",
                "DATE_OF_HIRE": "11/1/2015",
                "CITY": "Columbus",
                "POSTAL_CODE": "43215",
                "assignment_uuid": "3553a7fa-9151-451f-8ce9-d990f896595c",
                "GENDER": "Female",
                "HOME_PHONE": "513-885-7912",
                "STREET_ADDRESS": "43942 Forest Run Pass",
                "LATITUDE": "39.9671"
            },
            {
                "EMPLOYEE_ID": "146",
                "item_key": "75141008e5bab6ecee491c547feffc08",
                "LONGITUDE": "-106.4073",
                "STATE": "TX",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.94",
                "LAST_NAME": "Harlock",
                "EMAIL": "dharlock41@guardian.co.uk",
                "type": "DUPE",
                "item_value": "[score:85, key_id:5][hAlLoCk, 5]||[Harlock, 5]",
                "FIRST_NAME": "Dale",
                "score": "85",
                "DATE_OF_HIRE": "11/13/2017",
                "CITY": "El Paso",
                "POSTAL_CODE": "79934",
                "assignment_uuid": "57a81c7f-f3c1-4fe0-832e-53a4f9915c6c",
                "GENDER": "NULL",
                "HOME_PHONE": "915-842-8761",
                "STREET_ADDRESS": "6 Loeprich Pass",
                "LATITUDE": "31.9386"
            },
            {
                "EMPLOYEE_ID": "511",
                "item_key": "75141008e5bab6ecee491c547feffc08",
                "LONGITUDE": "-105.0259",
                "STATE": "CO",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "2.89",
                "type": "DUPE",
                "LAST_NAME": "hAlLoCk",
                "EMAIL": "bhallocke6@dailymail.co.uk",
                "item_value": "[score:85, key_id:5][hAlLoCk, 5]||[Harlock, 5]",
                "FIRST_NAME": "Beaufort",
                "score": "85",
                "DATE_OF_HIRE": "12/2/2018",
                "CITY": "Denver",
                "POSTAL_CODE": "80204",
                "assignment_uuid": "57a81c7f-f3c1-4fe0-832e-53a4f9915c6c",
                "GENDER": "Male",
                "HOME_PHONE": "303-255-9434",
                "STREET_ADDRESS": "17 Dixon Circle",
                "LATITUDE": "39.734"
            },
            {
                "EMPLOYEE_ID": "988",
                "item_key": "0dbe63bcc187c76779025aadb6d8b725",
                "LONGITUDE": "-81.2571",
                "STATE": "FL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "2.9",
                "type": "DUPE",
                "EMAIL": "kderellrf@ft.com",
                "LAST_NAME": "Pollins",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[Rollins, 6]",
                "FIRST_NAME": "Kassi",
                "score": "85",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Orlando",
                "POSTAL_CODE": "32825",
                "assignment_uuid": "fa9c772d-17b1-4f58-ac69-36f4e605f596",
                "GENDER": "NULL",
                "HOME_PHONE": "954-559-4887",
                "STREET_ADDRESS": "2 Shelley Crossing",
                "LATITUDE": "28.5469"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "0dbe63bcc187c76779025aadb6d8b725",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "LAST_NAME": "Rollins",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "type": "DUPE",
                "item_value": "[score:85, key_id:6][Pollins, 6]||[Rollins, 6]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "fa9c772d-17b1-4f58-ac69-36f4e605f596",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "987",
                "item_key": "e0e080d90dc8869bd964439b3c281dcb",
                "LONGITUDE": "-104.6459",
                "STATE": "CO",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "3.5",
                "type": "DUPE",
                "EMAIL": "kendeanre@seesaa.net",
                "LAST_NAME": "pollins",
                "item_value": "[score:85, key_id:7][pollins, 7]||[Rollins, 7]",
                "FIRST_NAME": "Katinka",
                "score": "85",
                "DATE_OF_HIRE": "4/24/2018",
                "CITY": "Colorado Springs",
                "POSTAL_CODE": "80925",
                "assignment_uuid": "6d60e80f-cf30-441f-9e6f-7729e1053f3d",
                "GENDER": "Female",
                "HOME_PHONE": "719-537-1533",
                "STREET_ADDRESS": "5 Sunnyside Junction",
                "LATITUDE": "38.7378"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "e0e080d90dc8869bd964439b3c281dcb",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "type": "DUPE",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "LAST_NAME": "Rollins",
                "item_value": "[score:85, key_id:7][pollins, 7]||[Rollins, 7]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "6d60e80f-cf30-441f-9e6f-7729e1053f3d",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "368",
                "item_key": "d274f588b216deeb298e82de120f0d5d",
                "LONGITUDE": "-80.441",
                "STATE": "FL",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "6.05",
                "type": "DUPE",
                "LAST_NAME": "Pollins",
                "EMAIL": "apollinsa7@pen.io",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[Rollins, 8]",
                "FIRST_NAME": "Ari",
                "score": "85",
                "DATE_OF_HIRE": "10/7/2015",
                "CITY": "Miami",
                "POSTAL_CODE": "33196",
                "assignment_uuid": "a1e3ac18-105a-430f-82fe-9c8bbce78a61",
                "GENDER": "Female",
                "HOME_PHONE": "786-873-7423",
                "STREET_ADDRESS": "150 Magdeline Crossing",
                "LATITUDE": "25.6615"
            },
            {
                "EMPLOYEE_ID": "499",
                "item_key": "d274f588b216deeb298e82de120f0d5d",
                "LONGITUDE": "-106.3",
                "STATE": "TX",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.02",
                "LAST_NAME": "Rollins",
                "EMAIL": "crollinsdu@sciencedaily.com",
                "type": "DUPE",
                "item_value": "[score:85, key_id:8][Pollins, 8]||[Rollins, 8]",
                "FIRST_NAME": "Colver",
                "score": "85",
                "DATE_OF_HIRE": "10/16/2018",
                "CITY": "El Paso",
                "POSTAL_CODE": "88535",
                "assignment_uuid": "a1e3ac18-105a-430f-82fe-9c8bbce78a61",
                "GENDER": "Male",
                "HOME_PHONE": "915-822-0254",
                "STREET_ADDRESS": "732 Burning Wood Crossing",
                "LATITUDE": "31.6948"
            },
            {
                "EMPLOYEE_ID": "994",
                "item_key": "1d8e18854fff862d459913a18e8b520b",
                "LONGITUDE": "-73.9808",
                "STATE": "NY",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.93",
                "EMAIL": "rfalconerrl@spotify.com",
                "LAST_NAME": "RIGGINS",
                "type": "DUPE",
                "item_value": "[score:85, key_id:9][RIGGINS, 9]||[Siggins, 9]",
                "FIRST_NAME": "Reamonn",
                "score": "85",
                "DATE_OF_HIRE": "11/17/2018",
                "CITY": "New York City",
                "POSTAL_CODE": "10110",
                "assignment_uuid": "74cfe04d-bdee-4a37-8547-9f22206e148f",
                "GENDER": "Female",
                "HOME_PHONE": "718-149-3139",
                "STREET_ADDRESS": "2 Gerald Park",
                "LATITUDE": "40.754"
            },
            {
                "EMPLOYEE_ID": "839",
                "item_key": "1d8e18854fff862d459913a18e8b520b",
                "LONGITUDE": "-90.0732",
                "STATE": "TN",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.88",
                "type": "DUPE",
                "LAST_NAME": "Siggins",
                "EMAIL": "fsigginsna@symantec.com",
                "item_value": "[score:85, key_id:9][RIGGINS, 9]||[Siggins, 9]",
                "FIRST_NAME": "Filia",
                "score": "85",
                "DATE_OF_HIRE": "12/6/2017",
                "CITY": "Memphis",
                "POSTAL_CODE": "38109",
                "assignment_uuid": "74cfe04d-bdee-4a37-8547-9f22206e148f",
                "GENDER": "Male",
                "HOME_PHONE": "901-601-7599",
                "STREET_ADDRESS": "6886 Granby Park",
                "LATITUDE": "35.0425"
            },
            {
                "EMPLOYEE_ID": "129",
                "item_key": "5b9dd5b39808dc16ecc4e5598639bf3c",
                "LONGITUDE": "-80.0649",
                "STATE": "PA",
                "DEPARTMENT": "Research and Development",
                "TIME_IN_SERVICE_YRS": "3.24",
                "EMAIL": "tmaywood3k@microsoft.com",
                "LAST_NAME": "Maywood",
                "type": "DUPE",
                "item_value": "[score:85, key_id:10][Maywood, 10]||[SaYwOoD, 10]",
                "FIRST_NAME": "Thaddeus",
                "score": "85",
                "DATE_OF_HIRE": "7/29/2018",
                "CITY": "Erie",
                "POSTAL_CODE": "16522",
                "assignment_uuid": "11361772-97f9-4fd3-90f4-78e4fb5e8124",
                "GENDER": "NULL",
                "HOME_PHONE": "814-174-0191",
                "STREET_ADDRESS": "96 Oneill Parkway",
                "LATITUDE": "42.1827"
            },
            {
                "EMPLOYEE_ID": "688",
                "item_key": "5b9dd5b39808dc16ecc4e5598639bf3c",
                "LONGITUDE": "-81.6217",
                "STATE": "FL",
                "DEPARTMENT": "Human Resources",
                "TIME_IN_SERVICE_YRS": "2.97",
                "LAST_NAME": "SaYwOoD",
                "type": "DUPE",
                "EMAIL": "dsaywoodj3@weibo.com",
                "item_value": "[score:85, key_id:10][Maywood, 10]||[SaYwOoD, 10]",
                "FIRST_NAME": "Denys",
                "score": "85",
                "DATE_OF_HIRE": "11/4/2018",
                "CITY": "Jacksonville",
                "POSTAL_CODE": "32259",
                "assignment_uuid": "11361772-97f9-4fd3-90f4-78e4fb5e8124",
                "GENDER": "Male",
                "HOME_PHONE": "904-482-9750",
                "STREET_ADDRESS": "00622 Golf Avenue",
                "LATITUDE": "30.0956"
            },
            {
                "EMPLOYEE_ID": "163",
                "item_key": "d81ee83e69021235176cbe205025577c",
                "LONGITUDE": "-122.7278",
                "STATE": "CA",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.06",
                "EMAIL": "rniblett4i@unblog.fr",
                "type": "DUPE",
                "LAST_NAME": "NibletT",
                "item_value": "[score:85, key_id:11][Giblett, 11]||[NibletT, 11]",
                "FIRST_NAME": "Rosetta",
                "score": "85",
                "DATE_OF_HIRE": "9/30/2018",
                "CITY": "San Francisco",
                "POSTAL_CODE": "94154",
                "assignment_uuid": "1712a573-d097-442d-9c05-aba9c3e5ae62",
                "GENDER": "NULL",
                "HOME_PHONE": "415-989-1878",
                "STREET_ADDRESS": "2177 Kenwood Drive",
                "LATITUDE": "37.7848"
            },
            {
                "EMPLOYEE_ID": "944",
                "item_key": "d81ee83e69021235176cbe205025577c",
                "LONGITUDE": "-97.7713",
                "STATE": "TX",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "3.11",
                "EMAIL": "kgiblettq7@census.gov",
                "LAST_NAME": "Giblett",
                "type": "DUPE",
                "item_value": "[score:85, key_id:11][Giblett, 11]||[NibletT, 11]",
                "FIRST_NAME": "Kata",
                "score": "85",
                "DATE_OF_HIRE": "9/12/2018",
                "CITY": "Austin",
                "POSTAL_CODE": "78769",
                "assignment_uuid": "1712a573-d097-442d-9c05-aba9c3e5ae62",
                "GENDER": "Female",
                "HOME_PHONE": "512-954-0424",
                "STREET_ADDRESS": "41171 Becker Lane",
                "LATITUDE": "30.3264"
            },
            {
                "EMPLOYEE_ID": "994",
                "item_key": "f6c39992dbe0d56c989e95bd8d7406c7",
                "LONGITUDE": "-73.9808",
                "STATE": "NY",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.93",
                "type": "DUPE",
                "EMAIL": "rfalconerrl@spotify.com",
                "LAST_NAME": "RIGGINS",
                "item_value": "[score:85, key_id:12][Diggins, 12]||[RIGGINS, 12]",
                "FIRST_NAME": "Reamonn",
                "score": "85",
                "DATE_OF_HIRE": "11/17/2018",
                "CITY": "New York City",
                "POSTAL_CODE": "10110",
                "assignment_uuid": "f01cadfa-bc93-4b52-a028-680171685da2",
                "GENDER": "Female",
                "HOME_PHONE": "718-149-3139",
                "STREET_ADDRESS": "2 Gerald Park",
                "LATITUDE": "40.754"
            },
            {
                "EMPLOYEE_ID": "100",
                "item_key": "f6c39992dbe0d56c989e95bd8d7406c7",
                "LONGITUDE": "-74.712",
                "STATE": "NJ",
                "DEPARTMENT": "Services",
                "TIME_IN_SERVICE_YRS": "2.88",
                "type": "DUPE",
                "LAST_NAME": "Diggins",
                "EMAIL": "ndiggins2r@gov.uk",
                "item_value": "[score:85, key_id:12][Diggins, 12]||[RIGGINS, 12]",
                "FIRST_NAME": "Nicky",
                "score": "85",
                "DATE_OF_HIRE": "12/4/2018",
                "CITY": "Trenton",
                "POSTAL_CODE": "8650",
                "assignment_uuid": "f01cadfa-bc93-4b52-a028-680171685da2",
                "GENDER": "Male",
                "HOME_PHONE": "609-938-9163",
                "STREET_ADDRESS": "3 Buena Vista Drive",
                "LATITUDE": "40.2805"
            },
            {
                "EMPLOYEE_ID": "100",
                "item_key": "6e5852c05cbb50923aee37a11e6f3072",
                "LONGITUDE": "-74.712",
                "STATE": "NJ",
                "DEPARTMENT": "Services",
                "TIME_IN_SERVICE_YRS": "2.88",
                "LAST_NAME": "Diggins",
                "EMAIL": "ndiggins2r@gov.uk",
                "type": "DUPE",
                "item_value": "[score:85, key_id:13][Diggins, 13]||[Siggins, 13]",
                "FIRST_NAME": "Nicky",
                "score": "85",
                "DATE_OF_HIRE": "12/4/2018",
                "CITY": "Trenton",
                "POSTAL_CODE": "8650",
                "assignment_uuid": "ad84c438-6b4f-423a-afe6-0a6cd4059a09",
                "GENDER": "Male",
                "HOME_PHONE": "609-938-9163",
                "STREET_ADDRESS": "3 Buena Vista Drive",
                "LATITUDE": "40.2805"
            },
            {
                "EMPLOYEE_ID": "839",
                "item_key": "6e5852c05cbb50923aee37a11e6f3072",
                "LONGITUDE": "-90.0732",
                "STATE": "TN",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "3.88",
                "type": "DUPE",
                "EMAIL": "fsigginsna@symantec.com",
                "LAST_NAME": "Siggins",
                "item_value": "[score:85, key_id:13][Diggins, 13]||[Siggins, 13]",
                "FIRST_NAME": "Filia",
                "score": "85",
                "DATE_OF_HIRE": "12/6/2017",
                "CITY": "Memphis",
                "POSTAL_CODE": "38109",
                "assignment_uuid": "ad84c438-6b4f-423a-afe6-0a6cd4059a09",
                "GENDER": "Male",
                "HOME_PHONE": "901-601-7599",
                "STREET_ADDRESS": "6886 Granby Park",
                "LATITUDE": "35.0425"
            },
            {
                "EMPLOYEE_ID": "706",
                "item_key": "1c577ef8c13f3d47b1e4de42dd841e22",
                "LONGITUDE": "-80.0244",
                "STATE": "NC",
                "DEPARTMENT": "Accounting",
                "TIME_IN_SERVICE_YRS": "2.99",
                "type": "DUPE",
                "LAST_NAME": "Robinet",
                "EMAIL": "brobinetjl@ftc.gov",
                "item_value": "[score:86, key_id:14][Robinet, 14]||[Robinett, 14]",
                "FIRST_NAME": "Buckie",
                "score": "86",
                "DATE_OF_HIRE": "10/25/2018",
                "CITY": "Greensboro",
                "POSTAL_CODE": "27404",
                "assignment_uuid": "cfcb1754-0e3b-4010-b957-a8ac36114e30",
                "GENDER": "Male",
                "HOME_PHONE": "336-142-9688",
                "STREET_ADDRESS": "6173 Glacier Hill Trail",
                "LATITUDE": "36.0807"
            },
            {
                "EMPLOYEE_ID": "815",
                "item_key": "1c577ef8c13f3d47b1e4de42dd841e22",
                "LONGITUDE": "-87.6378",
                "STATE": "IL",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "4.63",
                "type": "DUPE",
                "LAST_NAME": "Robinett",
                "EMAIL": "jrobinettmm@photobucket.com",
                "item_value": "[score:86, key_id:14][Robinet, 14]||[Robinett, 14]",
                "FIRST_NAME": "Johnna",
                "score": "86",
                "DATE_OF_HIRE": "3/6/2017",
                "CITY": "Chicago",
                "POSTAL_CODE": "60686",
                "assignment_uuid": "cfcb1754-0e3b-4010-b957-a8ac36114e30",
                "GENDER": "Female",
                "HOME_PHONE": "312-341-6435",
                "STREET_ADDRESS": "5883 Donald Alley",
                "LATITUDE": "41.8756"
            },
            {
                "EMPLOYEE_ID": "498",
                "item_key": "9f64f8ce2a968bae61143f7d1fe4c892",
                "LONGITUDE": "-82.7619",
                "STATE": "FL",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "3.35",
                "LAST_NAME": "Mousdall",
                "EMAIL": "mmousdalldt@phpbb.com",
                "type": "DUPE",
                "item_value": "[score:86, key_id:15][mosdall, 15]||[Mousdall, 15]",
                "FIRST_NAME": "May",
                "score": "86",
                "DATE_OF_HIRE": "6/17/2018",
                "CITY": "Largo",
                "POSTAL_CODE": "34643",
                "assignment_uuid": "96ca7a71-1c1a-4352-a3a8-85ddc3d11137",
                "GENDER": "NULL",
                "HOME_PHONE": "727-495-9149",
                "STREET_ADDRESS": "98 Myrtle Terrace",
                "LATITUDE": "27.881"
            },
            {
                "EMPLOYEE_ID": "680",
                "item_key": "9f64f8ce2a968bae61143f7d1fe4c892",
                "LONGITUDE": "-97.1558",
                "STATE": "KS",
                "DEPARTMENT": "Business Development",
                "TIME_IN_SERVICE_YRS": "5.27",
                "type": "DUPE",
                "LAST_NAME": "mosdall",
                "EMAIL": "dmosdalliv@acquirethisname.com",
                "item_value": "[score:86, key_id:15][mosdall, 15]||[Mousdall, 15]",
                "FIRST_NAME": "Dorotea",
                "score": "86",
                "DATE_OF_HIRE": "7/18/2016",
                "CITY": "Wichita",
                "POSTAL_CODE": "67230",
                "assignment_uuid": "96ca7a71-1c1a-4352-a3a8-85ddc3d11137",
                "GENDER": "Female",
                "HOME_PHONE": "316-864-5692",
                "STREET_ADDRESS": "4204 Vera Park",
                "LATITUDE": "37.6808"
            },
            {
                "EMPLOYEE_ID": "355",
                "item_key": "18547b14941780b808573e5c0b168802",
                "LONGITUDE": "-77.4422",
                "STATE": "VA",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.9",
                "LAST_NAME": "Eldridge",
                "EMAIL": "jeldridge9u@hp.com",
                "type": "DUPE",
                "item_value": "[score:86, key_id:16][Edridge, 16]||[Eldridge, 16]",
                "FIRST_NAME": "Justus",
                "score": "86",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Dulles",
                "POSTAL_CODE": "20189",
                "assignment_uuid": "dd4e298c-0287-48a3-a360-027f0762c254",
                "GENDER": "Male",
                "HOME_PHONE": "571-285-8377",
                "STREET_ADDRESS": "35 Carioca Court",
                "LATITUDE": "39.009"
            },
            {
                "EMPLOYEE_ID": "802",
                "item_key": "18547b14941780b808573e5c0b168802",
                "LONGITUDE": "-118.2987",
                "STATE": "CA",
                "DEPARTMENT": "Legal",
                "TIME_IN_SERVICE_YRS": "3.01",
                "type": "DUPE",
                "LAST_NAME": "Edridge",
                "EMAIL": "redridgem9@wikipedia.org",
                "item_value": "[score:86, key_id:16][Edridge, 16]||[Eldridge, 16]",
                "FIRST_NAME": "Rubin",
                "score": "86",
                "DATE_OF_HIRE": "10/19/2018",
                "CITY": "Northridge",
                "POSTAL_CODE": "91328",
                "assignment_uuid": "dd4e298c-0287-48a3-a360-027f0762c254",
                "GENDER": "Male",
                "HOME_PHONE": "818-851-0399",
                "STREET_ADDRESS": "95 Northwestern Pass",
                "LATITUDE": "33.7866"
            },
            {
                "EMPLOYEE_ID": "999",
                "item_key": "1819c7b917dd37799fe908ae4ca687ba",
                "LONGITUDE": "-93.8881",
                "STATE": "MN",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.59",
                "EMAIL": "cgreenroadrq@mapy.cz",
                "LAST_NAME": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:17][Gillings, 17]||[Millings, 17]",
                "FIRST_NAME": "Cloris",
                "score": "87",
                "DATE_OF_HIRE": "3/21/2018",
                "CITY": "Monticello",
                "POSTAL_CODE": "55565",
                "assignment_uuid": "72e56d15-45d3-4ab6-806d-a227856bf9c2",
                "GENDER": "Female",
                "HOME_PHONE": "763-174-2429",
                "STREET_ADDRESS": "8 Dorton Circle",
                "LATITUDE": "45.2009"
            },
            {
                "EMPLOYEE_ID": "441",
                "item_key": "1819c7b917dd37799fe908ae4ca687ba",
                "LONGITUDE": "-84.4179",
                "STATE": "OH",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.48",
                "type": "DUPE",
                "EMAIL": "cgillingsc8@stumbleupon.com",
                "LAST_NAME": "Gillings",
                "item_value": "[score:87, key_id:17][Gillings, 17]||[Millings, 17]",
                "FIRST_NAME": "Curcio",
                "score": "87",
                "DATE_OF_HIRE": "5/1/2018",
                "CITY": "Cincinnati",
                "POSTAL_CODE": "45228",
                "assignment_uuid": "72e56d15-45d3-4ab6-806d-a227856bf9c2",
                "GENDER": "Male",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "39.0706"
            },
            {
                "EMPLOYEE_ID": "179",
                "item_key": "a7a617a85a98df4781e55efed8cc97f0",
                "LONGITUDE": "-96.7676",
                "STATE": "TX",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "4.03",
                "type": "DUPE",
                "LAST_NAME": "Aldridge",
                "EMAIL": "jaldridge4y@instagram.com",
                "item_value": "[score:87, key_id:18][Aldridge, 18]||[Eldridge, 18]",
                "FIRST_NAME": "Jayme",
                "score": "87",
                "DATE_OF_HIRE": "10/13/2017",
                "CITY": "Dallas",
                "POSTAL_CODE": "75226",
                "assignment_uuid": "8a3542a4-0f75-49de-959b-07238ec0e5ae",
                "GENDER": "Female",
                "HOME_PHONE": "972-374-8599",
                "STREET_ADDRESS": "02931 Monument Drive",
                "LATITUDE": "32.7887"
            },
            {
                "EMPLOYEE_ID": "355",
                "item_key": "a7a617a85a98df4781e55efed8cc97f0",
                "LONGITUDE": "-77.4422",
                "STATE": "VA",
                "DEPARTMENT": "Marketing",
                "TIME_IN_SERVICE_YRS": "2.9",
                "LAST_NAME": "Eldridge",
                "type": "DUPE",
                "EMAIL": "jeldridge9u@hp.com",
                "item_value": "[score:87, key_id:18][Aldridge, 18]||[Eldridge, 18]",
                "FIRST_NAME": "Justus",
                "score": "87",
                "DATE_OF_HIRE": "11/28/2018",
                "CITY": "Dulles",
                "POSTAL_CODE": "20189",
                "assignment_uuid": "8a3542a4-0f75-49de-959b-07238ec0e5ae",
                "GENDER": "Male",
                "HOME_PHONE": "571-285-8377",
                "STREET_ADDRESS": "35 Carioca Court",
                "LATITUDE": "39.009"
            },
            {
                "EMPLOYEE_ID": "441",
                "item_key": "fb01aab9852c6542617a815e52d528ee",
                "LONGITUDE": "-84.4179",
                "STATE": "OH",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.48",
                "EMAIL": "cgillingsc8@stumbleupon.com",
                "type": "DUPE",
                "LAST_NAME": "Gillings",
                "item_value": "[score:87, key_id:19][Billings, 19]||[Gillings, 19]",
                "FIRST_NAME": "Curcio",
                "score": "87",
                "DATE_OF_HIRE": "5/1/2018",
                "CITY": "Cincinnati",
                "POSTAL_CODE": "45228",
                "assignment_uuid": "6a1831bb-1a16-4fef-8bd0-812a6795b587",
                "GENDER": "Male",
                "HOME_PHONE": "NULL",
                "STREET_ADDRESS": "NULL",
                "LATITUDE": "39.0706"
            },
            {
                "EMPLOYEE_ID": "624",
                "item_key": "fb01aab9852c6542617a815e52d528ee",
                "LONGITUDE": "-76.5891",
                "STATE": "MD",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "3.35",
                "EMAIL": "cbillingshb@nbcnews.com",
                "LAST_NAME": "Billings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:19][Billings, 19]||[Gillings, 19]",
                "FIRST_NAME": "Cecilia",
                "score": "87",
                "DATE_OF_HIRE": "6/18/2018",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21239",
                "assignment_uuid": "6a1831bb-1a16-4fef-8bd0-812a6795b587",
                "GENDER": "Female",
                "HOME_PHONE": "410-189-4551",
                "STREET_ADDRESS": "0903 Bellgrove Avenue",
                "LATITUDE": "39.361"
            },
            {
                "EMPLOYEE_ID": "999",
                "item_key": "e6c204d48e2f405a3d88028a5eb9dbd4",
                "LONGITUDE": "-93.8881",
                "STATE": "MN",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "3.59",
                "EMAIL": "cgreenroadrq@mapy.cz",
                "LAST_NAME": "Millings",
                "type": "DUPE",
                "item_value": "[score:87, key_id:20][Billings, 20]||[Millings, 20]",
                "FIRST_NAME": "Cloris",
                "score": "87",
                "DATE_OF_HIRE": "3/21/2018",
                "CITY": "Monticello",
                "POSTAL_CODE": "55565",
                "assignment_uuid": "b4a310d9-241d-438f-9e10-b3d7cc9717d5",
                "GENDER": "Female",
                "HOME_PHONE": "763-174-2429",
                "STREET_ADDRESS": "8 Dorton Circle",
                "LATITUDE": "45.2009"
            },
            {
                "EMPLOYEE_ID": "624",
                "item_key": "e6c204d48e2f405a3d88028a5eb9dbd4",
                "LONGITUDE": "-76.5891",
                "STATE": "MD",
                "DEPARTMENT": "Product Management",
                "TIME_IN_SERVICE_YRS": "3.35",
                "type": "DUPE",
                "LAST_NAME": "Billings",
                "EMAIL": "cbillingshb@nbcnews.com",
                "item_value": "[score:87, key_id:20][Billings, 20]||[Millings, 20]",
                "FIRST_NAME": "Cecilia",
                "score": "87",
                "DATE_OF_HIRE": "6/18/2018",
                "CITY": "Baltimore",
                "POSTAL_CODE": "21239",
                "assignment_uuid": "b4a310d9-241d-438f-9e10-b3d7cc9717d5",
                "GENDER": "Female",
                "HOME_PHONE": "410-189-4551",
                "STREET_ADDRESS": "0903 Bellgrove Avenue",
                "LATITUDE": "39.361"
            },
            {
                "EMPLOYEE_ID": "295",
                "item_key": "bdb9461c4312f5f9e60cd21e8dec7edd",
                "LONGITUDE": "-96.7697",
                "STATE": "TX",
                "DEPARTMENT": "Training",
                "TIME_IN_SERVICE_YRS": "2.99",
                "EMAIL": "hphilpots86@example.com",
                "LAST_NAME": "Philpots",
                "type": "DUPE",
                "item_value": "[score:88, key_id:21][Philpots, 21]||[PHILPOTTS, 21]",
                "FIRST_NAME": "Hynda",
                "score": "88",
                "DATE_OF_HIRE": "10/26/2018",
                "CITY": "Dallas",
                "POSTAL_CODE": "75246",
                "assignment_uuid": "725f3383-98d6-4337-b699-85543272abba",
                "GENDER": "Female",
                "HOME_PHONE": "972-569-5687",
                "STREET_ADDRESS": "59170 Manufacturers Pass",
                "LATITUDE": "32.7948"
            },
            {
                "EMPLOYEE_ID": "603",
                "item_key": "bdb9461c4312f5f9e60cd21e8dec7edd",
                "LONGITUDE": "-77.0146",
                "STATE": "DC",
                "DEPARTMENT": "Support",
                "TIME_IN_SERVICE_YRS": "3.16",
                "LAST_NAME": "PHILPOTTS",
                "type": "DUPE",
                "EMAIL": "bphilpottsgq@mail.ru",
                "item_value": "[score:88, key_id:21][Philpots, 21]||[PHILPOTTS, 21]",
                "FIRST_NAME": "Bettye",
                "score": "88",
                "DATE_OF_HIRE": "8/27/2018",
                "CITY": "Washington",
                "POSTAL_CODE": "20580",
                "assignment_uuid": "725f3383-98d6-4337-b699-85543272abba",
                "GENDER": "Female",
                "HOME_PHONE": "202-493-9320",
                "STREET_ADDRESS": "96 Sunbrook Plaza",
                "LATITUDE": "38.8933"
            }
        ],
        "columns": [
            {
                "data": "item_key",
                "name": "item_key",
                "title": "item_key"
            },
            {
                "data": "item_value",
                "name": "item_value",
                "title": "item_value"
            },
            {
                "data": "assignment_id",
                "name": "assignment_id",
                "title": "assignment_id"
            },
            {
                "data": "type",
                "name": "type",
                "title": "type"
            },
            {
                "data": "score",
                "name": "score",
                "title": "score"
            },
            {
                "data": "EMPLOYEE_ID",
                "name": "EMPLOYEE_ID",
                "title": "EMPLOYEE_ID"
            },
            {
                "data": "LONGITUDE",
                "name": "LONGITUDE",
                "title": "LONGITUDE"
            },
            {
                "data": "STATE",
                "name": "STATE",
                "title": "STATE"
            },
            {
                "data": "DEPARTMENT",
                "name": "DEPARTMENT",
                "title": "DEPARTMENT"
            },
            {
                "data": "TIME_IN_SERVICE_YRS",
                "name": "TIME_IN_SERVICE_YRS",
                "title": "TIME_IN_SERVICE_YRS"
            },
            {
                "data": "EMAIL",
                "name": "EMAIL",
                "title": "EMAIL"
            },
            {
                "data": "LAST_NAME",
                "name": "LAST_NAME",
                "title": "LAST_NAME"
            },
            {
                "data": "FIRST_NAME",
                "name": "FIRST_NAME",
                "title": "FIRST_NAME"
            },
            {
                "data": "DATE_OF_HIRE",
                "name": "DATE_OF_HIRE",
                "title": "DATE_OF_HIRE"
            },
            {
                "data": "CITY",
                "name": "CITY",
                "title": "CITY"
            },
            {
                "data": "POSTAL_CODE",
                "name": "POSTAL_CODE",
                "title": "POSTAL_CODE"
            },
            {
                "data": "assignment_uuid",
                "name": "assignment_uuid",
                "title": "assignment_uuid"
            },
            {
                "data": "GENDER",
                "name": "GENDER",
                "title": "GENDER"
            },
            {
                "data": "HOME_PHONE",
                "name": "HOME_PHONE",
                "title": "HOME_PHONE"
            },
            {
                "data": "STREET_ADDRESS",
                "name": "STREET_ADDRESS",
                "title": "STREET_ADDRESS"
            },
            {
                "data": "LATITUDE",
                "name": "LATITUDE",
                "title": "LATITUDE"
            }
        ]
    }
]

PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 1,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "354",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 2,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "Clardge",
        "dupe2_link_id": "990",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 3,
        "dupe1": "Clarage",
        "dupe1_link_id": "583",
        "dupe2": "CLARDGE",
        "dupe2_link_id": "989",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 4,
        "dupe1": "Tainton",
        "dupe1_link_id": "22",
        "dupe2": "Taunton",
        "dupe2_link_id": "437",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 5,
        "dupe1": "hAlLoCk",
        "dupe1_link_id": "511",
        "dupe2": "Harlock",
        "dupe2_link_id": "146",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 6,
        "dupe1": "Pollins",
        "dupe1_link_id": "368",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 7,
        "dupe1": "Pollins",
        "dupe1_link_id": "988",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 8,
        "dupe1": "pollins",
        "dupe1_link_id": "987",
        "dupe2": "Rollins",
        "dupe2_link_id": "499",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 9,
        "dupe1": "RIGGINS",
        "dupe1_link_id": "994",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 10,
        "dupe1": "Maywood",
        "dupe1_link_id": "129",
        "dupe2": "SaYwOoD",
        "dupe2_link_id": "688",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 11,
        "dupe1": "Giblett",
        "dupe1_link_id": "944",
        "dupe2": "NibletT",
        "dupe2_link_id": "163",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 12,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "RIGGINS",
        "dupe2_link_id": "994",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 13,
        "dupe1": "Diggins",
        "dupe1_link_id": "100",
        "dupe2": "Siggins",
        "dupe2_link_id": "839",
        "score": 85
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 14,
        "dupe1": "Robinet",
        "dupe1_link_id": "706",
        "dupe2": "Robinett",
        "dupe2_link_id": "815",
        "score": 86
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 15,
        "dupe1": "mosdall",
        "dupe1_link_id": "680",
        "dupe2": "Mousdall",
        "dupe2_link_id": "498",
        "score": 86
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 16,
        "dupe1": "Edridge",
        "dupe1_link_id": "802",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 86
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 17,
        "dupe1": "Gillings",
        "dupe1_link_id": "441",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 18,
        "dupe1": "Aldridge",
        "dupe1_link_id": "179",
        "dupe2": "Eldridge",
        "dupe2_link_id": "355",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 19,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Gillings",
        "dupe2_link_id": "441",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 20,
        "dupe1": "Billings",
        "dupe1_link_id": "624",
        "dupe2": "Millings",
        "dupe2_link_id": "999",
        "score": 87
    },
    {
        "seqno": None,
        "updts": "2024-07-14T22:25:34.580+0000",
        "job_uuid": "22790dc7-9cf8-4348-bb11-f9da81185759",
        "dataset": PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-07-14T00:00:00.000+0000",
        "key_id": 21,
        "dupe1": "Philpots",
        "dupe1_link_id": "295",
        "dupe2": "PHILPOTTS",
        "dupe2_link_id": "603",
        "score": 88
    }
]

PD_DBRKS_DUPES_SCORE_NOCASE_EMPLOYEES_DT_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "354",
        "FIRST_NAME": "Jdavie",
        "LAST_NAME": "Clardge",
        "EMAIL": "jclardge9t@illinois.edu",
        "GENDER": "Male",
        "CITY": "Huntington",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "38.4134",
        "LONGITUDE": "-82.2774",
        "HOME_PHONE": "304-559-1266",
        "POSTAL_CODE": "25716",
        "STATE": "WV",
        "STREET_ADDRESS": "83 Kropf Way",
        "DATE_OF_HIRE": "7/2/2018",
        "TIME_IN_SERVICE_YRS": 3.31
    },
    {
        "key_id": 1,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "583",
        "FIRST_NAME": "Katherine",
        "LAST_NAME": "Clarage",
        "EMAIL": "kclarageg6@creativecommons.org",
        "GENDER": "Male",
        "CITY": "Knoxville",
        "DEPARTMENT": "Sales",
        "LATITUDE": "40.7955",
        "LONGITUDE": "-84.1383",
        "HOME_PHONE": "865-418-3128",
        "POSTAL_CODE": "37924",
        "STATE": "TN",
        "STREET_ADDRESS": "66675 High Crossing Way",
        "DATE_OF_HIRE": "11/6/2018",
        "TIME_IN_SERVICE_YRS": 2.96
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "990",
        "FIRST_NAME": "Brook",
        "LAST_NAME": "Clardge",
        "EMAIL": "bcheerrh@marketwatch.com",
        "GENDER": "Male",
        "CITY": "San Bernardino",
        "DEPARTMENT": "Human Resources",
        "LATITUDE": "34.84",
        "LONGITUDE": "-115.9671",
        "HOME_PHONE": "909-606-7780",
        "POSTAL_CODE": "92424",
        "STATE": "CA",
        "STREET_ADDRESS": "8658 Ridgeway Point",
        "DATE_OF_HIRE": "9/9/2018",
        "TIME_IN_SERVICE_YRS": 3.12
    },
    {
        "key_id": 2,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "Clardge",
        "EMPLOYEE_ID": "583",
        "FIRST_NAME": "Katherine",
        "LAST_NAME": "Clarage",
        "EMAIL": "kclarageg6@creativecommons.org",
        "GENDER": "Male",
        "CITY": "Knoxville",
        "DEPARTMENT": "Sales",
        "LATITUDE": "40.7955",
        "LONGITUDE": "-84.1383",
        "HOME_PHONE": "865-418-3128",
        "POSTAL_CODE": "37924",
        "STATE": "TN",
        "STREET_ADDRESS": "66675 High Crossing Way",
        "DATE_OF_HIRE": "11/6/2018",
        "TIME_IN_SERVICE_YRS": 2.96
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "CLARDGE",
        "EMPLOYEE_ID": "989",
        "FIRST_NAME": "Terrye",
        "LAST_NAME": "CLARDGE",
        "EMAIL": "thayerrg@home.pl",
        "GENDER": None,
        "CITY": "New York City",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "40.7808",
        "LONGITUDE": "-73.9772",
        "HOME_PHONE": "212-511-8481",
        "POSTAL_CODE": "10125",
        "STATE": "NY",
        "STREET_ADDRESS": "505 Golf Course Road",
        "DATE_OF_HIRE": "4/1/2017",
        "TIME_IN_SERVICE_YRS": 4.56
    },
    {
        "key_id": 3,
        "score": 85,
        "dupe1": "Clarage",
        "dupe2": "CLARDGE",
        "EMPLOYEE_ID": "583",
        "FIRST_NAME": "Katherine",
        "LAST_NAME": "Clarage",
        "EMAIL": "kclarageg6@creativecommons.org",
        "GENDER": "Male",
        "CITY": "Knoxville",
        "DEPARTMENT": "Sales",
        "LATITUDE": "40.7955",
        "LONGITUDE": "-84.1383",
        "HOME_PHONE": "865-418-3128",
        "POSTAL_CODE": "37924",
        "STATE": "TN",
        "STREET_ADDRESS": "66675 High Crossing Way",
        "DATE_OF_HIRE": "11/6/2018",
        "TIME_IN_SERVICE_YRS": 2.96
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "EMPLOYEE_ID": "22",
        "FIRST_NAME": "Dyanne",
        "LAST_NAME": "Tainton",
        "EMAIL": "dtaintonl@answers.com",
        "GENDER": "Female",
        "CITY": "Young America",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "44.8055",
        "LONGITUDE": "-93.7665",
        "HOME_PHONE": "952-832-3196",
        "POSTAL_CODE": "55557",
        "STATE": "MN",
        "STREET_ADDRESS": "79438 Parkside Drive",
        "DATE_OF_HIRE": "9/30/2018",
        "TIME_IN_SERVICE_YRS": 3.06
    },
    {
        "key_id": 4,
        "score": 85,
        "dupe1": "Tainton",
        "dupe2": "Taunton",
        "EMPLOYEE_ID": "437",
        "FIRST_NAME": "Diena",
        "LAST_NAME": "Taunton",
        "EMAIL": "dtauntonc4@about.com",
        "GENDER": "Female",
        "CITY": "Columbus",
        "DEPARTMENT": "Engineering",
        "LATITUDE": "39.9671",
        "LONGITUDE": "-83.0044",
        "HOME_PHONE": "513-885-7912",
        "POSTAL_CODE": "43215",
        "STATE": "OH",
        "STREET_ADDRESS": "43942 Forest Run Pass",
        "DATE_OF_HIRE": "11/1/2015",
        "TIME_IN_SERVICE_YRS": 5.98
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "hAlLoCk",
        "dupe2": "Harlock",
        "EMPLOYEE_ID": "146",
        "FIRST_NAME": "Dale",
        "LAST_NAME": "Harlock",
        "EMAIL": "dharlock41@guardian.co.uk",
        "GENDER": None,
        "CITY": "El Paso",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "31.9386",
        "LONGITUDE": "-106.4073",
        "HOME_PHONE": "915-842-8761",
        "POSTAL_CODE": "79934",
        "STATE": "TX",
        "STREET_ADDRESS": "6 Loeprich Pass",
        "DATE_OF_HIRE": "11/13/2017",
        "TIME_IN_SERVICE_YRS": 3.94
    },
    {
        "key_id": 5,
        "score": 85,
        "dupe1": "hAlLoCk",
        "dupe2": "Harlock",
        "EMPLOYEE_ID": "511",
        "FIRST_NAME": "Beaufort",
        "LAST_NAME": "hAlLoCk",
        "EMAIL": "bhallocke6@dailymail.co.uk",
        "GENDER": "Male",
        "CITY": "Denver",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.734",
        "LONGITUDE": "-105.0259",
        "HOME_PHONE": "303-255-9434",
        "POSTAL_CODE": "80204",
        "STATE": "CO",
        "STREET_ADDRESS": "17 Dixon Circle",
        "DATE_OF_HIRE": "12/2/2018",
        "TIME_IN_SERVICE_YRS": 2.89
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "368",
        "FIRST_NAME": "Ari",
        "LAST_NAME": "Pollins",
        "EMAIL": "apollinsa7@pen.io",
        "GENDER": "Female",
        "CITY": "Miami",
        "DEPARTMENT": "Support",
        "LATITUDE": "25.6615",
        "LONGITUDE": "-80.441",
        "HOME_PHONE": "786-873-7423",
        "POSTAL_CODE": "33196",
        "STATE": "FL",
        "STREET_ADDRESS": "150 Magdeline Crossing",
        "DATE_OF_HIRE": "10/7/2015",
        "TIME_IN_SERVICE_YRS": 6.05
    },
    {
        "key_id": 6,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "988",
        "FIRST_NAME": "Kassi",
        "LAST_NAME": "Pollins",
        "EMAIL": "kderellrf@ft.com",
        "GENDER": None,
        "CITY": "Orlando",
        "DEPARTMENT": "Legal",
        "LATITUDE": "28.5469",
        "LONGITUDE": "-81.2571",
        "HOME_PHONE": "954-559-4887",
        "POSTAL_CODE": "32825",
        "STATE": "FL",
        "STREET_ADDRESS": "2 Shelley Crossing",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 7,
        "score": 85,
        "dupe1": "Pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "987",
        "FIRST_NAME": "Katinka",
        "LAST_NAME": "pollins",
        "EMAIL": "kendeanre@seesaa.net",
        "GENDER": "Female",
        "CITY": "Colorado Springs",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "38.7378",
        "LONGITUDE": "-104.6459",
        "HOME_PHONE": "719-537-1533",
        "POSTAL_CODE": "80925",
        "STATE": "CO",
        "STREET_ADDRESS": "5 Sunnyside Junction",
        "DATE_OF_HIRE": "4/24/2018",
        "TIME_IN_SERVICE_YRS": 3.5
    },
    {
        "key_id": 8,
        "score": 85,
        "dupe1": "pollins",
        "dupe2": "Rollins",
        "EMPLOYEE_ID": "499",
        "FIRST_NAME": "Colver",
        "LAST_NAME": "Rollins",
        "EMAIL": "crollinsdu@sciencedaily.com",
        "GENDER": "Male",
        "CITY": "El Paso",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "31.6948",
        "LONGITUDE": "-106.3",
        "HOME_PHONE": "915-822-0254",
        "POSTAL_CODE": "88535",
        "STATE": "TX",
        "STREET_ADDRESS": "732 Burning Wood Crossing",
        "DATE_OF_HIRE": "10/16/2018",
        "TIME_IN_SERVICE_YRS": 3.02
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "RIGGINS",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "994",
        "FIRST_NAME": "Reamonn",
        "LAST_NAME": "RIGGINS",
        "EMAIL": "rfalconerrl@spotify.com",
        "GENDER": "Female",
        "CITY": "New York City",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "40.754",
        "LONGITUDE": "-73.9808",
        "HOME_PHONE": "718-149-3139",
        "POSTAL_CODE": "10110",
        "STATE": "NY",
        "STREET_ADDRESS": "2 Gerald Park",
        "DATE_OF_HIRE": "11/17/2018",
        "TIME_IN_SERVICE_YRS": 2.93
    },
    {
        "key_id": 9,
        "score": 85,
        "dupe1": "RIGGINS",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "839",
        "FIRST_NAME": "Filia",
        "LAST_NAME": "Siggins",
        "EMAIL": "fsigginsna@symantec.com",
        "GENDER": "Male",
        "CITY": "Memphis",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "35.0425",
        "LONGITUDE": "-90.0732",
        "HOME_PHONE": "901-601-7599",
        "POSTAL_CODE": "38109",
        "STATE": "TN",
        "STREET_ADDRESS": "6886 Granby Park",
        "DATE_OF_HIRE": "12/6/2017",
        "TIME_IN_SERVICE_YRS": 3.88
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Maywood",
        "dupe2": "SaYwOoD",
        "EMPLOYEE_ID": "129",
        "FIRST_NAME": "Thaddeus",
        "LAST_NAME": "Maywood",
        "EMAIL": "tmaywood3k@microsoft.com",
        "GENDER": None,
        "CITY": "Erie",
        "DEPARTMENT": "Research and Development",
        "LATITUDE": "42.1827",
        "LONGITUDE": "-80.0649",
        "HOME_PHONE": "814-174-0191",
        "POSTAL_CODE": "16522",
        "STATE": "PA",
        "STREET_ADDRESS": "96 Oneill Parkway",
        "DATE_OF_HIRE": "7/29/2018",
        "TIME_IN_SERVICE_YRS": 3.24
    },
    {
        "key_id": 10,
        "score": 85,
        "dupe1": "Maywood",
        "dupe2": "SaYwOoD",
        "EMPLOYEE_ID": "688",
        "FIRST_NAME": "Denys",
        "LAST_NAME": "SaYwOoD",
        "EMAIL": "dsaywoodj3@weibo.com",
        "GENDER": "Male",
        "CITY": "Jacksonville",
        "DEPARTMENT": "Human Resources",
        "LATITUDE": "30.0956",
        "LONGITUDE": "-81.6217",
        "HOME_PHONE": "904-482-9750",
        "POSTAL_CODE": "32259",
        "STATE": "FL",
        "STREET_ADDRESS": "00622 Golf Avenue",
        "DATE_OF_HIRE": "11/4/2018",
        "TIME_IN_SERVICE_YRS": 2.97
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Giblett",
        "dupe2": "NibletT",
        "EMPLOYEE_ID": "163",
        "FIRST_NAME": "Rosetta",
        "LAST_NAME": "NibletT",
        "EMAIL": "rniblett4i@unblog.fr",
        "GENDER": None,
        "CITY": "San Francisco",
        "DEPARTMENT": "Training",
        "LATITUDE": "37.7848",
        "LONGITUDE": "-122.7278",
        "HOME_PHONE": "415-989-1878",
        "POSTAL_CODE": "94154",
        "STATE": "CA",
        "STREET_ADDRESS": "2177 Kenwood Drive",
        "DATE_OF_HIRE": "9/30/2018",
        "TIME_IN_SERVICE_YRS": 3.06
    },
    {
        "key_id": 11,
        "score": 85,
        "dupe1": "Giblett",
        "dupe2": "NibletT",
        "EMPLOYEE_ID": "944",
        "FIRST_NAME": "Kata",
        "LAST_NAME": "Giblett",
        "EMAIL": "kgiblettq7@census.gov",
        "GENDER": "Female",
        "CITY": "Austin",
        "DEPARTMENT": "Support",
        "LATITUDE": "30.3264",
        "LONGITUDE": "-97.7713",
        "HOME_PHONE": "512-954-0424",
        "POSTAL_CODE": "78769",
        "STATE": "TX",
        "STREET_ADDRESS": "41171 Becker Lane",
        "DATE_OF_HIRE": "9/12/2018",
        "TIME_IN_SERVICE_YRS": 3.11
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "RIGGINS",
        "EMPLOYEE_ID": "994",
        "FIRST_NAME": "Reamonn",
        "LAST_NAME": "RIGGINS",
        "EMAIL": "rfalconerrl@spotify.com",
        "GENDER": "Female",
        "CITY": "New York City",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "40.754",
        "LONGITUDE": "-73.9808",
        "HOME_PHONE": "718-149-3139",
        "POSTAL_CODE": "10110",
        "STATE": "NY",
        "STREET_ADDRESS": "2 Gerald Park",
        "DATE_OF_HIRE": "11/17/2018",
        "TIME_IN_SERVICE_YRS": 2.93
    },
    {
        "key_id": 12,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "RIGGINS",
        "EMPLOYEE_ID": "100",
        "FIRST_NAME": "Nicky",
        "LAST_NAME": "Diggins",
        "EMAIL": "ndiggins2r@gov.uk",
        "GENDER": "Male",
        "CITY": "Trenton",
        "DEPARTMENT": "Services",
        "LATITUDE": "40.2805",
        "LONGITUDE": "-74.712",
        "HOME_PHONE": "609-938-9163",
        "POSTAL_CODE": "8650",
        "STATE": "NJ",
        "STREET_ADDRESS": "3 Buena Vista Drive",
        "DATE_OF_HIRE": "12/4/2018",
        "TIME_IN_SERVICE_YRS": 2.88
    },
    {
        "key_id": 13,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "100",
        "FIRST_NAME": "Nicky",
        "LAST_NAME": "Diggins",
        "EMAIL": "ndiggins2r@gov.uk",
        "GENDER": "Male",
        "CITY": "Trenton",
        "DEPARTMENT": "Services",
        "LATITUDE": "40.2805",
        "LONGITUDE": "-74.712",
        "HOME_PHONE": "609-938-9163",
        "POSTAL_CODE": "8650",
        "STATE": "NJ",
        "STREET_ADDRESS": "3 Buena Vista Drive",
        "DATE_OF_HIRE": "12/4/2018",
        "TIME_IN_SERVICE_YRS": 2.88
    },
    {
        "key_id": 13,
        "score": 85,
        "dupe1": "Diggins",
        "dupe2": "Siggins",
        "EMPLOYEE_ID": "839",
        "FIRST_NAME": "Filia",
        "LAST_NAME": "Siggins",
        "EMAIL": "fsigginsna@symantec.com",
        "GENDER": "Male",
        "CITY": "Memphis",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "35.0425",
        "LONGITUDE": "-90.0732",
        "HOME_PHONE": "901-601-7599",
        "POSTAL_CODE": "38109",
        "STATE": "TN",
        "STREET_ADDRESS": "6886 Granby Park",
        "DATE_OF_HIRE": "12/6/2017",
        "TIME_IN_SERVICE_YRS": 3.88
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "EMPLOYEE_ID": "706",
        "FIRST_NAME": "Buckie",
        "LAST_NAME": "Robinet",
        "EMAIL": "brobinetjl@ftc.gov",
        "GENDER": "Male",
        "CITY": "Greensboro",
        "DEPARTMENT": "Accounting",
        "LATITUDE": "36.0807",
        "LONGITUDE": "-80.0244",
        "HOME_PHONE": "336-142-9688",
        "POSTAL_CODE": "27404",
        "STATE": "NC",
        "STREET_ADDRESS": "6173 Glacier Hill Trail",
        "DATE_OF_HIRE": "10/25/2018",
        "TIME_IN_SERVICE_YRS": 2.99
    },
    {
        "key_id": 14,
        "score": 86,
        "dupe1": "Robinet",
        "dupe2": "Robinett",
        "EMPLOYEE_ID": "815",
        "FIRST_NAME": "Johnna",
        "LAST_NAME": "Robinett",
        "EMAIL": "jrobinettmm@photobucket.com",
        "GENDER": "Female",
        "CITY": "Chicago",
        "DEPARTMENT": "Legal",
        "LATITUDE": "41.8756",
        "LONGITUDE": "-87.6378",
        "HOME_PHONE": "312-341-6435",
        "POSTAL_CODE": "60686",
        "STATE": "IL",
        "STREET_ADDRESS": "5883 Donald Alley",
        "DATE_OF_HIRE": "3/6/2017",
        "TIME_IN_SERVICE_YRS": 4.63
    },
    {
        "key_id": 15,
        "score": 86,
        "dupe1": "mosdall",
        "dupe2": "Mousdall",
        "EMPLOYEE_ID": "498",
        "FIRST_NAME": "May",
        "LAST_NAME": "Mousdall",
        "EMAIL": "mmousdalldt@phpbb.com",
        "GENDER": None,
        "CITY": "Largo",
        "DEPARTMENT": "Support",
        "LATITUDE": "27.881",
        "LONGITUDE": "-82.7619",
        "HOME_PHONE": "727-495-9149",
        "POSTAL_CODE": "34643",
        "STATE": "FL",
        "STREET_ADDRESS": "98 Myrtle Terrace",
        "DATE_OF_HIRE": "6/17/2018",
        "TIME_IN_SERVICE_YRS": 3.35
    },
    {
        "key_id": 15,
        "score": 86,
        "dupe1": "mosdall",
        "dupe2": "Mousdall",
        "EMPLOYEE_ID": "680",
        "FIRST_NAME": "Dorotea",
        "LAST_NAME": "mosdall",
        "EMAIL": "dmosdalliv@acquirethisname.com",
        "GENDER": "Female",
        "CITY": "Wichita",
        "DEPARTMENT": "Business Development",
        "LATITUDE": "37.6808",
        "LONGITUDE": "-97.1558",
        "HOME_PHONE": "316-864-5692",
        "POSTAL_CODE": "67230",
        "STATE": "KS",
        "STREET_ADDRESS": "4204 Vera Park",
        "DATE_OF_HIRE": "7/18/2016",
        "TIME_IN_SERVICE_YRS": 5.27
    },
    {
        "key_id": 16,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "355",
        "FIRST_NAME": "Justus",
        "LAST_NAME": "Eldridge",
        "EMAIL": "jeldridge9u@hp.com",
        "GENDER": "Male",
        "CITY": "Dulles",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "39.009",
        "LONGITUDE": "-77.4422",
        "HOME_PHONE": "571-285-8377",
        "POSTAL_CODE": "20189",
        "STATE": "VA",
        "STREET_ADDRESS": "35 Carioca Court",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 16,
        "score": 86,
        "dupe1": "Edridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "802",
        "FIRST_NAME": "Rubin",
        "LAST_NAME": "Edridge",
        "EMAIL": "redridgem9@wikipedia.org",
        "GENDER": "Male",
        "CITY": "Northridge",
        "DEPARTMENT": "Legal",
        "LATITUDE": "33.7866",
        "LONGITUDE": "-118.2987",
        "HOME_PHONE": "818-851-0399",
        "POSTAL_CODE": "91328",
        "STATE": "CA",
        "STREET_ADDRESS": "95 Northwestern Pass",
        "DATE_OF_HIRE": "10/19/2018",
        "TIME_IN_SERVICE_YRS": 3.01
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "999",
        "FIRST_NAME": "Cloris",
        "LAST_NAME": "Millings",
        "EMAIL": "cgreenroadrq@mapy.cz",
        "GENDER": "Female",
        "CITY": "Monticello",
        "DEPARTMENT": "Training",
        "LATITUDE": "45.2009",
        "LONGITUDE": "-93.8881",
        "HOME_PHONE": "763-174-2429",
        "POSTAL_CODE": "55565",
        "STATE": "MN",
        "STREET_ADDRESS": "8 Dorton Circle",
        "DATE_OF_HIRE": "3/21/2018",
        "TIME_IN_SERVICE_YRS": 3.59
    },
    {
        "key_id": 17,
        "score": 87,
        "dupe1": "Gillings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "441",
        "FIRST_NAME": "Curcio",
        "LAST_NAME": "Gillings",
        "EMAIL": "cgillingsc8@stumbleupon.com",
        "GENDER": "Male",
        "CITY": "Cincinnati",
        "DEPARTMENT": "Training",
        "LATITUDE": "39.0706",
        "LONGITUDE": "-84.4179",
        "HOME_PHONE": None,
        "POSTAL_CODE": "45228",
        "STATE": "OH",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "5/1/2018",
        "TIME_IN_SERVICE_YRS": 3.48
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "179",
        "FIRST_NAME": "Jayme",
        "LAST_NAME": "Aldridge",
        "EMAIL": "jaldridge4y@instagram.com",
        "GENDER": "Female",
        "CITY": "Dallas",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "32.7887",
        "LONGITUDE": "-96.7676",
        "HOME_PHONE": "972-374-8599",
        "POSTAL_CODE": "75226",
        "STATE": "TX",
        "STREET_ADDRESS": "02931 Monument Drive",
        "DATE_OF_HIRE": "10/13/2017",
        "TIME_IN_SERVICE_YRS": 4.03
    },
    {
        "key_id": 18,
        "score": 87,
        "dupe1": "Aldridge",
        "dupe2": "Eldridge",
        "EMPLOYEE_ID": "355",
        "FIRST_NAME": "Justus",
        "LAST_NAME": "Eldridge",
        "EMAIL": "jeldridge9u@hp.com",
        "GENDER": "Male",
        "CITY": "Dulles",
        "DEPARTMENT": "Marketing",
        "LATITUDE": "39.009",
        "LONGITUDE": "-77.4422",
        "HOME_PHONE": "571-285-8377",
        "POSTAL_CODE": "20189",
        "STATE": "VA",
        "STREET_ADDRESS": "35 Carioca Court",
        "DATE_OF_HIRE": "11/28/2018",
        "TIME_IN_SERVICE_YRS": 2.9
    },
    {
        "key_id": 19,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "EMPLOYEE_ID": "441",
        "FIRST_NAME": "Curcio",
        "LAST_NAME": "Gillings",
        "EMAIL": "cgillingsc8@stumbleupon.com",
        "GENDER": "Male",
        "CITY": "Cincinnati",
        "DEPARTMENT": "Training",
        "LATITUDE": "39.0706",
        "LONGITUDE": "-84.4179",
        "HOME_PHONE": None,
        "POSTAL_CODE": "45228",
        "STATE": "OH",
        "STREET_ADDRESS": None,
        "DATE_OF_HIRE": "5/1/2018",
        "TIME_IN_SERVICE_YRS": 3.48
    },
    {
        "key_id": 19,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Gillings",
        "EMPLOYEE_ID": "624",
        "FIRST_NAME": "Cecilia",
        "LAST_NAME": "Billings",
        "EMAIL": "cbillingshb@nbcnews.com",
        "GENDER": "Female",
        "CITY": "Baltimore",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.361",
        "LONGITUDE": "-76.5891",
        "HOME_PHONE": "410-189-4551",
        "POSTAL_CODE": "21239",
        "STATE": "MD",
        "STREET_ADDRESS": "0903 Bellgrove Avenue",
        "DATE_OF_HIRE": "6/18/2018",
        "TIME_IN_SERVICE_YRS": 3.35
    },
    {
        "key_id": 20,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "999",
        "FIRST_NAME": "Cloris",
        "LAST_NAME": "Millings",
        "EMAIL": "cgreenroadrq@mapy.cz",
        "GENDER": "Female",
        "CITY": "Monticello",
        "DEPARTMENT": "Training",
        "LATITUDE": "45.2009",
        "LONGITUDE": "-93.8881",
        "HOME_PHONE": "763-174-2429",
        "POSTAL_CODE": "55565",
        "STATE": "MN",
        "STREET_ADDRESS": "8 Dorton Circle",
        "DATE_OF_HIRE": "3/21/2018",
        "TIME_IN_SERVICE_YRS": 3.59
    },
    {
        "key_id": 20,
        "score": 87,
        "dupe1": "Billings",
        "dupe2": "Millings",
        "EMPLOYEE_ID": "624",
        "FIRST_NAME": "Cecilia",
        "LAST_NAME": "Billings",
        "EMAIL": "cbillingshb@nbcnews.com",
        "GENDER": "Female",
        "CITY": "Baltimore",
        "DEPARTMENT": "Product Management",
        "LATITUDE": "39.361",
        "LONGITUDE": "-76.5891",
        "HOME_PHONE": "410-189-4551",
        "POSTAL_CODE": "21239",
        "STATE": "MD",
        "STREET_ADDRESS": "0903 Bellgrove Avenue",
        "DATE_OF_HIRE": "6/18/2018",
        "TIME_IN_SERVICE_YRS": 3.35
    },
    {
        "key_id": 21,
        "score": 88,
        "dupe1": "Philpots",
        "dupe2": "PHILPOTTS",
        "EMPLOYEE_ID": "295",
        "FIRST_NAME": "Hynda",
        "LAST_NAME": "Philpots",
        "EMAIL": "hphilpots86@example.com",
        "GENDER": "Female",
        "CITY": "Dallas",
        "DEPARTMENT": "Training",
        "LATITUDE": "32.7948",
        "LONGITUDE": "-96.7697",
        "HOME_PHONE": "972-569-5687",
        "POSTAL_CODE": "75246",
        "STATE": "TX",
        "STREET_ADDRESS": "59170 Manufacturers Pass",
        "DATE_OF_HIRE": "10/26/2018",
        "TIME_IN_SERVICE_YRS": 2.99
    },
    {
        "key_id": 21,
        "score": 88,
        "dupe1": "Philpots",
        "dupe2": "PHILPOTTS",
        "EMPLOYEE_ID": "603",
        "FIRST_NAME": "Bettye",
        "LAST_NAME": "PHILPOTTS",
        "EMAIL": "bphilpottsgq@mail.ru",
        "GENDER": "Female",
        "CITY": "Washington",
        "DEPARTMENT": "Support",
        "LATITUDE": "38.8933",
        "LONGITUDE": "-77.0146",
        "HOME_PHONE": "202-493-9320",
        "POSTAL_CODE": "20580",
        "STATE": "DC",
        "STREET_ADDRESS": "96 Sunbrook Plaza",
        "DATE_OF_HIRE": "8/27/2018",
        "TIME_IN_SERVICE_YRS": 3.16
    }
]
