from payloads.dq_dgc_integration.pl_dq_dgc_user_defined_rules import (
    DS_DEF_DGC_USER_DEFINED_RULES_NAME,
)

DATA_CLASS_RULES_EXAMPLE = "data_class_rule_sample"
REGEX_RULE_EXAMPLE = "regex_sample_1"
FREEFORM_RULE_EXAMPLE = "freeform_rule_sample"
SIMPLE_RULE_EXAMPLE = "simple_rule_num"
TEMPLATE_RULE_EXAMPLE = "if_high_is_less_than_200_themplate_rule"
QUICK_RULE_EXAMPLE = "if_volume_is_NULLCHECK_quick"

POSTGRES_SCHEMA_NAME = "public"
POSTGRES_TABLE_NAME = "nyse"

DQ_DGC_USER_DEFINED_RULES_DEFINITIONS = [
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": SIMPLE_RULE_EXAMPLE,
        "ruleType": "SQLG",
        "ruleValue": "high BETWEEN 50 and 75",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "high",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": FREEFORM_RULE_EXAMPLE,
        "ruleType": "SQLF",
        "ruleValue": "SELECT * FROM @dataset WHERE open > 0",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": REGEX_RULE_EXAMPLE,
        "ruleType": "SQLF",
        "ruleValue": "SELECT * FROM @dataset WHERE (symbol rlike('.'))",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": QUICK_RULE_EXAMPLE,
        "ruleType": "NULLCHECK",
        "ruleValue": "volume",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "volume",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": TEMPLATE_RULE_EXAMPLE,
        "ruleType": "CUSTOM",
        "ruleValue": "high",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "less_than_200",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "high",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
        "ruleNm": DATA_CLASS_RULES_EXAMPLE,
        "ruleType": "CUSTOM",
        "ruleValue": "close",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "AMEX",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    }
]


DQ_DGC_USER_DEFINED_RULES_EXPECTED_RESULT = {
    "data": [
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": SIMPLE_RULE_EXAMPLE,
            "ruleType": "SQLG",
            "ruleValue": "high BETWEEN 50 and 75",
            "filterQuery": None,
            "score": 10,
            "perc": 10.487769544124603,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 434735,
                "uuid": "a002619a-61ad-43c5-b9d6-b76389df8135"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "high BETWEEN 50 and 75",
            "totalCount": 102815,
            "rowsBreaking": 10783,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": REGEX_RULE_EXAMPLE,
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {DS_DEF_DGC_USER_DEFINED_RULES_NAME}_dataset "
                         f"WHERE (symbol rlike('.')  )  ",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 434737,
                "uuid": "7a715ab9-869e-4c2d-acd5-b59c78465320"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "SELECT * FROM @dataset WHERE (symbol rlike('.'))",
            "totalCount": 102815,
            "rowsBreaking": 102815,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": QUICK_RULE_EXAMPLE,
            "ruleType": "NULLCHECK",
            "ruleValue": "volume",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 434732,
                "uuid": "a6287e7e-01a7-40f8-82fc-ee96f71dbf24"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "volume",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": TEMPLATE_RULE_EXAMPLE,
            "ruleType": "CUSTOM",
            "ruleValue": "high",
            "filterQuery": None,
            "score": 98,
            "perc": 98.01974296569824,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 434733,
                "uuid": "c7638b07-18e8-4602-91f3-a66fef9df126"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "high",
            "totalCount": 102815,
            "rowsBreaking": 100779,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": FREEFORM_RULE_EXAMPLE,
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {DS_DEF_DGC_USER_DEFINED_RULES_NAME}_dataset "
                         f"WHERE open > 0 ",
            "filterQuery": None,
            "score": 99,
            "perc": 99.4222640991211,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 434736,
                "uuid": "f60b9499-079b-4459-9e73-aefb949063ed"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "SELECT * FROM @dataset WHERE open > 0",
            "totalCount": 102815,
            "rowsBreaking": 102221,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": DS_DEF_DGC_USER_DEFINED_RULES_NAME,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": DATA_CLASS_RULES_EXAMPLE,
            "ruleType": "CUSTOM",
            "ruleValue": "close",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 434734,
                "uuid": "839d7c10-c4b3-4ebb-9da5-8bfdbf63a225"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "close",
            "totalCount": 102815,
            "rowsBreaking": 102815,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        }
    ]
}
