from data_test.access_security_permissions.data_user_role_access_common import ACCESS_ALL

from endpoints.v2.controller_rule import (
    V2_DATA_CLASS,
    V2_GET_ACTIVE_RULES_COUNT,
    V2_TEMPLATE_RULES,
    V2_GET_RULES,
    V2_GET_RULE_OUTPUT2,
    V2_GET_RULE_HISTORY_AUDIT,
    V2_GET_RULE_HISTORY,
    V2_GET_MOST_RECENT_OWL_CHECK_HISTORY,
    V2_GET_RULE_REPO,
)

ACCESS_MATRIX_RULE = {
    V2_DATA_CLASS: ACCESS_ALL,
    V2_GET_ACTIVE_RULES_COUNT: ACCESS_ALL,
    V2_TEMPLATE_RULES: ACCESS_ALL,
    V2_GET_RULES: ACCESS_ALL,
    V2_GET_RULE_OUTPUT2: ACCESS_ALL,
    V2_GET_RULE_HISTORY: ACCESS_ALL,
    V2_GET_RULE_HISTORY_AUDIT: ACCESS_ALL,
    V2_GET_MOST_RECENT_OWL_CHECK_HISTORY: ACCESS_ALL,
    V2_GET_RULE_REPO: ACCESS_ALL,
}
