from data_test.access_security_permissions.data_user_role_access_common import ACCESS_ALL
from endpoints.v2.controller_connections import (
    V2_GET_CONNECTION_ALIASES_NO_TEMPLATE,
    V2_GET_CONNECTIONS_COUNT,
    V2_GET_CONNECTIONS_BY_DB_BRAND,
    V2_GET_TEMPLATES,
    V2_GET_CONNECTIONS_WITH_ROLES2,
    V2_CONNECTIONS_GET_BY_DATASET,
    V2_GET_JDBC_CONNECTIONS_SENSITIVE,
    V2_GET_REMOTE_FILE_CONNECTIONS_SENSITIVE,
    V2_GET_ARCHIVE_CONNECTIONS,
    V2_GET_CONNECTION_ALIASES,
    V2_CHECK_CORE_SPECIFIC_DRIVER,
)

ALL_DATABASE_BRANDS = [
    "HIVE",
    "DB2",
    "GCS",
    "ORACLE",
    "AZUREDATALAKE",
    "DATABRICKS",
    "NFS",
    "GENERICJDBC",
    "PG",
    "BIGQUERY",
    "SNOWFLAKE",
    "ATHENA",
    "REDSHIFT",
    "SYBASE",
    "S3",
]

ACCESS_MATRIX_CONNECTIONS = {
    V2_CONNECTIONS_GET_BY_DATASET: ACCESS_ALL,
    V2_GET_CONNECTION_ALIASES_NO_TEMPLATE: ACCESS_ALL,
    V2_GET_CONNECTIONS_COUNT: ACCESS_ALL,
    V2_GET_CONNECTIONS_BY_DB_BRAND: ACCESS_ALL,
    V2_GET_TEMPLATES: ACCESS_ALL,
    V2_GET_CONNECTIONS_WITH_ROLES2: ACCESS_ALL,
    V2_GET_JDBC_CONNECTIONS_SENSITIVE: ACCESS_ALL,
    V2_GET_REMOTE_FILE_CONNECTIONS_SENSITIVE: ACCESS_ALL,
    V2_GET_ARCHIVE_CONNECTIONS: ACCESS_ALL,
    V2_GET_CONNECTION_ALIASES: ACCESS_ALL,
    V2_CHECK_CORE_SPECIFIC_DRIVER: ACCESS_ALL,
}
