DATA_AGENT = {
    "agentUUID": 0,
    "agentId": 0,
    "agentName": "",
    "agentDisplayname": "",
    "livyHost": "",
    "owlBasePath": "/opt/owl/",
    "owlCoreJar": "/opt/owl/bin/owl-core-version.jar",
    "owlCoreLogs": "/opt/owl/log",
    "owlScript": "/opt/owl/bin/owlcheck",
    "owlWebLogs": "/opt/owl/log",
    "queueDefault": "",
    "deployModeDefault": "cluster",
    "masterDefault": "k8s://",
    "sparkConf1Key": "",
    "sparkConf1Value": "",
    "numExecutors": "1",
    "executorMemory": "1g",
    "numCores": "1",
    "driverMemory": "4g",
    "freeFormAppend": "-conf spark.executor.memoryOverhead=1g",
    "useLivy": "0",
    "isLocalAgent": "0",
    "sparkDynamicAllocationEnabled": "false",
}
