RUN_CONNECTIONS = [
    # Connections with blocking issues:
    # "cdata_mongo_up", - Connection has no table data. Shards up/down, conn string?

    # Typical connections:
    "athena_pd",
    "athena_up",
    "bigquery_key",  # Keytab
    "bigquery_key_sensitive_prop",  # Keytab
    "bigquery_pd",
    "cdata_bigquery_key",  # Keytab
    "cdata_athena_up",
    "cdata_dbrks_up",
    "dbrks_cluster_endpoint",
    "dbrks_pd",
    "dbrks_sql_endpoint",
    "dbrks_sql_hive",
    "dbrks_sql_unity_catalog",
    "db2_up",
    "dremio_up",
    "hive_kp",  # Keytab
    "hive_up",
    "impala_kp",  # Keytab
    "mysql_up",
    "oracle_kkt",  # Keytab
    "oracle_pd",
    "oracle_up",
    "postgres_pwdmgr",  # Keytab
    "postgres_up",
    "postgres_up_sensitive_prop",
    "redshift_up",
    "redshift_pd",
    "saphana_pd",
    "saphana_up",
    "snowflake_pd",
    "snowflake_up",
    "sqlserver_pd",
    "sqlserver_up",
    "sybase_up",
    "trino_up",
    "trino_pd",

    # Remote files:
    "azure_key",
    "hdfs_kt",  # Keytab
    "nfs",
    "s3_break_records",
    "s3_key",
    "https_s3_key",
    "https_s3_minio",
    "https_s3_netapp",
    "gcs",
]

EXPECTED_NOT_FOUND = {"message": None}
EXPECTED_DATABASES = {
    "athena_up": [
        {"database": ["default"]},
        {"database": ["fourth_default"]},
        {"database": ["new_default"]},
    ],
    "athena_pd": [
        {"database": ["default"]},
        {"database": ["fourth_default"]},
        {"database": ["new_default"]},
    ],
    "bigquery_pd": [
        {"database": ["321_apples"]},
        {"database": ["austin_311"]},
        {"database": ["austin_bikeshare"]},
        {"database": ["collibradq_ps"]},
        {"database": ["dq_coe_titanic"]},
        {"database": ["gcp_assets"]},
        {"database": ["google_analytics"]},
        {"database": ["google_political_ads"]},
        {"database": ["kishoretest"]},
        {"database": ["nyc_taxi_trips"]},
        {"database": ["property_sample"]},
        {"database": ["public"]},
        {"database": ["samples"]},
        {"database": ["view_dataset"]},
        {"database": ["write_eu"]},
    ],
    "cdata_bigquery_key": [
        {"database": ["321_apples"]},
        {"database": ["austin_311"]},
        {"database": ["austin_bikeshare"]},
        {"database": ["collibradq_ps"]},
        {"database": ["dq_coe_titanic"]},
        {"database": ["gcp_assets"]},
        {"database": ["google_analytics"]},
        {"database": ["google_political_ads"]},
        {"database": ["kishoretest"]},
        {"database": ["nyc_taxi_trips"]},
        {"database": ["property_sample"]},
        {"database": ["public"]},
        {"database": ["samples"]},
        {"database": ["view_dataset"]},
        {"database": ["write_eu"]},
    ],
    "bigquery_key": [
        {"database": ["321_apples"]},
        {"database": ["austin_311"]},
        {"database": ["austin_bikeshare"]},
        {"database": ["collibradq_ps"]},
        {"database": ["dq_coe_titanic"]},
        {"database": ["gcp_assets"]},
        {"database": ["google_analytics"]},
        {"database": ["google_political_ads"]},
        {"database": ["kishoretest"]},
        {"database": ["nyc_taxi_trips"]},
        {"database": ["property_sample"]},
        {"database": ["public"]},
        {"database": ["samples"]},
        {"database": ["view_dataset"]},
        {"database": ["write_eu"]},
    ],
    "bigquery_key_sensitive_prop": [
        {"database": ["321_apples"]},
        {"database": ["austin_311"]},
        {"database": ["austin_bikeshare"]},
        {"database": ["collibradq_ps"]},
        {"database": ["dq_coe_titanic"]},
        {"database": ["gcp_assets"]},
        {"database": ["google_analytics"]},
        {"database": ["google_political_ads"]},
        {"database": ["kishoretest"]},
        {"database": ["nyc_taxi_trips"]},
        {"database": ["property_sample"]},
        {"database": ["public"]},
        {"database": ["samples"]},
        {"database": ["view_dataset"]},
        {"database": ["write_eu"]},
    ],
    "cdata_athena_up": [
        {"database": ["default"]},
        {"database": ["fifth_default"]},
        {"database": ["fourth_default"]},
        {"database": ["third_default"]},
    ],
    "cdata_dbrks_up": [
        {"database": ["data"]},
        {"database": ["default"]},
        {"database": ["mydb_tv"]},
        {"database": ["public"]},
        {"database": ["tpcds_sf10000_delta"]},
        {"database": ["tpcds_sf100_delta"]},
    ],
    "cdata_mongo_up": [{"database": ["sample_analytics"]}],
    "dbrks_cluster_endpoint": [
        {"database": ["data"]},
        {"database": ["default"]},
        {"database": ["global_temp"]},
        {"database": ["nyctaxi"]},
        {"database": ["public"]},
        {"database": ["tpcds_sf10000_delta"]},
        {"database": ["tpcds_sf100_delta"]},
        {"database": ["tpch"]},
    ],
    "dbrks_pd": [
        {"database": ["default"]},
        {"database": ["global_temp"]},
        {"database": ["magneto"]},
        {"database": ["public"]},
        {"database": ["test"]},
    ],
    "dbrks_sql_endpoint": [
        {"database": ["default"]},
        {"database": ["global_temp"]},
        {"database": ["magneto"]},
        {"database": ["public"]},
        {"database": ["test"]},
    ],
    "dbrks_sql_hive": [
        {"database": ["access"]},
        {"database": ["data"]},
        {"database": ["default"]},
        {"database": ["global_temp"]},
        {"database": ["lineage"]},
        {"database": ["magneto"]},
        {"database": ["mydb_tv"]},
        {"database": ["nyctaxi"]},
        {"database": ["public"]},
        {"database": ["test"]},
        {"database": ["tpcds_sf10000_delta"]},
        {"database": ["tpcds_sf100_delta"]},
        {"database": ["tpch"]},
    ],
    "dbrks_sql_unity_catalog": [
        {"database": ["default"]},
        {"database": ["global_temp"]},
        {"database": ["magneto"]},
        {"database": ["public"]},
        {"database": ["test"]},
    ],
    "db2_up": [
        {"database": ["NULLID"]},
        {"database": ["OWLDB2"]},
        {"database": ["SQLJ"]},
        {"database": ["SYSCAT"]},
        {"database": ["SYSFUN"]},
        {"database": ["SYSIBM"]},
        {"database": ["SYSIBMADM"]},
        {"database": ["SYSIBMINTERNAL"]},
        {"database": ["SYSIBMTS"]},
        {"database": ["SYSPROC"]},
        {"database": ["SYSPUBLIC"]},
        {"database": ["SYSSTAT"]},
        {"database": ["SYSTOOLS"]},
    ],
    "dremio_up": [
        {"database": ["$scratch"]},
        {"database": ["@admin"]},
        {"database": ["@test"]},
        {"database": ["collibra"]},
        {"database": ["collibra.data"]},
        {"database": ["collibra.demo"]},
        {"database": ["INFORMATION_SCHEMA"]},
        {"database": ["myspace"]},
        {"database": ["myspace.MyParquet"]},
        {"database": ["pg"]},
        {"database": ["pg.public"]},
        {"database": ["postgres-cloud"]},
        {"database": ["postgres-cloud.public"]},
        {"database": ["Samples"]},
        {"database": ["Samples.samples.dremio.com"]},
        {"database": ["Samples.samples.dremio.com.Dremio University"]},
        {"database": ["sys"]},
        {"database": ["sys.cache"]},
    ],
    "hive_kp": [
        {"database": ["default"]},
        {"database": ["information_schema"]},
        {"database": ["sys"]},
    ],
    "hive_up": [
        {"database": ["automation"]},
        {"database": ["db1"]},
        {"database": ["db2"]},
        {"database": ["default"]},
    ],
    "impala_kp": [
        {"database": ["_impala_builtins"]},
        {"database": ["default"]},
    ],
    "mysql_up": [
        {"database": ["information_schema"]},
        {"database": ["lake"]},
        {"database": ["mysql"]},
        {"database": ["performance_schema"]},
        {"database": ["public"]},
        {"database": ["sys"]},
    ],
    "oracle_kkt": [
        {"database": ["ANONYMOUS"]},
        {"database": ["APPQOSSYS"]},
        {"database": ["AUDSYS"]},
        {"database": ["CDQ_USER"]},
        {"database": ["CDQ_USER@DQ.CP.COLLIBRA.DEV"]},
        {"database": ["CTXSYS"]},
        {"database": ["DBSFWUSER"]},
        {"database": ["DBSNMP"]},
        {"database": ["DIP"]},
        {"database": ["DVF"]},
        {"database": ["DVSYS"]},
        {"database": ["GGSYS"]},
        {"database": ["GSMADMIN_INTERNAL"]},
        {"database": ["GSMCATUSER"]},
        {"database": ["GSMROOTUSER"]},
        {"database": ["GSMUSER"]},
        {"database": ["LBACSYS"]},
        {"database": ["MDDATA"]},
        {"database": ["MDSYS"]},
        {"database": ["OJVMSYS"]},
        {"database": ["OLAPSYS"]},
        {"database": ["ORACLE_OCM"]},
        {"database": ["ORDDATA"]},
        {"database": ["ORDPLUGINS"]},
        {"database": ["ORDSYS"]},
        {"database": ["OUTLN"]},
        {"database": ["OWLUSER"]},
        {"database": ["REMOTE_SCHEDULER_AGENT"]},
        {"database": ["SI_INFORMTN_SCHEMA"]},
        {"database": ["SYS"]},
        {"database": ["SYS$UMF"]},
        {"database": ["SYSBACKUP"]},
        {"database": ["SYSDG"]},
        {"database": ["SYSKM"]},
        {"database": ["SYSRAC"]},
        {"database": ["SYSTEM"]},
        {"database": ["WMSYS"]},
        {"database": ["XDB"]},
        {"database": ["XS$NULL"]},
    ],
    "oracle_up": [
        {"database": ["ANONYMOUS"]},
        {"database": ["APPQOSSYS"]},
        {"database": ["AUDSYS"]},
        {"database": ["DBSNMP"]},
        {"database": ["DIP"]},
        {"database": ["GEHC"]},
        {"database": ["GSMADMIN_INTERNAL"]},
        {"database": ["GSMCATUSER"]},
        {"database": ["GSMUSER"]},
        {"database": ["KRBKEY"]},
        {"database": ["KRBPASS"]},
        {"database": ["KRBTGT"]},
        {"database": ["ORACLE_OCM"]},
        {"database": ["OUTLN"]},
        {"database": ["OWLUSER"]},
        {"database": ["SYS"]},
        {"database": ["SYSBACKUP"]},
        {"database": ["SYSDG"]},
        {"database": ["SYSKM"]},
        {"database": ["SYSTEM"]},
        {"database": ["USER2"]},
        {"database": ["XDB"]},
        {"database": ["XS$NULL"]},
    ],
    "postgres_pwdmgr": [
        {"database": ["berka"]},
        {"database": ["demo"]},
        {"database": ["hx"]},
        {"database": ["information_schema"]},
        {"database": ["many_tables"]},
        {"database": ["mgd"]},
        {"database": ["owl_test"]},
        {"database": ["pg_catalog"]},
        {"database": ["platts"]},
        {"database": ["public"]},
        {"database": ["S`PEC!@L::CH.AR;i..[schema]"]},
        {"database": ["S`PEC!AL::CH.AR;i\\\\[schema]"]},
        {"database": ["samples"]},
    ],
    "postgres_up": [
        {"database": ["berka"]},
        {"database": ["demo"]},
        {"database": ["owl_test"]},
        {"database": ["pg_catalog"]},
        {"database": ["public"]},
        {"database": ["S`PEC!@L::CH.AR;i..[schema]"]},
        {"database": ["S`PEC!AL::CH.AR;i\\\\[schema]"]},
        {"database": ["samples"]},
        {"database": ["test"]},
    ],
    "postgres_up_sensitive_prop": [
        {"database": ["berka"]},
        {"database": ["demo"]},
        {"database": ["owl_test"]},
        {"database": ["pg_catalog"]},
        {"database": ["public"]},
        {"database": ["S`PEC!@L::CH.AR;i..[schema]"]},
        {"database": ["S`PEC!AL::CH.AR;i\\\\[schema]"]},
        {"database": ["samples"]},
        {"database": ["test"]},
    ],
    "redshift_up": [
        {"database": ["bitoolstest"]},
        {"database": ["catalog_history"]},
        {"database": ["information_schema"]},
        {"database": ["myspectrum_schema"]},
        {"database": ["myspectrum_schema1"]},
        {"database": ["pg_automv"]},
        {"database": ["pg_catalog"]},
        {"database": ["pg_internal"]},
        {"database": ["public"]},
        {"database": ["s3dataschema"]},
        {"database": ["schema1_200tables_50columns"]},
        {"database": ["schema2_1000tables_50columns"]},
        {"database": ["schema3_10000tables_50columns"]},
        {"database": ["tvspectrum_schema"]},
    ],
    "redshift_pd": [
        {"database": ["bitoolstest"]},
        {"database": ["catalog_history"]},
        {"database": ["information_schema"]},
        {"database": ["myspectrum_schema"]},
        {"database": ["myspectrum_schema1"]},
        {"database": ["pg_automv"]},
        {"database": ["pg_catalog"]},
        {"database": ["pg_internal"]},
        {"database": ["public"]},
        {"database": ["s3dataschema"]},
        {"database": ["schema1_200tables_50columns"]},
        {"database": ["schema2_1000tables_50columns"]},
        {"database": ["schema3_10000tables_50columns"]},
        {"database": ["tvspectrum_schema"]},
    ],
    "saphana_pd": [
        {"database": ["TEST"]},
    ],
    "saphana_up": [
        {"database": ["TEST"]},
    ],
    "snowflake_pd": [
        {"database": ["AUX"]},
        {"database": ["INFORMATION_SCHEMA"]},
        {"database": ["PUBLIC"]},
        {"database": ["UNDERSCORE_TEST"]},
    ],
    "snowflake_up": [
        {"database": ["ALERT"]},
        {"database": ["AUX"]},
        {"database": ["CORE"]},
        {"database": ["EXXON_SCHEMA"]},
        {"database": ["INFORMATION_SCHEMA"]},
        {"database": ["ML"]},
        {"database": ["OWLHUB"]},
        {"database": ["PUBLIC"]},
        {"database": ["TEST_SCHEMA"]},
        {"database": ["TPCH_SF1"]},
        {"database": ["TPCH_SF10"]},
        {"database": ["TPCH_SF100"]},
        {"database": ["TPCH_SF1000"]},
        {"database": ["UNDERSCORE_TEST"]},
    ],
    "sqlserver_up": [
        {"database": ["db_accessadmin"]},
        {"database": ["db_backupoperator"]},
        {"database": ["db_datareader"]},
        {"database": ["db_datawriter"]},
        {"database": ["db_ddladmin"]},
        {"database": ["db_denydatareader"]},
        {"database": ["db_denydatawriter"]},
        {"database": ["db_owner"]},
        {"database": ["db_securityadmin"]},
        {"database": ["dbo"]},
        {"database": ["guest"]},
        {"database": ["INFORMATION_SCHEMA"]},
        {"database": ["sys"]},
    ],
    "sybase_up": [
        {"database": ["dbo"]},
        {"database": ["dtm_tm_role"]},
        {"database": ["guest"]},
        {"database": ["ha_role"]},
        {"database": ["hadr_admin_role_gp"]},
        {"database": ["js_admin_role"]},
        {"database": ["js_client_role"]},
        {"database": ["js_user_role"]},
        {"database": ["keycustodian_role"]},
        {"database": ["messaging_role"]},
        {"database": ["mon_role"]},
        {"database": ["navigator_role"]},
        {"database": ["oper_role"]},
        {"database": ["probe"]},
        {"database": ["public"]},
        {"database": ["ReadOnly"]},
        {"database": ["ReadOnlyUser"]},
        {"database": ["replication_maint_role_gp"]},
        {"database": ["replication_role"]},
        {"database": ["sa_role"]},
        {"database": ["sa_serverprivs_role"]},
        {"database": ["sso_role"]},
        {"database": ["sybase_ts_role"]},
        {"database": ["usedb_user"]},
        {"database": ["webservices_role"]},
    ],
    "trino_up": [
        {"database": ["burstbank"]},
        {"database": ["demo"]},
    ],
    "trino_pd": [
        {"database": ["burstbank"]},
        {"database": ["demo"]},
    ],
    "azure_key": [{"database": ["abfs://azure-datasets@storagedq.dfs.core.windows.net/"]}],
    "gcs": [{"database": ["gs://owl-bucket"]}],
    "hdfs_kt": [
        {"database": ["hdfs://cdp-master-01.us-central1-a.c.owl-hadoop-cdh.internal:8020/"]}
    ],
    "nfs": [{"database": ["/opt/owl/data-packs/"]}],
    "s3_break_records": [{"database": ["s3://s3-owltest/archiveBreaks"]}],
    "s3_key": [{"database": ["s3://s3-datasets"]}],
    "https_s3_key": [{"database": ["s3://s3-datasets"]}],
    "https_s3_minio": [{"database": ["cdq-sample-datasets"]}],
    "https_s3_netapp": [{"database": ["collibradq"]}],
}
EXPECTED_TABLE_MAPS = {
    "athena_up": {
        "default": [
            {"table": "a_rule_breaks"},
            {"table": "a_rule_multiple_breaks"},
            {"table": "accounts"},
            {"table": "aclaims_master"},
            {"table": "austin_crime"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "claims_detail"},
            {"table": "claims_ids"},
            {"table": "claims_letter_orders"},
            {"table": "claims_master"},
            {"table": "customer_id"},
            {"table": "customers"},
            {"table": "dataclasses"},
            {"table": "decimal_test"},
            {"table": "decimal_test_parquet"},
            {"table": "dq_outlier_sample"},
            {"table": "nyse"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "price_history_nasdaq"},
            {"table": "price_history_nyse"},
            {"table": "process_manuf_order"},
            {"table": "rule_breaks"},
            {"table": "sales"},
            {"table": "special-character"},
            {"table": "test_data_types"},
            {"table": "test_rule_repo"},
        ]
    },
    "athena_pd": {
        "default": [
            {"table": "a_rule_breaks"},
            {"table": "a_rule_multiple_breaks"},
            {"table": "accounts"},
            {"table": "aclaims_master"},
            {"table": "amex_default_predictions"},
            {"table": "assets"},
            {"table": "attributes"},
            {"table": "austin_crime"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "bloomberg"},
            {"table": "claims_detail"},
            {"table": "claims_ids"},
            {"table": "claims_letter_orders"},
            {"table": "claims_master"},
            {"table": "customer_id"},
            {"table": "customers"},
            {"table": "dataclasses"},
            {"table": "decimal_test"},
            {"table": "decimal_test_parquet"},
            {"table": "dq_outlier_sample"},
            {"table": "nyse"},
            {"table": "nyse_categorical"},
        ]
    },
    "bigquery_key": {
        "austin_bikeshare": [
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
        ]
    },
    "bigquery_key_sensitive_prop": {
        "austin_bikeshare": [
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
        ]
    },
    "cdata_bigquery_key": {
        "austin_bikeshare": [
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
        ]
    },
    "bigquery_pd": {
        "austin_bikeshare": [
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
        ]
    },
    "cdata_athena_up": {"default": []},
    "cdata_dbrks_up": {
        "default": [
            {"table": "aclaims_master"},
            {"table": "austin_crime"},
            {"table": "blockchain_transactions"},
            {"table": "business_reporting"},
            {"table": "customers"},
            {"table": "databricks_blacklisted_types_test"},
            {"table": "employees"},
            {"table": "expense_data"},
            {"table": "expense_employee_reference"},
            {"table": "flight_data"},
            {"table": "images"},
            {"table": "iowa_liquor_sales3"},
            {"table": "ms_trade"},
            {"table": "nyse"},
            {"table": "sales"},
            {"table": "us_airports"},
        ]
    },
    "cdata_mongo_up": {},
    "dbrks_cluster_endpoint": {
        "default": [
            {"table": "aclaims_master"},
            {"table": "austin_crime"},
            {"table": "blockchain_transactions"},
            {"table": "business_reporting"},
            {"table": "customers"},
            {"table": "databricks_blacklisted_types_test"},
            {"table": "employees"},
            {"table": "expense_data"},
            {"table": "expense_employee_reference"},
            {"table": "flight_data"},
            {"table": "images"},
            {"table": "iowa_liquor_sales3"},
            {"table": "ms_trade"},
            {"table": "nyse"},
            {"table": "sales"},
            {"table": "us_airports"},
        ]
    },
    "dbrks_pd": {
        "default": [
            {"table": "behaviour_empty"},
            {"table": "behaviour_min_max_check"},
            {"table": "behaviour_shift_check"},
            {"table": "behaviour_unique_check"},
            {"table": "blockchain_transactions"},
            {"table": "collibra_dq_breaks"},
            {"table": "collibra_dq_outliers"},
            {"table": "databricks_blacklisted_types_test"},
            {"table": "expense_data"},
            {"table": "expense_employee_reference"},
            {"table": "loan_customer"},
            {"table": "loans_customer_table"},
            {"table": "nyse"},
            {"table": "zip_2_state"},
        ]
    },
    "dbrks_sql_endpoint": {
        "default": [
            {"table": "behaviour_empty"},
            {"table": "behaviour_empty_1"},
            {"table": "behaviour_empty_check"},
            {"table": "behaviour_min_max_check"},
            {"table": "behaviour_shift_check"},
            {"table": "behaviour_unique_check"},
            {"table": "behaviour_unique_check_2"},
            {"table": "behaviour_unique_check_3"},
            {"table": "blockchain_transactions"},
            {"table": "collibra_dq_breaks"},
            {"table": "collibra_dq_outliers"},
            {"table": "databricks_blacklisted_types_test"},
            {"table": "expense_data"},
            {"table": "expense_employee_reference"},
            {"table": "loan_customer"},
            {"table": "loans_customer_table"},
            {"table": "nyse"},
            {"table": "zip_2_state"},
            {"table": "zip_2_state_copy"},
        ]
    },
    "dbrks_sql_hive": {
        "default": [
            {"table": "aclaims_master"},
            {"table": "austin_crime"},
            {"table": "behaviour_empty"},
            {"table": "behaviour_empty_check"},
            {"table": "behaviour_min_max_check"},
            {"table": "behaviour_shift_check"},
            {"table": "behaviour_unique_check"},
            {"table": "blockchain_transactions"},
            {"table": "business_reporting"},
            {"table": "collibra_dq_breaks"},
            {"table": "collibra_dq_outliers"},
            {"table": "customers"},
            {"table": "databricks_blacklisted_types_test"},
            {"table": "employees"},
            {"table": "expense_data"},
            {"table": "expense_employee_reference"},
            {"table": "flight_data"},
            {"table": "images"},
            {"table": "iowa_liquor_sales3"},
            {"table": "loan_customer"},
            {"table": "loans_customer_table"},
            {"table": "ms_trade"},
            {"table": "nyse"},
            {"table": "sales"},
            {"table": "us_airports"},
            {"table": "zip_2_state"},
        ]
    },
    "dbrks_sql_unity_catalog": {"default": [{"table": "nyse"}]},
    "db2_up": {
        "OWLDB2": [
            {"table": "FPG_CUSTOMER"},
            {"table": "LOAN_CUSTOMER"},
            {"table": "NAME_CAT_OUTLIERS"},
            {"table": "NYSE_STOCKS"},
            {"table": "NYSE_STOCKS_CP"},
            {"table": "RESULTSFOROWL"},
            {"table": "SYNTHETIC25"},
        ]
    },
    "dremio_up": {
        "pg.public": [
            {"table": "accounts"},
            {"table": "ACLAIMS_FILE"},
            {"table": "aclaims_master"},
            {"table": "anameaddresstest"},
            {"table": "aus_symbol_date"},
            {"table": "austin_crime"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "claims_detail"},
            {"table": "claims_ids"},
            {"table": "claims_letter_orders"},
            {"table": "dataclass_discovery"},
            {"table": "dq_outlier_sample"},
            {"table": "dupe_example"},
            {"table": "esg_data_october"},
            {"table": "factors"},
            {"table": "fakedealership"},
            {"table": "fakeemployees"},
            {"table": "iowa_liquor_sales"},
            {"table": "nyse2"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "nyse_regular"},
            {"table": "process_manuf_order"},
            {"table": "product_sales"},
            {"table": "sales_data"},
        ]
    },
    "hive_kp": {"default": [{"table": "nyse"}]},
    "hive_up": {
        "default": [
            {"table": "datetable"},
            {"table": "employees"},
            {"table": "nysetechvdb"},
            {"table": "test"},
        ]
    },
    "impala_kp": {"default": [{"table": "nyse"}]},
    "mysql_up": {"sys": [{"table": "sys_config"}]},
    "oracle_kkt": {"OWLUSER": [{"table": "NYSE"}]},
    "oracle_up": {
        "OWLUSER": [
            {"table": "5M_SALES_RECORDS_ORACLE"},
            {"table": "BUSINESS_REPORTING"},
            {"table": "CLOB_DATA_TEST"},
            {"table": "CUSTOMER"},
            {"table": "CUSTOMER_ME"},
            {"table": "CUSTOMER_SM"},
            {"table": "DATATABLE_HTML_TAG"},
            {"table": "DATESERIES"},
            {"table": "DQ342_NYSE"},
            {"table": "DT_TEST"},
            {"table": "EIM_ASSET_DTL"},
            {"table": "LOAN_CUSTOMER"},
            {"table": "MAXIMUMSCORE"},
            {"table": "NONENGLISHCHARACTERS"},
            {"table": "NYSE"},
            {"table": "NYSE_LOCAL_TZ_TEST"},
            {"table": "NYSE_TS"},
            {"table": "ROLLUP"},
            {"table": "SALES_REP"},
            {"table": "SALESDATA"},
        ]
    },
    "postgres_pwdmgr": {
        "public": [
            {"table": "accountlist"},
            {"table": "aclaims_master"},
            {"table": "aclaims_master_run"},
            {"table": "ah_currency"},
            {"table": "ah_policy"},
            {"table": "ah_product"},
            {"table": "ah_transaction"},
            {"table": "all_date_types"},
            {"table": "amex_client_profile"},
            {"table": "amex_cm_profile"},
            {"table": "atm_customer"},
            {"table": "austin_crime"},
            {"table": "austin_waste"},
            {"table": "flights"},
            {"table": "fund_performance"},
            {"table": "fund_transactions"},
            {"table": "issues"},
            {"table": "life_insurance"},
            {"table": "loan_customer"},
            {"table": "loan_database"},
            {"table": "loan_lending"},
            {"table": "nine_million_by_ninety"},
            {"table": "numeric_table"},
            {"table": "nyse"},
            {"table": "nyse_categorical"},
            {"table": "nyse_monthly_summary"},
        ]
    },
    "postgres_up_sensitive_prop": {
        "public": [
            {"table": "accountlist"},
            {"table": "aclaims_master"},
            {"table": "aclaims_master_run"},
            {"table": "ah_bindersection"},
            {"table": "ah_currency"},
            {"table": "ah_policy"},
            {"table": "ah_policybinderasoc"},
            {"table": "ah_policysection"},
            {"table": "ah_product"},
            {"table": "ah_transaction"},
            {"table": "ahx_Binder"},
            {"table": "ahx_BinderSection"},
            {"table": "ahx_Currency"},
            {"table": "ahx_Policy"},
            {"table": "all_date_types"},
            {"table": "amex_billed_transactions"},
            {"table": "amex_client_profile"},
        ]
    },
    "postgres_up": {
        "public": [
            {"table": "accountlist"},
            {"table": "aclaims_master"},
            {"table": "aclaims_master_run"},
            {"table": "ah_bindersection"},
            {"table": "ah_currency"},
            {"table": "ah_policy"},
            {"table": "ah_policybinderasoc"},
            {"table": "ah_policysection"},
            {"table": "ah_product"},
            {"table": "ah_transaction"},
            {"table": "ahx_Binder"},
            {"table": "ahx_BinderSection"},
            {"table": "ahx_Currency"},
            {"table": "ahx_Policy"},
            {"table": "all_date_types"},
            {"table": "amex_billed_transactions"},
            {"table": "amex_client_profile"},
            {"table": "amex_cm_profile"},
            {"table": "amex_unbilled_transactions"},
            {"table": "atm_customer"},
            {"table": "austin_crime"},
            {"table": "austin_waste"},
            {"table": "bank_payments"},
            {"table": "bankozk_scorecard_upload"},
            {"table": "behavior"},
            {"table": "berka_transactions"},
            {"table": "bike_data"},
            {"table": "bike_summary"},
            {"table": "nyse"},
            {"table": "nyse_categorical"},
            {"table": "sch_onesource_uk"},
            {"table": "sch_onesource_vietnam"},
            {"table": "sch_plant_country"},
            {"table": "sch_sales"},
            {"table": "sch_vu_enriched"},
            {"table": "scorecard_ozk"},
            {"table": "semantic"},
        ]
    },
    "redshift_up": {
        "public": [
            {"table": "ca_airports"},
            {"table": "ca_ga_join_airports"},
            {"table": "category"},
            {"table": "covid19_jan_2022"},
            {"table": "covid19_jan_2022_numeric"},
            {"table": "covid19_june"},
            {"table": "date"},
            {"table": "event"},
            {"table": "ga_airports"},
            {"table": "listing"},
            {"table": "matillion_dim_airports"},
            {"table": "matillion_stg_airports"},
            {"table": "matillion_us_state_lookup"},
            {"table": "measures"},
            {"table": "mockdata"},
            {"table": "movies_and_tv_shows"},
            {"table": "nyse"},
            {"table": "sales"},
            {"table": "testdata_type"},
            {"table": "testing_table"},
            {"table": "testing_ts"},
            {"table": "testrule_repo"},
            {"table": "users"},
            {"table": "venue"},
            {"table": "ztest_table"},
        ]
    },
    "redshift_pd": {
        "public": [
            {"table": "ca_airports"},
            {"table": "ca_ga_join_airports"},
            {"table": "category"},
            {"table": "covid19_jan_2022"},
            {"table": "covid19_jan_2022_numeric"},
            {"table": "covid19_june"},
            {"table": "date"},
            {"table": "event"},
            {"table": "ga_airports"},
            {"table": "listing"},
            {"table": "matillion_dim_airports"},
            {"table": "matillion_stg_airports"},
            {"table": "matillion_us_state_lookup"},
            {"table": "measures"},
            {"table": "mockdata"},
            {"table": "movies_and_tv_shows"},
            {"table": "mv_tbl__tickets_mv__0"},
            {"table": "myo_categoryattributes_v"},
            {"table": "nyse"},
            {"table": "sales"},
            {"table": "testdata_type"},
            {"table": "testing_table"},
            {"table": "testing_ts"},
            {"table": "testrule_repo"},
            {"table": "users"},
            {"table": "venue"},
            {"table": "ztest_table"},
        ]
    },
    "saphana_pd": {
        "TEST": [
            {"table": "NYSE"},
            {"table": "SALES"},
        ]
    },
    "saphana_up": {
        "TEST": [
            {"table": "NYSE"},
            {"table": "SALES"},
        ]
    },
    "snowflake_pd": {
        "PUBLIC": [
            {"table": "ACCOUNTS"},
            {"table": "ACLAIMS_MASTER"},
            {"table": "ACLAIMS_MASTER_LTD"},
            {"table": "ACLAIMS_MASTER_RUN"},
            {"table": "ANAMEADDRESSTEST"},
            {"table": "AUM_DT"},
            {"table": "AUSTIN_CRIME"},
            {"table": "AUSTIN_WASTE"},
            {"table": "BEHAVIOUR_EMPTY"},
            {"table": "BIKESHARE_STATIONS"},
            {"table": "BIKESHARE_TRIPS"},
            {"table": "BLOOMBERG3"},
            {"table": "BUSINESS_REPORTING"},
            {"table": "CDP_REGISTRY"},
            {"table": "CITIES"},
            {"table": "CLAIMS_DETAIL"},
            {"table": "CLAIMS_IDS"},
            {"table": "CLAIMS_LETTER_ORDERS"},
            {"table": "CLAIMS_MASTER"},
            {"table": "COLLIBRA_DQ_BREAKS"},
            {"table": "COLLIBRA_DQ_DUPLICATES"},
            {"table": "COLLIBRA_DQ_OUTLIERS"},
            {"table": "COLLIBRA_DQ_RULES"},
            {"table": "COLLIBRA_DQ_SHAPES"},
            {"table": "CUSTOMER_COMPLETE"},
            {"table": "CUSTOMER_ID"},
            {"table": "CUSTOMERS"},
        ]
    },
    "snowflake_up": {
        "PUBLIC": [
            {"table": "ACCOUNTS"},
            {"table": "ACCOUNTS_WCB"},
            {"table": "ACLAIMS_MASTER"},
            {"table": "ACLAIMS_MASTER_LTD"},
            {"table": "ACLAIMS_MASTER_RUN"},
            {"table": "ACTIVITY_AUDIT"},
            {"table": "ADMIN_CONFIG"},
            {"table": "ADMIN_SETTINGS"},
            {"table": "AGENT"},
            {"table": "AGENT_CONNECTION"},
            {"table": "ASSIGNMENT_Q_AUDIT"},
            {"table": "AUSTIN_CRIME"},
            {"table": "AUSTIN_WASTE"},
            {"table": "AUTHORITIES"},
            {"table": "COLLIBRA_DQ_DUPLICATES"},
            {"table": "COLLIBRA_DQ_OUTLIERS"},
            {"table": "COLLIBRA_DQ_RULES"},
            {"table": "COLLIBRA_DQ_SHAPES"},
            {"table": "FINANCIAL_DATA"},
            {"table": "FIXED_ASSETS"},
            {"table": "FIXED_INCOME_NAMR"},
            {"table": "OPT_RECORD"},
            {"table": "SALEDATA"},
            {"table": "SALES"},
            {"table": "SALES_DATA"},
            {"table": "SALESTS"},
            {"table": "SAMPLETB"},
        ]
    },
    "sqlserver_pd": {
        "dbo": [
            {"table": "accounts"},
            {"table": "ACLAIMS_MASTER"},
            {"table": "ACLAIMS_MASTER_HD"},
            {"table": "ACLAIMS_MASTER_RUN"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "NYSE_Full"},
            {"table": "nyse_regular"},
        ],
    },
    "sqlserver_up": {
        "dbo": [
            {"table": "accounts"},
            {"table": "ACLAIMS_MASTER"},
            {"table": "ACLAIMS_MASTER_HD"},
            {"table": "ACLAIMS_MASTER_RUN"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "NYSE_Full"},
            {"table": "nyse_regular"},
        ],
    },
    "sybase_up": {"guest": [{"table": "test_table"}]},
    "trino_up": {
        "public": [
            {"table": "accounts"},
            {"table": "aclaims_master"},
            {"table": "aclaims_master_ltd"},
            {"table": "aclaims_master_run"},
            {"table": "austin_crime"},
            {"table": "austin_waste"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "business_reporting"},
            {"table": "claims_detail"},
            {"table": "claims_ids"},
            {"table": "claims_letter_orders"},
            {"table": "claims_master"},
            {"table": "collibra_dq_breaks"},
            {"table": "collibra_dq_duplicates"},
            {"table": "collibra_dq_outliers"},
            {"table": "collibra_dq_rules"},
            {"table": "collibra_dq_shapes"},
            {"table": "customer_complete"},
            {"table": "customer_id"},
            {"table": "nyse"},
            {"table": "nyse_break_records"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "nyse_edited"},
            {"table": "nyse_regular"},
            {"table": "saledata"},
            {"table": "sales"},
            {"table": "sales_data"},
            {"table": "salests"},
        ]
    },
    "trino_pd": {
        "public": [
            {"table": "accounts"},
            {"table": "aclaims_master"},
            {"table": "aclaims_master_ltd"},
            {"table": "aclaims_master_run"},
            {"table": "austin_crime"},
            {"table": "austin_waste"},
            {"table": "bikeshare_stations"},
            {"table": "bikeshare_trips"},
            {"table": "business_reporting"},
            {"table": "claims_detail"},
            {"table": "claims_ids"},
            {"table": "claims_letter_orders"},
            {"table": "claims_master"},
            {"table": "collibra_dq_breaks"},
            {"table": "collibra_dq_duplicates"},
            {"table": "collibra_dq_outliers"},
            {"table": "collibra_dq_rules"},
            {"table": "collibra_dq_shapes"},
            {"table": "customer_complete"},
            {"table": "customer_id"},
            {"table": "nyse"},
            {"table": "nyse_break_records"},
            {"table": "nyse_categorical"},
            {"table": "nyse_categorical_diff"},
            {"table": "nyse_edited"},
            {"table": "nyse_regular"},
            {"table": "saledata"},
            {"table": "sales"},
            {"table": "sales_data"},
            {"table": "salests"},
        ]
    },
}
EXPECTED_REMOTE_FILES = {
    "azure_key": [
        {"dir": "OWLDB2.NYSE_STOCKS"},
        {"dir": "OWLDB2.NYSE_STOCKS_NO_ARCHIVE"},
        {"dir": "OWLUSER.NYSE_2"},
        {"dir": "TEST_DATA_FILES"},
        {"dir": "archiveBreaks"},
        {"dir": "berka.transactions_4"},
        {"dir": "kb_archive_breaks_az"},
        {"file": "nyse.csv"},
        {"dir": "samples.claim"},
        {"dir": "samples.claim_3"},
        {"dir": "samples.nyse"},
        {"dir": "samples.nyse_2"},
        {"dir": "samples.nyse_3"},
        {"dir": "test"},
        {"file": "user_data.parquet"},
    ],
    "gcs": [
        {"file": "Auto_Insurance_Claims_Sample.csv"},
        {"file": "SparkJDBC41.jar"},
        {"file": "Traffic_Violations.csv"},
        {"file": "austin_bikeshare"},
        {"file": "column_colon.csv"},
        {"file": "dateseries.csv"},
        {"file": "dblp.xml"},
        {"file": "demo_schema.dump"},
        {"file": "distribution_change.csv"},
        {"file": "dupe.csv"},
        {"file": "energy.csv"},
        {"file": "energy.json"},
        {"file": "fpg_customers.csv"},
        {"file": "loan_customer.csv"},
        {"file": "nasa.xml"},
        {"file": "nyse.csv"},
        {"file": "row_count.csv"},
        {"file": "rule_globals.csv"},
        {"file": "shape.csv"},
        {"dir": "QA/"},
        {"dir": "TEST_DATA_FILES/"},
    ],
    "hdfs_kt": [
        {"dir": "TEST_DATA_FILES"},
        {"dir": "hive"},
        {"dir": "impala"},
        {"dir": "tmp"},
        {"dir": "user"},
        {"dir": "warehouse"},
        {"dir": "yarn"},
    ],
    "nfs": [
        {"file": "connection-template.csv"},
        {"file": "data-concept.csv"},
        {"file": "semantic-sensitivity.csv"},
        {"file": "rule-repo.csv"},
    ],
    "s3_break_records": [
        {"file": "archiveBreaks/price_history.csv"},
        {"dir": "archiveBreaks/2019_01_10_csv_1_GCS/"},
        {"dir": "archiveBreaks/JP_ARCHIVE_BREAK_SNOWFLAKE_PULLUP/"},
        {"dir": "archiveBreaks/JP_ARCHIVE_samples.12_leading_numeric_column_names/"},
        {"dir": "archiveBreaks/JP_CRDBRC_S3_TEST_DATA_FILES_nyse_csv001/"},
        {"dir": "archiveBreaks/JP_K8_S3_ARCHIVE_TEST_DATA_FILES_nyse_csv_001/"},
        {"dir": "archiveBreaks/JP_LINKID_DB2_POSTGRES_OWLDB2.NYSE_STOCKS_001/"},
        {"dir": "archiveBreaks/JP_LINK_IDTEST_DATA_FILES_nyse_csv_1/"},
        {"dir": "archiveBreaks/JP_ORACLE_OWLUSER.NYSE_2/"},
        {"dir": "archiveBreaks/JP_POSTGRES_BREAK_RECORDS/"},
        {"dir": "archiveBreaks/JP_samples.nyse_3/"},
        {"dir": "archiveBreaks/MEGA_berka.transactions_2/"},
        {"dir": "archiveBreaks/PUBLIC.NYSE_linkidchk/"},
        {"dir": "archiveBreaks/S3_Write_Multiple_Rules/"},
        {"dir": "archiveBreaks/berka.accounts/"},
        {"dir": "archiveBreaks/kb_PUBLIC.ACCOUNTS_PARENT/"},
        {"dir": "archiveBreaks/owl_test.loan_customer/"},
        {"dir": "archiveBreaks/s3_multiple_rules_fail_sp/"},
        {"dir": "archiveBreaks/samples.nyse/"},
        {"dir": "archiveBreaks/samples.nyse_5/"},
        {"dir": "archiveBreaks/test_multiple_rules_final/"},
    ],
    "s3_key": [
        {"file": "1000_cols.csv"},
        {"file": "100_cols.csv"},
        {"file": "150_cols.csv"},
        {"file": "200_cols.csv"},
        {"file": "2014_Financial_Data.csv"},
        {"file": "2015_Financial_Data.csv"},
        {"file": "2016_Financial_Data.csv"},
        {"file": "2017_Financial_Data.csv"},
        {"file": "2018_Financial_Data.csv"},
        {"file": "250_cols.csv"},
        {"file": "350_cols.csv"},
        {"file": "500_cols.csv"},
        {"dir": "ACLAIMS_MASTER/"},
        {"dir": "ACLAIMS_MASTER_RUN/"},
        {"dir": "BQ_ARCHIVE_RULE_BREAK_S3_samples.sales_data/"},
        {"dir": "BREAK_RECORDS/"},
        {"dir": "CLAIMS_IDS/"},
        {"dir": "austin_crime/"},
        {"dir": "bikeshare_stations/"},
        {"dir": "bikeshare_trips/"},
    ],
    "https_s3_key": [
        {"file": "1000_cols.csv"},
        {"file": "100_cols.csv"},
        {"file": "150_cols.csv"},
        {"file": "200_cols.csv"},
        {"file": "2014_Financial_Data.csv"},
        {"file": "2015_Financial_Data.csv"},
        {"file": "2016_Financial_Data.csv"},
        {"file": "2017_Financial_Data.csv"},
        {"file": "2018_Financial_Data.csv"},
        {"file": "250_cols.csv"},
        {"file": "350_cols.csv"},
        {"file": "500_cols.csv"},
        {"dir": "ACLAIMS_MASTER/"},
        {"dir": "ACLAIMS_MASTER_RUN/"},
        {"dir": "BQ_ARCHIVE_RULE_BREAK_S3_samples.sales_data/"},
        {"dir": "BREAK_RECORDS/"},
        {"dir": "CLAIMS_IDS/"},
        {"dir": "austin_crime/"},
        {"dir": "bikeshare_stations/"},
        {"dir": "bikeshare_trips/"},
    ],
    "https_s3_minio": [
        {"file": "covid19_timeseries_us_all_june_26.snappy.parquet"},
        {"dir": "TEST_DATA_FILES/"},
    ],
    "https_s3_netapp": [
        {"file": "a_test.csv"},
        {"dir": "JP_ORACLE_NETAPP/"},
    ],
}
