from payloads.pushdown.rules.pl_pd_rs_rules_basic import PD_RS_RULES_BASIC_DATASET

PD_RS_RULES_BASIC_RULE_DEFINITIONS = [
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "FF_exception",
        "ruleType": "SQLF",
        "ruleValue": "This rule will cause an exception.",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": "Unexpected exception: \"ERROR: syntax error at or near \"will\" in context "
                     "\"(This rule will\", at line 1   Position: 69\"",
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "if_zip_code_is_NULLCHECK",
        "ruleType": "NULLCHECK",
        "ruleValue": "zip_code",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "zip_code",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "stat_rule",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_RS_RULES_BASIC_DATASET} WHERE $rowCount > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "if_gender_is_GENDER",
        "ruleType": "CUSTOM",
        "ruleValue": "gender",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "GENDER",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "gender",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "FF_long",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_RS_RULES_BASIC_DATASET} WHERE auto_year = 2001",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_RS_RULES_BASIC_DATASET,
        "ruleNm": "SIMPLE_STRING",
        "ruleType": "SQLG",
        "ruleValue": "auto_make = 'Ford'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    }
]

PD_RS_RULES_BASIC_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "stat_rule",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from public.customers) WHERE 1044 > 1000",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1585991,
                "uuid": "435bdf5a-23a8-4e66-8324-cfbcbe9d1161"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_RS_RULES_BASIC_DATASET} WHERE $rowCount > 1000",
            "totalCount": 1044,
            "rowsBreaking": 1044,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "SIMPLE_STRING",
            "ruleType": "SQLG",
            "ruleValue": "auto_make = 'Ford'",
            "filterQuery": None,
            "score": 8,
            "perc": 8.237547892720306,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1585992,
                "uuid": "43c15cdb-d4d6-4926-9518-37c350dbb705"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "auto_make = 'Ford'",
            "totalCount": 1044,
            "rowsBreaking": 86,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "if_zip_code_is_NULLCHECK",
            "ruleType": "NULLCHECK",
            "ruleValue": "zip_code",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1585995,
                "uuid": "d6ec188e-9f9f-4bdb-8c0d-4921765ad02b"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "zip_code",
            "totalCount": 1044,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "if_gender_is_GENDER",
            "ruleType": "CUSTOM",
            "ruleValue": "not \"gender\" ~ '^(m|M|male|Male|MALE|f|F|female|Female|FEMALE)$'",
            "filterQuery": None,
            "score": 2,
            "perc": 2.203065134099617,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1585990,
                "uuid": "6dfdd99a-1a73-44ce-b5c8-1125886825ab"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "gender",
            "totalCount": 1044,
            "rowsBreaking": 23,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "FF_long",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from public.customers) WHERE auto_year = 2001",
            "filterQuery": None,
            "score": 4,
            "perc": 4.597701149425287,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1585994,
                "uuid": "8901b9b6-33b6-4ffd-9495-489f061afbc6"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_RS_RULES_BASIC_DATASET} WHERE auto_year = 2001",
            "totalCount": 1044,
            "rowsBreaking": 48,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_RS_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "FF_exception",
            "ruleType": "SQLF",
            "ruleValue": "This rule will cause an exception.",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "Unexpected exception: \"ERROR: syntax error at or near \"will\" in "
                         "context \"(This rule will\", at line 1   Position: 69\"",
            "owlId": "1",
            "breakMsg": "EXCEPTION",
            "assignmentId": {
                "id": 1585993,
                "uuid": "025a6c43-cc87-47db-9571-a1ed4144c57c"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "This rule will cause an exception.",
            "totalCount": 1044,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": None
        }
    ]
}
