from payloads.pushdown.rules.pl_pd_sf_rules_filter_tolerance_sales import (
    PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
)

PD_SF_RULES_FILTER_TOLERANCE_SALES_RULE_DEFINITIONS = [
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_filter_and_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "SALES > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "NAME = 'Steve'",
        "tolerance": 30,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_no_filter",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_filter",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "SALES = 1000",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_no_filter",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_filter",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "SALES = 1000",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_breaking_rows_above_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 10,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_breaking_rows_below_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 30,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_breaking_rows_above_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 10,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_breaking_rows_below_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 50,
        "active": True
    },
    {
        "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_filter_and_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE SALES > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "NAME = 'Steve'",
        "tolerance": 30,
        "active": True
    }
]

PD_SF_RULES_FILTER_TOLERANCE_SALES_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_filter_and_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "SALES > 1000",
            "filterQuery": "NAME = 'Steve'",
            "score": 0,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1655946,
                "uuid": "01ebbd8a-39ac-4187-be47-ba1505321b26"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "SALES > 1000",
            "totalCount": 5,
            "rowsBreaking": 1,
            "tolerance": 30,
            "ruleStatus": None
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_no_filter",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-01'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601813,
                "uuid": "78a69995-4945-4498-a0c7-541b79610f72"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-01'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_filter",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-01'",
            "filterQuery": "SALES = 1000",
            "score": 50,
            "perc": 50.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601808,
                "uuid": "b51aab29-5900-4b58-b7d6-4c4066e7fd0c"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-01'",
            "totalCount": 2,
            "rowsBreaking": 1,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_breaking_rows_below_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 0,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601807,
                "uuid": "e5582e9d-178c-472b-b61e-8a8276f452ff"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 30,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_breaking_rows_above_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601811,
                "uuid": "2e6a4afc-1850-4375-a38d-d8c7b54345fd"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 10,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_no_filter",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from PUBLIC.SALES) WHERE TRDATE = '2022-05-01'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601816,
                "uuid": "5f214207-02a9-4009-ab04-802aa8ece789"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-01'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_filter_and_tolerance",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from (select * from PUBLIC.SALES) "
                         "where NAME = 'Steve') WHERE SALES > 1000",
            "filterQuery": "NAME = 'Steve'",
            "score": 0,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601809,
                "uuid": "f0177e91-b64f-49ce-9fd0-a550cd001f4f"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE SALES > 1000",
            "totalCount": 5,
            "rowsBreaking": 1,
            "tolerance": 30,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_filter",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from (select * from PUBLIC.SALES) "
                         "where SALES = 1000) WHERE TRDATE = '2022-05-01'",
            "filterQuery": "SALES = 1000",
            "score": 50,
            "perc": 50.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601814,
                "uuid": "7f76ce35-c045-4dde-a127-4a8fc977bf00"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-01'",
            "totalCount": 2,
            "rowsBreaking": 1,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_breaking_rows_below_tolerance",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from PUBLIC.SALES) WHERE TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 0,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601815,
                "uuid": "f7fbf461-a819-4804-98b3-1fb5490d704a"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 50,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_breaking_rows_above_tolerance",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from PUBLIC.SALES) WHERE TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601819,
                "uuid": "7d588844-4303-4b66-ba7b-ec7b6f0403f1"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_SF_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 10,
            "ruleStatus": "BREAKING"
        }
    ]
}

PD_SF_RULES_FILTER_TOLERANCE_SALES_FF_FILTER_AND_TOLERANCE_EXPECTED_RULE_DATA_PREVIEW = {
    "draw": 1,
    "recordsTotal": 1,
    "recordsFiltered": 1,
    "dataAssetList": [
        {
            "NAME": "Steve",
            "SALES": "10000",
            "TRDATE": "2022-05-05"
        }
    ],
    "data": None
}
