from payloads.pushdown.rules.pl_pd_mssql_rules_basic import PD_MSSQL_RULES_BASIC_DATASET

PD_MSSQL_RULES_BASIC_RULE_DEFINITIONS = [
    {
        "dataset": PD_MSSQL_RULES_BASIC_DATASET,
        "ruleNm": "if_zip_code_is_NULL",
        "ruleType": "NULLCHECK",
        "ruleValue": "zip_code",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "zip_code",
        "businessCategory": None,
        "businessDesc": None,
        "dimId": 1,
        "dimName": "COMPLETENESS",
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_MSSQL_RULES_BASIC_DATASET,
        "ruleNm": "FF_long",
        "ruleType": "SQLF",
        "ruleValue": "select * from dbo.customers where auto_year = 2001",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "condition,rules,not,valid",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_MSSQL_RULES_BASIC_DATASET,
        "ruleNm": "SIMPLE_STRING",
        "ruleType": "SQLG",
        "ruleValue": "auto_make = 'Ford'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "condition,rules,not,valid",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    }
]

PD_MSSQL_RULES_BASIC_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PD_MSSQL_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "SIMPLE_STRING",
            "ruleType": "SQLG",
            "ruleValue": "auto_make = 'Ford'",
            "filterQuery": None,
            "score": 8,
            "perc": 8.237547892720306,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586075,
                "uuid": "b6bb4a99-dadd-4aa9-9a33-00122c6ebaa2"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "auto_make = 'Ford'",
            "totalCount": 1044,
            "rowsBreaking": 86,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_MSSQL_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "if_zip_code_is_NULL",
            "ruleType": "NULLCHECK",
            "ruleValue": "zip_code",
            "filterQuery": None,
            "score": 48,
            "perc": 48.85057471264368,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586074,
                "uuid": "b13f9851-0910-43c8-aa34-343a03a0583b"
            },
            "dimId": 1,
            "dimName": "COMPLETENESS",
            "ruleCondition": "zip_code",
            "totalCount": 1044,
            "rowsBreaking": 510,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_MSSQL_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "FF_long",
            "ruleType": "SQLF",
            "ruleValue": "select * from dbo.customers where auto_year = 2001",
            "filterQuery": None,
            "score": 4,
            "perc": 4.597701149425287,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586076,
                "uuid": "12db2abc-07d1-41e9-b39f-15b460a6317e"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from dbo.customers where auto_year = 2001",
            "totalCount": 1044,
            "rowsBreaking": 48,
            "tolerance": 0,
            "ruleStatus": None
        }
    ]
}
