from payloads.pushdown.rules.pl_pd_trino_rules_basic import PD_TRINO_RULES_BASIC_DATASET

PD_TRINO_RULES_BASIC_RULE_DEFINITIONS = [
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "FF_exception",
        "ruleType": "SQLF",
        "ruleValue": "This rule will cause an exception.",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": "Unexpected exception: \"Query failed (#20241031_205417_05883_c3a4m): "
                     "line 1:69: mismatched input 'will'. Expecting: '(', ')', 'CROSS', 'FULL', "
                     "'INNER', 'JOIN', 'LEFT', 'MATCH_RECOGNIZE', 'NATURAL', 'RIGHT', "
                     "'TABLESAMPLE'\"",
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "if_zip_code_is_NULLCHECK",
        "ruleType": "NULLCHECK",
        "ruleValue": "zip_code",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "zip_code",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "stat_rule",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_TRINO_RULES_BASIC_DATASET} WHERE $rowCount > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "if_gender_is_GENDER",
        "ruleType": "CUSTOM",
        "ruleValue": "gender",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "GENDER",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "gender",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "FF_long",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PD_TRINO_RULES_BASIC_DATASET} WHERE auto_year = 2001",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PD_TRINO_RULES_BASIC_DATASET,
        "ruleNm": "SIMPLE_STRING",
        "ruleType": "SQLG",
        "ruleValue": "auto_make = 'Ford'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    }
]

PD_TRINO_RULES_BASIC_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "stat_rule",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from public.customers) WHERE 1044 > 1000",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586096,
                "uuid": "8768b2c6-b8bb-47cb-b16b-abf0fa889f2d"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_TRINO_RULES_BASIC_DATASET} "
                             f"WHERE $rowCount > 1000",
            "totalCount": 1044,
            "rowsBreaking": 1044,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "SIMPLE_STRING",
            "ruleType": "SQLG",
            "ruleValue": "auto_make = 'Ford'",
            "filterQuery": None,
            "score": 8,
            "perc": 8.237547892720306,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586098,
                "uuid": "10a27561-2cec-4647-aaef-ad7365e9f219"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "auto_make = 'Ford'",
            "totalCount": 1044,
            "rowsBreaking": 86,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "if_zip_code_is_NULLCHECK",
            "ruleType": "NULLCHECK",
            "ruleValue": "zip_code",
            "filterQuery": None,
            "score": 48,
            "perc": 48.85057471264368,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586099,
                "uuid": "82ae9085-c70b-4585-9081-938c03bd8b0e"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "zip_code",
            "totalCount": 1044,
            "rowsBreaking": 510,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "if_gender_is_GENDER",
            "ruleType": "CUSTOM",
            "ruleValue": "gender",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1586101,
                "uuid": "e17b100a-0182-44d6-8226-f2eb94e13448"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "gender",
            "totalCount": 1044,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "FF_long",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * FROM (select * from public.customers) WHERE auto_year = 2001",
            "filterQuery": None,
            "score": 4,
            "perc": 4.597701149425287,
            "exception": None,
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1586100,
                "uuid": "f6cb24a1-a5b0-476c-8d14-76f5937d0112"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PD_TRINO_RULES_BASIC_DATASET} "
                             f"WHERE auto_year = 2001",
            "totalCount": 1044,
            "rowsBreaking": 48,
            "tolerance": 0,
            "ruleStatus": None
        },
        {
            "dataset": PD_TRINO_RULES_BASIC_DATASET,
            "runId": "2024-10-31T00:00:00.000+0000",
            "ruleNm": "FF_exception",
            "ruleType": "SQLF",
            "ruleValue": "This rule will cause an exception.",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "Unexpected exception: \"Query failed (#20241031_205417_05883_c3a4m): "
                         "line 1:69: mismatched input 'will'. Expecting: '(', ')', 'CROSS', "
                         "'FULL', 'INNER', 'JOIN', 'LEFT', 'MATCH_RECOGNIZE', 'NATURAL', 'RIGHT', "
                         "'TABLESAMPLE'\"",
            "owlId": "1",
            "breakMsg": "EXCEPTION",
            "assignmentId": {
                "id": 1586097,
                "uuid": "a054a248-20f1-4c26-ae72-e4e5b07c31d6"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "This rule will cause an exception.",
            "totalCount": 1044,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": None
        }
    ]
}
