from payloads.pushdown.outliers.pl_pd_dbrks_outliers_cat_key_nodate_nyse_archive_breaks import (
    PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
)

PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_EXPECTED_OUTLIERS = {
    "data": [
        {
            "id": 451,
            "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
            "runId": "2023-09-10T00:00:00.000+0000",
            "outKeyColumn": "EXCH",
            "outKey": "082sPD1zLaNhTsjLBdIR6Vum1Kg3jlNE2SsWua4tbDaalaP1mCOzH0I1NNTfPx+N",
            "outColumn": "SYMBOL",
            "outValue": "LBRT",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 2,
            "keyArr": [
                "NYSE"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "NYSE~|LBRT~|2018-01-16",
            "linkIdArr": [
                "2018-01-16",
                "NYSE",
                "LBRT"
            ],
            "assignmentId": {
                "id": 2226,
                "uuid": "b959180a-c42f-40be-bd35-bffad8bdc5ec"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        },
        {
            "id": 450,
            "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
            "runId": "2023-09-10T00:00:00.000+0000",
            "outKeyColumn": "EXCH",
            "outKey": "U1hRnZtCKr2V6PBdPtGcUm1UQJVQq7xH8Iq9fCnDoQyhRLAgWAfI01uBhOVre4I4",
            "outColumn": "SYMBOL",
            "outValue": "SRE-A",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 3,
            "keyArr": [
                "NYSE"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "NYSE~|SRE-A~|2018-01-16",
            "linkIdArr": [
                "2018-01-16",
                "NYSE",
                "SRE-A"
            ],
            "assignmentId": {
                "id": 2225,
                "uuid": "c5efe802-2b9d-48c9-9ac8-d8b339bc8979"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        }
    ]
}

PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "SRE-A",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "NYSE~|SRE-A~|2018-01-16",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.00031887755102040814
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "SRE-A",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "NYSE~|SRE-A~|2018-01-15",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.00031887755102040814
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "SRE-A",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "NYSE~|SRE-A~|2018-01-12",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.00031887755102040814
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "LBRT",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "NYSE~|LBRT~|2018-01-16",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 2,
        "percentile": 0.0
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "LBRT",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "NYSE~|LBRT~|2018-01-12",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 2,
        "percentile": 0.0
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "AAN",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 33,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 34,
        "percentile": 1.0
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "ZYME",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 33,
        "link_id": "",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 33,
        "percentile": 0.021683673469387755
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NYSE",
        "value_column": "SYMBOL",
        "value": "ZX",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 33,
        "link_id": "",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 33,
        "percentile": 0.021683673469387755
    },
    {
        "seqno": None,
        "updts": "2023-10-05T22:07:55.433+0000",
        "job_uuid": "7e4a7505-a627-4d6c-a747-feceaec4b090",
        "dataset": PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-10-05T00:00:00.000+0000",
        "id": 885,
        "key_column": "EXCH",
        "key_value": "NASDAQ",
        "value_column": "SYMBOL",
        "value": "AAN",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 100,
        "cnt": 1,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": True,
        "source_date": None,
        "frequency": 1,
        "percentile": 0.0
    }
]

PD_DBRKS_OUTLIERS_CAT_KEY_NODATE_NYSE_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "id": 885,
        "value_column": "SYMBOL",
        "EXCH": "NYSE",
        "SYMBOL": "LBRT",
        "TRADE_DATE": "2018-01-12",
        "OPEN": 21.2,
        "HIGH": 22.12,
        "LOW": 21.05,
        "CLOSE": 21.75,
        "VOLUME": 10448600,
        "PART_DATE_STR": "2018-01-12"
    },
    {
        "id": 885,
        "value_column": "SYMBOL",
        "EXCH": "NYSE",
        "SYMBOL": "SRE-A",
        "TRADE_DATE": "2018-01-12",
        "OPEN": 99.96,
        "HIGH": 100.62,
        "LOW": 99.96,
        "CLOSE": 100.28,
        "VOLUME": 543300,
        "PART_DATE_STR": "2018-01-12"
    },
    {
        "id": 885,
        "value_column": "SYMBOL",
        "EXCH": "NYSE",
        "SYMBOL": "SRE-A",
        "TRADE_DATE": "2018-01-15",
        "OPEN": 100.28,
        "HIGH": 100.28,
        "LOW": 100.28,
        "CLOSE": 100.28,
        "VOLUME": 0,
        "PART_DATE_STR": "2018-01-15"
    },
    {
        "id": 885,
        "value_column": "SYMBOL",
        "EXCH": "NYSE",
        "SYMBOL": "LBRT",
        "TRADE_DATE": "2018-01-16",
        "OPEN": 21.9,
        "HIGH": 22.09,
        "LOW": 21.36,
        "CLOSE": 21.82,
        "VOLUME": 1044100,
        "PART_DATE_STR": "2018-01-16"
    },
    {
        "id": 885,
        "value_column": "SYMBOL",
        "EXCH": "NYSE",
        "SYMBOL": "SRE-A",
        "TRADE_DATE": "2018-01-16",
        "OPEN": 100.3,
        "HIGH": 100.62,
        "LOW": 100.01,
        "CLOSE": 100.44,
        "VOLUME": 467600,
        "PART_DATE_STR": "2018-01-16"
    }
]
