# pylint: disable-next=line-too-long
from payloads.pushdown.outliers.pl_pd_bq_outliers_cat_nokey_nodate_us_airports_archive_breaks import (
    PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET
)

PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_OUTLIERS = {
    "data": [
        {
            "id": 50477,
            "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2023-08-16T00:00:00.000+0000",
            "outKeyColumn": "",
            "outKey": "6jiEVdj4rjrqoP5df1f7ed2sGdfvkJ5f+R2aeZiXbzG7zyRXFU+T90Rodz4D/Eky",
            "outColumn": "AIRPORT_TYPE",
            "outValue": "Balloonport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 14,
            "keyArr": [
                ""
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "8D867395-60D3-4834-A980-316982C89610",
            "linkIdArr": [
                "8D867395-60D3-4834-A980-316982C89610"
            ],
            "assignmentId": {
                "id": 408840,
                "uuid": "b0c8a254-5f38-4d05-b279-1d4cfdb30fc5"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        },
        {
            "id": 50476,
            "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2023-08-16T00:00:00.000+0000",
            "outKeyColumn": "",
            "outKey": "K/RdP7UW4xBkF1vDR5j5mEUsBydfDAG+fd73Vqq1J/i7lzKJ9s67xIEJV88kL1Nr",
            "outColumn": "AIRPORT_TYPE",
            "outValue": "Gliderport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 35,
            "keyArr": [
                ""
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E",
            "linkIdArr": [
                "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E"
            ],
            "assignmentId": {
                "id": 408839,
                "uuid": "20c52a0d-9252-4083-8b5c-88677d4d88ae"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        }
    ]
}

PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": 2986372,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "8D867395-60D3-4834-A980-316982C89610",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986373,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F2DB3A22-EC92-47C4-91D4-F8C51E83D8F3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986374,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "BB4362AB-7DFD-490E-A6CE-C336B6B7FC5F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986375,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "B9DED895-2060-463E-AD76-044FD671EF4E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986376,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7C5E64A9-5D56-43DA-BEDB-DF2407B63EFC",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986377,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "BECFAF24-2BE1-4A11-AFA7-D55DA21E8D94",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986378,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "80FF2471-9F06-43BE-9533-8950810670EE",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986379,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "65940756-C136-44B7-AAA1-EDB523CF8E8F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986380,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F0B7464C-CAA2-4BB6-8085-21070EBB47CE",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986381,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "4E4DE379-479D-4CE7-891F-22E726180768",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986382,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "09CD64C9-5197-40E2-9256-3559ED916B21",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986383,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "3D293EC3-AA04-4393-A3AD-D057097ABB6E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986384,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "D603389D-790E-4B8F-BD97-E6DF2F434425",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986385,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "CC1D172D-8954-46B9-A717-9758ACD8071A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 14,
        "percentile": 0.0
    },
    {
        "seqno": 2986386,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986387,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F7FDD38E-C679-4895-846A-9DC8274755AA",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986388,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F5ACE168-FDD3-41C3-8BA1-19CB0F465EA2",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986389,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "EB9793BC-8637-4A11-AA28-B85C3C5C2F01",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986390,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "CDE92C84-41AC-4AD3-9155-F137A5118680",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986391,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "0A4B2E93-19F1-4994-AEE2-B5DBAF59CEB9",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986392,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "488BECCB-A978-4A0E-B301-57B98BED7345",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986393,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "5AC398FF-0F72-4893-9546-0DC083F71B7E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986394,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F6659AE5-CD5B-4DB0-B619-F06F851B8F86",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986395,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "07BBAE9F-D196-4DC4-B7DB-CE3AA9D3E100",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986396,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "39FE6935-A2DE-44D1-97BF-E672C421250C",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986397,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E5CA5D08-6DBF-49C6-ACEF-E1258C4DC2F3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986398,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "0DCDD88A-FEB9-46E9-9019-0D66DEA5AD12",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986399,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "92A10121-2328-4FE6-944C-8F6E2919F63B",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986400,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "85EEEABB-C5F9-4C67-9E6D-6698581BCD12",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986401,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "15F12F96-297F-4D79-A03B-A762A3368A19",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986402,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7933DAF8-A609-42CF-94DF-04148DD3CA33",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986403,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F4728404-6AC2-4671-8058-883AE04844DF",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986404,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "46E7791C-F7C3-43B9-91CD-57C4A380DD54",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986405,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "736080ED-D37A-43BF-A7A1-0F3237598E71",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986406,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "49771B1D-7542-4CB8-816C-85BCA35D976A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986407,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7E7A424A-2BCA-435A-B86F-91D0D7D19EE3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986408,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E21AC7EF-3F43-40C9-8AA6-146B3C07AFAB",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986409,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "24518D23-BB6C-4459-8E72-2E0E1469CED0",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986410,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "795C28F5-9485-4980-B401-F830940E701F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986411,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "B5E4A142-2D35-4C07-8057-8EF8DF064FB9",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986412,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "EF382EDE-705A-49FC-A6A1-9EC7F2E5C9AD",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986413,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "B0ABC5B2-8CCD-444D-BBB2-D3376F26959C",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986414,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "9E143ADF-DE7B-4984-8BE2-BC0A4CD2953A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986415,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F822281D-5246-4AE7-A9C5-46867D28C221",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986416,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "17A97E72-C3B5-475C-B7A7-B3007133E374",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986417,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "5CA8C47A-CE0D-4078-8D8E-166FBE67CD69",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986418,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "A4480CF2-8935-43E7-9AC0-A82EB3D11E26",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986419,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E93769AC-B15C-4018-8BE8-B28797C66D1B",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986420,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "D5D36ED0-AE3F-41B9-8C75-989E3E504C8B",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 35,
        "percentile": 0.2
    },
    {
        "seqno": 2986422,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Seaport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 3,
        "cnt": 501,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 501,
        "percentile": 0.6
    },
    {
        "seqno": 2986423,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Heliport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 29,
        "cnt": 5876,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 5876,
        "percentile": 0.8
    },
    {
        "seqno": 2986424,
        "updts": "2023-08-16T18:55:12.806+0000",
        "job_uuid": "3ee244d8-4c31-4f76-9476-86bde1afdde8",
        "dataset": PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2023-08-16T00:00:00.000+0000",
        "id": 3513,
        "key_column": None,
        "key_value": None,
        "value_column": "AIRPORT_TYPE",
        "value": "Aerodome",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 67,
        "cnt": 13403,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 13403,
        "percentile": 1.0
    }
]

PD_BQ_OUTLIERS_CAT_NOKEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "2536",
        "GLOBAL_ID": "8D867395-60D3-4834-A980-316982C89610",
        "FAA_IDENTIFIER": "CO28",
        "NAME": "Suckla Farms",
        "LATITUDE": 40.05832341,
        "LONGITUDE": -104.8922079,
        "AIRPORT_GEOM": "POINT(-104.8922079 40.05832341)",
        "ELEVATION": 5050.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Dacono",
        "STATE_ABBREVIATION": "CO",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "1580",
        "GLOBAL_ID": "F7FDD38E-C679-4895-846A-9DC8274755AA",
        "FAA_IDENTIFIER": "AZ67",
        "NAME": "El Tiro",
        "LATITUDE": 32.42701973,
        "LONGITUDE": -111.3895653,
        "AIRPORT_GEOM": "POINT(-111.3895653 32.42701973)",
        "ELEVATION": 2100.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Tucson",
        "STATE_ABBREVIATION": "AZ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "14751",
        "GLOBAL_ID": "F4728404-6AC2-4671-8058-883AE04844DF",
        "FAA_IDENTIFIER": "TX23",
        "NAME": "Flf",
        "LATITUDE": 30.85629838,
        "LONGITUDE": -97.94586076,
        "AIRPORT_GEOM": "POINT(-97.94586076 30.85629838)",
        "ELEVATION": 1150.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Briggs",
        "STATE_ABBREVIATION": "TX",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "12142",
        "GLOBAL_ID": "46E7791C-F7C3-43B9-91CD-57C4A380DD54",
        "FAA_IDENTIFIER": "2OH9",
        "NAME": "Caesar Creek Soaring Club",
        "LATITUDE": 39.47673455,
        "LONGITUDE": -84.09382727,
        "AIRPORT_GEOM": "POINT(-84.09382727 39.47673455)",
        "ELEVATION": 940.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Waynesville",
        "STATE_ABBREVIATION": "OH",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "14315",
        "GLOBAL_ID": "E21AC7EF-3F43-40C9-8AA6-146B3C07AFAB",
        "FAA_IDENTIFIER": "50M",
        "NAME": "Puckett",
        "LATITUDE": 35.68945119,
        "LONGITUDE": -86.61500496,
        "AIRPORT_GEOM": "POINT(-86.61500496 35.68945119)",
        "ELEVATION": 780.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Eagleville",
        "STATE_ABBREVIATION": "TN",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "16735",
        "GLOBAL_ID": "D603389D-790E-4B8F-BD97-E6DF2F434425",
        "FAA_IDENTIFIER": "VA60",
        "NAME": "Flying Horse Farm",
        "LATITUDE": 39.0515039,
        "LONGITUDE": -77.77749698,
        "AIRPORT_GEOM": "POINT(-77.77749698 39.0515039)",
        "ELEVATION": 450.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Unison",
        "STATE_ABBREVIATION": "VA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "1285",
        "GLOBAL_ID": "736080ED-D37A-43BF-A7A1-0F3237598E71",
        "FAA_IDENTIFIER": "AZ86",
        "NAME": "A C Goodwin Mem Fld",
        "LATITUDE": 34.68519971,
        "LONGITUDE": -112.2902612,
        "AIRPORT_GEOM": "POINT(-112.2902612 34.68519971)",
        "ELEVATION": 4948.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Coyote Springs",
        "STATE_ABBREVIATION": "AZ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "11559",
        "GLOBAL_ID": "3D293EC3-AA04-4393-A3AD-D057097ABB6E",
        "FAA_IDENTIFIER": "4OH6",
        "NAME": "Wingfoot Lake Airship Operations",
        "LATITUDE": 41.00950913,
        "LONGITUDE": -81.35789045,
        "AIRPORT_GEOM": "POINT(-81.35789045 41.00950913)",
        "ELEVATION": 1164.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Akron Suffield",
        "STATE_ABBREVIATION": "OH",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "9758",
        "GLOBAL_ID": "49771B1D-7542-4CB8-816C-85BCA35D976A",
        "FAA_IDENTIFIER": "43NC",
        "NAME": "Bahnson",
        "LATITUDE": 36.02084039,
        "LONGITUDE": -80.51639208,
        "AIRPORT_GEOM": "POINT(-80.51639208 36.02084039)",
        "ELEVATION": 810.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Mocksville",
        "STATE_ABBREVIATION": "NC",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "3140",
        "GLOBAL_ID": "7E7A424A-2BCA-435A-B86F-91D0D7D19EE3",
        "FAA_IDENTIFIER": "FA44",
        "NAME": "Willis",
        "LATITUDE": 26.54813099,
        "LONGITUDE": -80.21477104,
        "AIRPORT_GEOM": "POINT(-80.21477104 26.54813099)",
        "ELEVATION": 18.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Boynton Beach",
        "STATE_ABBREVIATION": "FL",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "3244",
        "GLOBAL_ID": "24518D23-BB6C-4459-8E72-2E0E1469CED0",
        "FAA_IDENTIFIER": "6FL0",
        "NAME": "Seminole Lake",
        "LATITUDE": 28.40584391,
        "LONGITUDE": -81.83785852,
        "AIRPORT_GEOM": "POINT(-81.83785852 28.40584391)",
        "ELEVATION": 120.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Groveland",
        "STATE_ABBREVIATION": "FL",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "10548",
        "GLOBAL_ID": "CC1D172D-8954-46B9-A717-9758ACD8071A",
        "FAA_IDENTIFIER": "JY42",
        "NAME": "Mabel's",
        "LATITUDE": 40.46834151,
        "LONGITUDE": -75.02375176,
        "AIRPORT_GEOM": "POINT(-75.02375176 40.46834151)",
        "ELEVATION": 460.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Frenchtown",
        "STATE_ABBREVIATION": "NJ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "19706",
        "GLOBAL_ID": "09CD64C9-5197-40E2-9256-3559ED916B21",
        "FAA_IDENTIFIER": "CT30",
        "NAME": "Murphy's Landing",
        "LATITUDE": 41.66667236,
        "LONGITUDE": -73.18944569,
        "AIRPORT_GEOM": "POINT(-73.18944569 41.66667236)",
        "ELEVATION": 1050.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Bethlehem",
        "STATE_ABBREVIATION": "CT",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "6205",
        "GLOBAL_ID": "795C28F5-9485-4980-B401-F830940E701F",
        "FAA_IDENTIFIER": "SN76",
        "NAME": "Sunflower Aerodrome",
        "LATITUDE": 37.92628437,
        "LONGITUDE": -97.90670264,
        "AIRPORT_GEOM": "POINT(-97.90670264 37.92628437)",
        "ELEVATION": 1582.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Hutchinson",
        "STATE_ABBREVIATION": "KS",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": True,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "11076",
        "GLOBAL_ID": "B5E4A142-2D35-4C07-8057-8EF8DF064FB9",
        "FAA_IDENTIFIER": "NV23",
        "NAME": "Air Sailing",
        "LATITUDE": 39.87213533,
        "LONGITUDE": -119.7010356,
        "AIRPORT_GEOM": "POINT(-119.7010356 39.87213533)",
        "ELEVATION": 4300.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Sparks",
        "STATE_ABBREVIATION": "NV",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "5272",
        "GLOBAL_ID": "EF382EDE-705A-49FC-A6A1-9EC7F2E5C9AD",
        "FAA_IDENTIFIER": "3IL1",
        "NAME": "Silvercreek",
        "LATITUDE": 38.925285,
        "LONGITUDE": -89.66222829,
        "AIRPORT_GEOM": "POINT(-89.66222829 38.925285)",
        "ELEVATION": 595.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "New Douglas",
        "STATE_ABBREVIATION": "IL",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "10506",
        "GLOBAL_ID": "BECFAF24-2BE1-4A11-AFA7-D55DA21E8D94",
        "FAA_IDENTIFIER": "35JY",
        "NAME": "Cyber Density Balloon Spot",
        "LATITUDE": 40.43445262,
        "LONGITUDE": -74.63472385,
        "AIRPORT_GEOM": "POINT(-74.63472385 40.43445262)",
        "ELEVATION": 75.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Belle Mead",
        "STATE_ABBREVIATION": "NJ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "13186",
        "GLOBAL_ID": "B0ABC5B2-8CCD-444D-BBB2-D3376F26959C",
        "FAA_IDENTIFIER": "03G",
        "NAME": "Thermal-G",
        "LATITUDE": 42.02062215,
        "LONGITUDE": -80.07072291,
        "AIRPORT_GEOM": "POINT(-80.07072291 42.02062215)",
        "ELEVATION": 1434.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Erie",
        "STATE_ABBREVIATION": "PA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "15758",
        "GLOBAL_ID": "9E143ADF-DE7B-4984-8BE2-BC0A4CD2953A",
        "FAA_IDENTIFIER": "TA11",
        "NAME": "Tsa",
        "LATITUDE": 32.38348093,
        "LONGITUDE": -97.01417783,
        "AIRPORT_GEOM": "POINT(-97.01417783 32.38348093)",
        "ELEVATION": 660.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Midlothian",
        "STATE_ABBREVIATION": "TX",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "4041",
        "GLOBAL_ID": "A4480CF2-8935-43E7-9AC0-A82EB3D11E26",
        "FAA_IDENTIFIER": "8GA7",
        "NAME": "Etowah Bend",
        "LATITUDE": 34.20204623,
        "LONGITUDE": -84.97717079,
        "AIRPORT_GEOM": "POINT(-84.97717079 34.20204623)",
        "ELEVATION": 620.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Kingston",
        "STATE_ABBREVIATION": "GA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "16237",
        "GLOBAL_ID": "17A97E72-C3B5-475C-B7A7-B3007133E374",
        "FAA_IDENTIFIER": "89TA",
        "NAME": "Soaring Club of Houston",
        "LATITUDE": 30.19271915,
        "LONGITUDE": -95.96329606,
        "AIRPORT_GEOM": "POINT(-95.96329606 30.19271915)",
        "ELEVATION": 308.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Waller",
        "STATE_ABBREVIATION": "TX",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "11608",
        "GLOBAL_ID": "80FF2471-9F06-43BE-9533-8950810670EE",
        "FAA_IDENTIFIER": "NY80",
        "NAME": "Aurora",
        "LATITUDE": 42.69639734,
        "LONGITUDE": -78.56916971,
        "AIRPORT_GEOM": "POINT(-78.56916971 42.69639734)",
        "ELEVATION": 900.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "South Wales",
        "STATE_ABBREVIATION": "NY",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "2285",
        "GLOBAL_ID": "5CA8C47A-CE0D-4078-8D8E-166FBE67CD69",
        "FAA_IDENTIFIER": "CL35",
        "NAME": "Warner Springs",
        "LATITUDE": 33.28450763,
        "LONGITUDE": -116.6696688,
        "AIRPORT_GEOM": "POINT(-116.6696688 33.28450763)",
        "ELEVATION": 2880.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Warner Springs",
        "STATE_ABBREVIATION": "CA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "9600",
        "GLOBAL_ID": "7C5E64A9-5D56-43DA-BEDB-DF2407B63EFC",
        "FAA_IDENTIFIER": "28NC",
        "NAME": "Balloonport of Greensboro",
        "LATITUDE": 35.95584041,
        "LONGITUDE": -79.81889186,
        "AIRPORT_GEOM": "POINT(-79.81889186 35.95584041)",
        "ELEVATION": 800.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Greensboro",
        "STATE_ABBREVIATION": "NC",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "12893",
        "GLOBAL_ID": "F822281D-5246-4AE7-A9C5-46867D28C221",
        "FAA_IDENTIFIER": "1OR4",
        "NAME": "North Plains",
        "LATITUDE": 45.60400904,
        "LONGITUDE": -123.0248432,
        "AIRPORT_GEOM": "POINT(-123.0248432 45.60400904)",
        "ELEVATION": 210.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "North Plains",
        "STATE_ABBREVIATION": "OR",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "6977",
        "GLOBAL_ID": "B9DED895-2060-463E-AD76-044FD671EF4E",
        "FAA_IDENTIFIER": "MA26",
        "NAME": "Balloon Port At Dingley Dell",
        "LATITUDE": 42.12038053,
        "LONGITUDE": -72.25619152,
        "AIRPORT_GEOM": "POINT(-72.25619152 42.12038053)",
        "ELEVATION": 465.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Brimfield",
        "STATE_ABBREVIATION": "MA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "14178",
        "GLOBAL_ID": "E93769AC-B15C-4018-8BE8-B28797C66D1B",
        "FAA_IDENTIFIER": "92A",
        "NAME": "Chilhowee",
        "LATITUDE": 35.22646896,
        "LONGITUDE": -84.58493712,
        "AIRPORT_GEOM": "POINT(-84.58493712 35.22646896)",
        "ELEVATION": 770.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Benton",
        "STATE_ABBREVIATION": "TN",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Conditional",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "19431",
        "GLOBAL_ID": "488BECCB-A978-4A0E-B301-57B98BED7345",
        "FAA_IDENTIFIER": "29KS",
        "NAME": "McMaster",
        "LATITUDE": 37.76129578,
        "LONGITUDE": -97.17734963,
        "AIRPORT_GEOM": "POINT(-97.17734963 37.76129578)",
        "ELEVATION": 1403.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Wichita",
        "STATE_ABBREVIATION": "KS",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "5940",
        "GLOBAL_ID": "BB4362AB-7DFD-490E-A6CE-C336B6B7FC5F",
        "FAA_IDENTIFIER": "5KS0",
        "NAME": "Anthony",
        "LATITUDE": 37.09447395,
        "LONGITUDE": -97.96145675,
        "AIRPORT_GEOM": "POINT(-97.96145675 37.09447395)",
        "ELEVATION": 1250.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Anthony",
        "STATE_ABBREVIATION": "KS",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "13618",
        "GLOBAL_ID": "7933DAF8-A609-42CF-94DF-04148DD3CA33",
        "FAA_IDENTIFIER": "79N",
        "NAME": "Ridge Soaring",
        "LATITUDE": 40.88395675,
        "LONGITUDE": -77.90722825,
        "AIRPORT_GEOM": "POINT(-77.90722825 40.88395675)",
        "ELEVATION": 815.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Unionville",
        "STATE_ABBREVIATION": "PA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "10708",
        "GLOBAL_ID": "F2DB3A22-EC92-47C4-91D4-F8C51E83D8F3",
        "FAA_IDENTIFIER": "12JY",
        "NAME": "Clinton Elks Lodge",
        "LATITUDE": 40.60417487,
        "LONGITUDE": -74.92083507,
        "AIRPORT_GEOM": "POINT(-74.92083507 40.60417487)",
        "ELEVATION": 37.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Pittstown",
        "STATE_ABBREVIATION": "NJ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "18320",
        "GLOBAL_ID": "D5D36ED0-AE3F-41B9-8C75-989E3E504C8B",
        "FAA_IDENTIFIER": "ID36",
        "NAME": "King Mountain Glider Park",
        "LATITUDE": 43.76306178,
        "LONGITUDE": -113.3439014,
        "AIRPORT_GEOM": "POINT(-113.3439014 43.76306178)",
        "ELEVATION": 5500.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Moore",
        "STATE_ABBREVIATION": "ID",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "16240",
        "GLOBAL_ID": "F5ACE168-FDD3-41C3-8BA1-19CB0F465EA2",
        "FAA_IDENTIFIER": "TE71",
        "NAME": "Ghsa-Wallis Glideport",
        "LATITUDE": 29.61111626,
        "LONGITUDE": -96.02790716,
        "AIRPORT_GEOM": "POINT(-96.02790716 29.61111626)",
        "ELEVATION": 127.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Wallis",
        "STATE_ABBREVIATION": "TX",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "15243",
        "GLOBAL_ID": "5AC398FF-0F72-4893-9546-0DC083F71B7E",
        "FAA_IDENTIFIER": "35TS",
        "NAME": "Hempstead",
        "LATITUDE": 30.12161136,
        "LONGITUDE": -96.0866322,
        "AIRPORT_GEOM": "POINT(-96.0866322 30.12161136)",
        "ELEVATION": 260.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Hempstead",
        "STATE_ABBREVIATION": "TX",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "1038",
        "GLOBAL_ID": "F6659AE5-CD5B-4DB0-B619-F06F851B8F86",
        "FAA_IDENTIFIER": "4AR5",
        "NAME": "Lawrence Fld",
        "LATITUDE": 35.37083984,
        "LONGITUDE": -90.75056165,
        "AIRPORT_GEOM": "POINT(-90.75056165 35.37083984)",
        "ELEVATION": 284.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Cherry Valley",
        "STATE_ABBREVIATION": "AR",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "10801",
        "GLOBAL_ID": "65940756-C136-44B7-AAA1-EDB523CF8E8F",
        "FAA_IDENTIFIER": "JY33",
        "NAME": "Harmony",
        "LATITUDE": 40.73950822,
        "LONGITUDE": -75.13800181,
        "AIRPORT_GEOM": "POINT(-75.13800181 40.73950822)",
        "ELEVATION": 500.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Phillipsburg",
        "STATE_ABBREVIATION": "NJ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "7879",
        "GLOBAL_ID": "F0B7464C-CAA2-4BB6-8085-21070EBB47CE",
        "FAA_IDENTIFIER": "13M",
        "NAME": "Aeronut Park",
        "LATITUDE": 42.60417485,
        "LONGITUDE": -83.8586158,
        "AIRPORT_GEOM": "POINT(-83.8586158 42.60417485)",
        "ELEVATION": 980.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Howell",
        "STATE_ABBREVIATION": "MI",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "12091",
        "GLOBAL_ID": "E5CA5D08-6DBF-49C6-ACEF-E1258C4DC2F3",
        "FAA_IDENTIFIER": "14OI",
        "NAME": "Pleasant Home Gliding Club",
        "LATITUDE": 40.91923074,
        "LONGITUDE": -82.11404567,
        "AIRPORT_GEOM": "POINT(-82.11404567 40.91923074)",
        "ELEVATION": 1050.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Pleasant Home",
        "STATE_ABBREVIATION": "OH",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "4983",
        "GLOBAL_ID": "0DCDD88A-FEB9-46E9-9019-0D66DEA5AD12",
        "FAA_IDENTIFIER": "IL59",
        "NAME": "Chicago Glider Club",
        "LATITUDE": 41.43198274,
        "LONGITUDE": -88.24729116,
        "AIRPORT_GEOM": "POINT(-88.24729116 41.43198274)",
        "ELEVATION": 590.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Channahon",
        "STATE_ABBREVIATION": "IL",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "1406",
        "GLOBAL_ID": "85EEEABB-C5F9-4C67-9E6D-6698581BCD12",
        "FAA_IDENTIFIER": "E68",
        "NAME": "Estrella Sailport",
        "LATITUDE": 33.08533173,
        "LONGITUDE": -112.1609905,
        "AIRPORT_GEOM": "POINT(-112.1609905 33.08533173)",
        "ELEVATION": 1273.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Maricopa",
        "STATE_ABBREVIATION": "AZ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Public",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "11243",
        "GLOBAL_ID": "92A10121-2328-4FE6-944C-8F6E2919F63B",
        "FAA_IDENTIFIER": "NY77",
        "NAME": "Wandervogel",
        "LATITUDE": 42.71813974,
        "LONGITUDE": -74.1634633,
        "AIRPORT_GEOM": "POINT(-74.1634633 42.71813974)",
        "ELEVATION": 1260.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Delanson",
        "STATE_ABBREVIATION": "NY",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "10674",
        "GLOBAL_ID": "4E4DE379-479D-4CE7-891F-22E726180768",
        "FAA_IDENTIFIER": "2JY7",
        "NAME": "Alba Vineyard",
        "LATITUDE": 40.61569708,
        "LONGITUDE": -75.16416848,
        "AIRPORT_GEOM": "POINT(-75.16416848 40.61569708)",
        "ELEVATION": 240.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Balloonport",
        "SERVICE_CITY": "Milford",
        "STATE_ABBREVIATION": "NJ",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "No Objection",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "16480",
        "GLOBAL_ID": "15F12F96-297F-4D79-A03B-A762A3368A19",
        "FAA_IDENTIFIER": "08VA",
        "NAME": "Springwood Airstrip",
        "LATITUDE": 37.55402935,
        "LONGITUDE": -79.74976638,
        "AIRPORT_GEOM": "POINT(-79.74976638 37.55402935)",
        "ELEVATION": 1000.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Buchanan",
        "STATE_ABBREVIATION": "VA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "2290",
        "GLOBAL_ID": "39FE6935-A2DE-44D1-97BF-E672C421250C",
        "FAA_IDENTIFIER": "CN12",
        "NAME": "Williams",
        "LATITUDE": 39.1635073,
        "LONGITUDE": -122.1316545,
        "AIRPORT_GEOM": "POINT(-122.1316545 39.1635073)",
        "ELEVATION": 68.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Williams",
        "STATE_ABBREVIATION": "CA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "11253",
        "GLOBAL_ID": "07BBAE9F-D196-4DC4-B7DB-CE3AA9D3E100",
        "FAA_IDENTIFIER": "4NY8",
        "NAME": "Harris Hill",
        "LATITUDE": 42.12091592,
        "LONGITUDE": -76.90107414,
        "AIRPORT_GEOM": "POINT(-76.90107414 42.12091592)",
        "ELEVATION": 1709.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Elmira",
        "STATE_ABBREVIATION": "NY",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "2196",
        "GLOBAL_ID": "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E",
        "FAA_IDENTIFIER": "CA84",
        "NAME": "Torrey Pines",
        "LATITUDE": 32.889727,
        "LONGITUDE": -117.2469564,
        "AIRPORT_GEOM": "POINT(-117.2469564 32.889727)",
        "ELEVATION": 372.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "San Diego",
        "STATE_ABBREVIATION": "CA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "13932",
        "GLOBAL_ID": "0A4B2E93-19F1-4994-AEE2-B5DBAF59CEB9",
        "FAA_IDENTIFIER": "SC79",
        "NAME": "Bermuda High",
        "LATITUDE": 34.61127287,
        "LONGITUDE": -80.44979476,
        "AIRPORT_GEOM": "POINT(-80.44979476 34.61127287)",
        "ELEVATION": 550.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Lancaster",
        "STATE_ABBREVIATION": "SC",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "2795",
        "GLOBAL_ID": "EB9793BC-8637-4A11-AA28-B85C3C5C2F01",
        "FAA_IDENTIFIER": "4CO2",
        "NAME": "Owl Canyon",
        "LATITUDE": 40.80471156,
        "LONGITUDE": -104.9849825,
        "AIRPORT_GEOM": "POINT(-104.9849825 40.80471156)",
        "ELEVATION": 5545.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Wellington",
        "STATE_ABBREVIATION": "CO",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    },
    {
        "id": 3513,
        "value_column": "AIRPORT_TYPE",
        "OBJECT_ID": "13321",
        "GLOBAL_ID": "CDE92C84-41AC-4AD3-9155-F137A5118680",
        "FAA_IDENTIFIER": "3PA2",
        "NAME": "Philadelphia",
        "LATITUDE": 40.33123564,
        "LONGITUDE": -75.24812571,
        "AIRPORT_GEOM": "POINT(-75.24812571 40.33123564)",
        "ELEVATION": 670.0,
        "ICAO_ID": None,
        "AIRPORT_TYPE": "Gliderport",
        "SERVICE_CITY": "Hilltown",
        "STATE_ABBREVIATION": "PA",
        "COUNTRY": "United States",
        "OPER_STATUS": "Operational",
        "AIRPORT_USE": "Private",
        "IAP_EXISTS": False,
        "DOD_HIFLIP": False,
        "FAR_91": False,
        "FAR_93": False,
        "MIL_CODE": "CIVIL",
        "AIRSPACE_ANALYSIS": "Not Analyzed",
        "US_HIGH": False,
        "US_LOW": False,
        "AK_HIGH": False,
        "AK_LOW": False,
        "US_AREA": False,
        "PACIFIC": False
    }
]
