# pylint: disable-next=line-too-long
from payloads.pushdown.outliers.pl_pd_trino_outliers_cat_key_nodate_us_airports_archive_breaks import (
    PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
)

PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_OUTLIERS = {
    "data": [
        {
            "id": 492579,
            "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2024-09-22T00:00:00.000+0000",
            "outKeyColumn": "airport_use",
            "outKey": "M2vbM/v/Bo14gbNlHOH+bCIymwSjan1Bsygk2m00xfk9mdmiKHQoBqYu52XJupK5",
            "outColumn": "airport_type",
            "outValue": "Balloonport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 13,
            "keyArr": [
                "Private"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [
                ""
            ],
            "assignmentId": {
                "id": 1527204,
                "uuid": "6db5e448-d419-47d7-8796-c5a82c41bb19"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        },
        {
            "id": 492580,
            "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2024-09-22T00:00:00.000+0000",
            "outKeyColumn": "airport_use",
            "outKey": "P/Ii68u7uW8G+ogLSSyyV7/kFE+VQ7euac0GhH5PtFYBBmil6DkIYRqMJqUlVYvO",
            "outColumn": "airport_type",
            "outValue": "Gliderport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 30,
            "keyArr": [
                "Private"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [
                ""
            ],
            "assignmentId": {
                "id": 1527205,
                "uuid": "f8125251-a62d-492e-8334-f677f515a84d"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        },
        {
            "id": 492581,
            "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2024-09-22T00:00:00.000+0000",
            "outKeyColumn": "airport_use",
            "outKey": "G0HJtzng3OOKYeCzW8KTln++uqqJ7OQgcHhGtV17XMkGLVluqIWlzTk2bO+ZXpO4",
            "outColumn": "airport_type",
            "outValue": "Balloonport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": [
                "Public"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [
                ""
            ],
            "assignmentId": {
                "id": 1527206,
                "uuid": "7ec11d52-db69-41a7-84a3-9d2ee567eaa6"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        },
        {
            "id": 492582,
            "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
            "runId": "2024-09-22T00:00:00.000+0000",
            "outKeyColumn": "airport_use",
            "outKey": "uPpLcegeQi0azp9KBrfh/fhyQAtXy+CRVhIro/NAXjpeiyY5Eqq2EvHs+8uRE0Lu",
            "outColumn": "airport_type",
            "outValue": "Ultralightport",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 3,
            "keyArr": [
                "Public"
            ],
            "lb": 0.0,
            "ub": 0.0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [
                ""
            ],
            "assignmentId": {
                "id": 1527207,
                "uuid": "ba11052c-87ac-4464-93ed-91beb10be312"
            },
            "obsType": "OUTLIER_CATEGORICAL"
        }
    ]
}

PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_DATA = [
    {
        "seqno": 10862719,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Aerodome",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 57,
        "cnt": 8315,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 8315,
        "percentile": 1
    },
    {
        "seqno": 10862720,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Aerodome",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 95,
        "cnt": 5088,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 5088,
        "percentile": 1
    },
    {
        "seqno": 10862721,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Seaport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 2,
        "cnt": 290,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 290,
        "percentile": 0.6
    },
    {
        "seqno": 10862722,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Heliport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 40,
        "cnt": 5816,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 5816,
        "percentile": 0.8
    },
    {
        "seqno": 10862697,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Seaport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 4,
        "cnt": 211,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 211,
        "percentile": 0.8
    },
    {
        "seqno": 10862698,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Heliport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 1,
        "cnt": 60,
        "link_id": "",
        "is_outlier": False,
        "is_historical": False,
        "is_topn": True,
        "is_botn": False,
        "source_date": None,
        "frequency": 60,
        "percentile": 0.6
    },
    {
        "seqno": 10862699,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "CDE92C84-41AC-4AD3-9155-F137A5118680",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862700,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Ultralightport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "CE7C8233-FA31-4A01-AC3E-7609B838A49A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.2
    },
    {
        "seqno": 10862701,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7C5E64A9-5D56-43DA-BEDB-DF2407B63EFC",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862702,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "B9DED895-2060-463E-AD76-044FD671EF4E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862703,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F7FDD38E-C679-4895-846A-9DC8274755AA",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862704,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F4728404-6AC2-4671-8058-883AE04844DF",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862705,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "736080ED-D37A-43BF-A7A1-0F3237598E71",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862706,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7E7A424A-2BCA-435A-B86F-91D0D7D19EE3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862707,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "24518D23-BB6C-4459-8E72-2E0E1469CED0",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862708,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "795C28F5-9485-4980-B401-F830940E701F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862709,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "EF382EDE-705A-49FC-A6A1-9EC7F2E5C9AD",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862710,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "9E143ADF-DE7B-4984-8BE2-BC0A4CD2953A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862711,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "A4480CF2-8935-43E7-9AC0-A82EB3D11E26",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862712,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "5CA8C47A-CE0D-4078-8D8E-166FBE67CD69",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862713,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "488BECCB-A978-4A0E-B301-57B98BED7345",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862714,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "D5D36ED0-AE3F-41B9-8C75-989E3E504C8B",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862715,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "5AC398FF-0F72-4893-9546-0DC083F71B7E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862716,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "15F12F96-297F-4D79-A03B-A762A3368A19",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862717,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "07BBAE9F-D196-4DC4-B7DB-CE3AA9D3E100",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862718,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "0A4B2E93-19F1-4994-AEE2-B5DBAF59CEB9",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862723,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "EB9793BC-8637-4A11-AA28-B85C3C5C2F01",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862724,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F0B7464C-CAA2-4BB6-8085-21070EBB47CE",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 1,
        "percentile": 0
    },
    {
        "seqno": 10862725,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Ultralightport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E5A6ED47-D70F-473D-A1A8-1A9F7CE863DF",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.2
    },
    {
        "seqno": 10862726,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Public",
        "value_column": "airport_type",
        "value": "Ultralightport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "7E857160-ED3C-4626-93C1-732F4FFDC03D",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 3,
        "percentile": 0.2
    },
    {
        "seqno": 10862727,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "8D867395-60D3-4834-A980-316982C89610",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862728,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "D603389D-790E-4B8F-BD97-E6DF2F434425",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862729,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "3D293EC3-AA04-4393-A3AD-D057097ABB6E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862730,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "CC1D172D-8954-46B9-A717-9758ACD8071A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862731,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "09CD64C9-5197-40E2-9256-3559ED916B21",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862732,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "BECFAF24-2BE1-4A11-AFA7-D55DA21E8D94",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862733,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "80FF2471-9F06-43BE-9533-8950810670EE",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862734,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "BB4362AB-7DFD-490E-A6CE-C336B6B7FC5F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862735,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F2DB3A22-EC92-47C4-91D4-F8C51E83D8F3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862736,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "65940756-C136-44B7-AAA1-EDB523CF8E8F",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862737,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Balloonport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "4E4DE379-479D-4CE7-891F-22E726180768",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 13,
        "percentile": 0
    },
    {
        "seqno": 10862738,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "46E7791C-F7C3-43B9-91CD-57C4A380DD54",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862739,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "49771B1D-7542-4CB8-816C-85BCA35D976A",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862740,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "B5E4A142-2D35-4C07-8057-8EF8DF064FB9",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862741,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "17A97E72-C3B5-475C-B7A7-B3007133E374",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862742,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F822281D-5246-4AE7-A9C5-46867D28C221",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862743,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F5ACE168-FDD3-41C3-8BA1-19CB0F465EA2",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862744,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "F6659AE5-CD5B-4DB0-B619-F06F851B8F86",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862745,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E5CA5D08-6DBF-49C6-ACEF-E1258C4DC2F3",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862746,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "0DCDD88A-FEB9-46E9-9019-0D66DEA5AD12",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862747,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "92A10121-2328-4FE6-944C-8F6E2919F63B",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862748,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "39FE6935-A2DE-44D1-97BF-E672C421250C",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    },
    {
        "seqno": 10862749,
        "updts": "2024-10-02T12:11:12.312+0000",
        "job_uuid": "bc84b380-bfd1-4a07-b97d-af04f02b2e6e",
        "dataset": PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_DATASET,
        "run_id": "2024-10-02T00:00:00.000+0000",
        "id": 2081,
        "key_column": "airport_use",
        "key_value": "Private",
        "value_column": "airport_type",
        "value": "Gliderport",
        "date_value": None,
        "type": "CATEGORICAL",
        "median": "INVALID",
        "lb": None,
        "ub": None,
        "confidence": 0,
        "cnt": 1,
        "link_id": "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E",
        "is_outlier": True,
        "is_historical": False,
        "is_topn": False,
        "is_botn": True,
        "source_date": None,
        "frequency": 30,
        "percentile": 0.2
    }
]

PD_TRINO_OUTLIERS_CAT_KEY_NODATE_US_AIRPORTS_ARCHIVE_BREAKS_EXPECTED_QUERY_RESULT = [
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "13321",
    "global_id": "CDE92C84-41AC-4AD3-9155-F137A5118680",
    "faa_identifier": "3PA2",
    "name": "Philadelphia",
    "latitude": 40.33123564,
    "longitude": -75.24812571,
    "airport_geom": "POINT(-75.24812571 40.33123564)",
    "elevation": 670,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Hilltown",
    "state_abbreviation": "PA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "13251",
    "global_id": "CE7C8233-FA31-4A01-AC3E-7609B838A49A",
    "faa_identifier": "48P",
    "name": "Rocky Hill",
    "latitude": 41.14856385,
    "longitude": -75.27527966,
    "airport_geom": "POINT(-75.27527966 41.14856385)",
    "elevation": 1240,
    "icao_id": None,
    "airport_type": "Ultralightport",
    "service_city": "Cresco",
    "state_abbreviation": "PA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Public",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "9600",
    "global_id": "7C5E64A9-5D56-43DA-BEDB-DF2407B63EFC",
    "faa_identifier": "28NC",
    "name": "Balloonport of Greensboro",
    "latitude": 35.95584041,
    "longitude": -79.81889186,
    "airport_geom": "POINT(-79.81889186 35.95584041)",
    "elevation": 800,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Greensboro",
    "state_abbreviation": "NC",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "6977",
    "global_id": "B9DED895-2060-463E-AD76-044FD671EF4E",
    "faa_identifier": "MA26",
    "name": "Balloon Port At Dingley Dell",
    "latitude": 42.12038053,
    "longitude": -72.25619152,
    "airport_geom": "POINT(-72.25619152 42.12038053)",
    "elevation": 465,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Brimfield",
    "state_abbreviation": "MA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "1580",
    "global_id": "F7FDD38E-C679-4895-846A-9DC8274755AA",
    "faa_identifier": "AZ67",
    "name": "El Tiro",
    "latitude": 32.42701973,
    "longitude": -111.3895653,
    "airport_geom": "POINT(-111.3895653 32.42701973)",
    "elevation": 2100,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Tucson",
    "state_abbreviation": "AZ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "14751",
    "global_id": "F4728404-6AC2-4671-8058-883AE04844DF",
    "faa_identifier": "TX23",
    "name": "Flf",
    "latitude": 30.85629838,
    "longitude": -97.94586076,
    "airport_geom": "POINT(-97.94586076 30.85629838)",
    "elevation": 1150,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Briggs",
    "state_abbreviation": "TX",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "1285",
    "global_id": "736080ED-D37A-43BF-A7A1-0F3237598E71",
    "faa_identifier": "AZ86",
    "name": "A C Goodwin Mem Fld",
    "latitude": 34.68519971,
    "longitude": -112.2902612,
    "airport_geom": "POINT(-112.2902612 34.68519971)",
    "elevation": 4948,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Coyote Springs",
    "state_abbreviation": "AZ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "3140",
    "global_id": "7E7A424A-2BCA-435A-B86F-91D0D7D19EE3",
    "faa_identifier": "FA44",
    "name": "Willis",
    "latitude": 26.54813099,
    "longitude": -80.21477104,
    "airport_geom": "POINT(-80.21477104 26.54813099)",
    "elevation": 18,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Boynton Beach",
    "state_abbreviation": "FL",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "3244",
    "global_id": "24518D23-BB6C-4459-8E72-2E0E1469CED0",
    "faa_identifier": "6FL0",
    "name": "Seminole Lake",
    "latitude": 28.40584391,
    "longitude": -81.83785852,
    "airport_geom": "POINT(-81.83785852 28.40584391)",
    "elevation": 120,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Groveland",
    "state_abbreviation": "FL",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "6205",
    "global_id": "795C28F5-9485-4980-B401-F830940E701F",
    "faa_identifier": "SN76",
    "name": "Sunflower Aerodrome",
    "latitude": 37.92628437,
    "longitude": -97.90670264,
    "airport_geom": "POINT(-97.90670264 37.92628437)",
    "elevation": 1582,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Hutchinson",
    "state_abbreviation": "KS",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": True,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "5272",
    "global_id": "EF382EDE-705A-49FC-A6A1-9EC7F2E5C9AD",
    "faa_identifier": "3IL1",
    "name": "Silvercreek",
    "latitude": 38.925285,
    "longitude": -89.66222829,
    "airport_geom": "POINT(-89.66222829 38.925285)",
    "elevation": 595,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "New Douglas",
    "state_abbreviation": "IL",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "15758",
    "global_id": "9E143ADF-DE7B-4984-8BE2-BC0A4CD2953A",
    "faa_identifier": "TA11",
    "name": "Tsa",
    "latitude": 32.38348093,
    "longitude": -97.01417783,
    "airport_geom": "POINT(-97.01417783 32.38348093)",
    "elevation": 660,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Midlothian",
    "state_abbreviation": "TX",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "4041",
    "global_id": "A4480CF2-8935-43E7-9AC0-A82EB3D11E26",
    "faa_identifier": "8GA7",
    "name": "Etowah Bend",
    "latitude": 34.20204623,
    "longitude": -84.97717079,
    "airport_geom": "POINT(-84.97717079 34.20204623)",
    "elevation": 620,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Kingston",
    "state_abbreviation": "GA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "2285",
    "global_id": "5CA8C47A-CE0D-4078-8D8E-166FBE67CD69",
    "faa_identifier": "CL35",
    "name": "Warner Springs",
    "latitude": 33.28450763,
    "longitude": -116.6696688,
    "airport_geom": "POINT(-116.6696688 33.28450763)",
    "elevation": 2880,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Warner Springs",
    "state_abbreviation": "CA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "19431",
    "global_id": "488BECCB-A978-4A0E-B301-57B98BED7345",
    "faa_identifier": "29KS",
    "name": "McMaster",
    "latitude": 37.76129578,
    "longitude": -97.17734963,
    "airport_geom": "POINT(-97.17734963 37.76129578)",
    "elevation": 1403,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Wichita",
    "state_abbreviation": "KS",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "18320",
    "global_id": "D5D36ED0-AE3F-41B9-8C75-989E3E504C8B",
    "faa_identifier": "ID36",
    "name": "King Mountain Glider Park",
    "latitude": 43.76306178,
    "longitude": -113.3439014,
    "airport_geom": "POINT(-113.3439014 43.76306178)",
    "elevation": 5500,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Moore",
    "state_abbreviation": "ID",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "15243",
    "global_id": "5AC398FF-0F72-4893-9546-0DC083F71B7E",
    "faa_identifier": "35TS",
    "name": "Hempstead",
    "latitude": 30.12161136,
    "longitude": -96.0866322,
    "airport_geom": "POINT(-96.0866322 30.12161136)",
    "elevation": 260,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Hempstead",
    "state_abbreviation": "TX",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "16480",
    "global_id": "15F12F96-297F-4D79-A03B-A762A3368A19",
    "faa_identifier": "08VA",
    "name": "Springwood Airstrip",
    "latitude": 37.55402935,
    "longitude": -79.74976638,
    "airport_geom": "POINT(-79.74976638 37.55402935)",
    "elevation": 1000,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Buchanan",
    "state_abbreviation": "VA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "11253",
    "global_id": "07BBAE9F-D196-4DC4-B7DB-CE3AA9D3E100",
    "faa_identifier": "4NY8",
    "name": "Harris Hill",
    "latitude": 42.12091592,
    "longitude": -76.90107414,
    "airport_geom": "POINT(-76.90107414 42.12091592)",
    "elevation": 1709,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Elmira",
    "state_abbreviation": "NY",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "13932",
    "global_id": "0A4B2E93-19F1-4994-AEE2-B5DBAF59CEB9",
    "faa_identifier": "SC79",
    "name": "Bermuda High",
    "latitude": 34.61127287,
    "longitude": -80.44979476,
    "airport_geom": "POINT(-80.44979476 34.61127287)",
    "elevation": 550,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Lancaster",
    "state_abbreviation": "SC",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "2795",
    "global_id": "EB9793BC-8637-4A11-AA28-B85C3C5C2F01",
    "faa_identifier": "4CO2",
    "name": "Owl Canyon",
    "latitude": 40.80471156,
    "longitude": -104.9849825,
    "airport_geom": "POINT(-104.9849825 40.80471156)",
    "elevation": 5545,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Wellington",
    "state_abbreviation": "CO",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "7879",
    "global_id": "F0B7464C-CAA2-4BB6-8085-21070EBB47CE",
    "faa_identifier": "13M",
    "name": "Aeronut Park",
    "latitude": 42.60417485,
    "longitude": -83.8586158,
    "airport_geom": "POINT(-83.8586158 42.60417485)",
    "elevation": 980,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Howell",
    "state_abbreviation": "MI",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Public",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "5038",
    "global_id": "E5A6ED47-D70F-473D-A1A8-1A9F7CE863DF",
    "faa_identifier": "3H5",
    "name": "Erie Air Park",
    "latitude": 41.68242435,
    "longitude": -90.07861755,
    "airport_geom": "POINT(-90.07861755 41.68242435)",
    "elevation": 600,
    "icao_id": None,
    "airport_type": "Ultralightport",
    "service_city": "Erie",
    "state_abbreviation": "IL",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Public",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "17227",
    "global_id": "7E857160-ED3C-4626-93C1-732F4FFDC03D",
    "faa_identifier": "15S",
    "name": "Lester State",
    "latitude": 47.2151168,
    "longitude": -121.4623305,
    "airport_geom": "POINT(-121.4623305 47.2151168)",
    "elevation": 1693,
    "icao_id": None,
    "airport_type": "Ultralightport",
    "service_city": "Lester",
    "state_abbreviation": "WA",
    "country": "United States",
    "oper_status": "Indefinite",
    "airport_use": "Public",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "2536",
    "global_id": "8D867395-60D3-4834-A980-316982C89610",
    "faa_identifier": "CO28",
    "name": "Suckla Farms",
    "latitude": 40.05832341,
    "longitude": -104.8922079,
    "airport_geom": "POINT(-104.8922079 40.05832341)",
    "elevation": 5050,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Dacono",
    "state_abbreviation": "CO",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "16735",
    "global_id": "D603389D-790E-4B8F-BD97-E6DF2F434425",
    "faa_identifier": "VA60",
    "name": "Flying Horse Farm",
    "latitude": 39.0515039,
    "longitude": -77.77749698,
    "airport_geom": "POINT(-77.77749698 39.0515039)",
    "elevation": 450,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Unison",
    "state_abbreviation": "VA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "11559",
    "global_id": "3D293EC3-AA04-4393-A3AD-D057097ABB6E",
    "faa_identifier": "4OH6",
    "name": "Wingfoot Lake Airship Operations",
    "latitude": 41.00950913,
    "longitude": -81.35789045,
    "airport_geom": "POINT(-81.35789045 41.00950913)",
    "elevation": 1164,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Akron Suffield",
    "state_abbreviation": "OH",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "10548",
    "global_id": "CC1D172D-8954-46B9-A717-9758ACD8071A",
    "faa_identifier": "JY42",
    "name": "Mabel's",
    "latitude": 40.46834151,
    "longitude": -75.02375176,
    "airport_geom": "POINT(-75.02375176 40.46834151)",
    "elevation": 460,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Frenchtown",
    "state_abbreviation": "NJ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "19706",
    "global_id": "09CD64C9-5197-40E2-9256-3559ED916B21",
    "faa_identifier": "CT30",
    "name": "Murphy's Landing",
    "latitude": 41.66667236,
    "longitude": -73.18944569,
    "airport_geom": "POINT(-73.18944569 41.66667236)",
    "elevation": 1050,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Bethlehem",
    "state_abbreviation": "CT",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "10506",
    "global_id": "BECFAF24-2BE1-4A11-AFA7-D55DA21E8D94",
    "faa_identifier": "35JY",
    "name": "Cyber Density Balloon Spot",
    "latitude": 40.43445262,
    "longitude": -74.63472385,
    "airport_geom": "POINT(-74.63472385 40.43445262)",
    "elevation": 75,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Belle Mead",
    "state_abbreviation": "NJ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "11608",
    "global_id": "80FF2471-9F06-43BE-9533-8950810670EE",
    "faa_identifier": "NY80",
    "name": "Aurora",
    "latitude": 42.69639734,
    "longitude": -78.56916971,
    "airport_geom": "POINT(-78.56916971 42.69639734)",
    "elevation": 900,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "South Wales",
    "state_abbreviation": "NY",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "5940",
    "global_id": "BB4362AB-7DFD-490E-A6CE-C336B6B7FC5F",
    "faa_identifier": "5KS0",
    "name": "Anthony",
    "latitude": 37.09447395,
    "longitude": -97.96145675,
    "airport_geom": "POINT(-97.96145675 37.09447395)",
    "elevation": 1250,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Anthony",
    "state_abbreviation": "KS",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "10708",
    "global_id": "F2DB3A22-EC92-47C4-91D4-F8C51E83D8F3",
    "faa_identifier": "12JY",
    "name": "Clinton Elks Lodge",
    "latitude": 40.60417487,
    "longitude": -74.92083507,
    "airport_geom": "POINT(-74.92083507 40.60417487)",
    "elevation": 37,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Pittstown",
    "state_abbreviation": "NJ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "10801",
    "global_id": "65940756-C136-44B7-AAA1-EDB523CF8E8F",
    "faa_identifier": "JY33",
    "name": "Harmony",
    "latitude": 40.73950822,
    "longitude": -75.13800181,
    "airport_geom": "POINT(-75.13800181 40.73950822)",
    "elevation": 500,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Phillipsburg",
    "state_abbreviation": "NJ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "10674",
    "global_id": "4E4DE379-479D-4CE7-891F-22E726180768",
    "faa_identifier": "2JY7",
    "name": "Alba Vineyard",
    "latitude": 40.61569708,
    "longitude": -75.16416848,
    "airport_geom": "POINT(-75.16416848 40.61569708)",
    "elevation": 240,
    "icao_id": None,
    "airport_type": "Balloonport",
    "service_city": "Milford",
    "state_abbreviation": "NJ",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "12142",
    "global_id": "46E7791C-F7C3-43B9-91CD-57C4A380DD54",
    "faa_identifier": "2OH9",
    "name": "Caesar Creek Soaring Club",
    "latitude": 39.47673455,
    "longitude": -84.09382727,
    "airport_geom": "POINT(-84.09382727 39.47673455)",
    "elevation": 940,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Waynesville",
    "state_abbreviation": "OH",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "9758",
    "global_id": "49771B1D-7542-4CB8-816C-85BCA35D976A",
    "faa_identifier": "43NC",
    "name": "Bahnson",
    "latitude": 36.02084039,
    "longitude": -80.51639208,
    "airport_geom": "POINT(-80.51639208 36.02084039)",
    "elevation": 810,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Mocksville",
    "state_abbreviation": "NC",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "11076",
    "global_id": "B5E4A142-2D35-4C07-8057-8EF8DF064FB9",
    "faa_identifier": "NV23",
    "name": "Air Sailing",
    "latitude": 39.87213533,
    "longitude": -119.7010356,
    "airport_geom": "POINT(-119.7010356 39.87213533)",
    "elevation": 4300,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Sparks",
    "state_abbreviation": "NV",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "16237",
    "global_id": "17A97E72-C3B5-475C-B7A7-B3007133E374",
    "faa_identifier": "89TA",
    "name": "Soaring Club of Houston",
    "latitude": 30.19271915,
    "longitude": -95.96329606,
    "airport_geom": "POINT(-95.96329606 30.19271915)",
    "elevation": 308,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Waller",
    "state_abbreviation": "TX",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "12893",
    "global_id": "F822281D-5246-4AE7-A9C5-46867D28C221",
    "faa_identifier": "1OR4",
    "name": "North Plains",
    "latitude": 45.60400904,
    "longitude": -123.0248432,
    "airport_geom": "POINT(-123.0248432 45.60400904)",
    "elevation": 210,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "North Plains",
    "state_abbreviation": "OR",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Conditional",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "16240",
    "global_id": "F5ACE168-FDD3-41C3-8BA1-19CB0F465EA2",
    "faa_identifier": "TE71",
    "name": "Ghsa-Wallis Glideport",
    "latitude": 29.61111626,
    "longitude": -96.02790716,
    "airport_geom": "POINT(-96.02790716 29.61111626)",
    "elevation": 127,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Wallis",
    "state_abbreviation": "TX",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "1038",
    "global_id": "F6659AE5-CD5B-4DB0-B619-F06F851B8F86",
    "faa_identifier": "4AR5",
    "name": "Lawrence Fld",
    "latitude": 35.37083984,
    "longitude": -90.75056165,
    "airport_geom": "POINT(-90.75056165 35.37083984)",
    "elevation": 284,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Cherry Valley",
    "state_abbreviation": "AR",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "12091",
    "global_id": "E5CA5D08-6DBF-49C6-ACEF-E1258C4DC2F3",
    "faa_identifier": "14OI",
    "name": "Pleasant Home Gliding Club",
    "latitude": 40.91923074,
    "longitude": -82.11404567,
    "airport_geom": "POINT(-82.11404567 40.91923074)",
    "elevation": 1050,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Pleasant Home",
    "state_abbreviation": "OH",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "4983",
    "global_id": "0DCDD88A-FEB9-46E9-9019-0D66DEA5AD12",
    "faa_identifier": "IL59",
    "name": "Chicago Glider Club",
    "latitude": 41.43198274,
    "longitude": -88.24729116,
    "airport_geom": "POINT(-88.24729116 41.43198274)",
    "elevation": 590,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Channahon",
    "state_abbreviation": "IL",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "11243",
    "global_id": "92A10121-2328-4FE6-944C-8F6E2919F63B",
    "faa_identifier": "NY77",
    "name": "Wandervogel",
    "latitude": 42.71813974,
    "longitude": -74.1634633,
    "airport_geom": "POINT(-74.1634633 42.71813974)",
    "elevation": 1260,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Delanson",
    "state_abbreviation": "NY",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "No Objection",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "2290",
    "global_id": "39FE6935-A2DE-44D1-97BF-E672C421250C",
    "faa_identifier": "CN12",
    "name": "Williams",
    "latitude": 39.1635073,
    "longitude": -122.1316545,
    "airport_geom": "POINT(-122.1316545 39.1635073)",
    "elevation": 68,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "Williams",
    "state_abbreviation": "CA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  },
  {
    "id": 2081,
    "value_column": "airport_type",
    "object_id": "2196",
    "global_id": "E5D8CF07-4E56-45DE-A962-E6F1FD4CBC3E",
    "faa_identifier": "CA84",
    "name": "Torrey Pines",
    "latitude": 32.889727,
    "longitude": -117.2469564,
    "airport_geom": "POINT(-117.2469564 32.889727)",
    "elevation": 372,
    "icao_id": None,
    "airport_type": "Gliderport",
    "service_city": "San Diego",
    "state_abbreviation": "CA",
    "country": "United States",
    "oper_status": "Operational",
    "airport_use": "Private",
    "iap_exists": False,
    "dod_hiflip": False,
    "far_91": False,
    "far_93": False,
    "mil_code": "CIVIL",
    "airspace_analysis": "Not Analyzed",
    "us_high": False,
    "us_low": False,
    "ak_high": False,
    "ak_low": False,
    "us_area": False,
    "pacific": False
  }
]
