V2_FIND_ALL_PAGING_DATATABLES = "/v2/assignment-q/find-all-paging-datatables"
V2_ASSIGN_TO_USER = "/v2/assignment-q/assign-to-user"
V2_RESOLVE_ASSIGNMENT = "/v2/assignment-q/resolve"
V2_INVALIDATE_ASSIGNMENT = "/v2/assignment-q/invalidate"
V2_ASSIGNMENT_Q_INVALIDATE = "/v2/assignment-q/invalidate"
V2_ASSIGNMENT_Q_GET = "/v2/assignment-q/get"
