V2_OWL_OPTIONS_GET = "/v2/owl-options/get"
V2_OWL_OPTIONS_CLONE = "/v2/owl-options/clone"
V2_OWL_OPTIONS_GENERATE_TEMPORARY_DATASET_NAME = "/v2/owl-options/generateTemporaryDatasetName"
V2_UPSERT_OWL_OPTIONS = "/v2/upsertOwlOptions"
V2_UPSERT_LOAD_OPT = "/v2/upsertLoadOpt"
V2_DELETE_OWL_OPTIONS = "/v2/deleteOwlOptions"
V2_OWL_OPTIONS_DISTINCT_USERNAMES = "/v2/owl-options/distinctUserNames"
