V2_GET_RUN_IDS_BY_DATASET = "/v2/getrunidsbydataset"
V2_GET_LATEST_DATASET_HISTORY = "/v2/get-latest-dataset-history"
V2_GET_DATASET_HISTORY_RUN_ID = "/v2/getdatasethistoryrunid"
V2_DEPLOYMENT_TYPE = "/v2/deployment/type"
V2_GET_COUNT_IN_TRAINING = "/v2/getcountintraining"
V2_GET_UI_TIMEOUT = "/v2/getuitimeout"
V2_GET_RECENT_RUNS = "/v2/getrecentruns"
