V2_GET_PROFILE_DELTA = "/v2/getprofiledeltasbyrunid"
V2_GET_FILTERGRAM = "/v2/getfiltergram"
V2_GET_DATA_HISTOGRAM = "/v2/getdatahistogram"
V2_GET_DATASET_SCHEMA = "/v2/getdatasetschema"
V2_GET_DATASET_CORR = "/v2/getdatasetcorr"
V2_GET_RUN_IDS_BY_DATASET_DESC = "/v2/getrunidsbydatasetdesc"
V2_GET_DATASET_SCHEMA_AND_STATS = "/v2/getdatasetschemaandstats"
