V2_CMD_LINE2_JSON = "/v2/cmdline2json"
V2_GET_OWL_CHECK_Q_BY_AGENT_ID = "/v2/getowlcheckqbyagentid"
V2_GET_OWL_CHECK_INVENTORY = "/v2/getowlcheckinventory"
V2_GET_OWL_CHECKLIST = "/v2/getowlchecklist"
V2_GET_AGENT_Q_BY_DATASET_RUN_ID = "/v2/getagentqbydatasetrunid"
