# pylint: disable-msg=import-error
from payloads.pullup.pl_outlier_year_by_month import (
    DS_OUTLIER_YEAR_BY_MONTH,
    RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
)

EXPECTED_OUTLIER_YEAR_BY_MONTH = {
    "data": [
        {
            "id": 21143,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "a2dJKfUelDjBWf9oA1t74/X38fKOCWvmlcn5FGa/Ok6CY9NCZXFiAnf43doZioWm",
            "outColumn": "VOLUME",
            "outValue": "600.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "0.0",
            "outCount": 1,
            "keyArr": ["GJH"],
            "lb": 0,
            "ub": 0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40123, "uuid": "ad066926-877e-4fe2-9b42-a74e408f4453"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21144,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "ImWRrgxPQzy75chGuGW/bYOYuFzTx1Cc0bHpOwmMaOcs19j6yawuj3Q7SD8BLNUq",
            "outColumn": "VOLUME",
            "outValue": "100.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "0.0",
            "outCount": 1,
            "keyArr": ["GJP"],
            "lb": 0,
            "ub": 0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40124, "uuid": "809c3e04-b4d1-4f4a-9acb-efc6b87734ac"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21145,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "X41ZDINXF5umQvv6+KYIIMtRFAZdObf+hJfjS9ma/PDQ9GTwZQa9vCDYonk6gufE",
            "outColumn": "VOLUME",
            "outValue": "12400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "0.0",
            "outCount": 1,
            "keyArr": ["GYB"],
            "lb": -150,
            "ub": 250,
            "confidence": 2,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40125, "uuid": "500f23c7-0891-4276-bfac-ee8ab8e4bf4e"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21146,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "caIZpcuRNGfHqYbl+Vmz7bQGq278L+OS3RrRWljARmXix1oOEmCva1jC+JeCV/72",
            "outColumn": "VOLUME",
            "outValue": "125000.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "700.0",
            "outCount": 1,
            "keyArr": ["GIG.U"],
            "lb": -8100,
            "ub": 13500,
            "confidence": 10,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40126, "uuid": "c00bba26-be26-4917-bc11-31331310e617"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21147,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "63r7VpmzsCKs7XtP5frvOxvfec5mJ8CczEpJo3qvIaGHvaPR1vibSktvF+CTro++",
            "outColumn": "VOLUME",
            "outValue": "23700.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "1300.0",
            "outCount": 1,
            "keyArr": ["HT-E"],
            "lb": -2400,
            "ub": 4000,
            "confidence": 16,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40127, "uuid": "5da5b8d4-0072-48a1-a913-0f993fac4991"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21148,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "Zd2KJ2EUdhNe7h480PzNgyxcCV8xKZE98G800UuSfD2FKtQzKmHnO+JZpcW8WxQ1",
            "outColumn": "VOLUME",
            "outValue": "9300.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "500.0",
            "outCount": 1,
            "keyArr": ["GFY"],
            "lb": -1050,
            "ub": 1750,
            "confidence": 18,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40128, "uuid": "fd3bf3e1-3f1a-4c2d-a2af-491fda2ed95f"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21149,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "IVYw600EAtypii3adfC88PwFuZEkddJo8ZMdll+iifet0WVtcHbwrBNugztDXCuV",
            "outColumn": "VOLUME",
            "outValue": "456400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "15200.0",
            "outCount": 1,
            "keyArr": ["FEDU"],
            "lb": -55200,
            "ub": 92000,
            "confidence": 20,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40129, "uuid": "7750e377-12eb-4721-9ec8-154240c93049"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21150,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "1GSre6K2l+hAeXbjPQJeeshTIXxSW7Rf9Lne7EtS/pb+h9RZ6rTW7PFMgN68umWc",
            "outColumn": "VOLUME",
            "outValue": "1700.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "100.0",
            "outCount": 1,
            "keyArr": ["HT-C"],
            "lb": -300,
            "ub": 500,
            "confidence": 29,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40130, "uuid": "0ea26a38-4c08-4d93-af5e-03d2139f04dc"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21151,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "NetDRQrqGYC280pQCJt65ilNCdzvx14Tz0pJUjpWLM8V8inhI9QfiQNxe/97B2Ql",
            "outColumn": "VOLUME",
            "outValue": "12000.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "1100.0",
            "outCount": 1,
            "keyArr": ["IIP-A"],
            "lb": -2700,
            "ub": 4500,
            "confidence": 37,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40131, "uuid": "2faaadf3-3e2e-4efe-ac09-7978678ccacd"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21152,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "pVHKGLJ4T9wuazkuSH6UCJsrCR6n/0fb+xViNB7rXzoVJ8QYE5C1hX9SrMt1/vxc",
            "outColumn": "VOLUME",
            "outValue": "67400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "14200.0",
            "outCount": 1,
            "keyArr": ["FRC-H"],
            "lb": -22050,
            "ub": 36750,
            "confidence": 54,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40132, "uuid": "fa3a869f-f310-4ad9-8aaa-1141b8ba8ac9"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21153,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "TKMa6JffgM6Vo2NZKAnPCMFqKIKE1K2Yj3M9G9/cG6+pfDr5IJx8RzagoJQNtEuQ",
            "outColumn": "VOLUME",
            "outValue": "578300.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "107700.0",
            "outCount": 1,
            "keyArr": ["HOME"],
            "lb": -190050,
            "ub": 316750,
            "confidence": 54,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40133, "uuid": "3697c5e6-aa17-47a2-8e8f-b543f2ab673f"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21154,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "u2tjbjCVaeeUW1OvwbMApdhks3Ch/DFYDpwpNJOo9YtBfrnS/tR+ZcWJ8uW6mj+P",
            "outColumn": "VOLUME",
            "outValue": "12400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "2100.0",
            "outCount": 1,
            "keyArr": ["GSL-B"],
            "lb": -4500,
            "ub": 7500,
            "confidence": 60,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40134, "uuid": "cbeafc90-fc1b-4e63-9d08-593ac0841370"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21155,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "uNq9dIZnFi385uL2KslEHVnBW4s7JNk/0cMfWm2hQWHFKInPpnNoIRrzhyjgTtoK",
            "outColumn": "VOLUME",
            "outValue": "284300.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "69200.0",
            "outCount": 1,
            "keyArr": ["INSW"],
            "lb": -110100,
            "ub": 183500,
            "confidence": 64,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40135, "uuid": "9f9ad7ad-8d45-4606-bcf8-8542e9ac4123"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21156,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "RNH2I8fcSdPIa8nK7O7eIBu9YsFsZbNHV5b7a+aWPchXYBhC7gtKnz/6lPb/K3x1",
            "outColumn": "VOLUME",
            "outValue": "1747400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "386800.0",
            "outCount": 1,
            "keyArr": ["GNRT"],
            "lb": -682650,
            "ub": 1137750,
            "confidence": 65,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40136, "uuid": "fafd4a90-d2b5-45ac-8728-c928f88f2838"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21157,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "dECErfZYFbHn6gMM9VG3VafnprP1aKwQpP/PpJ1UAZ5D9MC/+vysj+zy4RqYXmZ1",
            "outColumn": "VOLUME",
            "outValue": "206100.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "52800.0",
            "outCount": 1,
            "keyArr": ["INB"],
            "lb": -86250,
            "ub": 143750,
            "confidence": 69,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40137, "uuid": "3c1ef777-f998-4678-b503-25a8112ef9a2"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21158,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "EpvVqsVdBk6/iLBMim0pGgzSCzLlmMGJqxpZyP8U22nLVRl1VSGVCQdDpLf3Sv38",
            "outColumn": "VOLUME",
            "outValue": "10100.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "2400.0",
            "outCount": 1,
            "keyArr": ["FRC-G"],
            "lb": -4500,
            "ub": 7500,
            "confidence": 74,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40138, "uuid": "63841007-3b63-4b03-9308-e9857b39b137"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21159,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "vhPRDebjk1BbR0WtZlaOmXiOw+6byNgFva72F+Zk1TeuLBhVYLYUUJcGCzT6qlYG",
            "outColumn": "VOLUME",
            "outValue": "6400.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "700.0",
            "outCount": 1,
            "keyArr": ["HK.W"],
            "lb": -2850,
            "ub": 4750,
            "confidence": 74,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40139, "uuid": "74a7ed20-2dcc-4506-a799-3c51864b9539"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21160,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "VspU0czL0sg+6SLk2yOUsUO7+IenU0VCdayJ73eiCaL4XOfOdmYtosYQZXDkzOCG",
            "outColumn": "VOLUME",
            "outValue": "15300.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "2400.0",
            "outCount": 1,
            "keyArr": ["FNB-E"],
            "lb": -7350,
            "ub": 12250,
            "confidence": 80,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40140, "uuid": "3eb691ca-1f3a-4bad-9258-e18b16d0217e"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21161,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "HQmvOG8tbf/LkdcrOGn0UfewDeKvRBDy7tb9i7Rbc507mNsK1kaXFzBBMxK9x9sG",
            "outColumn": "VOLUME",
            "outValue": "53200.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "11400.0",
            "outCount": 1,
            "keyArr": ["IRL"],
            "lb": -25800,
            "ub": 43000,
            "confidence": 80,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40141, "uuid": "d9386025-7d69-476a-ad71-f15de34f372c"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21162,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "yPlS1aeLe4pgpQVSGLZsnh3iclAYspy17cyRNHqGZ+wrnmtyiKMfmD8ZG1AhHfgM",
            "outColumn": "VOLUME",
            "outValue": "1.50752E7",
            "obsSubType": "NUMERICAL",
            "outMedian": "4508600.0",
            "outCount": 1,
            "keyArr": ["IBN"],
            "lb": -7492500,
            "ub": 12487500,
            "confidence": 82,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40142, "uuid": "d9967c16-0711-4be8-b5ca-466dae03e007"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21163,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "sYa/whAYsS/2vx26I5yE/7mfQ4eRMCWoqtPrVKxgeHagaFLEEC5GUlm68GlVAudw",
            "outColumn": "VOLUME",
            "outValue": "1500.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "0.0",
            "outCount": 1,
            "keyArr": ["GYC"],
            "lb": -750,
            "ub": 1250,
            "confidence": 83,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40143, "uuid": "42af5f6a-29a2-448d-bff9-55c3a9cf84d9"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21164,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "sTs+wwLRnTtiFkIGOjhmx5ZKxCg8Em5khz1kpbw+1d8GdwUjvaLnBFZyi6+gpiJQ",
            "outColumn": "VOLUME",
            "outValue": "20900.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "5800.0",
            "outCount": 1,
            "keyArr": ["IRE-C"],
            "lb": -10500,
            "ub": 17500,
            "confidence": 83,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40144, "uuid": "20b57544-16c4-4456-93ca-07fd8c00d5be"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21165,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "tzqPH0cE9xY0fQCCqrgN6QHPz8A8wMX/IGhsDY58R5Lg3UXK5IxycY9O2VPrR9cK",
            "outColumn": "VOLUME",
            "outValue": "2.38361E7",
            "obsSubType": "NUMERICAL",
            "outMedian": "6623400.0",
            "outCount": 1,
            "keyArr": ["GG"],
            "lb": -12327750,
            "ub": 20546250,
            "confidence": 86,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40145, "uuid": "27ee23bc-9013-47ef-8a59-672d5c016bfc"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21166,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "CtUorVMp/V7qnO4AQfReW6GgVZbRwvnYdyig46+1jAvrQwXc3q3frVSc1sP45ghD",
            "outColumn": "VOLUME",
            "outValue": "644200.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "210600.0",
            "outCount": 1,
            "keyArr": ["IO"],
            "lb": -332850,
            "ub": 554750,
            "confidence": 86,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40146, "uuid": "307605f0-d417-42ed-ba1e-67b1c4cbeaa0"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21167,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "n35Q/c32m6g0JqscRgu1ptAEAMQzSoY1iPdhw+TPXFbGIciwsuJ69lVvwHxsXNN6",
            "outColumn": "VOLUME",
            "outValue": "72900.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "18400.0",
            "outCount": 1,
            "keyArr": ["GDL"],
            "lb": -39450,
            "ub": 65750,
            "confidence": 90,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40147, "uuid": "0ef5cd1c-b002-4e5a-bd4f-e94457ee4422"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21168,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "GpwFgnBfjiaO4lszFRaAZM+MWrA8i0bLF8SEjaKo+/CrMiEHJ3/M2/ZY/oJtT0p7",
            "outColumn": "VOLUME",
            "outValue": "6578600.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "1632000.0",
            "outCount": 1,
            "keyArr": ["HMY"],
            "lb": -3642000,
            "ub": 6070000,
            "confidence": 92,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40148, "uuid": "a5c95d55-ab8e-429e-bffa-f4fbd9fe68fa"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21169,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "rLWWRR07EWOtqliO1K7fo9zf22Gp6c+2H0pTCNXX3NDCCnC6sppQtVHp4oSbFiF3",
            "outColumn": "VOLUME",
            "outValue": "2900.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "900.0",
            "outCount": 1,
            "keyArr": ["EZT"],
            "lb": -1650,
            "ub": 2750,
            "confidence": 94,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40149, "uuid": "e9d06d5d-e690-4792-9985-560696241cb0"},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 21170,
            "dataset": DS_OUTLIER_YEAR_BY_MONTH,
            "runId": RUN_DATE_OUTLIER_YEAR_BY_MONTH_FULL,
            "outKeyColumn": "SYMBOL",
            "outKey": "/HxvDV0QJb7RmyqH5JcrtMn2ViZWb5UzOGzHzJyEKI4qUiAHRfIji9qjXdA61eEF",
            "outColumn": "VOLUME",
            "outValue": "70800.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "14900.0",
            "outCount": 1,
            "keyArr": ["GEH"],
            "lb": -40950,
            "ub": 68250,
            "confidence": 96,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {"id": 40150, "uuid": "ce9eb911-103a-4c09-8e6e-ef5bf8b7bec2"},
            "obsType": "OUTLIER_NUMERICAL",
        },
    ]
}
