from payloads.pullup.pl_pullup_test_all_rule_types import (
    PULLUP_TEST_ALL_RULE_TYPES_DATASET,
)

PULLUP_TEST_ALL_RULE_TYPES_RULE_DEFINITIONS = [
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlf_pass_rule",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                     f"where A.volume.$min > 1",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "if_part_date_str_is_DATE_YYYY-MM-DD",
        "ruleType": "CUSTOM",
        "ruleValue": "part_date_str",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "DATE YYYY-MM-DD",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "part_date_str",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": 4,
        "dimName": "VALIDITY",
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "native_close_notnullchk_allrecords_break",
        "ruleType": "NATIVE",
        "ruleValue": "select * from nyse_regular where nyse_regular.\"close\" is not null",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlf_close_206_br",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A where A.close = 25.3",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "if_trade_date_is_valid_DATE_YYYY-MM-DD",
        "ruleType": "CUSTOM",
        "ruleValue": "trade_date",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "DATE YYYY-MM-DD",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "trade_date",
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "native_partdatestr_nullcheck_allpass",
        "ruleType": "NATIVE",
        "ruleValue": "select * from nyse_regular where nyse_regular.\"part_date_str\" is null",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "part_date_str",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "partdatestr_passrule",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                     f"where A.part_date_str = '2023-12-19 00:00:00.0'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "part_date_str",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlf_stat_br",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                     f"where A.volume.$min < 1",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlg_close_206_br",
        "ruleType": "SQLG",
        "ruleValue": "close = 25.3",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlg_partdate_str_passrule",
        "ruleType": "SQLG",
        "ruleValue": "part_date_str = '2023-12-19 00:00:00.0'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "part_date_str",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlg_stat_volume_br",
        "ruleType": "SQLG",
        "ruleValue": "volume.$min < 1",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "volume",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
        "ruleNm": "sqlg_stat_volume_passrule",
        "ruleType": "SQLG",
        "ruleValue": "volume.$min > 1",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "volume",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "{\"condition\":\"AND\",\"rules\":[{\"id\":null,\"field\":null,"
                            "\"type\":null,\"input\":null,\"operator\":null}],\"not\":false,"
                            "\"valid\":false}",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0,
        "active": True
    }
]

PULLUP_TEST_ALL_RULE_TYPES_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlf_pass_rule",
            "ruleType": "SQLF",
            "ruleValue": f"select * from {PULLUP_TEST_ALL_RULE_TYPES_DATASET}_dataset A "
                         f"where 0 > 1 ",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439416,
                "uuid": "0f3999f9-df60-425a-acb2-866b31e1b8da"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                             f"where A.volume.$min > 1",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "if_part_date_str_is_DATE_YYYY-MM-DD",
            "ruleType": "CUSTOM",
            "ruleValue": "part_date_str",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439417,
                "uuid": "252a6172-97f0-4edb-b787-9dcb076d7f63"
            },
            "dimId": 4,
            "dimName": "VALIDITY",
            "ruleCondition": "part_date_str",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "native_close_notnullchk_allrecords_break",
            "ruleType": "NATIVE",
            "ruleValue": "select * from nyse_regular where nyse_regular.\"close\" is not null",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 439414,
                "uuid": "bc059265-9efb-4d17-bcb0-4ea0d5a63d25"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from nyse_regular where nyse_regular.\"close\" is not null",
            "totalCount": 102815,
            "rowsBreaking": 102815,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlf_close_206_br",
            "ruleType": "SQLF",
            "ruleValue": f"select * from {PULLUP_TEST_ALL_RULE_TYPES_DATASET}_dataset A "
                         f"where A.close = 25.3 ",
            "filterQuery": None,
            "score": 0,
            "perc": 0.20035987254232168,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 439424,
                "uuid": "d0af685f-f5b6-4b7a-8dda-71033a5dc425"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                             f"where A.close = 25.3",
            "totalCount": 102815,
            "rowsBreaking": 206,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "if_trade_date_is_valid_DATE_YYYY-MM-DD",
            "ruleType": "CUSTOM",
            "ruleValue": "trade_date",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439418,
                "uuid": "a3193605-7b2b-461e-8ebb-fc511fed2c28"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "trade_date",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "native_partdatestr_nullcheck_allpass",
            "ruleType": "NATIVE",
            "ruleValue": "select * from nyse_regular where nyse_regular.\"part_date_str\" is null",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439415,
                "uuid": "a25f46e0-a68b-433e-a367-6c2d590850ed"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from nyse_regular "
                             "where nyse_regular.\"part_date_str\" is null",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "partdatestr_passrule",
            "ruleType": "SQLF",
            "ruleValue": f"select * from {PULLUP_TEST_ALL_RULE_TYPES_DATASET}_dataset A "
                         f"where A.part_date_str = '2023-12-19 00:00:00.0' ",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439419,
                "uuid": "b515de8f-864f-4fb5-bd5f-296d8928d090"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                             f"where A.part_date_str = '2023-12-19 00:00:00.0'",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlf_stat_br",
            "ruleType": "SQLF",
            "ruleValue": f"select * from {PULLUP_TEST_ALL_RULE_TYPES_DATASET}_dataset A "
                         f"where 0 < 1 ",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 439421,
                "uuid": "ec26fb36-170c-419f-b586-4ba538e65ff1"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"select * from @{PULLUP_TEST_ALL_RULE_TYPES_DATASET} A "
                             f"where A.volume.$min < 1",
            "totalCount": 102815,
            "rowsBreaking": 102815,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlg_close_206_br",
            "ruleType": "SQLG",
            "ruleValue": "close = 25.3",
            "filterQuery": None,
            "score": 0,
            "perc": 0.20035987254232168,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 439420,
                "uuid": "24efb7c6-13e2-4e75-948d-6b4fcd6bf17b"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "close = 25.3",
            "totalCount": 102815,
            "rowsBreaking": 206,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlg_partdate_str_passrule",
            "ruleType": "SQLG",
            "ruleValue": "part_date_str = '2023-12-19 00:00:00.0'",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439423,
                "uuid": "f2510a53-4063-451b-8514-1edac2eef323"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "part_date_str = '2023-12-19 00:00:00.0'",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlg_stat_volume_br",
            "ruleType": "SQLG",
            "ruleValue": "0 < 1",
            "filterQuery": None,
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 439425,
                "uuid": "70af0803-b707-4ff9-a07c-bad56d0a0c2f"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "volume.$min < 1",
            "totalCount": 102815,
            "rowsBreaking": 102815,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_TEST_ALL_RULE_TYPES_DATASET,
            "runId": "2024-11-13T00:00:00.000+0000",
            "ruleNm": "sqlg_stat_volume_passrule",
            "ruleType": "SQLG",
            "ruleValue": "0 > 1",
            "filterQuery": None,
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 439422,
                "uuid": "19d18cf5-108c-41da-a083-50d2bfcaafbd"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "volume.$min > 1",
            "totalCount": 102815,
            "rowsBreaking": 0,
            "tolerance": 0,
            "ruleStatus": "PASSING"
        }
    ]
}
