from payloads.pullup.pl_pullup_rules_filter_tolerance_sales import (
    PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
)

PULLUP_RULES_FILTER_TOLERANCE_SALES_RULE_DEFINITIONS = [
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_filter_and_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "SALES > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "NAME = 'Steve'",
        "tolerance": 30,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_no_filter",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_filter",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "SALES = 1000",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_no_filter",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_filter",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "SALES = 1000",
        "tolerance": 0,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_breaking_rows_above_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 10,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Simple_breaking_rows_below_tolerance",
        "ruleType": "SQLG",
        "ruleValue": "TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 30,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_breaking_rows_above_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 10,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_breaking_rows_below_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 50,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "FF_filter_and_tolerance",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                     f"WHERE SALES > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "NAME = 'Steve'",
        "tolerance": 30,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Native_no_filter",
        "ruleType": "NATIVE",
        "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 0,
        "active": True

    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Native_breaking_rows_above_tolerance",
        "ruleType": "NATIVE",
        "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 10,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Native_breaking_rows_below_tolerance",
        "ruleType": "NATIVE",
        "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "",
        "tolerance": 50,
        "active": True
    },
    {
        "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
        "ruleNm": "Native_filter",
        "ruleType": "NATIVE",
        "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": "SALES = 1000",
        "tolerance": 0,
        "active": True
    }
]

PULLUP_RULES_FILTER_TOLERANCE_SALES_EXPECTED_RULE_OUTPUT = {
    "data": [
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_filter_and_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "SALES > 1000",
            "filterQuery": "NAME = 'Steve'",
            "score": 0,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1655913,
                "uuid": "15b73c4a-d947-4a62-9e1b-45b59e1a9cbf"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "SALES > 1000",
            "totalCount": 5,
            "rowsBreaking": 1,
            "tolerance": 30,
            "ruleStatus": None
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_no_filter",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-01'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601924,
                "uuid": "f4c9fd00-bdb9-48c5-9397-d544d0ea75dc"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-01'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_filter",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-01'",
            "filterQuery": "SALES = 1000",
            "score": 50,
            "perc": 50.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601930,
                "uuid": "f4bd472a-1d49-4ba8-a36d-e1ed6e04edc6"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-01'",
            "totalCount": 2,
            "rowsBreaking": 1,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_breaking_rows_below_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 0,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601926,
                "uuid": "170ea08c-b8eb-4b2c-a1fa-1367205cf3fb"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 30,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "Simple_breaking_rows_above_tolerance",
            "ruleType": "SQLG",
            "ruleValue": "TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601925,
                "uuid": "3563223a-699e-47b3-ad9a-f73805980b30"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 10,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_no_filter",
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET}_dataset "
                         f"WHERE TRDATE = '2022-05-01' ",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601929,
                "uuid": "47f9b184-fc9d-4da2-8d67-55c757a87637"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-01'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_filter_and_tolerance",
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET}_dataset "
                         f"WHERE SALES > 1000 ",
            "filterQuery": "NAME = 'Steve'",
            "score": 0,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601932,
                "uuid": "80775d7b-0a1a-4286-935c-712e1d639d95"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE SALES > 1000",
            "totalCount": 5,
            "rowsBreaking": 1,
            "tolerance": 30,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_filter",
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET}_dataset "
                         f"WHERE TRDATE = '2022-05-01' ",
            "filterQuery": "SALES = 1000",
            "score": 50,
            "perc": 50.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601931,
                "uuid": "df951db4-239a-4cff-ae28-6ffe7908589c"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-01'",
            "totalCount": 2,
            "rowsBreaking": 1,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_breaking_rows_below_tolerance",
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET}_dataset "
                         f"WHERE TRDATE = '2022-05-03' ",
            "filterQuery": "",
            "score": 0,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 1601928,
                "uuid": "cb20e8af-1f68-4bb4-b4bf-edafca3488a3"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 50,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-17T00:00:00.000+0000",
            "ruleNm": "FF_breaking_rows_above_tolerance",
            "ruleType": "SQLF",
            "ruleValue": f"SELECT * FROM {PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET}_dataset "
                         f"WHERE TRDATE = '2022-05-03' ",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 1601927,
                "uuid": "a9d76523-5e77-4073-9aae-897bee5ebb6d"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": f"SELECT * FROM @{PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET} "
                             f"WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 10,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-25T00:00:00.000+0000",
            "ruleNm": "Native_no_filter",
            "ruleType": "NATIVE",
            "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 509591,
                "uuid": "f925efd5-b249-4c5b-9817-ed9440b5a7df"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-25T00:00:00.000+0000",
            "ruleNm": "Native_breaking_rows_above_tolerance",
            "ruleType": "NATIVE",
            "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 20,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 509603,
                "uuid": "21d99aa4-7a99-4a4c-aee5-d3e6f920d7b7"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 10,
            "ruleStatus": "BREAKING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-25T00:00:00.000+0000",
            "ruleNm": "Native_breaking_rows_below_tolerance",
            "ruleType": "NATIVE",
            "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
            "filterQuery": "",
            "score": 0,
            "perc": 20.000000298023224,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {
                "id": 509630,
                "uuid": "016ef477-a09c-47bc-a13c-254558624239"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-03'",
            "totalCount": 10,
            "rowsBreaking": 2,
            "tolerance": 50,
            "ruleStatus": "PASSING"
        },
        {
            "dataset": PULLUP_RULES_FILTER_TOLERANCE_SALES_DATASET,
            "runId": "2024-11-25T00:00:00.000+0000",
            "ruleNm": "Native_filter",
            "ruleType": "NATIVE",
            "ruleValue": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
            "filterQuery": "SALES = 1000",
            "score": 50,
            "perc": 50.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {
                "id": 27336,
                "uuid": "9ad2ae7a-bbe3-426d-8761-9156ca5d7dfc"
            },
            "dimId": None,
            "dimName": None,
            "ruleCondition": "select * from PUBLIC.SALES WHERE TRDATE = '2022-05-01'",
            "totalCount": 2,
            "rowsBreaking": 1,
            "tolerance": 0,
            "ruleStatus": "BREAKING"
        }
    ]
}

PULLUP_RULES_FILTER_TOLERANCE_SALES_FF_FILTER_AND_TOLERANCE_EXPECTED_RULE_DATA_PREVIEW = {
    "draw": 1,
    "recordsTotal": 1,
    "recordsFiltered": 1,
    "dataAssetList": [
        {
            "NAME": "Steve",
            "owl_id": "9",
            "SALES": "10000",
            "TRDATE": "2022-05-05"
        }
    ],
    "data": None
}
