MISMATCH_LIST_FILTER_MISMATCH_SRC_TYPE = [
    "VALIDATE_SOURCE_SCHEMA",
    "VALIDATE_SOURCE_VALUE",
    "VALIDATE_SOURCE_COUNT",
]
EXP_PG_DTS_FILTER_MISMATCH_SRC_TYPE = {
    "BEHAVIOR": 0,
    "OUTLIER": 3,
    "DATASHAPE": 25,
    "RULE": 0,
    "DUPE": 1,
    "SUGGESTIVE": 1,
    "RECORD_CHANGES": 1,
    "SCHEMA_EVOLUTION": 0,
    "MISMATCH_SRC": 13,
    "VALIDATE_SOURCE_SCHEMA": 0,
    "VALIDATE_SOURCE_COUNT": 1,
    "VALIDATE_SOURCE_VALUE": 12,
}
EXP_ISSUE_COUNT_FILTER_MISMATCH_SRC_TYPE = {
    "SHAPE": 25,
    "OUTLIER": 3,
    "PATTERN": 1,
    "SCHEMA": 0,
    "DUPE": 1,
    "SOURCE": 13,
    "RECORD": 1,
    "RULE": 0,
}
