# pylint: disable-msg=import-error
from payloads.pullup.pl_all_params_enabled import (
    DATASET_ALL_PARAMS,
    RUN_ID_ALL_PARAMS,
    RUN_ID_FULL_ALL_PARAMS,
    CONNECTION_ALL_PARAMS,
    LIB_ALL_PARAMS,
    DRIVER_NAME_ALL_PARAMS,
    QUERY_ALL_PARAMS,
    DATE_COLUMN_ALL_PARAMS,
)
from utils.constants import BASE_CREDS, PROD_HOST

EXP_CMD_LINE_ALL_PARAMS = [
    f'-lib "{LIB_ALL_PARAMS}"',
    f"-srccxn {CONNECTION_ALL_PARAMS}",
    "-fpginc tax",
    "-dl",
    "-conf spark.executor.memoryOverhead=1g",
    "-fpgkey salestate",
    f"-ds {DATASET_ALL_PARAMS}",
    "-deploymode cluster -bhlb 10",
    f"-cxn {CONNECTION_ALL_PARAMS}",
    "-numexecutors 1",
    "-executorcores 2",
    "-fpgon",
    "-drivermemory 1g",
    f'-rd "{RUN_ID_ALL_PARAMS}"',
    f'-driver "{DRIVER_NAME_ALL_PARAMS}"',
    f'-srcd "{DRIVER_NAME_ALL_PARAMS}"',
    "-dupeinc dailyid,date,email,firstname,lastname,salestate",
    f'-srcq "{QUERY_ALL_PARAMS} limit 10"',
    "-validatevalues",
    "-vs",
    f"-owluser {BASE_CREDS['username']}",
    "-fpglb 5",
    "-corron",
    f"-fpgdc {DATE_COLUMN_ALL_PARAMS}",
    "-dllb 5",
    "-bhmeanon",
    "-dupecutoff 95",
    "-datashapegranular",
    "-key salesid",
    "-dlkey dailyid",
    "-executormemory 1g",
    "-dlinc cost,email,firstname,lastname,salesid,tax,vendor",
    "-bhminon",
    f"-h {PROD_HOST}",
    "-dupe",
    "-valsrcinc cost,cost_desc,costcode,dailyid,date,email,firstname,lastname,lost_column,"
    "rep,salesid,salestate,tax,time",
    "-valsrckey salesid",
    "-master k8s://",
    f'-q "{QUERY_ALL_PARAMS}',
    "-depth 2",
    "-histon",
    "-bhmaxon",
    "-loglevel INFO",
    "-bhminsupport 3",
    "-dupenocase",
    f"-srcds {DATASET_ALL_PARAMS}",
    f'-libsrc "{LIB_ALL_PARAMS}"',
    f"-dc {DATE_COLUMN_ALL_PARAMS}",
]
EXP_OUTLIER_ALL_PARAMS = {
    "data": [
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "tax",
            "outValue": "0.115",
            "obsSubType": "NUMERICAL",
            "outMedian": "0.0",
            "outCount": 1,
            "keyArr": ["3DB"],
            "lb": 0,
            "ub": 0,
            "confidence": 0,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "239100.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "4293.12",
            "outCount": 1,
            "keyArr": ["3E7"],
            "lb": -4085.5300000000007,
            "ub": 16452.550000000003,
            "confidence": 6,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "1398.63",
            "obsSubType": "NUMERICAL",
            "outMedian": "6318.98",
            "outCount": 1,
            "keyArr": ["1C0"],
            "lb": 4107.3369999999995,
            "ub": 8530.623,
            "confidence": 34,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "1319.13",
            "obsSubType": "NUMERICAL",
            "outMedian": "5485.81",
            "outCount": 1,
            "keyArr": ["FE"],
            "lb": 2771.3599999999988,
            "ub": 8288.480000000001,
            "confidence": 47,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "7958.32",
            "obsSubType": "NUMERICAL",
            "outMedian": "2829.54",
            "outCount": 1,
            "keyArr": ["20E"],
            "lb": 1291.4900000000002,
            "ub": 5237.65,
            "confidence": 65,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "1806.75",
            "obsSubType": "NUMERICAL",
            "outMedian": "7118.38",
            "outCount": 1,
            "keyArr": ["1E6"],
            "lb": 2725.190000000002,
            "ub": 12483.509999999998,
            "confidence": 66,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "2698.17",
            "obsSubType": "NUMERICAL",
            "outMedian": "6176.01",
            "outCount": 1,
            "keyArr": ["F3"],
            "lb": 4014.4064999999996,
            "ub": 8337.613500000001,
            "confidence": 67,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8924.95",
            "obsSubType": "NUMERICAL",
            "outMedian": "2653.88",
            "outCount": 1,
            "keyArr": ["E3"],
            "lb": 139.88499999999976,
            "ub": 6761.445,
            "confidence": 75,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "6435.99",
            "obsSubType": "NUMERICAL",
            "outMedian": "1124.11",
            "outCount": 1,
            "keyArr": ["2B"],
            "lb": -1250.715,
            "ub": 5047.485,
            "confidence": 78,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "1765.4",
            "obsSubType": "NUMERICAL",
            "outMedian": "4242.43",
            "outCount": 1,
            "keyArr": ["39C"],
            "lb": 2262.3000000000006,
            "ub": 7229.74,
            "confidence": 78,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "2524.37",
            "obsSubType": "NUMERICAL",
            "outMedian": "7782.35",
            "outCount": 1,
            "keyArr": ["1FC"],
            "lb": 3107.8100000000004,
            "ub": 11048.130000000001,
            "confidence": 81,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8819.47",
            "obsSubType": "NUMERICAL",
            "outMedian": "4694.45",
            "outCount": 1,
            "keyArr": ["224"],
            "lb": 1407.7549999999997,
            "ub": 7504.275,
            "confidence": 85,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "7569.62",
            "obsSubType": "NUMERICAL",
            "outMedian": "2998.59",
            "outCount": 1,
            "keyArr": ["19B"],
            "lb": 657.3399999999988,
            "ub": 6513.020000000001,
            "confidence": 86,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8669.0",
            "obsSubType": "NUMERICAL",
            "outMedian": "2142.97",
            "outCount": 1,
            "keyArr": ["1CD"],
            "lb": -2385.68,
            "ub": 7740.639999999999,
            "confidence": 89,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "3364.33",
            "obsSubType": "NUMERICAL",
            "outMedian": "6443.56",
            "outCount": 1,
            "keyArr": ["131"],
            "lb": 3701.6800000000007,
            "ub": 10257.119999999999,
            "confidence": 90,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "3362.99",
            "obsSubType": "NUMERICAL",
            "outMedian": "8209.41",
            "outCount": 1,
            "keyArr": ["2A7"],
            "lb": 3590.144999999998,
            "ub": 11456.505000000003,
            "confidence": 93,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "7907.22",
            "obsSubType": "NUMERICAL",
            "outMedian": "2626.62",
            "outCount": 1,
            "keyArr": ["2D1"],
            "lb": -494.66999999999916,
            "ub": 7393.249999999999,
            "confidence": 93,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "6995.95",
            "obsSubType": "NUMERICAL",
            "outMedian": "3367.66",
            "outCount": 1,
            "keyArr": ["353"],
            "lb": -526.5849999999996,
            "ub": 6555.9349999999995,
            "confidence": 93,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8620.42",
            "obsSubType": "NUMERICAL",
            "outMedian": "3579.14",
            "outCount": 1,
            "keyArr": ["97"],
            "lb": -371.73,
            "ub": 8126.110000000001,
            "confidence": 94,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "2814.9",
            "obsSubType": "NUMERICAL",
            "outMedian": "6006.98",
            "outCount": 1,
            "keyArr": ["17B"],
            "lb": 2948.000000000001,
            "ub": 11059.919999999998,
            "confidence": 95,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8992.82",
            "obsSubType": "NUMERICAL",
            "outMedian": "6147.18",
            "outCount": 1,
            "keyArr": ["18A"],
            "lb": 3361.1,
            "ub": 8805.58,
            "confidence": 97,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "3781.89",
            "obsSubType": "NUMERICAL",
            "outMedian": "6814.35",
            "outCount": 1,
            "keyArr": ["192"],
            "lb": 3892.0350000000008,
            "ub": 11115.274999999998,
            "confidence": 97,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8707.99",
            "obsSubType": "NUMERICAL",
            "outMedian": "1592.32",
            "outCount": 1,
            "keyArr": ["261"],
            "lb": -2928.06,
            "ub": 8692.82,
            "confidence": 99,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "cost",
            "outValue": "8274.58",
            "obsSubType": "NUMERICAL",
            "outMedian": "3391.52",
            "outCount": 1,
            "keyArr": ["354"],
            "lb": -3148.245,
            "ub": 8218.755000000001,
            "confidence": 99,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_NUMERICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "email",
            "outValue": "gerogegotyou@qq.com",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": ["1"],
            "lb": 0,
            "ub": 0,
            "confidence": 100,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_CATEGORICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "firstname",
            "outValue": "George",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": ["1"],
            "lb": 0,
            "ub": 0,
            "confidence": 100,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_CATEGORICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "lastname",
            "outValue": "Malarachy",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": ["1"],
            "lb": 0,
            "ub": 0,
            "confidence": 100,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_CATEGORICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "vendor",
            "outValue": "Construction Expeditor",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": ["1C"],
            "lb": 0,
            "ub": 0,
            "confidence": 100,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_CATEGORICAL",
        },
        {
            "id": 0,
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "outKeyColumn": "dailyid",
            "outKey": "",
            "outColumn": "vendor",
            "outValue": "Project Manager",
            "obsSubType": "CATEGORICAL",
            "outMedian": "INVALID",
            "outCount": 1,
            "keyArr": ["2B0"],
            "lb": 0,
            "ub": 0,
            "confidence": 100,
            "owlRank": 0,
            "linkId": "",
            "linkIdArr": [""],
            "assignmentId": {},
            "obsType": "OUTLIER_CATEGORICAL",
        },
    ]
}
EXP_OBSERVATIONS_ALL_PARAMS = [
    {
        "dataset": DATASET_ALL_PARAMS,
        "runId": RUN_ID_FULL_ALL_PARAMS,
        "obsType": "SUGGESTIVE",
        "obs": " [DE DE 0.115000000000000000  -> DE 0E-18  ] ~~ [salestate,tax]",
        "obsScore": 1,
        "owlRank": 1,
        "linkId": "",
        "obsSubType": None,
    },
    {
        "dataset": DATASET_ALL_PARAMS,
        "runId": RUN_ID_FULL_ALL_PARAMS,
        "obsType": "RECORD_CHANGES",
        "obs": "Record Dropped *** dailyid -> 3D8 *** was in dataset on 2022-01-06",
        "obsScore": None,
        "owlRank": 1,
        "linkId": "",
        "obsSubType": None,
    },
    {
        "dataset": DATASET_ALL_PARAMS,
        "runId": RUN_ID_FULL_ALL_PARAMS,
        "obsType": "DUPE",
        "obs": "[score: 95 ][2022-01-07,3DE,Francine,Todarini,ftodarini1@aol.com,NY,498]"
        " || [2022-01-07,3DD,Francine,Todarini,ftodarini1o@aol.com,NY,8589934807]",
        "obsScore": 95,
        "owlRank": 1,
        "linkId": "",
        "obsSubType": None,
    },
]
EXP_SHAPES_ALL_PARAMS = {
    "data": [
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "costcode",
            "colFormat": "Double",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 1,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "Length_10",
            "colFormatCnt": 3,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.3,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "Length_12",
            "colFormatCnt": 8,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.801,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxx xxxxx",
            "colFormatCnt": 6,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.601,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxx xxxx",
            "colFormatCnt": 3,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.3,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxxx xxxx",
            "colFormatCnt": 5,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.501,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxxxx xxx",
            "colFormatCnt": 3,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.3,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxx xxxxxxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxx xxxxxx",
            "colFormatCnt": 7,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.701,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxxx xxxxx",
            "colFormatCnt": 3,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.3,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "cost_desc",
            "colFormat": "xxxxxxx xxxx",
            "colFormatCnt": 7,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.701,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 10,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "dailyid",
            "colFormat": "Length_1",
            "colFormatCnt": 9,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.901,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 2,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "dailyid",
            "colFormat": "x",
            "colFormatCnt": 6,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.601,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 2,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "email",
            "colFormat": "xxxxxxxnx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 1,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "Length_10",
            "colFormatCnt": 6,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.601,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "Length_12",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "Length_2",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "xx",
            "colFormatCnt": 4,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.4,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "xxx-xxxxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "xxxxx-xxxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "firstname",
            "colFormat": "xxxxxxxxxxxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 7,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "salestate",
            "colFormat": "Length_3",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 2,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "salestate",
            "colFormat": "xxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 2,
        },
        {
            "dataset": DATASET_ALL_PARAMS,
            "runId": RUN_ID_FULL_ALL_PARAMS,
            "colName": "vendor",
            "colFormat": "xxxxxx",
            "colFormatCnt": 1,
            "owlRank": 1,
            "linkId": None,
            "assignmentId": {},
            "percent": 0.1,
            "rowCountTotal": 999,
            "definedSchema": "String",
            "shapePerColumn": 1,
        },
    ]
}
EXP_SOURCE_COUNT_COMPARISON_ALL_PARAMS = {
    "targetRowCount": 999,
    "sourceRowCount": 10,
    "targetColCount": 14,
    "sourceColCount": 15,
    "data": [
        {
            "countType": "Dataset Row Count",
            "targetCount": 999,
            "sourceCount": 10,
            "change": 989,
            "percChange": 9890.0,
            "description": "The row size does not match. Source has 10 rows. Target has 999 rows."
            " Source-to-target difference: 989 (+9890.00%)",
        }
    ],
}
EXP_RCSRC_ALL_PARAMS = [
    {
        "runId": RUN_ID_FULL_ALL_PARAMS,
        "dataset": DATASET_ALL_PARAMS,
        "score": 0,
        "rc": 999,
        "passFail": 0,
        "peak": 1,
        "scoreDupe": 1,
        "scoreSource": 15,
        "scoreDatashape": 24,
        "scoreSchema": 0,
        "scoreRecord": 1,
        "scoreOutlier": 29,
        "scorePattern": 1,
        "scoreRule": 0,
        "scoreBehavior": 100,
        "passFailAvg": 0.0,
        "physicalName": None,
        "userLabel": None,
        "rcSrc": 10,
        "passFailRc": 1,
        "pushDownOptions": None,
        "daysWithoutData": 0,
        "runsWithoutData": 0,
        "daysSinceLastRun": 0,
    }
]
EXP_OBS_DETAILS_ALL_PARAMS = [
    {
        "data": [
            {
                "date": RUN_ID_ALL_PARAMS,
                "score": "95",
                "firstname": "Francine",
                "assignment_uuid": "",
                "item_key": "",
                "dailyid": "3DE",
                "type": "DUPE",
                "item_value": "[score: 95 ][2022-01-07,3DE,Francine,Todarini,ftodarini1@aol.com,NY,"
                "498] || [2022-01-07,3DD,Francine,Todarini,ftodarini1o@aol.com,"
                "NY,8589934807]",
                "email": "ftodarini1@aol.com",
                "lastname": "Todarini",
                "owl_id": "498",
                "salestate": "NY",
            },
            {
                "date": RUN_ID_ALL_PARAMS,
                "score": "95",
                "firstname": "Francine",
                "assignment_uuid": "",
                "item_key": "",
                "dailyid": "3DD",
                "type": "DUPE",
                "item_value": "[score: 95 ][2022-01-07,3DE,Francine,Todarini,ftodarini1@aol.com,"
                "NY,498] || [2022-01-07,3DD,Francine,Todarini,ftodarini1o@aol.com,"
                "NY,8589934807]",
                "email": "ftodarini1o@aol.com",
                "salestate": "NY",
                "lastname": "Todarini",
                "owl_id": "8589934807",
            },
        ],
        "columns": [
            {"data": "item_key", "name": "item_key", "title": "item_key"},
            {"data": "item_value", "name": "item_value", "title": "item_value"},
            {"data": "assignment_id", "name": "assignment_id", "title": "assignment_id"},
            {"data": "type", "name": "type", "title": "type"},
            {"data": "score", "name": "score", "title": "score"},
            {"data": "date", "name": "date", "title": "date"},
            {"data": "firstname", "name": "firstname", "title": "firstname"},
            {"data": "assignment_uuid", "name": "assignment_uuid", "title": "assignment_uuid"},
            {"data": "dailyid", "name": "dailyid", "title": "dailyid"},
            {"data": "email", "name": "email", "title": "email"},
            {"data": "lastname", "name": "lastname", "title": "lastname"},
            {"data": "owl_id", "name": "owl_id", "title": "owl_id"},
            {"data": "salestate", "name": "salestate", "title": "salestate"},
        ],
    }
]
