# pylint: disable-msg=import-error
from payloads.pullup.pl_export_import_owl_rule import RULES_OPERATIONS_DS, RULES_DS_NAME

EXPORT_IMPORT_RULES_DEFINITION = [
    {
        "dataset": RULES_OPERATIONS_DS["dataset"],
        "ruleNm": "test_simple",
        "ruleType": "SQLG",
        "ruleValue": "close > 100",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
        "active": True,
    },
    {
        "dataset": RULES_OPERATIONS_DS["dataset"],
        "ruleNm": "test_FF",
        "ruleType": "SQLF",
        "ruleValue": f"SELECT * FROM @{RULES_DS_NAME} where close > 100",
        "points": 1,
        "perc": 1,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "close",
        "businessCategory": "",
        "businessDesc": "",
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30,
        "scoringScheme": 0,
        "active": True,
    },
]
