# pylint: disable-msg=import-error
# pylint: disable=anomalous-backslash-in-string

from datetime import datetime
from utils.constants import PROD_RUN_ID

NOW = datetime.now().strftime("%Y%m%d%H%M%S")

RUN_ID_EXPORT_RULE_DETAILS = f"{PROD_RUN_ID}T00:00:00.000+0000"
CONNECTION_EXPORT_RULE_DETAILS = "APPROVED_ORACLE_UP"
DATASET_EXPORT_RULE_DETAILS = "AUTO_RULES_EXPORT_DETAILS_2"  # Not unique err, will it happen again?
QUERY_EXPORT_RULE_DETAILS = "select * from OWLUSER.LOAN_CUSTOMER"

PL_GEN_EXPORT_RULE_DETAILS = {
    "dataset": DATASET_EXPORT_RULE_DETAILS,
    "runId": PROD_RUN_ID,
}

# List of rules to add. Note parameters vary depending on the rule type.
PL_EXPORT_RULE_DETAILS = [
    {
        "rulerepo": "EMPTYCHECK",
        "dataset": DATASET_EXPORT_RULE_DETAILS,
        "ruleBar": "Simple Rule",
        "from": DATASET_EXPORT_RULE_DETAILS,
        "ruletype": "EMPTYCHECK",
        "primarycolumn": "ADJ_RATE_CHANGE",
        "where": "ADJ_RATE_CHANGE",
        "rulenm": "if_ADJ_RATE_CHANGE_is_EMPTYCHECK",
        "previewlimit": 6,
        "runTimeLimit": 30,
        "points": 1,
        "perc": 1,
    },
    {
        "rulerepo": "",
        "dataset": DATASET_EXPORT_RULE_DETAILS,
        "ruleBar": "Simple Rule",
        "from": DATASET_EXPORT_RULE_DETAILS,
        "ruletype": "SQLG",
        "primarycolumn": "ADJ_RATE_CHANGE",
        "where": "ADJ_RATE_CHANGE = ''",
        "rulenm": "if_ADJ_RATE_CHANGE_is_EMPTY_simple",
        "previewlimit": 6,
        "runTimeLimit": 30,
        "points": 1,
        "perc": 1,
        "rulevaluebuilder": {
            "condition": "AND",
            "rules": [
                {
                    "id": None,
                    "field": None,
                    "type": None,
                    "input": None,
                    "operator": None,
                }
            ],
            "not": False,
            "valid": False,
        },
    },
    {
        "rulerepo": "",
        "dataset": DATASET_EXPORT_RULE_DETAILS,
        "ruleBar": "Simple Rule",
        "from": DATASET_EXPORT_RULE_DETAILS,
        "ruletype": "SQLF",
        "primarycolumn": "ADJ_RATE_CHANGE",
        "where": f"SELECT * from @{DATASET_EXPORT_RULE_DETAILS}"
        + r" WHERE LOAD_DT not rlike '^\d{1,2}/d{2}/d{4}$'",
        "rulenm": "if_LOAD_DT_is_DATE_MM_DD_YYYY_freeform",
        "previewlimit": 6,
        "runTimeLimit": 30,
        "points": 1,
        "perc": 1,
        "rulevaluebuilder": {
            "condition": "AND",
            "rules": [
                {
                    "id": None,
                    "field": None,
                    "type": None,
                    "input": None,
                    "operator": None,
                }
            ],
            "not": False,
            "valid": False,
        },
    },
    {
        "rulerepo": "",
        "dataset": DATASET_EXPORT_RULE_DETAILS,
        "ruleBar": "Simple Rule",
        "from": DATASET_EXPORT_RULE_DETAILS,
        "ruletype": "SQLG",
        "primarycolumn": "POST_CD_NUM",
        "where": "POST_CD_NUM not rlike '^[0-9]{5}(?:-[0-9]{4})?$'",
        "rulenm": "if_POST_CD_NUM_is_ZIP_CODE_simple",
        "previewlimit": 6,
        "runTimeLimit": 30,
        "points": 1,
        "perc": 1,
        "rulevaluebuilder": {
            "condition": "AND",
            "rules": [
                {
                    "id": None,
                    "field": None,
                    "type": None,
                    "input": None,
                    "operator": None,
                }
            ],
            "not": False,
            "valid": False,
        },
    },
]

# Large DATASET, recommend collapsing!
EXP_EXPORT_RULE_DETAILS = [
    {
        "main": {
            "dataset": DATASET_EXPORT_RULE_DETAILS,
            "runId": "",  # Updated later
            "ruleNm": "if_ADJ_RATE_CHANGE_is_EMPTYCHECK",
            "ruleType": "EMPTYCHECK",
            "ruleValue": "ADJ_RATE_CHANGE",
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {},
            "dimId": None,
            "dimName": None,
            "ruleCondition": None,
        },
        "detail": [],
    },
    {
        "main": {
            "dataset": DATASET_EXPORT_RULE_DETAILS,
            "runId": "",
            "ruleNm": "if_ADJ_RATE_CHANGE_is_EMPTY_simple",
            "ruleType": "SQLG",
            "ruleValue": "ADJ_RATE_CHANGE = ''",
            "score": 0,
            "perc": 0.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "PASSING",
            "assignmentId": {},
            "dimId": None,
            "dimName": None,
            "ruleCondition": None,
        },
        "detail": [],
    },
    {
        "main": {
            "dataset": DATASET_EXPORT_RULE_DETAILS,
            "runId": "",
            "ruleNm": "if_LOAD_DT_is_DATE_MM_DD_YYYY_freeform",
            "ruleType": "SQLF",
            "ruleValue": "SELECT * from "
            + DATASET_EXPORT_RULE_DETAILS
            + "_dataset WHERE LOAD_DT not rlike '^\\d{1,2}/d{2}/d{4}$' ",
            "score": 100,
            "perc": 100.0,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {},
            "dimId": None,
            "dimName": None,
            "ruleCondition": None,
        },
        "detail": [
            {
                "MORTGAGE_AMT": "484273.32",
                "UNIV_CD": "Georgia Health Sciences University",
                "EMPL_NUM": "75-6227326",
                "PAYMENTS_REMAINING": "112",
                "MORTAGE_RATE": "9.02",
                "ISBN_CD_NUM": "890957873-4",
                "MONTHS_PD_AMT": "135",
                "PMNT_TM_DAY": "10:52 PM",
                "EMAIL": "pmasding2j@youtube.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2017-12-24 00:00:00.0",
                "COUNTRY_INIT": "US",
                "SIZE_CD": "XL",
                "BUSINESS_NUM_ID": "35-818-0946",
                "BRAND_CD": "Pantoprazole Sodium",
                "REFINANCE_RATE": "1.05",
                "ID": "92",
                "DEPT_RETAIL": "Movies",
                "BZZ_WRD": "bottom-line",
                "IP_ADDRESS_HOME": "20.41.185.116",
                "YEARS_REMAINING": "98",
                "owl_id": "0",
                "MONTHS_LEFT": "201",
                "MONTHS_MISSED": "3",
                "YEARS_AFT_REFI_DATE": "7",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "PAYMENTS_MADE": "213",
                "RND_WORDS": "duis bibendum felis sed interdum venenatis"
                " turpis enim blandit mi in porttitor pede"
                " justo eu massa donec",
                "HELOC_RATE": "4.86",
                "STRT_ADDRSS": "012 Pond Lane",
                "CAR_VIN": "5UXZV8C5XD0620714",
                "YEARS_AFT_INTRST_CHANGE": "9",
                "MORTGAGE_DLQT_AMT": "9355.91",
                "INTRST_RATE": "2.37",
                "USRNAME_COL": "pmasding2j",
                "MORTGAGE_BALANCE_OUTSATNDING": "656815.50",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "10",
                "USR_NAME": "pmasding2j",
                "SCIENTIFIC_NAME": "Colaptes campestroides",
                "MONTHS_BEHIND": "3",
                "AUTO_LN_RATE": "2.95",
                "LAST_PAYMENT_AMT": "91",
                "LAST_NAME": "Masding",
                "SSN_NUMBER": "823-32-4867",
                "FIRST_NAME": "Pauletta",
                "GUID_NUM": "33e56b13-be76-4a2e-9d19-e5daf04b3f78",
                "SHRT_HEX_CD": "#e7d",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2017-08-02 00:00:00.0",
                "STATE_CD": "Nevada",
                "EMPLMT_INDUSTRY": "Auto Manufacturing",
                "TITLE_ABBRV": "Ms",
                "GENDER": "Female",
                "PRSNL_LN_RATE": "8.10",
                "OUTS_BALANCE_AMT": "$9.74",
                "LAST_RUN_DT": "2018-01-05 00:00:00.0",
                "APP_ID": "com.phpbb.Regrant",
                "LANG_CD": "Kurdish",
                "POST_CD_NUM": "89193",
                "PLNT_FMLY": "Scrophulariaceae",
                "ADJ_RATE_CHANGE": "3.18",
                "DEPT_CORP": "Accounting",
                "CMPNY_NM": "Lesch-Toy",
                "PRC_TO_SV_NUM": "0",
                "CC_CD": "jcb",
                "YEAR_IN_TO_LOAN": "271",
                "LOAN_RATE": "4.74",
                "MORTGAGE_PAYMT_AMT": "2836.10",
                "YEARS_DLQT": "10",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/Los_Angeles",
            },
            {
                "MORTGAGE_AMT": "732636.18",
                "UNIV_CD": "Memphis College of Art",
                "EMPL_NUM": "57-8155283",
                "MORTAGE_RATE": "6.58",
                "PAYMENTS_REMAINING": "184",
                "ISBN_CD_NUM": "569075500-1",
                "MONTHS_PD_AMT": "283",
                "PMNT_TM_DAY": "8:50 AM",
                "EMAIL": "sfarryann2k@wp.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2018-02-10 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "77-585-8954",
                "SIZE_CD": "M",
                "BRAND_CD": "Cellisys EX Wrinkle Solution Eye Contour",
                "REFINANCE_RATE": "1.43",
                "ID": "93",
                "BZZ_WRD": "Up-sized",
                "DEPT_RETAIL": "Outdoors",
                "IP_ADDRESS_HOME": "145.243.196.15",
                "owl_id": "1",
                "YEARS_REMAINING": "40",
                "MONTHS_LEFT": "349",
                "MONTHS_MISSED": "4",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "4",
                "PAYMENTS_MADE": "63",
                "RND_WORDS": "nam dui proin leo odio porttitor id consequat"
                " in consequat ut nulla sed accumsan",
                "HELOC_RATE": "6.94",
                "STRT_ADDRSS": "85 Anthes Road",
                "CAR_VIN": "WBA5B1C53FG885997",
                "MORTGAGE_DLQT_AMT": "80809.58",
                "YEARS_AFT_INTRST_CHANGE": "8",
                "INTRST_RATE": "7.87",
                "USRNAME_COL": "sfarryann2k",
                "MORTGAGE_BALANCE_OUTSATNDING": "444413.79",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "1",
                "USR_NAME": "sfarryann2k",
                "SCIENTIFIC_NAME": "Otaria flavescens",
                "MONTHS_BEHIND": "3",
                "AUTO_LN_RATE": "8.86",
                "LAST_PAYMENT_AMT": "40",
                "LAST_NAME": "Farryann",
                "SSN_NUMBER": "486-46-6080",
                "FIRST_NAME": "Sonnnie",
                "GUID_NUM": "185742d6-fa10-4619-96d8-86b0ac7fb8ba",
                "SHRT_HEX_CD": "#2ed",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2018-07-13 00:00:00.0",
                "STATE_CD": "Louisiana",
                "EMPLMT_INDUSTRY": "n/a",
                "TITLE_ABBRV": "Mrs",
                "GENDER": "Female",
                "PRSNL_LN_RATE": "9.43",
                "OUTS_BALANCE_AMT": "$7.93",
                "LAST_RUN_DT": "2017-09-23 00:00:00.0",
                "APP_ID": "com.marriott.Stringtough",
                "LANG_CD": "Kurdish",
                "POST_CD_NUM": "70129",
                "ADJ_RATE_CHANGE": "1.78",
                "PLNT_FMLY": "Ericaceae",
                "DEPT_CORP": "Legal",
                "CMPNY_NM": "Flatley-Eichmann",
                "CC_CD": "mastercard",
                "PRC_TO_SV_NUM": "0",
                "YEAR_IN_TO_LOAN": "222",
                "LOAN_RATE": "9.48",
                "MORTGAGE_PAYMT_AMT": "6322.61",
                "YEARS_DLQT": "4",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/Chicago",
            },
            {
                "MORTGAGE_AMT": "462906.31",
                "UNIV_CD": "Albany Law School",
                "EMPL_NUM": "38-6251193",
                "MORTAGE_RATE": "6.75",
                "PAYMENTS_REMAINING": "342",
                "ISBN_CD_NUM": "716643373-6",
                "MONTHS_PD_AMT": "126",
                "PMNT_TM_DAY": "9:37 PM",
                "EMAIL": "ajorigo@ucla.edu",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2017-08-18 00:00:00.0",
                "COUNTRY_INIT": "US",
                "SIZE_CD": "S",
                "BUSINESS_NUM_ID": "17-666-9541",
                "BRAND_CD": "AUREOBASIDIUM PULLULANS VAR PULLULANS",
                "REFINANCE_RATE": "null",
                "ID": "601",
                "DEPT_RETAIL": "Outdoors",
                "BZZ_WRD": "interface",
                "IP_ADDRESS_HOME": "25.252.78.194",
                "owl_id": "2",
                "YEARS_REMAINING": "68",
                "MONTHS_LEFT": "302",
                "MONTHS_MISSED": "1",
                "YEARS_AFT_REFI_DATE": "1",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "PAYMENTS_MADE": "185",
                "RND_WORDS": "curae donec pharetra magna vestibulum aliquet"
                " ultrices erat tortor sollicitudin mi",
                "HELOC_RATE": "null",
                "STRT_ADDRSS": "777 Buhler Court",
                "CAR_VIN": "1G6YV36AX75061524",
                "YEARS_AFT_INTRST_CHANGE": "6",
                "MORTGAGE_DLQT_AMT": "64585.84",
                "INTRST_RATE": "6.47",
                "USRNAME_COL": "ajorigo",
                "MORTGAGE_BALANCE_OUTSATNDING": "842141.87",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "false",
                "YEARS_AFT_ORGN_LOAN": "9",
                "USR_NAME": "ajorigo",
                "SCIENTIFIC_NAME": "Echimys chrysurus",
                "MONTHS_BEHIND": "20",
                "AUTO_LN_RATE": "null",
                "LAST_PAYMENT_AMT": "48",
                "LAST_NAME": "Jori",
                "SSN_NUMBER": "840-07-8718",
                "FIRST_NAME": "Aubree",
                "GUID_NUM": "9bd38fe6-6739-4200-9bd3-c04dded5973f",
                "SHRT_HEX_CD": "#006",
                "LOAD_DT": "2017-11-29 00:00:00.0",
                "EMP_NUL_COL": "null",
                "STATE_CD": "Texas",
                "EMPLMT_INDUSTRY": "Real Estate Investment Trusts",
                "TITLE_ABBRV": "Mr",
                "GENDER": "Female",
                "PRSNL_LN_RATE": "null",
                "OUTS_BALANCE_AMT": "$8.15",
                "LAST_RUN_DT": "2017-09-15 00:00:00.0",
                "APP_ID": "ru.yandex.Zoolab",
                "LANG_CD": "Yiddish",
                "POST_CD_NUM": "78255",
                "ADJ_RATE_CHANGE": "null",
                "PLNT_FMLY": "Loranthaceae",
                "DEPT_CORP": "Product Management",
                "CMPNY_NM": "Zemlak Inc",
                "CC_CD": "diners-club-us-ca",
                "YEAR_IN_TO_LOAN": "213",
                "PRC_TO_SV_NUM": "1",
                "LOAN_RATE": "null",
                "MORTGAGE_PAYMT_AMT": "7855.07",
                "YEARS_DLQT": "8",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/Chicago",
            },
            {
                "MORTGAGE_AMT": "818215.04",
                "UNIV_CD": "Union College Nebraska",
                "EMPL_NUM": "30-9587208",
                "MORTAGE_RATE": "2.89",
                "PAYMENTS_REMAINING": "277",
                "ISBN_CD_NUM": "079626368-X",
                "MONTHS_PD_AMT": "218",
                "PMNT_TM_DAY": "9:18 PM",
                "EMAIL": "rparradinei@cbsnews.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2017-11-08 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "01-222-2779",
                "SIZE_CD": "L",
                "REFINANCE_RATE": "null",
                "BRAND_CD": "Liothyronine Sodium",
                "ID": "19",
                "BZZ_WRD": "Reduced",
                "DEPT_RETAIL": "Baby",
                "IP_ADDRESS_HOME": "105.7.205.239",
                "owl_id": "3",
                "YEARS_REMAINING": "329",
                "MONTHS_LEFT": "331",
                "MONTHS_MISSED": "24",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "7",
                "PAYMENTS_MADE": "353",
                "RND_WORDS": "faucibus orci luctus et ultrices posuere"
                " cubilia curae nulla dapibus dolor vel"
                " est donec odio",
                "HELOC_RATE": "null",
                "STRT_ADDRSS": "56 Bayside Parkway",
                "CAR_VIN": "2C3CCAEG5DH303684",
                "MORTGAGE_DLQT_AMT": "54377.73",
                "YEARS_AFT_INTRST_CHANGE": "2",
                "INTRST_RATE": "4.34",
                "USRNAME_COL": "rparradinei",
                "MORTGAGE_BALANCE_OUTSATNDING": "127108.39",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "false",
                "YEARS_AFT_ORGN_LOAN": "5",
                "USR_NAME": "rparradinei",
                "SCIENTIFIC_NAME": "Nesomimus trifasciatus",
                "MONTHS_BEHIND": "23",
                "AUTO_LN_RATE": "null",
                "LAST_PAYMENT_AMT": "47",
                "LAST_NAME": "Parradine",
                "SSN_NUMBER": "192-71-4291",
                "FIRST_NAME": "Rolland",
                "GUID_NUM": "2874b24a-f81b-4203-89a7-7f8d366e9877",
                "SHRT_HEX_CD": "#f6b",
                "LOAD_DT": "2018-05-13 00:00:00.0",
                "EMP_NUL_COL": "null",
                "STATE_CD": "Alaska",
                "TITLE_ABBRV": "Dr",
                "EMPLMT_INDUSTRY": "Major Banks",
                "PRSNL_LN_RATE": "null",
                "GENDER": "Male",
                "OUTS_BALANCE_AMT": "$4.21",
                "LAST_RUN_DT": "2017-12-18 00:00:00.0",
                "APP_ID": "jp.ne.dion.Alpha",
                "LANG_CD": "Dhivehi",
                "POST_CD_NUM": "99517",
                "PLNT_FMLY": "Melastomataceae",
                "ADJ_RATE_CHANGE": "null",
                "DEPT_CORP": "Support",
                "CMPNY_NM": "Farrell, Effertz and Abbott",
                "YEAR_IN_TO_LOAN": "295",
                "CC_CD": "mastercard",
                "PRC_TO_SV_NUM": "0",
                "LOAN_RATE": "null",
                "MORTGAGE_PAYMT_AMT": "4052.97",
                "YEARS_DLQT": "7",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/Anchorage",
            },
            {
                "MORTGAGE_AMT": "607970.36",
                "UNIV_CD": "Philadelphia College of Osteopathic Medicine",
                "EMPL_NUM": "87-8041683",
                "MORTAGE_RATE": "5.85",
                "PAYMENTS_REMAINING": "214",
                "ISBN_CD_NUM": "919783298-7",
                "MONTHS_PD_AMT": "113",
                "PMNT_TM_DAY": "4:16 PM",
                "EMAIL": "abolsover13@constantcontact.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2018-05-21 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "94-814-2783",
                "SIZE_CD": "3XL",
                "REFINANCE_RATE": "5.44",
                "BRAND_CD": "Promethazine Hydrochloride",
                "ID": "40",
                "BZZ_WRD": "knowledge base",
                "DEPT_RETAIL": "Automotive",
                "IP_ADDRESS_HOME": "186.96.84.26",
                "YEARS_REMAINING": "14",
                "owl_id": "4",
                "MONTHS_LEFT": "281",
                "MONTHS_MISSED": "2",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "10",
                "PAYMENTS_MADE": "251",
                "RND_WORDS": "ante vestibulum ante ipsum primis in faucibus"
                " orci luctus et ultrices posuere cubilia curae"
                " duis faucibus accumsan odio",
                "HELOC_RATE": "2.37",
                "STRT_ADDRSS": "8 Schurz Point",
                "CAR_VIN": "3G5DA03E24S234183",
                "MORTGAGE_DLQT_AMT": "44755.75",
                "YEARS_AFT_INTRST_CHANGE": "3",
                "INTRST_RATE": "8.02",
                "USRNAME_COL": "abolsover13",
                "MORTGAGE_BALANCE_OUTSATNDING": "461738.19",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "false",
                "YEARS_AFT_ORGN_LOAN": "2",
                "USR_NAME": "abolsover13",
                "SCIENTIFIC_NAME": "Anastomus oscitans",
                "MONTHS_BEHIND": "13",
                "AUTO_LN_RATE": "1.07",
                "LAST_PAYMENT_AMT": "99",
                "LAST_NAME": "Bolsover",
                "SSN_NUMBER": "589-82-1828",
                "FIRST_NAME": "Arlette",
                "GUID_NUM": "3208ddd7-fb97-437b-ad07-9d42b3dc2ab5",
                "SHRT_HEX_CD": "#f3e",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2018-02-03 00:00:00.0",
                "STATE_CD": "Florida",
                "TITLE_ABBRV": "Mr",
                "EMPLMT_INDUSTRY": "Business Services",
                "PRSNL_LN_RATE": "6.33",
                "GENDER": "Female",
                "OUTS_BALANCE_AMT": "$2.55",
                "LAST_RUN_DT": "2017-12-16 00:00:00.0",
                "APP_ID": "com.alexa.Subin",
                "LANG_CD": "Korean",
                "POST_CD_NUM": "33705",
                "PLNT_FMLY": "Fabaceae",
                "ADJ_RATE_CHANGE": "2.45",
                "DEPT_CORP": "Services",
                "CMPNY_NM": "Wilkinson, Thompson and Turcotte",
                "PRC_TO_SV_NUM": "1",
                "YEAR_IN_TO_LOAN": "5",
                "CC_CD": "china-unionpay",
                "LOAN_RATE": "9.01",
                "MORTGAGE_PAYMT_AMT": "2732.94",
                "YEARS_DLQT": "8",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "232645.87",
                "UNIV_CD": "Lane College",
                "EMPL_NUM": "74-6406015",
                "MORTAGE_RATE": "6.93",
                "PAYMENTS_REMAINING": "99",
                "ISBN_CD_NUM": "526862974-3",
                "MONTHS_PD_AMT": "342",
                "PMNT_TM_DAY": "7:25 AM",
                "EMAIL": "kklos2d@feedburner.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "F",
                "LAST_BILL_CYCL": "2018-01-08 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "84-903-7427",
                "SIZE_CD": "M",
                "REFINANCE_RATE": "8.94",
                "BRAND_CD": "Major Ranitidine",
                "ID": "86",
                "BZZ_WRD": "collaboration",
                "DEPT_RETAIL": "Health",
                "IP_ADDRESS_HOME": "128.205.226.26",
                "owl_id": "5",
                "YEARS_REMAINING": "233",
                "MONTHS_LEFT": "74",
                "MONTHS_MISSED": "20",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "6",
                "PAYMENTS_MADE": "107",
                "RND_WORDS": "nascetur ridiculus mus vivamus vestibulum"
                " sagittis sapien cum sociis natoque",
                "HELOC_RATE": "8.13",
                "STRT_ADDRSS": "1 Delladonna Hill",
                "CAR_VIN": "1GYS4EEJ6BR605550",
                "MORTGAGE_DLQT_AMT": "84991.66",
                "YEARS_AFT_INTRST_CHANGE": "1",
                "INTRST_RATE": "5.78",
                "USRNAME_COL": "kklos2d",
                "MORTGAGE_BALANCE_OUTSATNDING": "844658.71",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "false",
                "YEARS_AFT_ORGN_LOAN": "10",
                "USR_NAME": "kklos2d",
                "SCIENTIFIC_NAME": "Tachybaptus ruficollis",
                "MONTHS_BEHIND": "5",
                "AUTO_LN_RATE": "5.87",
                "LAST_PAYMENT_AMT": "28",
                "LAST_NAME": "Klos",
                "SSN_NUMBER": "310-77-9105",
                "FIRST_NAME": "Kelsey",
                "GUID_NUM": "426faa03-17a3-4a1a-adb2-bf0c34365edf",
                "SHRT_HEX_CD": "#b7b",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2018-06-03 00:00:00.0",
                "STATE_CD": "Pennsylvania",
                "EMPLMT_INDUSTRY": "Real Estate Investment Trusts",
                "TITLE_ABBRV": "Mr",
                "PRSNL_LN_RATE": "1.54",
                "GENDER": "Male",
                "OUTS_BALANCE_AMT": "$2.41",
                "LAST_RUN_DT": "2018-04-02 00:00:00.0",
                "APP_ID": "it.tuttocitta.Bitchip",
                "LANG_CD": "Fijian",
                "POST_CD_NUM": "15279",
                "PLNT_FMLY": "Hydrophyllaceae",
                "ADJ_RATE_CHANGE": "3.13",
                "DEPT_CORP": "Legal",
                "CMPNY_NM": "Anderson-Howe",
                "PRC_TO_SV_NUM": "0",
                "CC_CD": "americanexpress",
                "YEAR_IN_TO_LOAN": "172",
                "LOAN_RATE": "4.45",
                "MORTGAGE_PAYMT_AMT": "3870.77",
                "YEARS_DLQT": "1",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
        ],
    },
    {
        "main": {
            "dataset": DATASET_EXPORT_RULE_DETAILS,
            "runId": "2023-06-21T00:00:00.000+0000",
            "ruleNm": "if_POST_CD_NUM_is_ZIP_CODE_simple",
            "ruleType": "SQLG",
            "ruleValue": "POST_CD_NUM not rlike '^[0-9]{5}(?:-[0-9]{4})?$'",
            "score": 3,
            "perc": 3.864734247326851,
            "exception": "",
            "owlId": "1",
            "breakMsg": "BREAKING",
            "assignmentId": {},
            "dimId": None,
            "dimName": None,
            "ruleCondition": None,
        },
        "detail": [
            {
                "MORTGAGE_AMT": "404744.52",
                "UNIV_CD": "Winthrop University",
                "EMPL_NUM": "83-2505150",
                "PAYMENTS_REMAINING": "304",
                "MORTAGE_RATE": "4.52",
                "ISBN_CD_NUM": "812185530-6",
                "MONTHS_PD_AMT": "293",
                "PMNT_TM_DAY": "12:27 PM",
                "EMAIL": "abrocklesbyfa@dailymail.co.uk",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2017-09-25 00:00:00.0",
                "COUNTRY_INIT": "US",
                "SIZE_CD": "M",
                "BUSINESS_NUM_ID": "97-943-8508",
                "BRAND_CD": "milk of magnesia",
                "REFINANCE_RATE": "6.44",
                "ID": "551",
                "DEPT_RETAIL": "Baby",
                "BZZ_WRD": "24/7",
                "IP_ADDRESS_HOME": "106.102.115.52",
                "YEARS_REMAINING": "200",
                "owl_id": "22",
                "MONTHS_LEFT": "82",
                "MONTHS_MISSED": "17",
                "YEARS_AFT_REFI_DATE": "5",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "PAYMENTS_MADE": "185",
                "RND_WORDS": "id ornare imperdiet sapien urna pretium nisl ut"
                " volutpat sapien arcu sed augue aliquam",
                "HELOC_RATE": "7.81",
                "STRT_ADDRSS": "360 West Way",
                "CAR_VIN": "JTHDU1EF1C5244481",
                "YEARS_AFT_INTRST_CHANGE": "1",
                "MORTGAGE_DLQT_AMT": "4174.48",
                "INTRST_RATE": "9.95",
                "USRNAME_COL": "abrocklesbyfa",
                "MORTGAGE_BALANCE_OUTSATNDING": "694691.49",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "9",
                "USR_NAME": "abrocklesbyfa",
                "SCIENTIFIC_NAME": "Vulpes vulpes",
                "MONTHS_BEHIND": "17",
                "AUTO_LN_RATE": "3.03",
                "LAST_PAYMENT_AMT": "29",
                "LAST_NAME": "Brocklesby",
                "SSN_NUMBER": "838-70-7640",
                "FIRST_NAME": "Alec",
                "GUID_NUM": "9a46dcc8-8e18-4812-83eb-7ff160d9f411",
                "SHRT_HEX_CD": "#a2d",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2018-04-27 00:00:00.0",
                "STATE_CD": "Massachusetts",
                "EMPLMT_INDUSTRY": "n/a",
                "TITLE_ABBRV": "Mr",
                "GENDER": "Male",
                "PRSNL_LN_RATE": "5.47",
                "OUTS_BALANCE_AMT": "$1.78",
                "LAST_RUN_DT": "2018-01-13 00:00:00.0",
                "APP_ID": "org.joomla.Span",
                "LANG_CD": "Tswana",
                "POST_CD_NUM": "2142",
                "PLNT_FMLY": "Dryopteridaceae",
                "ADJ_RATE_CHANGE": "2.73",
                "DEPT_CORP": "Accounting",
                "CMPNY_NM": "Osinski-Koepp",
                "PRC_TO_SV_NUM": "0",
                "CC_CD": "china-unionpay",
                "YEAR_IN_TO_LOAN": "211",
                "LOAN_RATE": "4.44",
                "MORTGAGE_PAYMT_AMT": "7260.84",
                "YEARS_DLQT": "10",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "118741.57",
                "UNIV_CD": "Whittier College",
                "EMPL_NUM": "61-0221006",
                "MORTAGE_RATE": "9.62",
                "PAYMENTS_REMAINING": "260",
                "ISBN_CD_NUM": "177602793-0",
                "MONTHS_PD_AMT": "50",
                "PMNT_TM_DAY": "8:03 PM",
                "EMAIL": "kcaselyp3@merriam-webster.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2018-03-24 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "25-724-8388",
                "SIZE_CD": "3XL",
                "BRAND_CD": "Category IV",
                "REFINANCE_RATE": "2.24",
                "ID": "904",
                "BZZ_WRD": "service-desk",
                "DEPT_RETAIL": "Outdoors",
                "IP_ADDRESS_HOME": "125.163.142.207",
                "owl_id": "37",
                "YEARS_REMAINING": "210",
                "MONTHS_LEFT": "355",
                "MONTHS_MISSED": "15",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "4",
                "PAYMENTS_MADE": "264",
                "RND_WORDS": "varius nulla facilisi cras non velit nec nisi"
                " vulputate nonummy maecenas tincidunt lacus"
                " at velit vivamus",
                "HELOC_RATE": "6.84",
                "STRT_ADDRSS": "7598 Charing Cross Lane",
                "CAR_VIN": "WBAVB73567K859461",
                "MORTGAGE_DLQT_AMT": "24371.00",
                "YEARS_AFT_INTRST_CHANGE": "4",
                "INTRST_RATE": "2.49",
                "USRNAME_COL": "kcaselyp3",
                "MORTGAGE_BALANCE_OUTSATNDING": "752996.05",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "false",
                "YEARS_AFT_ORGN_LOAN": "2",
                "USR_NAME": "kcaselyp3",
                "SCIENTIFIC_NAME": "Dasyurus viverrinus",
                "MONTHS_BEHIND": "5",
                "AUTO_LN_RATE": "9.44",
                "LAST_PAYMENT_AMT": "15",
                "LAST_NAME": "Casely",
                "SSN_NUMBER": "710-87-8823",
                "FIRST_NAME": "Kassie",
                "GUID_NUM": "52776a7e-d263-4f27-a1b0-edc6c7a75f11",
                "SHRT_HEX_CD": "#f6f",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2017-09-09 00:00:00.0",
                "STATE_CD": "Massachusetts",
                "EMPLMT_INDUSTRY": "Coal Mining",
                "TITLE_ABBRV": "Dr",
                "GENDER": "Female",
                "PRSNL_LN_RATE": "8.42",
                "OUTS_BALANCE_AMT": "$0.39",
                "LAST_RUN_DT": "2017-12-27 00:00:00.0",
                "APP_ID": "com.netscape.Trippledex",
                "LANG_CD": "Maltese",
                "POST_CD_NUM": "1105",
                "ADJ_RATE_CHANGE": "2.76",
                "PLNT_FMLY": "Onagraceae",
                "DEPT_CORP": "Research and Development",
                "CMPNY_NM": "Marks Group",
                "CC_CD": "mastercard",
                "PRC_TO_SV_NUM": "1",
                "YEAR_IN_TO_LOAN": "34",
                "LOAN_RATE": "6.80",
                "MORTGAGE_PAYMT_AMT": "3999.14",
                "YEARS_DLQT": "5",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "709342.45",
                "UNIV_CD": "San Joaquin College of Law",
                "EMPL_NUM": "67-9865694",
                "MORTAGE_RATE": "3.42",
                "PAYMENTS_REMAINING": "337",
                "ISBN_CD_NUM": "982886580-7",
                "MONTHS_PD_AMT": "51",
                "PMNT_TM_DAY": "10:06 AM",
                "EMAIL": "rmendenhall27@people.com.cn",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "F",
                "LAST_BILL_CYCL": "2017-08-24 00:00:00.0",
                "COUNTRY_INIT": "US",
                "SIZE_CD": "XS",
                "BUSINESS_NUM_ID": "89-047-2091",
                "BRAND_CD": "Ibuprofen",
                "REFINANCE_RATE": "5.57",
                "ID": "80",
                "DEPT_RETAIL": "Garden",
                "BZZ_WRD": "application",
                "IP_ADDRESS_HOME": "135.109.61.159",
                "owl_id": "42",
                "YEARS_REMAINING": "317",
                "MONTHS_LEFT": "154",
                "MONTHS_MISSED": "6",
                "YEARS_AFT_REFI_DATE": "4",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "PAYMENTS_MADE": "5",
                "RND_WORDS": "morbi sem mauris laoreet ut rhoncus aliquet"
                " pulvinar sed nisl nunc rhoncus dui vel sem sed"
                " sagittis nam congue",
                "HELOC_RATE": "3.80",
                "STRT_ADDRSS": "31773 Mandrake Center",
                "CAR_VIN": "YV440MBM5F1611330",
                "YEARS_AFT_INTRST_CHANGE": "6",
                "MORTGAGE_DLQT_AMT": "57568.57",
                "INTRST_RATE": "5.78",
                "USRNAME_COL": "rmendenhall27",
                "MORTGAGE_BALANCE_OUTSATNDING": "480266.11",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "8",
                "USR_NAME": "rmendenhall27",
                "SCIENTIFIC_NAME": "Macropus agilis",
                "MONTHS_BEHIND": "1",
                "AUTO_LN_RATE": "8.53",
                "LAST_PAYMENT_AMT": "81",
                "LAST_NAME": "Mendenhall",
                "SSN_NUMBER": "164-12-1853",
                "FIRST_NAME": "Regen",
                "GUID_NUM": "0fa15295-70f3-473b-acc1-4eaaa2b8f432",
                "SHRT_HEX_CD": "#c0e",
                "LOAD_DT": "2017-11-21 00:00:00.0",
                "EMP_NUL_COL": "null",
                "STATE_CD": "Massachusetts",
                "EMPLMT_INDUSTRY": "Finance: Consumer Services",
                "TITLE_ABBRV": "Dr",
                "GENDER": "Male",
                "PRSNL_LN_RATE": "6.71",
                "OUTS_BALANCE_AMT": "$0.64",
                "LAST_RUN_DT": "2018-05-02 00:00:00.0",
                "APP_ID": "jp.ameblo.Gembucket",
                "LANG_CD": "Kannada",
                "POST_CD_NUM": "2298",
                "ADJ_RATE_CHANGE": "1.13",
                "PLNT_FMLY": "Rosaceae",
                "DEPT_CORP": "Marketing",
                "CMPNY_NM": "Grimes-Hamill",
                "CC_CD": "diners-club-us-ca",
                "YEAR_IN_TO_LOAN": "136",
                "PRC_TO_SV_NUM": "0",
                "LOAN_RATE": "7.02",
                "MORTGAGE_PAYMT_AMT": "8823.61",
                "YEARS_DLQT": "1",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "108597.23",
                "UNIV_CD": "University of Illinois at Urbana-Champaign",
                "EMPL_NUM": "37-1359328",
                "MORTAGE_RATE": "7.61",
                "PAYMENTS_REMAINING": "60",
                "ISBN_CD_NUM": "666457041-6",
                "MONTHS_PD_AMT": "9",
                "PMNT_TM_DAY": "9:01 AM",
                "EMAIL": "pcollettr@technorati.com",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2018-02-09 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "05-193-3930",
                "SIZE_CD": "3XL",
                "REFINANCE_RATE": "null",
                "BRAND_CD": "Kaletra",
                "ID": "28",
                "BZZ_WRD": "algorithm",
                "DEPT_RETAIL": "Garden",
                "IP_ADDRESS_HOME": "198.26.91.255",
                "owl_id": "88",
                "YEARS_REMAINING": "289",
                "MONTHS_LEFT": "129",
                "MONTHS_MISSED": "19",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "3",
                "PAYMENTS_MADE": "239",
                "RND_WORDS": "sit amet lobortis sapien sapien non mi integer ac neque duis",
                "HELOC_RATE": "null",
                "STRT_ADDRSS": "52 Graedel Park",
                "CAR_VIN": "WP1AA2AP7AL140261",
                "MORTGAGE_DLQT_AMT": "12323.20",
                "YEARS_AFT_INTRST_CHANGE": "3",
                "INTRST_RATE": "8.18",
                "USRNAME_COL": "pcollettr",
                "MORTGAGE_BALANCE_OUTSATNDING": "461995.83",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "9",
                "USR_NAME": "pcollettr",
                "SCIENTIFIC_NAME": "Carduelis pinus",
                "MONTHS_BEHIND": "20",
                "AUTO_LN_RATE": "null",
                "LAST_PAYMENT_AMT": "93",
                "LAST_NAME": "Collett",
                "SSN_NUMBER": "563-85-0836",
                "FIRST_NAME": "Pamella",
                "GUID_NUM": "0a7fbeca-7b79-4963-baf7-b922d5355c15",
                "SHRT_HEX_CD": "#727",
                "LOAD_DT": "2018-06-14 00:00:00.0",
                "EMP_NUL_COL": "null",
                "STATE_CD": "Massachusetts",
                "TITLE_ABBRV": "Mr",
                "EMPLMT_INDUSTRY": "Oil & Gas Production",
                "PRSNL_LN_RATE": "null",
                "GENDER": "Female",
                "OUTS_BALANCE_AMT": "$7.06",
                "LAST_RUN_DT": "2017-10-23 00:00:00.0",
                "APP_ID": "pl.home.Fixflex",
                "LANG_CD": "Oriya",
                "POST_CD_NUM": "1605",
                "PLNT_FMLY": "Polypodiaceae",
                "ADJ_RATE_CHANGE": "null",
                "DEPT_CORP": "Support",
                "CMPNY_NM": "Balistreri and Sons",
                "YEAR_IN_TO_LOAN": "104",
                "CC_CD": "maestro",
                "PRC_TO_SV_NUM": "0",
                "LOAN_RATE": "null",
                "MORTGAGE_PAYMT_AMT": "4057.77",
                "YEARS_DLQT": "10",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "107540.69",
                "UNIV_CD": "Cumberland College",
                "EMPL_NUM": "35-9582281",
                "MORTAGE_RATE": "7.23",
                "PAYMENTS_REMAINING": "129",
                "ISBN_CD_NUM": "237082300-3",
                "MONTHS_PD_AMT": "113",
                "PMNT_TM_DAY": "9:41 AM",
                "EMAIL": "buphill4a@furl.net",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "F",
                "LAST_BILL_CYCL": "2018-02-03 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "42-558-2125",
                "SIZE_CD": "S",
                "REFINANCE_RATE": "3.93",
                "BRAND_CD": "Gentamicin Sulfate in Sodium Chloride",
                "ID": "155",
                "BZZ_WRD": "Up-sized",
                "DEPT_RETAIL": "Industrial",
                "IP_ADDRESS_HOME": "255.189.240.35",
                "YEARS_REMAINING": "246",
                "owl_id": "8589934612",
                "MONTHS_LEFT": "279",
                "MONTHS_MISSED": "23",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "1",
                "PAYMENTS_MADE": "205",
                "RND_WORDS": "aliquet massa id lobortis convallis tortor risus"
                " dapibus augue vel accumsan tellus nisi eu orci",
                "HELOC_RATE": "8.56",
                "STRT_ADDRSS": "2 Oak Road",
                "CAR_VIN": "WAUEF98E76A916957",
                "MORTGAGE_DLQT_AMT": "44625.35",
                "YEARS_AFT_INTRST_CHANGE": "8",
                "INTRST_RATE": "1.90",
                "USRNAME_COL": "buphill4a",
                "MORTGAGE_BALANCE_OUTSATNDING": "197778.92",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "9",
                "USR_NAME": "buphill4a",
                "SCIENTIFIC_NAME": "Bucorvus leadbeateri",
                "MONTHS_BEHIND": "6",
                "AUTO_LN_RATE": "4.93",
                "LAST_PAYMENT_AMT": "70",
                "LAST_NAME": "Uphill",
                "SSN_NUMBER": "754-09-2379",
                "FIRST_NAME": "Barclay",
                "GUID_NUM": "91af8f54-f1a6-49bc-8bdb-8b353124adf8",
                "SHRT_HEX_CD": "#310",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2017-09-03 00:00:00.0",
                "STATE_CD": "New Jersey",
                "TITLE_ABBRV": "Mr",
                "EMPLMT_INDUSTRY": "Real Estate",
                "PRSNL_LN_RATE": "3.70",
                "GENDER": "Male",
                "OUTS_BALANCE_AMT": "$7.18",
                "LAST_RUN_DT": "2018-04-06 00:00:00.0",
                "APP_ID": "com.linkedin.Zamit",
                "LANG_CD": "Dzongkha",
                "POST_CD_NUM": "7112",
                "PLNT_FMLY": "Cyperaceae",
                "ADJ_RATE_CHANGE": "1.28",
                "DEPT_CORP": "Research and Development",
                "CMPNY_NM": "Murphy, Medhurst and Carroll",
                "PRC_TO_SV_NUM": "1",
                "YEAR_IN_TO_LOAN": "298",
                "CC_CD": "jcb",
                "LOAN_RATE": "2.73",
                "MORTGAGE_PAYMT_AMT": "3966.16",
                "YEARS_DLQT": "2",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
            {
                "MORTGAGE_AMT": "585111.63",
                "UNIV_CD": "University of Missouri - Columbia",
                "EMPL_NUM": "23-8999634",
                "MORTAGE_RATE": "9.09",
                "PAYMENTS_REMAINING": "107",
                "ISBN_CD_NUM": "990709634-2",
                "MONTHS_PD_AMT": "266",
                "PMNT_TM_DAY": "11:15 AM",
                "EMAIL": "tpizzeyv@t.co",
                "COUNTRY_CD": "United States",
                "GNDR_ABBRV_CD": "M",
                "LAST_BILL_CYCL": "2017-08-18 00:00:00.0",
                "COUNTRY_INIT": "US",
                "BUSINESS_NUM_ID": "32-634-1329",
                "SIZE_CD": "S",
                "REFINANCE_RATE": "null",
                "BRAND_CD": "Methylphenidate Hydrochloride",
                "ID": "32",
                "BZZ_WRD": "methodical",
                "DEPT_RETAIL": "Health",
                "IP_ADDRESS_HOME": "207.92.209.43",
                "owl_id": "8589934652",
                "YEARS_REMAINING": "188",
                "MONTHS_LEFT": "195",
                "MONTHS_MISSED": "12",
                "RUN_DT": "2018-07-14 00:00:00.0",
                "YEARS_AFT_REFI_DATE": "4",
                "PAYMENTS_MADE": "183",
                "RND_WORDS": "sociis natoque penatibus et magnis dis parturient"
                " montes nascetur ridiculus mus vivamus vestibulum",
                "HELOC_RATE": "null",
                "STRT_ADDRSS": "73637 Independence Pass",
                "CAR_VIN": "JTDKTUD33ED755588",
                "MORTGAGE_DLQT_AMT": "10226.46",
                "YEARS_AFT_INTRST_CHANGE": "1",
                "INTRST_RATE": "9.67",
                "USRNAME_COL": "tpizzeyv",
                "MORTGAGE_BALANCE_OUTSATNDING": "806428.56",
                "CC_NUMBER": "2147483647",
                "UP_TO_DT_PAYMENT": "true",
                "YEARS_AFT_ORGN_LOAN": "5",
                "USR_NAME": "tpizzeyv",
                "SCIENTIFIC_NAME": "Tamiasciurus hudsonicus",
                "MONTHS_BEHIND": "15",
                "AUTO_LN_RATE": "null",
                "LAST_PAYMENT_AMT": "60",
                "LAST_NAME": "Pizzey",
                "SSN_NUMBER": "251-34-2283",
                "FIRST_NAME": "Timi",
                "GUID_NUM": "39d30b72-e51f-4517-b1d3-42032e3927d9",
                "SHRT_HEX_CD": "#7fb",
                "EMP_NUL_COL": "null",
                "LOAD_DT": "2017-08-10 00:00:00.0",
                "STATE_CD": "Connecticut",
                "EMPLMT_INDUSTRY": "Major Pharmaceuticals",
                "TITLE_ABBRV": "Mrs",
                "PRSNL_LN_RATE": "null",
                "GENDER": "Female",
                "OUTS_BALANCE_AMT": "$2.12",
                "LAST_RUN_DT": "2017-12-18 00:00:00.0",
                "APP_ID": "com.artisteer.Stringtough",
                "LANG_CD": "Malayalam",
                "POST_CD_NUM": "6152",
                "PLNT_FMLY": "Campanulaceae",
                "ADJ_RATE_CHANGE": "null",
                "DEPT_CORP": "Training",
                "CMPNY_NM": "Grady-Bednar",
                "PRC_TO_SV_NUM": "1",
                "CC_CD": "jcb",
                "YEAR_IN_TO_LOAN": "55",
                "LOAN_RATE": "null",
                "MORTGAGE_PAYMT_AMT": "1015.72",
                "YEARS_DLQT": "8",
                "CURR_CD": "Dollar",
                "IP_ADDRESS": "America/New_York",
            },
        ],
    },
]
