from payloads.pullup.pl_pullup_outliers_num_nokey_date_nyse import \
    PULLUP_OUTLIERS_NUM_NOKEY_DATE_NYSE_PAYLOAD
from payloads.pullup.pl_source_scope_operations import DATASET_NAME_JDBC

ORACLE_CATALOG_OUTPUT = {
    "icon": "",
    "dataset": "AUTO_CXN_ORACLE_UP_1",
    "alias": "AUTO_CXN_ORACLE_UP_1",
    "source": "Oracle",
    "dbNm": "OWLUSER",
    "tableNm": "CUSTOMER",
    "tags": "",
    "host": "10.150.0.31",
    "editDeleteIcons": "",
    "t1": None,
    "t2": None,
    "t3": None,
    "t4": None,
    "timeZone": "UTC",
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "sun": 1,
    "semantic": 0,
    "runs": 12,
    "runMode": "draft",
    "dataConceptId": 0,
    "dataConceptNm": None,
    "sourceName": None,
}

SNOWFLAKE_CATALOG_OUTPUT = {
    "icon": "",
    "dataset": "AUTO_CXN_SNOWFLAKE_UP_FULL_PROFILE",
    "alias": "AUTO_CXN_SNOWFLAKE_UP_FULL_PROFILE",
    "source": "snowflake",
    "dbNm": "PUBLIC",
    "tableNm": "ACCOUNTS",
    "tags": "",
    "host": "owlanalyticspartner.us-east-2.aws.snowflakecomputing.com",
    "editDeleteIcons": "",
    "t1": None,
    "t2": None,
    "t3": None,
    "t4": None,
    "timeZone": "UTC",
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "sun": 1,
    "semantic": 0,
    "runs": 90,
    "runMode": "draft",
    "dataConceptId": 0,
    "dataConceptNm": None,
    "sourceName": None,
}

S3_CATALOG_OUTPUT = {
    "icon": "",
    "dataset": "AUTO_CXN_S3",
    "alias": "AUTO_CXN_S3",
    "source": "File:s3",
    "dbNm": "cdq-datasets-hr7wprr",
    "tableNm": "nyse.csv",
    "tags": "",
    "host": "s3a:/cdq-datasets-hr7wprr",
    "editDeleteIcons": "",
    "t1": None,
    "t2": None,
    "t3": None,
    "t4": None,
    "timeZone": "UTC",
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "sun": 1,
    "semantic": 0,
    "runs": 8,
    "runMode": "draft",
    "dataConceptId": 0,
    "dataConceptNm": None,
    "sourceName": "",
}

GET_SCHEMA_RESPONSE_BODY = {
    "gender": {
        "dataset": DATASET_NAME_JDBC,
        "colName": "gender",
        "dtcnt": 0,
        "ncnt": 0,
        "ecnt": 0,
        "cardinality": 0,
        "unique": 0,
        "colSchema": "String",
        "colTyp": "String",
        "min": "",
        "max": "",
        "mean": "",
        "semantic": "",
        "runId": None,
    },
    "last_name": {
        "dataset": DATASET_NAME_JDBC,
        "colName": "last_name",
        "dtcnt": 0,
        "ncnt": 0,
        "ecnt": 0,
        "cardinality": 0,
        "unique": 0,
        "colSchema": "String",
        "colTyp": "String",
        "min": "",
        "max": "",
        "mean": "",
        "semantic": "",
        "runId": None,
    },
    "id": {
        "dataset": DATASET_NAME_JDBC,
        "colName": "id",
        "dtcnt": 0,
        "ncnt": 0,
        "ecnt": 0,
        "cardinality": 0,
        "unique": 0,
        "colSchema": "Integer",
        "colTyp": "Int",
        "min": "",
        "max": "",
        "mean": "",
        "semantic": "",
        "runId": None,
    },
    "first_name": {
        "dataset": DATASET_NAME_JDBC,
        "colName": "first_name",
        "dtcnt": 0,
        "ncnt": 0,
        "ecnt": 0,
        "cardinality": 0,
        "unique": 0,
        "colSchema": "String",
        "colTyp": "String",
        "min": "",
        "max": "",
        "mean": "",
        "semantic": "",
        "runId": None,
    },
    "email": {
        "dataset": DATASET_NAME_JDBC,
        "colName": "email",
        "dtcnt": 0,
        "ncnt": 0,
        "ecnt": 0,
        "cardinality": 0,
        "unique": 0,
        "colSchema": "String",
        "colTyp": "String",
        "min": "",
        "max": "",
        "mean": "",
        "semantic": "",
        "runId": None,
    },
}


DUPE_OPT_RESPONSE = {
    "result": {
        "dataset": "AUTO_DUPE_CASESENSITIVE",
        "on": True,
        "only": False,
        "include": ["gender"],
        "exclude": None,
        "depth": 0,
        "lowerBound": 99,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": False,
        "score": 1,
        "limit": 300,
    }
}

OUTLIER_OPT_RESPONSE = {
    "result": [
        {
            "id": 1156,
            "dataset":  PULLUP_OUTLIERS_NUM_NOKEY_DATE_NYSE_PAYLOAD["dataset"],
            "on": False,
            "only": False,
            "lookback": 5,
            "lookbackQuery": "",
            "key": None,
            "include": ["VOLUME"],
            "exclude": [
                "EXCH",
                "SYMBOL",
                "TRADE_DATE",
                "OPEN",
                "HIGH",
                "LOW",
                "CLOSE",
                "PART_DATE_STR",
            ],
            "dateColumn": "TRADE_DATE",
            "timeColumn": None,
            "timeBin": "DAY",
            "timeBinQuery": "",
            "categorical": False,
            "by": None,
            "limit": 300,
            "minHistory": 3,
            "historyLimit": 5,
            "score": 1,
            "aggFunc": "",
            "aggQuery": "",
            "query": "",
            "q1": 0.01,
            "q3": 0.99,
            "categoricalColumnConcatenation": False,
            "limitCategorical": None,
            "measurementUnit": "",
            "multiplierUpper": 1.35,
            "multiplierLower": 1.35,
            "record": True,
            "filter": None,
            "combine": True,
            "categoricalConfidenceType": "",
            "categoricalTopN": 3,
            "categoricalBottomN": 2,
            "categoricalMaxConfidence": 0.02,
            "categoricalMaxFrequencyPercentile": 0.25,
            "categoricalMinFrequency": 1,
            "categoricalMinVariance": 0,
            "categoricalMaxCategoryN": 1,
            "categoricalParallel": True,
            "categoricalAlgorithm": "",
            "categoricalAlgorithmParameters": {},
        }
    ]
}

SOURCE_OPT_RESPONSE = {
    "result": {
        "on": True,
        "only": False,
        "validateValues": True,
        "key": ["id"],
        "include": ["id", "first_name", "last_name", "gender", "email"],
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": {"email_address": "email", "last_namez": "last_name", "first_namez": "first_name"},
        "score": 1,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNone": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateValuesShowMissingKeys": False,
        "validateValuesFilter": "",
        "dataset": DATASET_NAME_JDBC,
        "datasetSrc": f"src_{DATASET_NAME_JDBC}",
        "driverName": "org.postgresql.Driver",
        "user": "owluser",
        "password": "",
        "passwordManager": None,
        "connectionName": "APPROVED_POSTGRES_UP",
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "query": "select * from samples.name_gender_email_source",
        "lib": "/opt/owl/drivers/postgres/",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
        "hasHeader": True,
    }
}
