import copy
from datetime import datetime

DS_DEF_DGC_COLUMN_RELATION_JOB_NAME = "AUTO_DQ_COLUMN_RELATION_IN_DIC_" + datetime.now().strftime(
    "%Y%m%d%H%M%S"
)


DS_DEF_DGC_COLUMN_RELATION_IN_DIC = {
    "dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME,
    "runId": "2022-01-07",
    "runIdEnd": "",
    "runState": "DRAFT",
    "passFail": 1,
    "passFailLimit": 75,
    "jobDescription": "",
    "jobId": None,
    "coreMaxActiveConnections": None,
    "linkId": None,
    "licenseKey": "",
    "logFile": "",
    "logLevel": "INFO",
    "hootOnly": False,
    "prettyPrint": True,
    "useTemplate": False,
    "parallel": False,
    "plan": False,
    "dataPreviewOff": False,
    "datasetSafeOff": False,
    "obslimit": 300,
    "pgUser": "",
    "pgPassword": "",
    "host": "10.64.2.3:5432/dqqa?currentSchema=automation",
    "port": "5432/dqqa?currentSchema=automation",
    "user": "misha",
    "alertEmail": None,
    "scheduleTime": None,
    "schemaScore": 1.0,
    "optionAppend": "",
    "keyDelimiter": "~~",
    "agentId": {"id": 6, "uuid": "8eb1f6a8-70ab-4285-a903-b587523ae61e"},
    "load": {
        "readonly": False,
        "passwordManager": None,
        "alias": "",
        "query": "select * from public.sales_data_002 where transaction_date = '${rd}'",
        "queryHistory": "",
        "key": "sales_id",
        "expression": "lost_column=CAST(lost_column as String) as lost_column",
        "addDateColumn": False,
        "zeroFillNull": False,
        "replaceNulls": "",
        "stringMode": False,
        "operator": None,
        "dateColumn": None,
        "transform": None,
        "filter": "",
        "filterNot": "",
        "sample": 1.0,
        "backRun": 0,
        "backRunBin": "DAY",
        "unionLookBack": False,
        "unionLookBackMinRow": 0,
        "cache": True,
        "dateFormat": "yyyy-MM-dd",
        "timeFormat": "HH:mm:ss.SSS",
        "timestamp": False,
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "fileHeader": None,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "skipLines": 0,
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "lib": "/opt/owl/drivers/postgres/",
        "additionalLib": "",
        "driverName": "org.postgresql.Driver",
        "connectionName": "APPROVED_POSTGRES_UP",
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "userName": "owluser",
        "password": "",
        "connectionProperties": {},
        "hiveNative": False,
        "hiveNativeHWC": False,
        "useSql": True,
        "columnName": None,
        "lowerBound": None,
        "upperBound": None,
        "numPartitions": 0,
        "partitionNumber": 0,
        "escapeWithBackTick": False,
        "escapeWithSingleQuote": False,
        "escapeWithDoubleQuote": False,
        "escapeCharacter": "",
        "checkHeader": True,
        "archiveConnection": "",
        "coreFetchMode": False,
        "archiveBreaks": False,
        "ruleSerial": False,
    },
    "pushdown": {
        "dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME,
        "connectionName": "",
        "maxConnections": 10,
        "sourceQuery": "",
        "backRuns": 0,
        "backRunBin": "DAY",
        "dateFormatType": "DATE",
        "threads": 5,
        "manualSourceQuery": False,
        "key": "",
        "sourceOutputSchema": "",
        "sourceBreakRules": False,
        "sourceBreakOutliers": False,
        "sourceBreakDupes": False,
        "sourceBreakShapes": False,
        "sourceBreakResults": False,
        "sqlLoggingToggle": True,
    },
    "outliers": [
        {
            "id": 339,
            "dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME,
            "only": False,
            "lookback": 5,
            "key": ["daily_id"],
            "include": ["sales_id", "first_name", "last_name", "email"],
            "exclude": [
                "transaction_date",
                "transaction_time",
                "daily_id",
                "vendor_type",
                "cost",
                "cost_code",
                "cost_description",
                "sales_rep",
                "sale_state",
                "state_tax",
                "lost_column",
            ],
            "dateColumn": "transaction_date",
            "timeColumn": None,
            "timeBin": "DAY",
            "timeBinQuery": "",
            "categorical": True,
            "by": None,
            "limit": 300,
            "minHistory": 3,
            "historyLimit": 5,
            "score": 1.0,
            "aggFunc": "",
            "aggQuery": "",
            "query": "",
            "q1": 0.15,
            "q3": 0.85,
            "categoricalColumnConcatenation": False,
            "limitCategorical": None,
            "measurementUnit": "",
            "multiplierUpper": 1.35,
            "multiplierLower": 1.35,
            "record": True,
            "filter": None,
            "combine": True,
            "categoricalConfidenceType": "",
            "categoricalTopN": 3,
            "categoricalBottomN": 2,
            "categoricalMaxConfidence": 0.02,
            "categoricalMaxFrequencyPercentile": 0.25,
            "categoricalMinFrequency": 1,
            "categoricalMinVariance": 0.0,
            "categoricalMaxCategoryN": 1,
            "categoricalParallel": True,
            "categoricalAlgorithm": "",
            "categoricalAlgorithmParameters": {},
        }
    ],
    "patterns": [
        {
            "id": 38,
            "dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME,
            "only": False,
            "lookback": 5,
            "key": ["sale_state"],
            "dateColumn": "transaction_date",
            "include": ["state_tax"],
            "exclude": [
                "sales_id",
                "transaction_date",
                "transaction_time",
                "daily_id",
                "first_name",
                "last_name",
                "email",
                "vendor_type",
                "cost",
                "cost_code",
                "cost_description",
                "sales_rep",
                "sale_state",
                "lost_column",
            ],
            "score": 1.0,
            "minSupport": 3.3e-5,
            "confidence": 0.6,
            "limit": 30,
            "on": True,
            "query": "",
            "filter": None,
            "timeBin": "DAY",
        }
    ],
    "dupe": {
        "on": True,
        "only": False,
        "include": ["email", "first_name", "last_name"],
        "exclude": None,
        "depth": 2,
        "lowerBound": 95,
        "upperBound": 100,
        "approximate": 1,
        "limitPerDupe": 15,
        "checkHeader": True,
        "filter": None,
        "ignoreCase": True,
        "score": 1.0,
        "limit": 300,
    },
    "profile": {
        "on": True,
        "only": False,
        "include": [
            "sales_id",
            "transaction_date",
            "transaction_time",
            "daily_id",
            "first_name",
            "last_name",
            "email",
            "vendor_type",
            "cost",
            "cost_code",
            "cost_description",
            "sales_rep",
            "sale_state",
            "state_tax",
            "lost_column",
        ],
        "exclude": [],
        "correlation": True,
        "histogram": True,
        "semantic": None,
        "dataConceptId": None,
        "limit": 300,
        "histogramLimit": 0,
        "score": 1.0,
        "shape": True,
        "shapeTotalScore": 0,
        "shapeSensitivity": 0.0,
        "shapeMaxPerCol": 0,
        "shapeMaxColSize": 0,
        "shapeGranular": True,
        "behavioralDimension": "",
        "behavioralDimensionGroup": "",
        "behavioralValueColumn": "",
        "behaviorScoreOff": False,
        "behaviorLookback": 10,
        "behaviorMinSupport": 3,
        "profilePushDown": None,
        "behaviorRowCheck": True,
        "behaviorTimeCheck": False,
        "behaviorMinValueCheck": False,
        "behaviorMaxValueCheck": False,
        "behaviorMeanValueCheck": False,
        "behaviorNullCheck": True,
        "behaviorEmptyCheck": True,
        "behaviorUniqueCheck": True,
        "profileStringLength": False,
        "detectStringNumerics": True,
        "detectTopnBotn": True,
        "detectScalePrecision": True,
        "adaptiveTier": None,
        "advancedTier": None,
        "filter": "",
    },
    "source": {
        "on": True,
        "only": False,
        "validateValues": True,
        "key": None,
        "include": [
            "cost",
            "cost_code",
            "cost_description",
            "daily_id",
            "email",
            "first_name",
            "last_name",
            "lost_column",
            "sale_state",
            "sales_id",
            "sales_rep",
            "state_tax",
            "transaction_date",
            "transaction_time",
            "vendor_type",
        ],
        "exclude": None,
        "includeSrc": None,
        "excludeSrc": None,
        "map": {
            "transaction_date": "transaction_date",
            "sales_rep": "sales_rep",
            "cost": "cost",
            "cost_description": "cost_description",
            "daily_id": "daily_id",
            "last_name": "last_name",
            "state_tax": "state_tax",
            "lost_column": "lost_column",
            "transaction_time": "transaction_time",
            "first_name": "first_name",
            "sales_id": "sales_id",
            "cost_code": "cost_code",
            "email": "email",
            "sale_state": "sale_state",
            "vendor_type": "vendor_type",
        },
        "score": 1.0,
        "limit": 30,
        "sourcePushDownCount": False,
        "checkType": True,
        "checkCase": False,
        "validateSchemaOrder": False,
        "matches": False,
        "validateValuesThreshold": 0.9,
        "validateValuesThresholdStrictDownScore": False,
        "validateValuesShowAll": False,
        "validateValuesIgnoreNull": False,
        "validateValuesIgnoreEmpty": False,
        "validateValuesIgnorePrecision": False,
        "validateValuesTrim": False,
        "validateValuesShowMissingKeys": False,
        "validateSrcJoinOnly": False,
        "validateValuesFilter": "",
        "dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME,
        "driverName": "org.postgresql.Driver",
        "user": "owluser",
        "password": "",
        "passwordManager": None,
        "connectionName": "APPROVED_POSTGRES_UP",
        "connectionUrl": "jdbc:postgresql://35.190.143.55:5432/postgres?cs=test&test=test&t2=t2",
        "query": "select * from public.sales_data_002 where transaction_date = '2024-08-14'",
        "lib": "/opt/owl/drivers/postgres/",
        "connectionProperties": {},
        "filePath": "",
        "fileQuery": "",
        "fullFile": False,
        "header": None,
        "skipLines": 0,
        "inferSchema": True,
        "fileType": None,
        "delimiter": ",",
        "fileCharSet": "UTF-8",
        "avroSchema": "",
        "xmlRowTag": "",
        "flatten": False,
        "handleMaps": False,
        "handleMixedJson": False,
        "multiLine": False,
        "filterCols": None,
    },
    "rule": {
        "on": True,
        "only": False,
        "lib": None,
        "name": "",
        "absoluteScoring": False,
        "ruleBreakPreviewLimit": 6,
    },
    "colMatch": {
        "colMatchParallelProcesses": 3,
        "colMatchDurationMins": 20,
        "colMatchBatchSize": 2,
        "level": "exact",
        "fuzzyDistance": 1,
        "connectionList": [],
    },
    "spark": {
        "numExecutors": 1,
        "driverMemory": "1g",
        "executorMemory": "1g",
        "executorCores": 2,
        "conf": "",
        "queue": "",
        "master": "k8s://",
        "principal": "",
        "keyTab": "",
        "deployMode": "cluster",
        "jars": None,
        "packages": None,
        "files": None,
    },
    "env": {"dataset": DS_DEF_DGC_COLUMN_RELATION_JOB_NAME, "jdbcPrincipal": "", "jdbcKeyTab": ""},
    "record": {
        "on": False,
        "in": "",
        "notIn": "",
        "include": None,
        "percDeltaLimit": 0.1,
        "score": 1.0,
        "dataset": None,
        "dateColumn": None,
        "keyColumn": None,
        "timeBin": "DAY",
        "by": None,
    },
    "stream": None,
    "pipeline": [],
    "metaTags": [],
    "outlierConfiguration": {
        "only": False,
        "lookback": 5,
        "dateColumn": "transaction_date",
        "timeBin": "DAY",
        "by": None,
        "q1": 0.15,
        "q3": 0.85,
        "categorical": True,
        "columnSensitivitySettings": [
            {"name": "transaction_date", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "sales_rep", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "cost", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "cost_description", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "daily_id", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "last_name", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "state_tax", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "lost_column", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "transaction_time", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "first_name", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "sales_id", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "cost_code", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "email", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "sale_state", "weight": 1.0, "unit": "DEFAULT"},
            {"name": "vendor_type", "weight": 1.0, "unit": "DEFAULT"},
        ],
        "configurations": [
            {
                "id": 339,
                "key": ["daily_id"],
                "include": ["sales_id", "first_name", "last_name", "email"],
                "exclude": [
                    "transaction_date",
                    "transaction_time",
                    "daily_id",
                    "vendor_type",
                    "cost",
                    "cost_code",
                    "cost_description",
                    "sales_rep",
                    "sale_state",
                    "state_tax",
                    "lost_column",
                ],
                "timeColumn": None,
                "timeBinQuery": "",
                "limit": 300,
                "minHistory": 3,
                "historyLimit": 5,
                "score": 1.0,
                "aggFunc": "",
                "aggQuery": "",
                "query": "",
                "categoricalColumnConcatenation": False,
                "limitCategorical": None,
                "measurementUnit": "",
                "multiplierUpper": 1.35,
                "multiplierLower": 1.35,
                "record": True,
                "filter": None,
                "combine": True,
                "categoricalConfidenceType": "",
                "categoricalTopN": 3,
                "categoricalBottomN": 2,
                "categoricalMaxConfidence": 0.02,
                "categoricalMaxFrequencyPercentile": 0.25,
                "categoricalMinFrequency": 1,
                "categoricalMinVariance": 0.0,
                "categoricalMaxCategoryN": 1,
                "categoricalParallel": True,
                "categoricalAlgorithm": "",
                "categoricalAlgorithmParameters": {},
            }
        ],
    },
    "shape": {
        "enabled": True,
        "totalScore": 0,
        "sensitivity": 0.0,
        "maxPerCol": 0,
        "maxColSize": 0,
        "granular": True,
        "columnSettings": [
            {"enabled": False, "name": "cost", "type": "Decimal"},
            {"enabled": True, "name": "cost_code", "type": "String, Double"},
            {"enabled": False, "name": "cost_description", "type": "String"},
            {"enabled": False, "name": "daily_id", "type": "Long, String, Int"},
            {"enabled": True, "name": "email", "type": "String"},
            {"enabled": False, "name": "first_name", "type": "String"},
            {"enabled": False, "name": "last_name", "type": "String"},
            {"enabled": False, "name": "lost_column", "type": "String"},
            {"enabled": False, "name": "sale_state", "type": "String"},
            {"enabled": False, "name": "sales_id", "type": "Int"},
            {"enabled": False, "name": "sales_rep", "type": "String"},
            {"enabled": False, "name": "state_tax", "type": "Decimal"},
            {"enabled": False, "name": "transaction_date", "type": "Timestamp"},
            {"enabled": False, "name": "transaction_time", "type": "String"},
            {"enabled": False, "name": "vendor_type", "type": "String"},
        ],
    },
    "jobSchedule": None,
    "connectionType": "PULLUP",
}

DS_DEF_DGC_COLUMN_RELATIONS_NAME = "AUTO_DQ_COLUMN_RELATION_IN_DIC_"
DS_DEF_DGC_COLUMN_RELATIONS_SECONDARY = copy.deepcopy(DS_DEF_DGC_COLUMN_RELATION_IN_DIC)
DS_DEF_DGC_COLUMN_RELATIONS_SECONDARY["load"]["query"] = (
    "select cost, cost_code, cost_description, "
    "daily_id, email,first_name, last_name, "
    "lost_column, sale_state, sales_id, "
    "sales_rep, state_tax, transaction_date, "
    "transaction_time "
    "from public.sales_data_002 where "
    "transaction_date = '${rd}'"
)
