from payloads.pushdown.rule_import_export.pl_pd_sf_rules_import_export import (
    PD_SF_RULES_IMPORT_EXPORT_DATASET,
)

PD_SF_RULES_IMPORT_EXPORT_RULE_DEFINITIONS = [
    {
        "dataset": PD_SF_RULES_IMPORT_EXPORT_DATASET,
        "ruleNm": "if_zip_code_is_NULL",
        "ruleType": "NULLCHECK",
        "ruleValue": "zip_code",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "zip_code",
        "businessCategory": None,
        "businessDesc": None,
        "dimId": 1,
        "dimName": "COMPLETENESS",
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0
    },
    {
        "dataset": PD_SF_RULES_IMPORT_EXPORT_DATASET,
        "ruleNm": "if_gender_is_GENDER",
        "ruleType": "CUSTOM",
        "ruleValue": "gender",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "GENDER",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": "gender",
        "businessCategory": None,
        "businessDesc": None,
        "dimId": 4,
        "dimName": "VALIDITY",
        "ruleValueBuilder": None,
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0
    },
    {
        "dataset": PD_SF_RULES_IMPORT_EXPORT_DATASET,
        "ruleNm": "SIMPLE_STRING",
        "ruleType": "SQLG",
        "ruleValue": "\"auto_make\" = 'Ford'",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "condition,rules,not,valid",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0
    },
    {
        "dataset": PD_SF_RULES_IMPORT_EXPORT_DATASET,
        "ruleNm": "FF_long",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PD_SF_RULES_IMPORT_EXPORT_DATASET} "
                     f"where \"auto_year\" = 2001",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "condition,rules,not,valid",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0
    },
    {
        "dataset": PD_SF_RULES_IMPORT_EXPORT_DATASET,
        "ruleNm": "stat_rule",
        "ruleType": "SQLF",
        "ruleValue": f"select * from @{PD_SF_RULES_IMPORT_EXPORT_DATASET} where $rowCount > 1000",
        "points": 1,
        "perc": 1.0,
        "ruleRepo": "",
        "isActive": 1,
        "userNm": None,
        "exception": None,
        "columnName": None,
        "businessCategory": None,
        "businessDesc": None,
        "dimId": None,
        "dimName": None,
        "ruleValueBuilder": "condition,rules,not,valid",
        "previewLimit": 6,
        "runTimeLimit": 30.0,
        "scoringScheme": 0,
        "filterQuery": None,
        "tolerance": 0
    }
]
