name: Style Check

on: [pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install libxml2 and libxslt
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Upgrade setuptools and wheel
        run: pip install --upgrade setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch branch
        run: git fetch origin main

      - name: Find merge base
        id: merge-base
        run: echo "::set-output name=merge-base::$(git merge-base origin/main HEAD)"

      - name: List modified files
        run: |
          git diff --name-only ${{ steps.merge-base.outputs.merge-base }}..HEAD -- "*.py" > modified_files.txt

      - name: Run Flake8
        run: flake8 --config .flake8 --exclude=modified_files.txt $(cat modified_files.txt) || true

      - name: Run Black
        run: |
          while IFS= read -r file; do
            black --check --line-length 100 "$file" || true
          done < modified_files.txt

      - name: Run Pylint
        run: |
          if [ -s modified_files.txt ]; then
            pylint --rcfile=pylintrc $(cat modified_files.txt)
          else
            echo "No modified Python files found."
          fi
